### ISSUE TITLE
Mention the location of the logs when okteto up fails

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1004]
**Describe the bug**
Making it more visible  would help troubleshooting issues 

We could add them as a hint to syncthing-related errors.

**Comment by snitkdan** [comment]
Hi @rberrelleza! I would love to take a look at this issue if that's alright. If so, I just had a couple of quick questions to clarify my understanding: 

* By "logs", would that correspond to the `okteto.log` file generated from [okteto doctor](https://okteto.com/docs/reference/cli/index.html#doctor)? Or is it related to the [logrus logger](https://github.com/okteto/okteto/blob/master/main.go#L63) we use throughout the code-base? 
* I see that there are several [Syncthing errors](https://github.com/okteto/okteto/blob/master/pkg/errors/errors.go#L53); did you have in mind to add the log location as context to the base errors in `errors.go`, or pass in that context selectively from `okteto up` related call-sites? 

Thanks!

**Comment by rberrelleza** [comment]
@snitkdan for the scope of this issue, it's about showing the user the path to the okteto log (which by default would be $HOME/.okteto/okteto.log), for cases when okteto up failed. 

As for the syncthing errors, that's a good point. It would be nice to show the path as well. How about you open a second issue for that one and we discuss it separately?

**Comment by pchico83** [comment]
@jLopezbarb this looks easy to implement and provides a lot of value

**Comment by RinkiyaKeDad** [comment]
@jLopezbarb are you currently working on this? If not I'd like to try and take this up :)

@rberrelleza from what I understood, do we simply need to append text, pointing to the location of `okteto.log`, to the `err` being [returned](https://github.com/okteto/okteto/blob/master/cmd/up/up.go#L179) here?

**Comment by jLopezbarb** [comment]
@RinkiyaKeDad No, I'm not working on this. Feel free to work on this ;)
