### ISSUE TITLE
User friendly message when the context is not found

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1017]
**Describe the bug**
If my okteto.yml has a context that doesn't exist on the active KUBECONFIG, okteto outputs the following:
```
invalid configuration: [context was not found for specified context: okteto-dev, cluster has no server defined]
```

It would be useful to have a clearer message like: `'$CONTEXT' context not found in $KUBECONFIG`

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.8.17

**Comment by pchico83** [comment]
Reference docs for okteto `context` field: 
https://okteto.com/docs/reference/manifest#context-string-optional

**Comment by snitkdan** [comment]
@rberrelleza - would it be alright if I look into this issue?

**Comment by rberrelleza** [comment]
@snitkdan yes, thanks a lot of contributing!
