### ISSUE TITLE
automatically install package dependencies

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1018]
**Is your feature request related to a problem? Please describe.**
When I add a dependency to my package.json, I have to manually go to the remote container and run `yarn install` to install it.

**Describe the solution you'd like**
I'd like okteto to detect that this special file was updated, and perform the corresponding install action.

**Describe alternatives you've considered**
Manually configure something like https://facebook.github.io/watchman/ on my dev container

**Comment by pchico83** [comment]
Duplicated of https://github.com/okteto/okteto/issues/1263
