### ISSUE TITLE
Add more info to "okteto doctor"

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1036]
Information that would be helpful:
- cpu/memory resources
- .stignore file
- okteto manifest
- command logs
- syncthing folder size

**Comment by rberrelleza** [comment]
What do you mean by command logs?

**Comment by pchico83** [comment]
@rberrelleza the execution of the okteto manifest start command

**Comment by rberrelleza** [comment]
@pchico83 do you mean logging the output of the command? or the command itself?

**Comment by pchico83** [comment]
@rberrelleza I was thinking about the output of the command. But we can skip that for now.
