### ISSUE TITLE
Add an option for 'automation friendly' output

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1041]
**Is your feature request related to a problem? Please describe.**
When I run `okteto stack deploy --wait` on Okteto Cloud (or other headless systems) the output looks like this:

![image](https://user-images.githubusercontent.com/475313/93400358-78638f80-f834-11ea-935f-84a1f7d1c0e6.png)

**Describe the solution you'd like**
Ideas:
- A quiet mode, where non-essential output is not shown.  
- A `headless` mode, only logs errors , or logs text without animations.

**Comment by ravindrabhargava** [comment]
I would like to understand it more before start working on it Thanks

**Comment by rberrelleza** [comment]
@ravindrabhargava thanks for the help!

What I was thinking is that we could have an optional `--no-progress` flag in the commands. If the the flag is present, then we don't display the progress bars, and we only output normal text (okteto up, okteto stack deploy, and okteto pipeline deploy are three commands that use progress bar extensively, they would be a good candidate)
