### ISSUE TITLE
okteto build should retry on transient errors

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1042]
**Is your feature request related to a problem? Please describe.**
Every now and then okteto build will fail to push or build my image due to transient errors (network, handshakes timing out, 
etc.). 

**Describe the solution you'd like**
It would be useful if okteto was to retry in those situations.

**Describe alternatives you've considered**
Today, I rerun the command manually.

Examples:

In both of these cases, rerunning the command resulted in a successful build. 

- ` build failed: failed to solve: rpc error: code = Unknown desc = failed to copy: failed to do request: Put https://docker.pkg.github.com/v2/rberrelleza/go-getting-started/go/blobs/uploads/260370841/287d62a9-e0c4-473b-8641-ee70ecacf4cb/3dae2700-f835-11ea-8717-6be13ff22cbf?digest=sha256%!A(MISSING)57df1a1f1ad841deaf50c8f662d77e93b4b17af776ed66148116607f9aceffa8: tls: use of closed connection`
- `error building image for 'fastapi': build failed: failed to solve: rpc error: code = Unknown desc = failed to authorize: failed to fetch oauth token: Post https://okteto.cloud.okteto.net/auth/registry: dial tcp: lookup okteto.cloud.okteto.net on 10.132.0.10:53: no such host`

**Comment by jLopezbarb** [comment]
I think this was done [here](https://github.com/okteto/okteto/pull/1309)
