### ISSUE TITLE
Feature Request:  okteto up to an ARM cluster

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1049]
**Is your feature request related to a problem? Please describe.**
I want to deploy my development environment on an ARM cluster (e.g.  k3s running on a graviton EC2 instance)

**Additional context**
okteto has several dependencies, so we'll need to ensure that the following work on arm, and then build multiarch docker images.  We started the work already, but still needs to be integrated, and tested end to end.
- github.com/okteto/remote
- github.com/okteto/clean
- github.com/okteto/supervisor
- github.com/okteto/bin

We're looking for contributors with experience on multiarch docker builds to help us make [okteto/bin](https://github.com/okteto/okteto/blob/master/images/bin/Dockerfile) arm friendly.

**Comment by fdelucchijr** [comment]
What’s the current status for this issue? the last arm64 compatible version was 1.2.22, If you need help maintaining the build count on me, in our business we use Okteto as a core part of our development environment but we are stuck with a exec format error in the same environment where everything was working before.

 I’m pretty advanced in multi arch docker build (I use from armv7 to arm64 in almost all my environments since 2020).

**Comment by vinodkumark369** [comment]
@fdelucchijr As a temporary workaround I was able to use oketeto/bin:1.2.22 with arm cluster by passing OKTETO_BIN env variable.

`OKTETO_BIN=okteto/bin:1.2.22 okteto up`

**Comment by pchico83** [comment]
@vinodkumark369 does that mean that if we build `okteto/bin` with ARM support, `okteto up` works out of the box in ARM clusters?

**Comment by vinodkumark369** [comment]
@pchico83 I think so, I have not tested it extensively. I used the python-getting-started changed the image (okteto/hello-world) and used it to test, command line is working fine. Need to test VS Code integration.

**Comment by fdelucchijr** [comment]
> @vinodkumark369 does that mean that if we build `okteto/bin` with ARM support, `okteto up` works out of the box in ARM clusters?

Yes, I was having problems using the 1.2.22, so I rebuild the `okteto/bin` image with `--platform=linux/arm64` tag and pushed to a private registry with the following command: 
```shell
docker buildx build -t ghcr.io/fdelucchijr/okteto/bin --label "latest,1.3.7" --push  -f Dockerfile --platform=linux/arm64 https://github.com/okteto/bin-image.git
```
(The image I build is public, use it at your own risk as an alternative (is the same dockerfile), but if you wanna push your own just change the registry url to one where you have write access)

Everything works flawlessly, so I think indeed with `okteto/bin` with arm64 support out of the box everything works perfect.
Other thing is de development environment images like `okteto/node`, that image has just nodemon added to the image but still isn’t build with arm64 (even with all `node:etc` support it). 

When the development environments 'okteto/bin' and 'okteto/...' are compatible with arm64, I would say okteto is ready for the arm64 cluster.

PD: I really love Okteto as a tool in my job and personal projects, thanks

**Comment by pchico83** [comment]
@fdelucchijr that's amazing?
Would you or @vinodkumark369 be open to send a PR to automate the ARM build? We already have an open issue for it https://github.com/okteto/bin-image/issues/3
Respect to our dev images, you can always use your own. At some point we could also automate the ARM build in this repo:
https://github.com/okteto/devenv/blob/main/docker-compose.yml

**Comment by vinodkumark369** [comment]
@pchico83 Are you using github actions or circle-ci or both for releases?
In  `.github/workflows/release-bin.yml`, I could see the following:

```
 docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --output "type=image,push=true" \
            --build-arg COMMIT_SHA=${{ github.sha }} -t okteto/bin:${{ github.event.inputs.tag }} .
```

I think this should take care of the automatic build on its own, provided the release is done using github actions.
If it is not making a multi-arch image, then I would suspect a custom builder is being used which has only support for linux/amd64 platform.

**Comment by fdelucchijr** [comment]
@pchico83, I just check at `okteto/bin` build process ( [here](https://github.com/okteto/bin-image/blob/master/Makefile) ) , is using `okteto build` command, I've never used  that command before in the okteto cli, but as I see in the docs and -h flag, there is no `--platform` flag to build the image with a specified arch. Do you prefer to develop that flag in order to build the bin image? Or maybe can we change the build command in CircleCI for something like the one I added in the earlier comment?

I've made a PR in okteto/devenv#93 for the multi-arch images, OpenFAAS is really necessary? Requires a script to rebuild it or talk to the base image maintainer to get arm64 support.

**Comment by pchico83** [comment]
> @pchico83, I just check at `okteto/bin` build process ( [here](https://github.com/okteto/bin-image/blob/master/Makefile) ) , is using `okteto build` command, I've never used that command before in the okteto cli, but as I see in the docs and -h flag, there is no `--platform` flag to build the image with a specified arch. Do you prefer to develop that flag in order to build the bin image? Or maybe can we change the build command in CircleCI for something like the one I added in the earlier comment?
> 
> I've made a PR in [okteto/devenv#93](https://github.com/okteto/devenv/pull/93) for the multi-arch images, OpenFAAS is really necessary? Requires a script to rebuild it or talk to the base image maintainer to get arm64 support.

We can switch to `docker buildx` in the CircleCI configuration.

About OpenFAAS, we don't need it. At some point we should remove that image from the repo

**Comment by fdelucchijr** [comment]
Perfect, if the okteto/devenv#94 and  okteto/bin-image#4 PR's works at CircleCI, we can say our work is done 🥂

**Comment by pchico83** [comment]
I am reopening the issue, working on a PR to support ARM clusters. 
@fdelucchijr and @vinodkumark369 thanks for helping with this!

**Comment by pchico83** [comment]
@fdelucchijr @vinodkumark369 I don't have an easy way to test if it works, but this PR should bring support to ARM clusters.

**Comment by rberrelleza** [comment]
@pchico83 does this mean that okteto now works on arm clusters?

**Comment by pchico83** [comment]
> @pchico83 does this mean that okteto now works on arm clusters?

@rberrelleza yes!

**Comment by rberrelleza** [comment]
🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳

**Comment by RinkiyaKeDad** [comment]
Hey @fdelucchijr! Thanks for helping with this. I'm really interested in learning more about your use case with Okteto, which required ARM support. Would you be interested in sharing what you've been doing? :) If yes, could you please share your email with me at arsh@okteto.com so we could talk more? Thanks!
