### ISSUE TITLE
Okteto stacks "depends_on" condition

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1060]
**Is your feature request related to a problem? Please describe.**
I want to hold one of my services deployments until other service is available. This is very common, for example, to wait for the database to be up and running.

**Describe the solution you'd like**
The "wait" logic could be implemented by an init container of the service that needs to wait for another one, just checking the port is available. Also, the init container could wait for jobs to finish.

**Comment by jLopezbarb** [comment]
I think this can be closed in favor of [this issue](https://github.com/okteto/okteto/issues/1386)
