### ISSUE TITLE
Allow mounting of existing secrets/config maps

### ISSUE THREAD

**Issue by leighhopcroft** [okteto/okteto#1103]
**Is your feature request related to a problem? Please describe.**
I have some secrets and config maps already defined in k8s but can't consume them from the development container. The `secrets` map seems to be only for specifying new secrets to create from local files if I have understood the docs correctly.

**Describe the solution you'd like**
I'd like to be able to reference existing k8s secrets/config maps by name in the `okteto.yml` manifest so that they can be mounted in to the development container, either as files or env variables and therefore be available in dev environment as they are in the production pod.

**Comment by pchico83** [comment]
@leighhopcroft you can deploy your deployment first using k8s manifests and run `okteto up` against a running deployment to put the deployment in dev mode.
When you do this, the dev container inherits all the configuration from the k8s deployment (including volumes, secrets, configmaps...). Would this fit your use case?

**Comment by leighhopcroft** [comment]
@pchico83 incidentally this is actually how I had done it, I just didn’t realise that this was the behaviour by default. Nice 👍. Might be worth updating the docs to make this behaviour more prominent.
