### ISSUE TITLE
Improve reconnection logic after laptop resumes after sleeping

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1131]
**Describe the bug**
The `okteto up` sequence is executed before there is internet connection, getting this error:
```
read: connection reset by peer
```

**Comment by pchico83** [comment]
![image (5)](https://user-images.githubusercontent.com/7474696/97524918-f7a4c100-19a5-11eb-8c65-6cfd5a2902c3.png)
![image (6)](https://user-images.githubusercontent.com/7474696/97524924-fa9fb180-19a5-11eb-8329-7d91f3b11110.png)

**Comment by rberrelleza** [comment]
fixed by #1143
