### ISSUE TITLE
"okteto up" reconnects with the wrong image.

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1138]
**Describe the bug**
If "okteto up" reconnects because there is a deployment update, `okteto up` reuses the old image of the deployment to reconnect.

**To Reproduce**
1. Deploy a stack
2. `okteto up`
3. Change code
4. `okteto stack deploy --build`

**Expected behavior**
`okteto up` should use the new image build by `okteto stack deploy --build` if `image` is not defined in the okteto manifest.

**Comment by rberrelleza** [comment]
is this just on okteto stack deploy @pchico83 ?

**Comment by pchico83** [comment]
No, it is when the okteto manifest doesn't have an image. The `okteto stack deploy` is just an example to reproduce it
