### ISSUE TITLE
External IP is none

### ISSUE THREAD

**Issue by maxkaustav** [okteto/okteto#1144]
`apiVersion: v1
kind: Service
metadata:
  name: wak1
spec:
  selector:
    app: webapp-and-kubernets
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer`

but my external ip is none

**Comment by rberrelleza** [comment]
Hey @maxkaustav . Where did you deployed this? 

If it's in Okteto cloud, check the ingress list to get the url of the endpoint.

**Comment by maxkaustav** [comment]
ok thank you, it worked
