### ISSUE TITLE
"okteto exec" should always use "kubectl exec" to avoid dependency on "okteto up" being runninng

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1145]
**Is your feature request related to a problem? Please describe.**
Otherwise, you get this error:
![image (7)](https://user-images.githubusercontent.com/7474696/97852239-c48c6580-1cf6-11eb-9ad4-f34166c161a1.png)

**Comment by pchico83** [comment]
@rberrelleza also, `okteto exec` is broken if `remote` is not defined, but `reverse` is defined

**Comment by rberrelleza** [comment]
> **Is your feature request related to a problem? Please describe.**
> Otherwise, you get this error:
> ![image (7)](https://user-images.githubusercontent.com/7474696/97852239-c48c6580-1cf6-11eb-9ad4-f34166c161a1.png)

I think that okteto exec should be tied to okteto up, since it's part of that flow. if you do okteto exec and land on a non-dev container, your dev tools won't be there, and it will be a different exception.

I think we should check if up is not running and log a more description error, rather than just the SSH one.

**Comment by rberrelleza** [comment]
> @rberrelleza also, `okteto exec` is broken if `remote` is not defined, but `reverse` is defined

Yes, I'll fix this on a separate PR/issue.

**Comment by pchico83** [comment]
@rberrelleza it should be tied to `up`, but there are cases where you `up` command fails, and you want to `exec` to debug what's going on. But the dev container is already created.

**Comment by rberrelleza** [comment]
I see, in that case, the SSH server should be running already no?

**Comment by rberrelleza** [comment]
I'm thinking 3 escenarios:

**Comment by pchico83** [comment]
If you want to use ssh, I would support `exec` only if `up` is properly running for now, and show a better error.

**Comment by rberrelleza** [comment]
> If you want to use ssh, I would support `exec` only if `up` is properly running for now, and show a better error.

with the port issue fixed we should be there. okteto exec will fail if the dev pod is not healthy. as long as the SSH server is running, it will be able to connect, independently of the command's status

**Comment by pchico83** [comment]
Sounds good
