### ISSUE TITLE
start.sh sets the content of `/var/syncthing/` as read only

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1156]
**Describe the bug**
start.sh sets the content of `/var/syncthing/` as read only if fsGroup is defined at the deployment level, but runAsUser and runAsGroup are set at the container level.

`okteto up` succeeds, but if the user does exit, the second okteto up will fail until the volume is deleted.

**To Reproduce**
Use https://github.com/okteto/go-non-root-container/tree/separate-fs-group to reproduce it.

**Expected behavior**
okteto up should be successful multiple times.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.9.4

**Comment by pchico83** [comment]
Fixed by #1158
