### ISSUE TITLE
support imagePullSecrets

### ISSUE THREAD

**Issue by kbc8894** [okteto/okteto#1178]
**Is your feature request related to a problem? Please describe.**
- When I want to use private image, I can't set imagePullSecrets in okteto.yaml.

**Describe the solution you'd like**
- support imagePullSecrets okteto.yaml

**Describe alternatives you've considered**
- use public image? but, it is not solution.

**Additional context**

**Comment by pchico83** [comment]
Hi @kbc8894 
There are three different options to use private images with the Okteto CLI:
a) Define the pull secret in your Deployment manifest.
    When `okteto up` puts this deployment in dev mode, it will use keep your deployment pull secrets.
b) Attach pull secrets to the service account used to run `okteto up`. This process is defined here:
    https://okteto.com/docs/reference/faqs#how-to-use-private-images
c) If you are in Okteto Cloud/Okteto Enterprise, use the Okteto private Registry:
    https://okteto.com/docs/cloud/registry

**Comment by kbc8894** [comment]
thanks, It works!

**Comment by renepardon** [comment]
@kbc8894 how did you made it work? imagePullSecrets is not available within okteto.yml and adding a docker-secret seem to be ignored by okteto itself.

I try `okteto up` with a docker image from private docker registry. I followed the instrcutions at https://okteto.com/docs/reference/faqs/index.html#how-to-use-private-images and also tried adding the secret to kube-system namespace default service account without success..

**Comment by pchico83** [comment]
@renepardon you need to add the secret to the default service account of the namespaces where you are deploying your application

**Comment by renepardon** [comment]
Hi @pchico83 
yeah I’m working with k3d. There is just the default and kube-system. I added the secret to both default service accounts without success.

**Comment by pchico83** [comment]
@renepardon are you using a service account in the deployment you want to put in development mode?

**Comment by renepardon** [comment]
Nevermind. After I started my laptop today it just worked for whatever reason without the permission error when I tried to reproduce everyhing
