### ISSUE TITLE
ability to configure the service created by okteto

### ISSUE THREAD

**Issue by horacimacias** [okteto/okteto#1184]
**Is your feature request related to a problem? Please describe.**
I'm using okteto with an application that opens two ports, e.g. 8080 and 50055.
I see okteto is creating a service that exposes 8080, but not 50055.
I'm not able to find where can I configure which ports will be enabled on the service created by okteto, if that is configurable.

**Describe the solution you'd like**
Extend manifest so I can have a list of ports that will be added to the k8s service created by okteto

**Describe alternatives you've considered**
Manually editing k8s service after it's been created, but needs to be done every time service is created new.

**Additional context**

**Comment by pchico83** [comment]
@horacimacias thanks for your feedback.
`okteto up` is able to put a running deployment in development mode. That means that you can use kubernetes manifests, helm charts, or any other deployment tool to create your deployments and services. Then, run `okteto up` to start developing on your deployment, and your development container will reuse all the YAML from the original deployment, like envvars, ports, volumes, secrets...

If you want to avoid writing kubernetes manifests, you might want to have a look at Okteto Stacks:
https://okteto.com/docs/reference/stacks

**Comment by horacimacias** [comment]
thanks. I'll explore Stacks; looks definitely interesting.

I was basically talking about allowing configuration of the "automatically created" service in case I'm not reusing a running deployment (in my specific case I need a new/different deployment).
Looks like https://github.com/okteto/okteto/blob/68ecc7fed2af68edcc649ce6bdab9610a6908d7e/pkg/k8s/services/translate.go sets up port 8080 by default (which in fact is quite handy for me as that's one of the ports I definitely need), it would be good to allow service ports to be read from model.Dev, similarly to how annotations are already configurable.

Maybe my use case is very specific; I'm using 2 development deployments and one using the other by service name / DNS, but since only one of the ports is exposed by the service I cannot get things talking. 
I can refer to pods by IP instead of service name, but of course that is less than ideal.
Given there are already several items taken from manifest when creating the service, adding ports sounded like a quick win (I may be missing the bigger picture).

I'll explore other alternatives including Stack. If this change sounds like a potentially welcomed contribution please let me know.
