### ISSUE TITLE
.net core okteto yml template additional environment variables

### ISSUE THREAD

**Issue by alanmbarr** [okteto/okteto#1185]
**Is your feature request related to a problem? Please describe.**
I need to add environment variables by hand and I would like the template to do this itself. I'm planning on taking this on as I have time.
https://github.com/okteto/okteto/blob/be251ebe5d9169b6fd23f8aa2b0e99ffa9480945/pkg/linguist/dev.go#L205

**Describe the solution you'd like**
On Okteto up when asked to create a default yml for .net core apps I would like additional parameters in the environment for being able to attach to the unit tests and debug them.
environment:
 - ASPNETCORE_ENVIRONMENT=Development
>New stuff below
 - VSTEST_HOST_DEBUG=0
 - VSTEST_RUNNER_DEBUG=0

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by rberrelleza** [comment]
fixed by #1188
