### ISSUE TITLE
Set timeout in okteto manifest

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1197]
**Is your feature request related to a problem? Please describe.**
When working with big images, okteto up times out often, specially if the image is pretty large and not pulled. It would be useful to be able to specify a bigger timeout directly in the manifest, instead of setting an env var.

**Comment by girishramnani** [comment]
I would like to work on this issue

**Comment by rberrelleza** [comment]
Perfect @girishramnani, it's all yours :)

**Comment by girishramnani** [comment]
any suggestion on what should the parameter be called in the manifest?

**Comment by rberrelleza** [comment]
@girishramnani I think we can just call it timeout for now. it should take an int:

```yaml
name: my-app
image: okteto/go:1
timeout: 10m
```

**Comment by rberrelleza** [comment]
I think it's useful if the timeout is defined as golang duration (e.g. 5s, 2m, 1h)

**Comment by girishramnani** [comment]
Got it
