### ISSUE TITLE
Compatibility with syncthing 1.12 for use with Apple silicon Macs

### ISSUE THREAD

**Issue by vitobotta** [okteto/okteto#1199]
**Describe the bug**
Hi. This is a follow up to my conversation on Slack with @rberrelleza. I am using Okteto on an Apple silicon Mac, and I am using syncthing 1.12 built for ARM Macs with this version:

```
syncthing v1.12.1-rc.1 "Fermium Flea" (devel +ac0ba67 Mon Dec 7 10:56:21 2020 +0000 darwin-arm64) teamcity@build.syncthing.net 2020-12-06 12:46:27 UTC [noquic, stnoupgrade]
```

One connection between local and remote seems to get cut quite soon after the synchronization is started, with errors like:

```
Connection to <id> at 127.0.0.1:49946-127.0.0.1:49943/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256 closed: reading length: read tcp 127.0.0.1:49946->127.0.0.1:4
9943: use of closed network connection
```

Soon after, in the log, I also see this:

```
UPnP parse: dial tcp 192.168.10.1:38400: operation was canceled
```

Thanks in advance for any help and please let me know if there is something I can do to test/troubleshoot.

**To Reproduce**
I replaced the x86 syncthing build downloaded by Okteto with syncthing v1.12.1-rc.1 built for ARM Macs. I had to patch the latest version of Okteto and rebuild so that it doesn't replace that binary when starting.

**Expected behavior**
I would expect sync to work two ways as usual.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
macOS 
11.1 on M1 Mac Mini

**Comment by rberrelleza** [comment]
we need to wait for syncthing 1.13, since that will include a native build for Apple sillicon

**Comment by pchico83** [comment]
This is now supported :-)
