### ISSUE TITLE
"okteto up" fails with another syncthing instance running error

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1204]
**Describe the bug**

`okteto up` fails and the local syncthing logs "Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)".

**Expected behavior**
`okteto up` should be able to recover from this error.

**Comment by rberrelleza** [comment]
This happens if, for some reason, the syncthing.pid file is deleted but the process is still alive.  We can use https://github.com/shirou/gopsutil/blob/master/v3 to scan for processes and delete by name on top of by PID.

**Comment by rberrelleza** [comment]
From my experiments, I haven't been able to determine how this is triggered, but I've seen it. The following needs to happen for this to repo:
- `okteto up` doesn't exit correctly  (or, it fails to stop the syncthing process)
- the okteto folder is deleted ( or at the very list, the syncthing.pid file)

Running okteto down will also fix the issue.

**Comment by pchico83** [comment]
@rberrelleza could it be that `okteto up` fails before storing the `syncthing.pid` file?
What about if we also kill the previous syncthing by name, not only by `pid`?

**Comment by rberrelleza** [comment]
Yeah, that's what I was suggesting in my previous comment. the problem is that it's non-trivial to do it across windows/linux/mac :(. Hopefully there's a library that does it for us.
