### ISSUE TITLE
Expose "no-cache" in the stack manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1205]
**Is your feature request related to a problem? Please describe.**
I want to build one of my stack services without using the cache.
`okteto build --no-cache` is not exposed in the stack manifest

**Comment by rberrelleza** [comment]
What is the use case for this? Wouldn't you want to use the cache expect for very few situations?

**Comment by pchico83** [comment]
This is very useful for debugging scenarios. For example, your build is caching and old dependency and you want to force a clean build.

**Comment by rberrelleza** [comment]
for debugging scenarios "okteto stacks --no-cache" is more useful than to have to edit a file no?

**Comment by pchico83** [comment]
@rberrelleza yes, I guess that one, in combination with the ability to build a single service, gives a better ux. It is also how docker-compose exposes it
