### ISSUE TITLE
okteto should support different ports in the same domain name

### ISSUE THREAD

**Issue by chaowenGUO** [okteto/okteto#1213]
Right now okteto always translate loadbalancer service to some auto-ingree and just can access the first port under service and there is no way to access the second port.

For example, consider the following yaml
`apiVersion: v1
kind: Service
metadata:
    name: aiohttp
spec:
    selector:
        app: aiohttp
    type: LoadBalancer
    ports:
    - port: 8080`

I can access the aiohttp pod via https://aiohttp-chaowenguo.cloud.okteto.net`

If I modify the yaml into multiple ports situation. For example:
`apiVersion: v1
kind: Service
metadata:
    name: aiohttp
spec:
    selector:
        app: aiohttp
    type: LoadBalancer
    ports:
    - port: 8080
      name: first
    - port: 8081
      name: second`

I can still access the 8080 port via https://aiohttp-chaowenguo.cloud.okteto.net, but there is no way to access the 8081 port from outside.

What I want:
Could okteto modify auto-ingress to support something like this:
use https://aiohttp-chaowenguo.cloud.okteto.net:8080 to access 8080 port
and use https://aiohttp-chaowenguo.cloud.okteto.net:8081 to access 8081 port
or something like play with k8s, I can use kubectl get svc to check the external ports
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                           AGE
aiohttp      LoadBalancer   10.106.150.9     <pending>          8080:12345/TCP,8081:23456/TCP   17s
then I can use https://aiohttp-chaowenguo.cloud.okteto.net:12345 to access the 8080 port and use https://aiohttp-chaowenguo.cloud.okteto.net:23456 to access the 8081 port. That means okteto provide a domain name for each individual kubernetes cluster not each individual service.

Or is there any method to help me to access the 8081 port?
Thank you very much

**Comment by pchico83** [comment]
Hi @chaowenGUO.
This repo is for the Okteto CLI, for Okteto Cloud related issues you can use this repo:
https://github.com/okteto/cloud-feedback

In order to expose different ports you need to define an ingress. There is more information about it on this link:
https://okteto.com/docs/cloud/ssl#bring-your-own-ingress

This is also another example:
https://github.com/okteto/movies/blob/master/chart/templates/ingress.yaml
