### ISSUE TITLE
okteto stack deploy --build doesn't build if there's no "build" attribute in the manifest

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1217]
**Describe the bug**
okteto stack deploy --build doesn't build if there's no "build" attribute in the manifest

**Expected behavior**
I'd expect to try and build it using my local Dockefile. If not, then I would expect it to fail. Once I added "build: ." to the manifest it worked as expected.

**Comment by pchico83** [comment]
We show a warning message now
