### ISSUE TITLE
okteto stack deploy doesn't work with images that don't have `sh`

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1219]
**Describe the bug**
If my container doesn't have `sh` (e.g. if I'm using scratch as the base image), the deployment with stack fails. I think this is because stacks use "sh -c"  to run the command.

**Comment by pchico83** [comment]
It works if you use the extended notation:
```
command:
  - your-command
```
We should document this on the docs

**Comment by jLopezbarb** [comment]
I think this can be closed due to [this](https://github.com/okteto/okteto/pull/1449)
