### ISSUE TITLE
active "okteto up"  relaunches the dev environment if I run "okteto down" on a separate terminal

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1224]
**Describe the bug**
Active "okteto up"  relaunches the dev environment if I run "okteto down" on a separate **terminal**

**To Reproduce**
1. run "okteto up" on terminal 1, wait for it to finish sequence
2.on terminal two, run "okteto down"

**Expected behavior**
The "okteto up" on terminal 1 should exit. Instead, it's relaunching "okteto up".

**Desktop (please complete the following information):**
 - OS: macos
 - Version 1.10.1

**Additional context**
This is making the integration test fail in Windows.

**Comment by pchico83** [comment]
Closed by #1228
