### ISSUE TITLE
"okteto namespace" and "okteto namespace xxx" don't reuse kubeconfig context

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1231]
**Describe the bug**
`okteto namespace` and `okteto namespace xxx` don't reuse kubeconfig context. They should create the same context, and just set the `namespace` field of the context as needed.

**Additional context**
After this change, deleting contexts on `okteto namespace delete` doesn't makes sense anymore, since the personal namespace cannot be deleted.

**Comment by rberrelleza** [comment]
Why should they reuse the kubeconfig context? We designed it this way to be able to keep a context per namespace, to make it easier to switch between them when you're using kubectl or other tools.

**Comment by pchico83** [comment]
@rberrelleza it was badly designed then. For a single context you can switch namespaces, it is not a good practice to create a different context per namespace. When you work with several namespaces and shared namespaces, your list of kubeconfig contexts grows with a long list of okteto contexts, which is noisy and impractical.
Using the current context, you can switch namespaces with something like this:
```
kubectl config set-context --current --namespace=xxx
```
or `okteto namespace xxx`.

But we need to adhere to the good practices about contexts and namespaces.

**Comment by rberrelleza** [comment]
> it is not a good practice to create a different context per namespace.

**Comment by pchico83** [comment]
@rberrelleza where is the breaking change?

I have already talked with users about this. Everyone using more than one namespace has complained about our current design. Think about this use case. I have three contexts: prod, staging, okteto. Someone shares his namespace on okteto for troubleshooting. I use `okteto namespace xxx`, which creates a new context. After I am done, I am not going to create that context again, and I have to delete it manually. Everytime I do this the list of my okteto temporal contexts grows.

Every tool I know create a context per cluster, okteto is the only one creating a context per namespace.
No-one edits kubeconfig files manually, people use `kubectl config`, or things like `kctx`, and there, our long list appears.

Have a look to https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/, it talks all the time about using contexts to access different clusters, not different namespaces.
