### ISSUE TITLE
`okteto build` doesn't seem to work in MacOS unless docker is installed

### ISSUE THREAD

**Issue by rlamana** [okteto/okteto#1237]
**Describe the bug**
I didn't install `docker` in my machine and `okteto build` kept failing with the following error:
```
error building image 'okteto.dev/frontend:c5e6811f9ccce5a43ba4ac627144e259d788305f': 
build failed: failed to solve: rpc error: code = Unknown desc = failed to load cache key: 
rpc error: code = Unknown desc = 
error getting credentials - err: exec: "docker-credential-osxkeychain": 
executable file not found in $PATH, out: ''
```

I was expecting to be able to use okteto without having docker in my machine but installing it fixed the keychain configuration issue.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version: 1.10.2

**Comment by pchico83** [comment]
The docker auth provider is defined here:
https://github.com/okteto/okteto/blob/master/pkg/cmd/build/authprovider.go#L31

**Comment by jLopezbarb** [comment]
Hi @rlamana, 
I've tried to reproduce your error by building the image without having installed docker with the command `okteto build -t okteto.dev/{your_image_name} .` and the image was succesfully pushed to the registry. 

Could you give me more details about the steps you took to try to reproduce it?

**Comment by rlamana** [comment]
@jLopezbarb This happened nearly two months ago and since then I installed `docker` and everything started working again. I'm afraid I cannot give you more info at this moment. @pchico83 wasn't this an issue that more people were having? or it was just me? in that case and if we can't repro, we should then close it.

**Comment by pchico83** [comment]
@rlamana AFAIK, only you. I haven't tried to repro it

**Comment by pchico83** [comment]
Closing it for now
