### ISSUE TITLE
Support for Apple Sillicon

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1240]
**Is your feature request related to a problem? Please describe.**
I want to run `okteto` on a machine with Apple Silicon natively, instead of via Rosetta

We need to do the following:
1. Update to syncthing 1.13
2. Build with golang 1.16
3. Update the 'get-okteto.sh' script to consider Darwin+ARM
4. Update our brew recipe to consider Darwin+ARM

**Comment by pchico83** [comment]
Fixed by #1239
