### ISSUE TITLE
Add nodeSelector and affinity options to Okteto manifest

### ISSUE THREAD

**Issue by lamphuc** [okteto/okteto#1245]
**Is your feature request related to a problem? Please describe.**
I want to strictly run my Okteto pods in special worker nodes e.g. GPU enabled.

**Describe the solution you'd like**
Add `nodeSelector` and `affinity` options to Okteto manifest that maps to `nodeSelector` and `affinity` in Kubernetes manifest.

**Describe alternatives you've considered**
2 alternatives to solve this problem:
- As suggested by @rberrelleza, I could pre-create a deployment with any configuration that I want and make the `okteto.yaml` to refer to that deployment. This may work but it involves extra steps for my users and hence, inconvenience workflow.
- I can write my own mutating webhooks to watch and update Okteto pod. This works too but requires extra efforts to solve the issue that can simply be done by Okteto itself.

**Additional context**
No more additional context.

**Comment by yahel2410** [comment]
We're looking for the same exact thing. Any progress on this?

**Comment by pchico83** [comment]
@lamphuc @yahel2410 the issue has been assigned to @jLopezbarb. We will work on it for the next release
