### ISSUE TITLE
okteto doesn't enable persistent volumes if only the size is defined

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1254]
**Describe the bug**
Ran okteto up with this manifest:
```
name: auth-depl
image: okteto/node:12
command: bash
sync:
- .:/usr/src/app
forward:
- 3001:3001
- 9230:9230
persistentVolume:
  size: 1Gi
```

The resulting dev env didn't have a volume attached. Adding `enabled: true` to the `persistentVolume` fixed the issue.

**Expected behavior**
Since I'm specifying a size, I should be getting the volume automatically enabled.

**Comment by pchico83** [comment]
Maybe https://github.com/okteto/okteto/blob/10a317d894e1674e690b4c8833230138e84d355e/pkg/model/volumes.go#L172 gets deprecated
