### ISSUE TITLE
okteto commands log "getCPUInfo for OS darwin: not implemented" in apple silicon

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1262]
**Describe the bug**
All okteto commands in Apple Silicon log the following:

``` 
"ERRO[0000] failure getting variant                       error="getCPUInfo for OS darwin: not implemented"
```

This is a known issue, caused by containerd. We need to update our dependencies for that message to go away. It doesn't seem to have any side effects besides the error.

**Comment by pchico83** [comment]
@rberrelleza is this already fixed?

**Comment by rberrelleza** [comment]
No, the issue is on containerd, they haven't fixed it yet.
