### ISSUE TITLE
Okteto up asking for creating a .stignore file should mention the affected folder

### ISSUE THREAD

**Issue by danny-stytch** [okteto/okteto#1266]
**Describe the bug**
When I run okteto up, it prompts me to initialize a .stignore even though one already exists in the directory.

![image](https://user-images.githubusercontent.com/70562257/107242189-93e85600-69e0-11eb-9e81-16addd8e7ae5.png)

I'm only getting an error for this service and my other services don't have this issue.

**To Reproduce**
Run `oketeto up` in a repo with a `.stignore` file. 

**Expected behavior**
It should use the existing .stignore file.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.4
 - Okteto version: 1.10.2

**Additional context**
Add any other context about the problem here (e.g okteto.yml, k8s manifests, logs)

**Comment by pchico83** [comment]
Hi @danny-stytch, what is the `sync` field of your okteto manifest?
`.stognore` files must be defined for each `sync` folder, we should make that clearer.

**Comment by danny-stytch** [comment]
Ah, that's the issue then. I added a new sync folder, and it doesn't have a `.stignore` yet.

**Comment by pchico83** [comment]
Cool, I will use this issue to track the work of making the info message clearer to mention the affected folder.
