### ISSUE TITLE
Can't deploy stack after deleting it

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1267]
**Describe the bug**
`okteto stack deploy --wait` failed to launch my stack after destroying it.

**To Reproduce**
- Deploy stack succesfully.
- Deploy same stack with different command, have it fail due to resources. 
- `okteto stack destroy`
- Try to deploy stack again

Stack failed to be deployed with the error below:
       x  error installing stack: cannot re-use a name that is still in use

I was blocked until I manually deleted the following secrets:

       kubectl delete secret sh.helm.release.v1.spago.v3 
       secret "sh.helm.release.v1.spago.v3" deleted

       kubectl delete secret sh.helm.release.v1.spago.v4 
       secret "sh.helm.release.v1.spago.v4" deleted

I didn't have any pending helm releases
       helm ls
      NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.10.6

**Comment by rberrelleza** [comment]
This might be the same root cause than #1269

**Comment by pchico83** [comment]
Fixed by #1333
