### ISSUE TITLE
Okteto Stack hangs when command fails to start

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1268]
**Describe the bug**
I ran an okteto stack, where the container failed with exit code 127 (due to me using an image without `sh` on it).

The cli waited forever, even if the kubernetes resource was already marked in CrashLoopBackoff for over 6 minutes.

```
okteto stack deploy --wait                        
⠇ StatefulSet is not ready: rberrelleza/spago. 0 out of 1 expected pods are ready... 
```

```
kubectl get pod
NAME      READY   STATUS             RESTARTS   AGE
spago-0   0/1     CrashLoopBackOff   6          6m20s
```

**Comment by pchico83** [comment]
Fixed by #1333
