### ISSUE TITLE
"cd": executable file not found in $PATH

### ISSUE THREAD

**Issue by yahel2410** [okteto/okteto#1270]
**Describe the bug**
Our team use remote development with okteto v1.9.4 & PyCharm for a while, using the procedure described here:
https://okteto.com/blog/remote-development-environments-with-pycharm/
However, when we upgrade to okteto v1.10.6, the PyCharm remote execution fails with this error:
```
ssh://root@localhost:2222/usr/local/bin/python -u /okteto/test.py
"cd": executable file not found in $PATH
Process finished with exit code 1
```

**To Reproduce**
1. Install okteto v1.10.6
2. Follow the procedure described here: https://okteto.com/blog/remote-development-environments-with-pycharm/

**Expected behavior**
The remote execution should succeed

**Desktop (please complete the following information):**
Same error on:
 - MacOS 11.1
 - MacOS 10.14.6
 - Ubuntu 20.04

**Additional context** - okteto.yml:
```
namespace: yahel
name: data-test

annotations:
  janitor/ttl: "3h"

forward:
  - 8899:8899       # jupyter notebook port

image: okteto/python:3

volumes:
  - /root/.cache/pip
  - /root/.local/lib/python3.9/site-packages
  - /root/.local/bin/

sync:
  - .:/okteto

workdir: /okteto
remote: 2222
```

**Comment by rberrelleza** [comment]
@yahel2410 What does the file  /okteto/test.py looks like? I'm trying to figure out where the call to `cd` is happening, but haven't been able to reproduce it.

**Comment by rberrelleza** [comment]
Nevermind, I have a repro, looking at the root cause of the issue.

**Comment by rberrelleza** [comment]
This will be fixed in the next release!

**Comment by yahel2410** [comment]
Hi @rberrelleza, thanks for the quick response and solution!

**Comment by yahel2410** [comment]
I can confirm this issue is fixed, thanks @pchico83
