### ISSUE TITLE
split configuration of healthchecks into separate fields for liveness and readiness

### ISSUE THREAD

**Issue by cameronbraid** [okteto/okteto#1296]
I would like to run with the readiness probes that my deployment defines.  

This way when I am not running/debugging the app in my container, the deployment pod's endpoints wont be exposed via services.

However I wish to disable the liveness probe, otherwise my container will get restarted over and over again.

Suggest configuring using a struct with fields

```
healthchecks:
  liveness: boolean
  readiness: boolean
```

**Comment by pchico83** [comment]
@cameronbraid this is not available in Okteto 1.11.5.
We have taken this opportunity to rename the field to `probes` to use the same notation than kubernetes:
https://okteto.com/docs/reference/manifest#probes-boolean-optional

**Comment by cameronbraid** [comment]
Perfect, thanks :)
