### ISSUE TITLE
Would you like me to add the GitHub Super-Linter ??

### ISSUE THREAD

**Issue by jbampton** [okteto/okteto#1369]
**Is your feature request related to a problem? Please describe.**

We can lint and test most file types like Markdown, Shell, YAML and others.

**Describe the solution you'd like**

Add the GitHub Super-Linter for more testing.

**Describe alternatives you've considered**

Individual GitHub Actions for each language.

**Additional context**

- https://github.com/github/super-linter
- https://github.com/marketplace/actions/super-linter

**Comment by rberrelleza** [comment]
yeah, I think this would be pretty useful, since we have shell scripts, go, Dockefile and markdown on the repository.

**Comment by rberrelleza** [comment]
This is running now!
