### ISSUE TITLE
Environment variables without the = sign are not getting populated

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1399]
**Describe the bug**
When using the following okteto.yaml:
```
name: hello-world
image: nginx:alpine
environment:
- MY_VAR
```

The $MY_VAR env var is not getting populated when doing `okteto up`. The  `MY_VAR`  variable exists, but the value its empty.

**Expected behavior**
Based on our docs, the value should be populated if `MY_VAR` exists in my environment.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.12.5

**Comment by pchico83** [comment]
@jLopezbarb this should also be the case for Okteto Stacks. Not sure if it works there
