### ISSUE TITLE
There's a strange warning when using my own build of the bin container

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1418]
**Describe the bug**
There's a strange warning when using my own build of the bin container

**To Reproduce**
1. Build your own bin image
2. `export OKTETO_BIN=user/bin:dev` 
3. okteto up
![image](https://user-images.githubusercontent.com/475313/114968211-85347a00-9e3b-11eb-8799-06d72fe58a10.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version latest from master

**Comment by pchico83** [comment]
You need to rebuild the `bin` image with the Okteto CLI version:
https://github.com/okteto/okteto/blob/master/images/bin/Dockerfile#L17
