### ISSUE TITLE
"okteto namespace" not working if KUBECONFIG points to several files

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1433]
**Describe the bug**
I have `KUBECONFIG=~\.kube\config; ~\.kube\okteto-kube.config`.
`okteto namespace` modifies `~\.kube\config;`, but `okteto up` is taking the content of `~\.kube\okteto-kube.config`.
Then, `okteto up` is timing out if `~\.kube\okteto-kube.config` is pointing to a wrong okteto context.

**Comment by gerundium** [comment]
Had the same issue. Stripping down the environment variable "KUBECONFIG" to one location and rerun "okteto login" worked for me. Thank you for the quick help!
