### ISSUE TITLE
Omit well known ports from being public

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#1442]
**Is your feature request related to a problem? Please describe.**
I want to avoid well known ports like the ones from mongodb, mysql, rabbit... to expose a service.

**Describe the solution you'd like**
If the service has one of these ports it should be always private and don't expose any service.

**Comment by pchico83** [comment]
@jLopezbarb the service could have other public ports. I would just ignore the check of `hostPort` for these well-known ports
