### ISSUE TITLE
Add logo to Okteto stack

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#1443]
**Is your feature request related to a problem? Please describe.**
I want to be able to display a logo on the web to my Okteto stack so I can see at a glance which stack is deployed

**Describe the solution you'd like**
Adding a logo field to Okteto stack where you can enter a logo  to show it in the web

**Comment by pchico83** [comment]
This requires changes in the backend & frontend too

**Comment by pchico83** [comment]
We will be unifying stacks and pipelines, this will be part of that unifycation
