### ISSUE TITLE
Better error if namespace cannot be created

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1452]
**Describe the bug**

I am hitting my namespace quota, and I am getting this error:

```
$ okteto create namespace
x failed to create namespace
```

**Expected behavior**
A more descriptive error

**Comment by jLopezbarb** [comment]
Are you sure the error is because you hit your namespace quota? 
The error I'm getting is  `x  you have exceeded your namespace quota, please contact your administrator to increase it`

**Comment by pchico83** [comment]
@jLopezbarb I think it was because a non allowed char, I think it was `/`
