### ISSUE TITLE
Unable to execute Okteto:up with environment variables set

### ISSUE THREAD

**Issue by SteveCurran** [okteto/okteto#1535]
**Describe the bug**
Trying to set environment variables in okteto manifest and I receive "- line 4: cannot unmarshal !!map into []model.EnvVar" error

**To Reproduce**
Try deploy the below manifest to AKS and receive the above error from OktetoUp

**Expected behavior**
Is there a correct way of doing this?
**Desktop (please complete the following information):**
 - OS: Windows 10/VSCode
 - Version 0.2.1

**Additional context**
name: aks-development
image: okteto/golang:1.15
environment:
- TESTCUSTOMER: testcalicodev
namespace: sectest
autocreate: true
command: bash
securityContext:
  capabilities:
    add:
    - SYS_PTRACE
volumes:
- /go/pkg/
- /root/.cache/go-build/  # persist go build cache
- /root/.vscode/    # persist vscode extensions
sync:
- .:/usr/src/app
forward:
- 2345:2345
- 8080:8080
persistentVolume:
  enabled: true

**Comment by SteveCurran** [comment]
Checked the manifest reference example:

environment:
- 'TESTCUSTOMER=testcalico'
-  'WHATEVER=true'

**Comment by pchico83** [comment]
@jLopezbarb could we support both notations as we do for Okteto Stacks?
Same for labels and annotations

**Comment by jLopezbarb** [comment]
It is already like that. The problem here is that we don't support this syntax:
```
environment:
  - TESTCUSTOMER: testcalicodev
```

The accepted syntax are:
```
environment:
  - TESTCUSTOMER=testcalicodev
```
or 
```
environment:
  TESTCUSTOMER: testcalicodev
```

**Comment by pchico83** [comment]
Cool! Thanks @jLopezbarb
