### ISSUE TITLE
support statefulset please

### ISSUE THREAD

**Issue by romberli** [okteto/okteto#1615]
**Is your feature request related to a problem? Please describe.**
we're working on deploying database on the kubernetes as statefulset, and it's very hard to debug remotely,
okteto is very useful to develop deployment application, but it seems that it does not support statefulset.

**Describe the solution you'd like**
okteto supports statefulset, works like deployment

**Describe alternatives you've considered**
okteto should simulate the network, pvc and so on, mount appropriate storage

**Additional context**

**Comment by pchico83** [comment]
Hi @romberli 
We have received this feedback several times. We have an ongoing branch to support stateful sets, but I don't have a date for it to be ready yet.

**Comment by romberli** [comment]
Hi @pchico83 ,thanks for your reply.
Is there any early version that we can have a test?

**Comment by pchico83** [comment]
@romberli not yet, but we will update the branch to be in a working state and let you know

**Comment by romberli** [comment]
@pchico83 , thanks in advance

**Comment by pchico83** [comment]
@romberli you can have a look to this branch:
https://github.com/okteto/okteto/pull/1631

**Comment by romberli** [comment]
> @romberli you can have a look to this branch:
> #1631

thanks a lot for your work
