### ISSUE TITLE
analytics command accepts an argument but expects a flag

### ISSUE THREAD

**Issue by chris-crone** [okteto/okteto#1628]
**Describe the bug**
The analytics command accepts an argument (like disable) but expects only flags.

**To Reproduce**

1. Run `okteto analytics disable`
2. See ` ✓  Analytics have been enabled`

**Expected behavior**
I would expect the command to exit with a non-zero status code and a message along the lines of "unexpected argument" along with the help being printed out

**Desktop (please complete the following information):**

```console
➜  ~ okteto version  
okteto version 1.13.0
```

**Comment by pchico83** [comment]
@chris-crone thanks for the feedback!
@jLopezbarb we probably need to validate the number of `args` is most of our commands
