### ISSUE TITLE
Feature Request: Add the ability to disable the security context

### ISSUE THREAD

**Issue by mrpresidentjk** [okteto/okteto#1658]
**Is your feature request related to a problem? Please describe.**

Provide a mechanism to disable security context in order support OpenShift non-root containers .

**Additional context**

By default OpenShift limits containers to run as a non-root user that has a randomly generated UID. 

This UID falls within a set range that is allocated to the project.  You can find this range by running the following command:

```
oc describe project <project name>

....
Annotations:    openshift.io/description=
                        openshift.io/display-name=
                        openshift.io/requester=developer
                        openshift.io/sa.scc.mcs=s0:c25,c10
                        openshift.io/sa.scc.supplemental-groups=1000620000/10000
                        openshift.io/sa.scc.uid-range=1000620000/10000
```
I really like Okteto and I want to be able to use it with OpenShift 4, however this means that we have to explicitly set the `runAsUser` parameter to a UID in these ranges. This is painful in a namespace per developer setup, especially when storing the manifest in Git.

It would be awesome if there was a way we could tell the tool to disable the security context  as Okteto currently defaults to the root user. 

I firmly believe in the value this project provides, and I wouldn't mind having a crack at contributing if this is something that you guys don't have time to look at.

**A potential solution**

A lot of helm charts allow you to disable pod and container security contexts. This could be used to resolve this problem as not setting them would allow OpenShift to automatically set them.

The Okteto manifest could look like this:

```
...
securityContext:
    enabled: false
```
This would prevent the security context from being set.

It does not really follow the Kubernetes specification closely though.

**Comment by mrpresidentjk** [comment]
Sorry updated this issue to make it clearer

**Comment by pchico83** [comment]
@mrpresidentjk it would be awesome if you can contribute to the implementation since it is hard for us to replicate an Openshift realistic environment.

We require to specify the container user because, by default, okteto mounts a persistent volume (PV) and it needed to set the value of `fsGroup`. Would it be possible to get the user openshift is using at run time?

**Comment by mrpresidentjk** [comment]
Hi @pchico83, thanks for your reply! If `fsGroup` is unset OpenShift should set it to the ID of the user belonging to the pod. 

For further context I was able to modify the [setRunAsUserDefaults](https://github.com/okteto/okteto/blob/3680cafbe308d7f8d61fcbbd8cb8c4d803484ea2/pkg/model/dev.go#L569) function to not set the security context if it is disabled. The code looked something like this:

```
func (dev *Dev) SecurityContextEnabled() bool {
        if dev.SecurityContext == nil  {
                return true
        }
        if dev.SecurityContext.Enabled == nil {
                return true
        }
        return *dev.SecurityContext.Enabled
}

func (dev *Dev) setRunAsUserDefaults(main *Dev) {
        if !main.PersistentVolumeEnabled() {
		return
	}
        if !main.SecurityContextEnabled() {
                return
        }
        if dev.SecurityContext == nil {
                dev.SecurityContext = &SecurityContext{}
        }
	if dev.SecurityContext.RunAsUser == nil {
		dev.SecurityContext.RunAsUser = &rootUser
	}
	if dev.SecurityContext.RunAsGroup == nil {
		dev.SecurityContext.RunAsGroup = dev.SecurityContext.RunAsUser
	}
	if dev.SecurityContext.FSGroup == nil {
		dev.SecurityContext.FSGroup = dev.SecurityContext.RunAsUser
	}
}
```
I was then able to launch a development container using the following manifest:
```
name: example
labels:
  app: example
command:
  - 'bash'
workdir: /usr/src/app
securityContext:
   enabled: false
image: 'python:3'
remote: 22222
sync:
 - ./:/usr/src/app
```
Values for `fsGroup` and `runAsUser` were then automatically set to `1000630000` which was the OpenShift user.

Let me know if you guys think that this is something that fits with your application. I am more than happy to continue, and eventually open a pull request.

**Comment by pchico83** [comment]
@mrpresidentjk awesome! Sorry for the late response, I have been on holiday these days and I forgot to assign the issue to someone else.
Yes, I like the `Enabled` approach, let's go with it!

**Comment by mrpresidentjk** [comment]
@pchico83 Not at all, sorry for being MIA. I finally got the chance to look at this again this weekend. After thinking about this more, I felt that it would make more sense to solve this issue by allowing users to override the `runAsNonRoot` option in the manifest. I have opened a pull request with a hefty description that explains this in detail. Let me know what you guys think about it!
