### ISSUE TITLE
Okteto: Up failed to load your Okteto manifest: Cannot read property 'matchAll' of undefined

### ISSUE THREAD

**Issue by dmuiX** [okteto/okteto#1678]
**Describe the bug**
This error is shown if I try to use okteto up. Happened just today. Might be related to update vs code to a newer version:
1.58.2
okteto version current 1.13.2

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by dmuiX** [comment]
okay I could solve it. Update of the kubernetes extension did the trick. Maybe next time I wait some days before I update my vs code until the update of the kubernetes extension is also getting updated. Do you know when this is normally the case?

**Comment by dmuiX** [comment]
Had another issue. Okteto was stopping with a failrure. Downgrade to vs code version 1.58.1 did the trick. So next time I will definitely wait minimum a month before I do the vs code upgrade.

**Comment by rberrelleza** [comment]
@dmuiX this was caused due to a regression on https://github.com/okteto/remote-kubernetes. Upgrading to version 0.3.3 should fix this. But if it doesn't, could you let us know?
