### ISSUE TITLE
Actually is it possible to deactivate the automatic update mechanism?

### ISSUE THREAD

**Issue by dmuiX** [okteto/okteto#1679]
**Describe the bug**
 I am using the okteto binary setting to link to my own okteto.exe path. And here I had the older version 1.13.1. But everytime I try to use it with okteto up it is getting updated...

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by rberrelleza** [comment]
@dmuiX is this on the okteto CLI or on the vscode extension?
