### ISSUE TITLE
Okteto exec command freezes when there are connectivity issues

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#168]
**Describe the bug**
cnd exec command freezes when there are connectivity issues, or when my mac goes to sleep. For example, if I run `cnd exec sh`, and then I turn off the Wifi, wait a minute, and turn it back on, the sheel freezes, and I can't exit it other than by killing the process.

**To Reproduce**
Steps to reproduce the behavior (using the vote sample)
1. `cnd exec sh`
2. Run a never ending command: `while [[ 1 ]]; do date && sleep 1; done;`
3. Sleep your mac
4. Wake up

**Expected behavior**
The command should exit cleanly on ctrl+c

**Desktop (please complete the following information):**
 - OS: macos
 - Version 0.4.4

**Comment by rberrelleza** [comment]
Waiting on https://github.com/kubernetes/client-go/issues/554 to get some clarity

**Comment by pchico83** [comment]
Closed by #245
