### ISSUE TITLE
Logs from an internal library are leaking into the GitHub action

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1731]
![image](https://user-images.githubusercontent.com/475313/131381443-636c6c64-4f2c-43ec-a0fa-d24931b68cf5.png)

**Comment by jLopezbarb** [comment]
I could not reproduce it. I think this was solve by https://github.com/okteto/deploy-preview/pull/26. @rberrelleza can you confirm it's already fixed?

**Comment by rberrelleza** [comment]
It's not fixed yet. The change I did was to pin to a specific version of the dependency before the warning appeared. The moment we unpin that the message will pop up again. 

We need to wait for octokit to fix the dependency.

**Comment by shepting** [comment]
Looking forward to seeing this get sorted out as well.
