### ISSUE TITLE
Overwrite kubeconfig endpoint value

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#174]
**Is your feature request related to a problem? Please describe.**
My KubeAPI is exposed through a jump box.

**Describe the solution you'd like**
Overwrite my kubeconfig cluster endpoint from `okteto up` to avoid modifying the original kubeconfig. With this, I can expose the k8 endpoints via a SSH tunnel, and still run my `okteto` commands locally.

**Comment by rberrelleza** [comment]
@pchico83  Do you think this should come from `cnd.yml` or from a param? 

If we go with the manifest approach: Once you do `cnd up` , should all other calls (exec, run, down) automatically use the same endpoint as before?

**Comment by pchico83** [comment]
It would go with a parameter, stored in our internal state to be used in exec, run, down...
Optionally, it could be in the manifest too, but low priority.

**Comment by pchico83** [comment]
This is not longer a requirement
