### ISSUE TITLE
Splitted output information when running `okteto up`

### ISSUE THREAD

**Issue by rlamana** [okteto/okteto#1855]
When starting `okteto up` we can now see the context and the namespace right away. The problem is that the way it is displayed looks exactly like the info table shown below when the command finishes, giving it an splitted/broken look:

![image](https://user-images.githubusercontent.com/237819/138070013-56e475b5-4795-4d4c-abb1-ae096bad6b95.png)

As a suggestion, we could change the context output to look like a subtle reminder before starting, and keep the complete output later. Here is an example of how the output could look:

![Frame 8](https://user-images.githubusercontent.com/237819/138070437-882a0798-6294-4925-add3-cf1017556a7f.png)

**Comment by rberrelleza** [comment]
What do you think about removing the `as context` part @rlamana ? I feel it's kind of redundant.
