### ISSUE TITLE
`okteto up` should deploy the pipeline if it's not deployed

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1910]
**Is your feature request related to a problem? Please describe.**
I cloned my repo and run `okteto up`. It doesn't work because I didn't deploy my app

**Describe the solution you'd like**
Automate the execution of `okteto deploy` when running `okteto up` if my app is not deployed

**Comment by jmacelroy** [comment]
@pchico83 is this still valid or is the behavior covered with 'autocreate'?

**Comment by pchico83** [comment]
@jLopezbarb it's still valid. @jLopezbarb is working on it
