### ISSUE TITLE
"Okteto list namespace " command should display the status instead of just if it is sleeping or not

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#1916]
**Is your feature request related to a problem? Please describe.**
As we are having different namespace status, make sense to display the status in the CLI instead of just showing if the namespace is sleeping or not.

**Describe the solution you'd like**
I would like to see the namespace status in the list command, something similar to:

```
Namespace                Status
namespace-1             Active
namespace-2             Inactive
namespace-3             Destroying
```

**Describe alternatives you've considered**
-

**Additional context**
Sleeping flag is being deprecated in the API in favor of Status

**Comment by pchico83** [comment]
@jLopezbarb are we showing something similar for preview environments?

**Comment by jLopezbarb** [comment]
We are only showing the scope and if it's sleeping or not for each preview
