### ISSUE TITLE
Allow to override readOnlyRootFilesystem

### ISSUE THREAD

**Issue by vflaux** [okteto/okteto#1970]
**Is your feature request related to a problem? Please describe.**
My app container run with `securityContext.readOnlyRootFilesystem = true`.
I want to use okteto without Persistent Volumes (as there is no pv available in the cluster) but the init container fails as the root file system is in read only.
```
cp: cannot create regular file '/usr/src/app/.stignore': Read-only file system
```

**Describe the solution you'd like**
In the okteto config file, add a `securityContext.readOnlyRootFilesystem` option to override the one in the deployment manifest.

**Describe alternatives you've considered**
Allow to use emptyDir volumes.
Instead of failing when `volumes` are defined and `persistentVolume.enabled = false`, okteto could use emptyDir volumes.

Edit: Second option may be better as if you are also forbidden to run as root you have no choice but to use a Volume. The `/usr/src/app` is owned by root in the okteto images (at least okteto/golang).

**Comment by pchico83** [comment]
@vflaux would you like to work on a PR?
We already have a `securityContext` section, it's a matter of adding `readOnlyRootFilesystem` there:
https://github.com/okteto/okteto/blob/5c7e8590e25b8a353af1e7647357d6dddaeb75b6/pkg/model/dev.go#L190

If you don't have time, let me know, I will schedule this issue for December.
