### ISSUE TITLE
Support for `okteto logs` command

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1982]
**Is your feature request related to a problem? Please describe.**
I have several services running in my namespace and I need an easy way to query logs across containers, pods, deployments, ...

**Describe the solution you'd like**
An `okteto logs` command that, by default, shows all the output generated by the containers in my namespace in the last 5m. It could have labels to filter the output by service, to show/hide timestamps and to follow logs in streaming. Also, each log line will show the container and the pod name generating that line.

**Comment by jLopezbarb** [comment]
@maroshi Is this issue fixed by #2120?

**Comment by maroshii** [comment]
This will be fixed by #2120 yeah but there's still some debate around how it should work
