### ISSUE TITLE
A command to list the resources of my namespace.

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1984]
**Is your feature request related to a problem? Please describe.**
If I go to the Okteto UI I have a summary of the resources running in my namespace and their state. I have things grouped by pipeline, stack, or helm chart. But there is no way to get this information from the Okteto CLI.

**Describe the solution you'd like**
A command that shows a similar output to what you get in the Okteto UI

**Comment by RinkiyaKeDad** [comment]
Hey @pchico83! I'd like to work on this. When you say "list the resources of my namespace" do you mean showing the names of the kubernetes objects present (for example api and frontend deployements in the image below) in the `movies` pipeline?

Also is there a place we could query this information from? Thanks!


![image](https://user-images.githubusercontent.com/56963264/143199360-adbb7312-f9cb-4fb7-ae16-fbc9240b446d.png)

**Comment by pchico83** [comment]
Thanks @RinkiyaKeDad . This one requires some refactor between the okteto backend and the okteto cli.
