### ISSUE TITLE
feat: support contextless okteto down (--all)

### ISSUE THREAD

**Issue by ShragaUser** [okteto/okteto#2001]
**Is your feature request related to a problem? Please describe.**
I deploy using several helms into one namespace, and use okteto to spin up dev containers for specific services.
The issue is that I can't upgrade my deployment before first shutting down all dev containers. That means I have to always be aware of dev containers, okteto manifest files etc'

**adding to that**:
I create one namespace that holds several deployments, some of which are held in different code repos. 
so I have one/more manifests per repo, with similar namespace and configs, but different sync files, repo and images. 

**Describe the solution you'd like**
I would like there to be an option to run `okteto down --all` (or anything similar) that does not depend on any specific manifest file, but can "find" (or have saved from before) all okteto dev containers currently running and specifically shut them down.

**Describe alternatives you've considered**
the most straight forward solution would be to "know" all available okteto manifest files available and try shutting them down (regardless of their status) before running a deployment \ helm upgrade. 
the issue I have with this is that I dont want to assume that I know all the locations of every manifest file (multi-repo, can be in different locations in the file directory).

**Additional context**
I love this project, think its insanely cool and would love to contribute, maybe even take this as a first PR if thats an option (and after we agree and finalize an idea for a solution)!

**Comment by pchico83** [comment]
@ShragaUser makes sense. I think we will do something similar with `okteto destroy --all`

**Comment by jLopezbarb** [comment]
Closing because it's already implemented
