### ISSUE TITLE
Create a node image with the LTS node version

### ISSUE THREAD

**Issue by lukasm0** [okteto/okteto#2002]
We are using the current LTS version of node (v16.13.0, with npm v8.1.0) in our project.
The most recent okteto:node image that exists is for version 14 (v14.18.1, with npm v6.14.15).

If you run "npm install" on the okteto development container you will get version missmatches because npm v6 works with package-lock.json version 1 while npm v7+ uses package-lock.json version 2. 

--> Please create a okteto:node:16 image.

**Comment by pchico83** [comment]
Hi @lukasm0, thanks for the feedback.
Would you mind sending a PR? Our node image is defined here:
https://github.com/okteto/devenv/blob/main/docker-compose.yml#L63

**Comment by lukasm0** [comment]
https://github.com/okteto/devenv/pull/92
