### ISSUE TITLE
Okteto CLI releases affect to other components release/CI pipelines

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2012]
**Describe the bug**
When there is an ongoing CLI release, it seems that temporary it is not available in https://github.com/okteto/okteto/releases/latest/download/okteto-Linux-x86_64 and other components release or CI pipelines fail.

I don't know for how long it happens.

It happened to me doing a pipeline-installer-image release

![Captura de pantalla 2021-11-24 a las 13 10 55](https://user-images.githubusercontent.com/3510171/143236135-4a7bdd21-99a1-4dfd-afce-d7799627a888.png)

**To Reproduce**

1. During a CLI release
2. Try to download the CLI

**Expected behavior**
Ideally, there shouldn't be any interruption to download. Not sure if there is something we can do here.
Maybe other option is to download the CLI from other part for the CI pipelines

**Desktop (please complete the following information):**
-

**Additional context**
-

**Comment by jLopezbarb** [comment]
This one is fixed by the new release pipeline since we have no downtime on the script now
