### ISSUE TITLE
Support `--context` flag in any okteto command that supports `--namespace`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2022]
**Is your feature request related to a problem? Please describe.**
I want to run an okteto comman in a different context than my current okteto context.

**Describe the solution you'd like**
Have to uption to run `okteto up --context staging` if I want to run my okteto command in a particular context

**Comment by pchico83** [comment]
@AgustinRamiroDiaz we should support `--context` in:
- `okteto build`
- `okteto deploy`
- `okteto up`
- `okteto down`

**Comment by AgustinRamiroDiaz** [comment]
@pchico83 All those commands except `build` have that option. The option is used with the url like `okteto deploy --context https://cloud.okteto.com`

I'll add the option for build.

**Comment by AgustinRamiroDiaz** [comment]
Seems like the deploy command doesn't work properly since it need the build to work in the correct context. I think that after I implement the context flag for the build command it'll work as expected
