### ISSUE TITLE
Beta release channel

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2039]
**Is your feature request related to a problem? Please describe.**
Support a beta release channel to make it easier to test experimental or breaking features without affecting all users.

**Describe the solution you'd like**
We can do something similar to https://github.com/syncthing/syncthing

**Comment by jmacelroy** [comment]
What is it that syncthing does that you'd like to emulate? It looks like they are using branches to create rc, or release candidates. I thought we wanted to avoid a branch and keep using main? 

I think it may be easier and allow us to make progress to simply figure out how to merge experimental features into main while not having them in the release. This could be done with build tags or possibly adding a switch to the cli? After we do that we can figure out how to build and release binaries that use that strategy?

**Comment by pchico83** [comment]
@jmacelroy I haven't thought about it yet, we could explore what other tools like syncthing, helm or kubectl does. 

I agree on keeping things simple and use a single branch.

Ideally, I would like to have the latest stable release, and a beta release. And make it possible to install both of them with `brew` and `curl` in an easy way.
