### ISSUE TITLE
`okteto namespace` version II

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2043]
**Is your feature request related to a problem? Please describe.**
I need a better way to switch my okteto context namespace

**Describe the solution you'd like**
- `okteto namespace` won't modify the kubernetes context anymore. In order to do that, we have to implement `okteto kubeconfig`, and alias of `okteto kubeconfig update`
- `okteto ns` is an alias of `okteto namespace`
- `okteto namespace`(alias for `okteto namespace use`) :  with no arguments, works similar to `okteto context` and shows a list of available namespaces or gives the option to create one. With an argument, it uses that namespace:
Output:
```
✓ Using pchico83 @ [cloud.okteto.com](http://cloud.okteto.com/) as context
 i  Run 'okteto kubeconfig update' to update your kubectl credentials
```
- `okteto namespace create`: creates a namespace. `okteto create namespace` is deprecated.
- `okteto namespace delete`: deletes a namespace. `okteto delete namespace` is deprecated.
- `okteto namespace list`: list available namespaces. `*` for current namespace. `okteto list namespace` is deprecated.

**Additional context**
This is a breaking change and it should be released on 1.15-beta

**Comment by jmacelroy** [comment]
Is it correct to assume that we can't merge any progress on this into the main branch until we figure out how to isolate it as beta/experimental?

**Comment by pchico83** [comment]
@jmacelroy that's right. this is a breaking change that must go on 1.15. And I would like to have a beta channel in place before releasing 1.15
