### ISSUE TITLE
feat: allow port ranges in "forward" / "reverse" props in manifest

### ISSUE THREAD

**Issue by ShragaUser** [okteto/okteto#2051]
**Is your feature request related to a problem? Please describe.**
feat: allow port ranges in "forward" / "reverse" props in manifest

**Describe the solution you'd like**
i'd like it to support port ranges in the same manner docker-compose does
see: https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

**Additional context**
I personally needed this to support remote debugging (attach to process) with rubymine using debase & ruby-debug-ide (launches subprocesses that dispatch at random ports in range). 
see: https://github.com/ruby-debug/ruby-debug-ide/issues/73

**Comment by pchico83** [comment]
@ShragaUser how large is your port range? would it work if you specify one by one for now?

**Comment by ShragaUser** [comment]
@pchico83 the port range in my specific use case is in the hundred's so wouldn't be possible to do this one by one. But this isn't urgent as I've handled the situation differently (running a remote interpreter instead of attaching to a remote debug process)
