### ISSUE TITLE
Support for `env_file` in the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2053]
**Is your feature request related to a problem? Please describe.**
I have several `.env` files I would like to reuse in my dev container.

**Describe the solution you'd like**
Similarly to Okteto Stacks, support `env_file` in my okteto manifest:
https://okteto.com/docs/reference/stacks/#env_file-string-optional

**Comment by jLopezbarb** [comment]
We use camel case syntax for okteto manifest. Should it be `envFiles`?

**Comment by pchico83** [comment]
@jLopezbarb yes!
