### ISSUE TITLE
Support for `okteto preview destroy --wait`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2057]
**Is your feature request related to a problem? Please describe.**
I am scripting some tests and I need to know when a preview environment is destroyed. Right now, the preview namespace can stay in `Terminating` state for a while.

**Describe the solution you'd like**
Implement a `--wait` flag that makes sure the namespace is gone.

**Comment by nitishfy** [comment]
I noticed there are a [lot of issues](https://github.com/okteto/okteto/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) with the label **_help-wanted_** being assigned/unassigned. There are no updates from the assignee over the issues for a long time. I'll start fixing these issues now, starting with this one. 

@pchico83 Please assign this to me.

**Comment by pchico83** [comment]
@nitishfy I assigned it to you, thanks!

**Comment by nitishfy** [comment]
@pchico83 Could you try explaining with more information?

- Do we intend to create only a `--wait` flag?

**Comment by jLopezbarb** [comment]
> @pchico83 Could you try explaining this issue with a little more information?
> 
> * Do we intend to create only a `--wait` flag?
> * How will the output differ when we use `--wait` flag with `okteto preview destroy`?

We'd need to create the `--wait` flag on the preview destroy command and after the current execution execution is completed, we must check that the preview namespace is completely removed. We can do this by listing the previews every x seconds (we'd need to define it, but 1 second is ok) until the name of the preview is no longer on the list
