### ISSUE TITLE
`okteto build` is not equivalent to the `docker build` behavior for dockerignore files

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2098]
**Is your feature request related to a problem? Please describe.**
This is the docker behavior:

```
The Docker client tries to load <dockerfile-name>.dockerignore first and then falls back to .dockerignore if it can't be found. So docker build -f Dockerfile.foo . first tries to load Dockerfile.foo.dockerignore.
```

**Comment by syntastical** [comment]
I was just coming here to submit this.  This would REALLY help me out.

**Comment by jmacelroy** [comment]
The Docker client tries to load `<dockerfile-name>.dockerignore` first and then falls back to `.dockerignore` if it can't be found. So `docker build -f Dockerfile.foo .` first tries to load Dockerfile.foo.dockerignore.

**Comment by jmacelroy** [comment]
@jLopezbarb do you have some time to look at this one?
