### ISSUE TITLE
Failed to create subPath directory for volumeMount {volume} of container {container}

### ISSUE THREAD

**Issue by userneeds-ahe** [okteto/okteto#2108]
**Describe the bug**
Running `okteto up` for the first time, this prevents me from proceeding.

**To Reproduce**

1. With no prior oktekto.yml manifest, okteto creates one on the fly when running `okteto up` 

**Expected behavior**
A working development environment to be running. 

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
I tried commenting-out the auto-created volumes directive, to no avail.

**Comment by rberrelleza** [comment]
@userneeds-ahe could you provide a sample / repro steps for this? We haven't been able to figure out the scenario.

**Comment by pchico83** [comment]
@userneeds-ahe was this a temporal issue? or was it a persistent error?
