### ISSUE TITLE
Refactor the `GetManifestV2` logic

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2111]
The logic of `GetManifestV2` should handle everything about reading manifest. This way, the caller doesn't need to know if it's reading an old manifest, a pipeline or a v2 manifest. The interface should be `GetManifestV2(path string)`, with `path` being optional. 

If `path` isn't specified, the logic should do something similar to the `GetManifest` function.

Also, all these functions shouldbn¡t be in the `context` package. They should be in the `model` package close to the manifestV2 struct definition.

We should also have unit tests for type of files and manifests.

**Comment by jmacelroy** [comment]
Does `model` package make sense? It seems generic and fairly non-specific, can any struct or data model be put there? With such a large application would it make more sense to have it in a more specific package like`manifest`?

Generic package names are something we've begun to address in the backend and I'm wondering if it makes sense here.

**Comment by jmacelroy** [comment]
Also, I wonder if a type switch is better than an "optional" param. There's not really a good way of doing optional params in golang and I think type switches are more common then different implementations can be used from there, sometimes by a different struct with receivers implementing the same interface then path is part of the struct.

I think the main point is that we could benefit from a re-factor but I think I wanted to refactor away from some of the patterns that caused the issue and I don't know if this exactly solves that. We should probably sync up a bit to talk and see what we think and agree upon @pchico83 and @jLopezbarb

**Comment by jLopezbarb** [comment]
I don't think we will need a type switch for that kind of problem, we can check if the path is empty and if it is then we can look for all the okteto files (dev, pipeline, compose) and merge them into the manifest struct

since we are going to change that, I would like to propose that each type should have its declaration, serialization, reading and validation in separate files. This would help a lot to make the serialization files not as large and difficult to read, specially dev and stack. 
What do yo think?

**Comment by pchico83** [comment]
+1 for @jLopezbarb suggestion. A part of the refactor into smaller packages, it's important to have a single function to read a manifest, independently of being a v2 dev manifest, a pipeline, a v1 dev manifest (or a stack -- we can do this one later). The final struct should be agnostic about the type of file used
