### ISSUE TITLE
Support for export-cache in `okteto build`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2126]
**Is your feature request related to a problem? Please describe.**
I want to export my build-cache after running `okteto build`. This way I can reuse it for future builds.
This is how cache is exported with buildkit:
https://github.com/moby/buildkit#export-cache

This is the code for cache imports, which is very similar to cache exports:
https://github.com/okteto/okteto/blob/master/pkg/cmd/build/buildkit.go#L119

**Describe the solution you'd like**
Have the `okteto build` flag `--export-cache`. If the specify tag is the same we are building, use buildkit `mode=min` option. Otherwise, use buildkit `mode=max` option.

This option should be also supported in okteto stacks and the new `build` section of the okteto manifest v2.

**Describe alternatives you've considered**
We could use `inline`export cache by default, but in general, it slows things. I think we would be optimizing the corner case there. But we exporting the cache is an interesting option for advanced users.

**Comment by jmacelroy** [comment]
I'm not sure I understand the solution and the options we want when `--export-cache` is present or not. 

When `--export-cache` is provided should we use the `registry` exporter and add the option of `mode=max`?

When `--export-cache` is provided should we use the `inline` exporter and leave mode at the default of `mode=min`?

**Comment by pchico83** [comment]
@jmacelroy `mode=max` is only supported if you push the cache to a different image than the one your are building. Therefore, I would infer it automatically. If you do `okteto build -t okteto.dev/api:dev --export-cache okteto.dev/api:test` we infer mode=mix, if you do `okteto build -t okteto.dev/api:dev --export-cache okteto.dev/api:cache` we infer mode=max

**Comment by RinkiyaKeDad** [comment]
>  If you do `okteto build -t okteto.dev/api:dev --export-cache okteto.dev/api:test` we infer mode=mix, if you do `okteto build -t okteto.dev/api:dev --export-cache okteto.dev/api:cache` we infer mode=max

@pchico83 In both the cases the tags are different - is that a typo? Did you mean:

If you do `okteto build -t okteto.dev/api:dev --export-cache okteto.dev/api:dev` we infer mode=min, if you do `okteto build -t okteto.dev/api:dev --export-cache okteto.dev/api:cache` we infer mode=max?

And in both the cases we use the `registry` exporter, right?

**Comment by teresaromero** [comment]
@RinkiyaKeDad @pchico83 the PR is ready to merge, should this be documented? should i do a draft at the docs?

**Comment by teresaromero** [comment]
tested at release 2.2.0-rc-1 - ok
moved to done
