### ISSUE TITLE
Unpin google.golang.org/grpc v1.40.0

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2129]
While introducing a new dependency the grpc package has been updated. 

````
❯ go get github.com/google/go-containerregistry
````
```
go get: upgraded google.golang.org/grpc v1.40.0 => v1.43.0
```
This caused an error at when creating the buildkit client:

```
INFO[0000] failed to create okteto build client: failed to dial "<buildkit url>" . make sure buildkitd is running: ClientConn's authority from transport creds "<buildkit url>" and dial option "<buildkit url>" don't match
```

So the grpc version has been pinned to v1.40.0 for the moment in order to proceed with the change of the registry library

**Comment by teresaromero** [comment]
@jmacelroy should we reopen this?

**Comment by AgustinRamiroDiaz** [comment]
@teresaromero do you have more context on this? I'm upgrading som packages in the cli and wouldn't like to break anything

**Comment by teresaromero** [comment]
when updating and `okteto build` i think it was, any command instanciating buildkit client, you got the error

**Comment by jLopezbarb** [comment]
@jmacelroy I just saw that this one is closed but checking the `go.mod` file the issue still persists. I'm reopening it again, if you have any objection, feel free to close it with a comment explaining why we have to close it.

**Comment by andreafalzetti** [comment]
Moved to JIRA https://okteto.atlassian.net/browse/LAKE-86
