### ISSUE TITLE
okteto namespace shouldn't include deleting namespaces

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2140]
**Describe the bug**
okteto namespace shouldn't display namespaces in the 'deleting' state (for okteto cloud users), since those are no longer functional.  I think we should filter those out of the list displayed.

**Comment by RinkiyaKeDad** [comment]
> list displayed

What list is being refered to here? I don't see any list when I run `okteto namespace` 😕 

![image](https://user-images.githubusercontent.com/56963264/150319151-becdf870-839e-4f7f-8e8b-f10e7cb038f8.png)

**Comment by pchico83** [comment]
@RinkiyaKeDad you need to try building from master, or installing the [beta release](https://github.com/okteto/okteto/blob/master/docs/how-to-install-okteto-cli.md#installing-the-latest-okteto-release-candidate)
