### ISSUE TITLE
Create a doc defining the Okteto CLI release process

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2159]
There is an internal document describing the release process of the Okteto CLI, but it should be part of this repo:
https://www.notion.so/okteto/Okteto-CLI-Release-Plan-35153e8094df47ff9c943f666f55db87
We should also cover how we generate release notes and how the release is announced.

**Comment by jmacelroy** [comment]
@maroshii Can you take a look at this one and see how much is covered with recent updates and if anything remains please.

**Comment by maroshii** [comment]
We can close this. Most of it has been added to https://github.com/okteto/okteto/blob/master/docs/RELEASE.md including how we generate release notes. We are missing the release announcements but created a separate more descriptive issue for it https://github.com/okteto/okteto/issues/2761
