### ISSUE TITLE
Deprecate `okteto pipeline` command

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2168]
**Is your feature request related to a problem? Please describe.**
In order to simplify the okteto dev experience, we should have a single way to deploy an application. `okteto pipeline deploy` is equivalent to `okteto deploy` if the `branch` or `repository` flags are specified. More information [here](https://github.com/okteto/okteto/issues/2094).

**Comment by RinkiyaKeDad** [comment]
@pchico83 by "deprecate" do you mean we first add a warning message to the output of the command saying we will remove it soon or should we just remove it right away?

**Comment by pchico83** [comment]
@RinkiyaKeDad I mean to show a warning
