### ISSUE TITLE
Deprecate `okteto update` in favor of `okteto version update`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2177]
Also, `okteto version` should be an alias of `okteto version show`

**Comment by RinkiyaKeDad** [comment]
@pchico83 does the code for `okteto version update` also needs to be added as part of this issue, because I don't see it in [version.go](https://github.com/okteto/okteto/blob/master/cmd/version.go)?

**Comment by pchico83** [comment]
> @pchico83 does the code for `okteto version update` also needs to be added as part of this issue, because I don't see it in [version.go](https://github.com/okteto/okteto/blob/master/cmd/version.go)?

@RinkiyaKeDad it's implemented in the `okteto update` command, which should be deprecated. It just prints what you have to do to update the Okteto CLI
