### ISSUE TITLE
Support for `okteto build --global`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2182]
**Is your feature request related to a problem? Please describe.**
I want to build my images on the Okteto Global Registry on each merged to `main`, but I don't now about the label convention okteto uses (we are using a combination os git commits and build-arg hashes).

This should be transparent. If I want to push to the Okteto Global registry I just do `okteto build --global`

**Comment by teresaromero** [comment]
pending to merge https://github.com/okteto/build/pull/9
