### ISSUE TITLE
`okteto stack destroy` and `okteto destroy` should clean resourcces created by `okteto up`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2183]
**Describe the bug**
If I deploy something and run `okteto up`, a new mirror deployment is created. The mirror deployment should be deleted when running `okteto destroy` or `okteto stack destroy`.

For `okteto stack destroy` we can check the dev label when deleting a service. For `okteto destroy`, we can check the dev label in the proxy logic.

**Expected behavior**
All dev resources (but the okteto persistent volume) are deleted.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by ifbyol** [comment]
Mirror deployment is created outside the proxy flow. The proxy is only used for the deploy operation. Isn't the okteto up cloning the labels to the mirror deployment? If so, the deployed-by label should be in the mirror deployment too, so the okteto destroy should delete it

**Comment by pchico83** [comment]
@ifbyol yes, it could be already working. We need to go through both flows to validate the behavior.

**Comment by jLopezbarb** [comment]
Tested and it's working as expected. The only case is not working is:
1. Deploy with `okteto stack deploy` command
2. Run `okteto destroy`
3. Resources are still there

I think it's the correct behaviour so I believe we can close this issue
