### ISSUE TITLE
okteto init has two arguments for `-o`

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2201]
**Describe the bug**
On 1.15.X, `okteto init` has two different `-o` arguments. 

![image](https://user-images.githubusercontent.com/475313/151290103-9ec12612-6777-41a3-aa9e-1c53c0d9ad9b.png)

**Comment by jLopezbarb** [comment]
Changing the global flag for output will require a new coordinated installer release because we need to change the flag from output to `--logoutput`.
Another option is to use the `--replace` flag on the init v2 instead of overwrite and then replace this command by the new one. WDYT?

**Comment by rberrelleza** [comment]
yeah, --replace could be a good alternative.

**Comment by jLopezbarb** [comment]
Closed by https://github.com/okteto/okteto/pull/2357
