### ISSUE TITLE
Multiple dev sessions

### ISSUE THREAD

**Issue by mladedav** [okteto/okteto#2209]
**Is your feature request related to a problem? Please describe.**
I want to have multiple open terminals where I can do different things in the dev container (such as running an app, moving around files, etc.)

**Describe the solution you'd like**
either `okteto up` recognizing I already have a running session with file sync etc. and starting just an ssh tunnel, or having another command for that.

**Describe alternatives you've considered**
SSH somehow directly into the container. I don't know where to start though.

**Comment by pchico83** [comment]
@mladedav I think what you are looking for is `okteto exec`:
https://www.okteto.com/docs/reference/cli/#exec

**Comment by mladedav** [comment]
I am, thank you very much. Sorry for missing it between the commands.
