### ISSUE TITLE
Endpoints are being displayed in a single line between [] when a deployment finishes with plain output

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2212]
**Describe the bug**
In `1.14.10` each endpoint was being displayed in a separate line like this:

![Captura de pantalla 2022-01-26 a las 12 52 04](https://user-images.githubusercontent.com/3510171/151577752-6a2d2376-625d-4a5f-b06c-b846727c6fd5.png)

but in `1.15.2` all the endpoints are being displayed in one single line:

![Captura de pantalla 2022-01-26 a las 12 43 24](https://user-images.githubusercontent.com/3510171/151577867-d752494a-fa84-4cb1-be21-38d4208c3fe3.png)

This is harder to read if you have several endpoints and it is causing that the first link of the list is not clickable when the CLI is used by the pipeline installer

**To Reproduce**

**Expected behavior**
Each endpoint is displayed in a separate line

**Additional context**
-

**Comment by ifbyol** [comment]
The real issue is that the default output mode for the CLI has changed to `tty` instead of `plain`, so the installer needs to pass `plain` to the CLI when running the command.

cc @maroshii

**Comment by jLopezbarb** [comment]
Closed, this one is already fixed in master
<img width="612" alt="Captura de pantalla 2022-03-04 a las 15 10 25" src="https://user-images.githubusercontent.com/25170843/156778581-487f78df-afad-426f-9faa-816ac14f6dfc.png">
