### ISSUE TITLE
Refactor: use the go docker-compose deserializer

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2219]
**Is your feature request related to a problem? Please describe.**
As part of the effort to move to a 100% compose compatibility, we should move to the official compose deserializer:
https://github.com/docker/compose/tree/v2

We could keep using (and deprecate it at some point) our own serializer for `okteto-stack.***` files, which have a slightly different syntax/behavior than compose. For example, `commands` and `args` have different behaviors today depending on the name of the file.

**Comment by jLopezbarb** [comment]
Just a quick update.
The compose serialised library that is used by https://github.com/docker/compose/tree/v2 is https://github.com/compose-spec/compose-go

**Comment by jmacelroy** [comment]
@jLopezbarb I put this on a future release milestone. Help me evaluate when a good time to work on this would be as we do more release planning in the future.

**Comment by jLopezbarb** [comment]
Could we put this one on 2.5? The last three regressions came because of this code, so having it as soon as possible can fix all the issues that we are having

**Comment by pchico83** [comment]
@jLopezbarb @jmacelroy @ifbyol one option here is to use the official compose struct as the interface for `deploy/destroy` commands, and let our serializer generate this struct from our custom stack fields. This way, `deploy/deploy` don't need to handle stack-specific logic.
Ideally, the serializer could also reuse the official compose serializer, not sure if that should be done in a different PR

**Comment by ifbyol** [comment]
> @jLopezbarb @jmacelroy @ifbyol one option here is to use the official compose struct as the interface for `deploy/destroy` commands, and let our serializer generate this struct from our custom stack fields. This way, `deploy/deploy` don't need to handle stack-specific logic. Ideally, the serializer could also reuse the official compose serializer, not sure if that should be done in a different PR

@pchico83  I'm not familiar with the code, but that sounds good to me. What I'm not sure what to do is how to know which serializer we should use depending on the manifest

**Comment by pchico83** [comment]
This will be created in planning when needed
