### ISSUE TITLE
Allow per user copies of okteto deployment

### ISSUE THREAD

**Issue by JCoder01** [okteto/okteto#2228]
**Is your feature request related to a problem? Please describe.**
It's not possible for 2 developers to work on the same deployment at the same time. An `okteto up` from one user replaces another users deployment.

**Describe the solution you'd like**
Add a feature that would allow creating multiple "clone" deployments using some suffix (such as user) so `my-awesome-app-okteto` would become `my-awesome-app-oketeo-{username}`

**Describe alternatives you've considered**
The alternative would appear to be to create a deployment per user, and then have each user point their okteto.yml to thier deployment, but this seems like a lot of overhead as small changes in the app deployment would then need to be carried over to each users deployment. 

**Additional context**
It _looks_ like this would be rather easily achievable by just adding a sanitized username here: 
https://github.com/okteto/okteto/blob/master/pkg/model/dev.go#L1311

**Comment by pchico83** [comment]
@JCoder01 have you tried our **divert** feature?
https://www.okteto.com/docs/tutorials/getting-started-with-divert/

You need to try it in Okteto Cloud. It's not supported in vanilla Kubernetes clusters yet

**Comment by JCoder01** [comment]
Hi @pchico83, I saw it in the docs but moved on after getting an error about the namespace needing to be managed by okteto. Do you have a timeline for when it will be supported outside okteto cloud? I don't think our security folks would be too happy with my uploading our stuff outside our VPC.

**Comment by pchico83** [comment]
@JCoder01 we don't have plans to support it in vanilla Kubernetes clusters yet, this feature requires cluster-side components. One option is to run [Okteto Self-Hosted](https://www.okteto.com/docs/enterprise/).
