### ISSUE TITLE
JSON output is not including a stage for the endpoints

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2233]
**Describe the bug**
When the `okteto deploy` command is executed with `json` output, the logs with the endpoints list don't include the stage, so the UI is filter them out and the endpoints are not included in the logs. As you can see here, the stage is empty.

```
{"level":"info","stage":"","message":"Retrieving endpoints...","timestamp":1643990945}
{"level":"info","stage":"","message":" i  Endpoints available:\n  - https://movies-ifbyol.staging/.***.net/\n  - https://movies-ifbyol.staging/.***.net/api\n","timestamp":1643990945}
```

Not sure if this was done in purpose or we should include a stage to be included in the UI. If the stage has to be included, I think a new stage has to be included 

**To Reproduce**
Execute a pipeline from the UI in an Okteto instance with the structured logs. You will see that the endpoints are not printed in the logs

**Expected behavior**
Endpoints should have a stage as the rest of json output

**Desktop (please complete the following information):**

**Additional context**
This is part of structured logs for pipelines

**Comment by jLopezbarb** [comment]
I wouldn't create a new stage just for showing the endpoints, here are my thoughts: 
Including it on the latest command doesn't make sense, because having the okteto endpoints on a helm command can mislead the user.
We are already showing the endpoints at the top of the UI, so showing them as another stage called `Show endpoints` seems redundant and does not provide too many value. 

WDYT @maroshii @pchico83 @rlamana?

**Comment by rlamana** [comment]
+1 for showing them. Users would expect that the output in the UI is the same that they would get in the CLI, even though is grouped or organized nicely with stages.

As we discussed offline, I would add a final stage "Successfully deployed" that when expanded displays the endpoints information (very similar to the command output). We could in the future use that also to give hints for what comes next, documentation, etc... (which we will indeed do in the CLI too).

Would this new stage be a lot of work?

**Comment by ifbyol** [comment]
I would also add that having different outputs in the UI and in the CLI could be a headache for us if we want to check what input is missing in the UI that is present in the CLI or viceversa. Having to check if there is a stage or not to know if the log is rendered in the UI is a bit scary and probably misleading. As Ramon says, I would expect the same output in both places.

In general, I think the `output` flag should change the output format not the content

**Comment by jLopezbarb** [comment]
We will need to have some UI changes because it's seems weird to have a stage as Running successfully deployed.I don't know if it is possible to remove the running and set it as the `Spin up environment` stage.
<img width="356" alt="Captura de pantalla 2022-02-07 a las 17 10 56" src="https://user-images.githubusercontent.com/25170843/152826540-2e123d62-a1e3-418d-a6ab-6b22ca678d65.png">

**Comment by rlamana** [comment]
@jLopezbarb We already have a "Spin up environment" stage that differs from the "Run XXXXX" format:
<img width="289" alt="Screenshot 2022-02-07 at 17 54 58" src="https://user-images.githubusercontent.com/237819/152834619-281ce9c7-1b2f-4ebd-9dc2-b6dbe6620149.png">
It's a different stage type.

**Comment by maroshii** [comment]
+1 for not showing endpoints in the UI.

The output is already not the same in both places since the installer adds extra logs that don't appear in the CLI.

IMO, having a `success` stage makes it easier to implement but is confusing since nothing runs there which is different from the setup stage

**Comment by pchico83** [comment]
> +1 for not showing endpoints in the UI.
> 
> The output is already not the same in both places since the installer adds extra logs that don't appear in the CLI.
> 
> IMO, having a `success` stage makes it easier to implement but is confusing since nothing runs there which is different from the setup stage

I agree. We have better alternatives to show this info in the UI. It's weird to show this kind of info in a section that is highly couple to show the output of user commands

**Comment by jmacelroy** [comment]
> > +1 for not showing endpoints in the UI.
> > The output is already not the same in both places since the installer adds extra logs that don't appear in the CLI.
> > IMO, having a `success` stage makes it easier to implement but is confusing since nothing runs there which is different from the setup stage
> 
> I agree. We have better alternatives to show this info in the UI. It's weird to show this kind of info in a section that is highly couple to show the output of user commands

+1, However, I do believe there should be parity between cli and ui. It doesn't need to be logging. We could open an issue to create some cli command to list endpoints?

**Comment by pchico83** [comment]
> > > +1 for not showing endpoints in the UI.
> > > The output is already not the same in both places since the installer adds extra logs that don't appear in the CLI.
> > > IMO, having a `success` stage makes it easier to implement but is confusing since nothing runs there which is different from the setup stage
> > 
> > 
> > I agree. We have better alternatives to show this info in the UI. It's weird to show this kind of info in a section that is highly couple to show the output of user commands
> 
> +1, However, I do believe there should be parity between cli and ui. It doesn't need to be logging. We could open an issue to create some cli command to list endpoints?

@jmacelroy `okteto endpoints` is in the [okteto dev](https://www.notion.so/okteto/Okteto-DEV-915b72bf1a8f4275879974e544a2d614#4b28caa859b14e05b392b4fbabe64a02) spec. we still need to create issues in GitHub for a few missing parts

**Comment by pchico83** [comment]
@jLopezbarb talked offline with @rlamana.  Let's show the endpoints just in tty output. This means we don't need a successful stage yet

**Comment by jLopezbarb** [comment]
Can we close this issue then?
