### ISSUE TITLE
Silence .stignore degraded performance warnings

### ISSUE THREAD

**Issue by jmacelroy** [okteto/okteto#2250]
**Is your feature request related to a problem? Please describe.**
Sometimes I know I don't want to add a particular file to .stignore but I keep getting reminded of the performance implications.

**Describe the solution you'd like**
I would like to prevent these prompts from continuously showing up.

**Describe alternatives you've considered**

**Additional context**
```
i  Using default @ <some-context> as context
 i  The synchronization service performance is degraded if the '.git' folder is synchronized.
 ?      Do you want to ignore the '.git' folder in your '.stignore' file? [y/n] n
```

**Comment by jmacelroy** [comment]
@jLopezbarb or @pchico83 Do you know if there's a way to do this already or would it require changes?

**Comment by ammolitor** [comment]
I find myself often working with "fresh" clones of a project, and `.stignore` is not something that is in their codebases. It would be great if there was an option in the manifest to silence syncthing warnings.

An example from today.. I'll start `okteto up` and then grab a coffee. 15 minutes later... Ugh, no syncthing, I **do** want my `.git` directory synchronized, thanks for asking. Now I'll wait some more.

**Comment by pchico83** [comment]
@jLopezbarb this is being reported by many users. What about showing this warning only of `.git` exists in the folder?

**Comment by jLopezbarb** [comment]
Yes, we can only show the warning, I think is the less intrusive way to fix the issue

**Comment by pchico83** [comment]
@jLopezbarb great, I put it on the next sprint
