### ISSUE TITLE
Support for RunAsUser

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#226]

**Comment by rberrelleza** [comment]
Currently, the dev environment will inherit the userGroup and fsGroup from the kubernetes deployment. Maybe that's all we need to do by now? 

I really like to push the idea of using the same user and group in prod and dev to reduce drift, allowing a custom RunAsUser might go against that no? ((that's how the [java](https://github.com/okteto/samples/blob/master/java/manifests/deployment.yaml) sample works right now)?

**Comment by pchico83** [comment]
Yes, I like the approach used in the java example, less magic on the okteto side.
Also, I think it is a good practice to be explicit in the manifests for the user (and other fields), instead of relying on the docker image definition. This way, a malicious change on the image would have fewer privileges.
