### ISSUE TITLE
An error loading the manifest while the deploy command is executed doesn't contain value for the stage property on json output

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2273]
**Describe the bug**
When I use the output flag to specify `json`, if there is an error reading the manifest, that error is logged without any section, so it is not displayed in the UI. We should review all the places where we are not setting any `stage`

If you see this screenshot, you can see that the pipeline failed but the logs don't show any error. Checking the pod logs, you see:

```
{"level":"error","stage":"","message":" x  Path '/***/src/non-existent-folder' does not exist","timestamp":1645360958}
{"level":"info","stage":"","message":"    Update the `sync` field in your *** manifest file to a valid directory path.","timestamp":1645360958}
{"level":"info","stage":"","timestamp":1645360958,"message":"\nFAILED: okteto pipeline has failed with: exit status 1."}
{"level":"info","stage":"","timestamp":1645360958,"message":"See https://okteto.com/docs/cloud/okteto-pipeline for details on how to configure your okteto pipeline."}
{"level":"error","stage":"","timestamp":1645360958,"message":"\u001b[91mexit status 1\u001b[0m"}
{"level":"info","stage":"done","timestamp":1645360958,"message":"EOF"}
```

![Captura de pantalla 2022-02-20 a las 13 45 58](https://user-images.githubusercontent.com/3510171/154843237-8986fef5-e88b-44e4-8ffd-4e6a9e720853.png)

**To Reproduce**
Deploy this repository `https://github.com/ifbyol/movies` in Okteto Cloud or Staging

**Expected behavior**
The error should be displayed in the UI so user is able to find out the real issue

**Desktop (please complete the following information):**
-

**Additional context**
-

**Comment by pchico83** [comment]
@jLopezbarb we should port this fix to 1.15.5 too
