### ISSUE TITLE
Manifest v2 should look for compose before k8s manifests

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2289]
When using okteto deploy or build in a repo with k8s manifests and docker compose, the manifest v2 is parsed as kubernetes files insead of compose. 

v2 manifest -> compose -> automatic deployment should be the order

**Comment by jLopezbarb** [comment]
If we change this we should change also docs on https://www.okteto.com/docs/cloud/deploy-from-git/#prerequisites.
The new order will be:

1. Manifest v2
2. Okteto Pipeline files
3. Okteto compose 
4. Helm chart
5. kubernetes manifest folder
6. kubernetes manifest file
7. Okteto manifest v1

Does this looks ok?

**Comment by jLopezbarb** [comment]
I said it because it can break some pipelines from people that have it configured with the prior order. 

> Other option could be to remove that part from the installer and rely on the CLI to store that information

The CLI is storing that information, if it's a compose it will store the compose file instead of the generated manifest
