### ISSUE TITLE
Don't create public ports for 2222 on compose support

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2293]
**Is your feature request related to a problem? Please describe.**
I have a docker-compose file, and I want to forward the okteto ssh server on `okteto up`.
Today I have to redefine a `dev` container in my okteto manifest.

**Describe the solution you'd like**
I could do the following in my docker-compose file, but it creates a public endpoint:
```
forward:
  - 2204:2222
```

**Comment by imskr** [comment]
Can I work on this?

**Comment by RinkiyaKeDad** [comment]
Hey @imskr, thanks for showing interest in contributing! Yes, please feel free to work on this, should I assign this issue to you? If you have any questions or need help, let us know here.

**Comment by imskr** [comment]
Yeah please @RinkiyaKeDad

**Comment by RinkiyaKeDad** [comment]
Hey @imskr! I just wanted to check in and see if you're still interested in working on this? 😄
