### ISSUE TITLE
Okteto kubeconfig after "okteto context use --token" requires a token

### ISSUE THREAD

**Issue by mnevadom** [okteto/okteto#2298]
**Describe the bug**
Im running a context git action inside a container. With --token and use URL. After the context itself it runs an okteto kubeconfig.
Which is giving me this error:
 x  This command is not supported without the ‘--token’ flag from inside a container
When running this:
running: okteto context use --token=ACMGX7Cn3SdOaoo5he0ruYKxXEL0NTUWmklKkSlB https://okteto.t28feb1.dev.okteto.net/
It seems like is forcing me to export the OKTETO_TOKEN env. When I do that, it works perfectly.
When I run the same in my local I dont get the error.
CLI version 1.15

**To Reproduce**
In the acceptance repo, run an okteto UP and try to run okteto context use with token flag.

**Expected behavior**
Okteto context should run okteto kubeconfig without problems with the given token

**Desktop (please complete the following information):**

- OS: macOS

**Comment by jLopezbarb** [comment]
I was able to do this inside a container using 2.0.1 build and setting staging as the cluster I want to operate in.
<img width="430" alt="Captura de pantalla 2022-03-25 a las 18 09 24" src="https://user-images.githubusercontent.com/25170843/160168612-953d0415-9692-4176-9f47-01d329cf9f4a.png">
PD: token is expired so don't try to use it :)
