### ISSUE TITLE
Support for custom commands on `okteto up`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2300]
**Is your feature request related to a problem? Please describe.**
I want to run `okteto up` with a custom command, for example `okteto up -- bash`to debug my service

**Comment by jLopezbarb** [comment]
`--` means the end of command options and only positional options are available along with args.
Now that we have an arg (`okteto up svc`) that can interfere with this new arg. We should do that all these commands run the same way
- `okteto up svc`
- `okteto up svc -- bash`
- `okteto up svc bash`
- `okteto up bash`
- `okteto up -- bash`

**Comment by abs007** [comment]
Can I get some context into what `svc` stands for in `okteto up svc`?

**Comment by pchico83** [comment]
@abs007 is the name of each dev container in the okteto manifest, for the case there is more than one defined.
For example, in this sample, you can run `okteto up frontend`:
https://github.com/okteto/movies/blob/main/okteto.yml#L43

**Comment by abs007** [comment]
And I'm guessing that we want to add `-- bash` as a flag to enter the container and debug it ?

**Comment by pchico83** [comment]
> And I'm guessing that we want to add `-- bash` as a flag to enter the container and debug it ?

`-- bash` would be equivalent to running `okteto up` with `command: bash` in your okteto manifest

**Comment by abs007** [comment]
Got it, but would I have to add this as a flag?

**Comment by pchico83** [comment]
> Got it, but would I have to add this as a flag?

It's not a flag, it's an argument. You can check the `okteto exec` command, it does something similar. For example, `okteto exec -- ls` works, or `okteto exec frontend -- ls`

**Comment by abs007** [comment]
So, flags are something that we'd want to add to the command but an argument is what we're supplying to the main command. 

Here we'd be adding an extra command argument for `up` in the form of `okteto up [devName] [command]` and this would offer similar functionality as the `deploy` section in the okteto manifest

**Comment by pchico83** [comment]
> similar functionality as the `deploy` section in the okteto manifest

All right, but `similar functionality as the deploy section in the okteto manifest` is not correct. `[command]` will replace the `command` field in the `dev` section. This guy:
https://www.okteto.com/docs/reference/manifest/#command-string-optional

Use case: my `command` is `yarn start`, but today I just want to run tests in my dev container. I can run `okteto up -- yarn test`

**Comment by abs007** [comment]
Ah yes, understood. I'd like to work on this issue.

**Comment by pchico83** [comment]
@abs007 awesome, I assigned the issue to you. This is a great feature!

**Comment by abs007** [comment]
@pchico83 Can I get the file which reads the commands from the `command` section in the okteto manifest?

**Comment by pchico83** [comment]
> @pchico83 Can I get the file which reads the commands from the `command` section in the okteto manifest?

@abs007 it's defined here:
https://github.com/okteto/okteto/blob/master/pkg/model/dev.go#L68

And the serializer is here:
https://github.com/okteto/okteto/blob/master/pkg/model/serializer.go#L259
