### ISSUE TITLE
Running two apps at the same time and calling one from the other causes `Error: connect ECONNREFUSED` error

### ISSUE THREAD

**Issue by seunggs** [okteto/okteto#2306]
**Describe the bug**
I'm running two ExpressJs apps on ports `3001` and `4004` using Okteto (production version of these apps are running in Kubernetes, but I'm running both apps in dev environment so I can test everything without deploying to Kubernetes cluster). When I use the browser, both apps work but using `axios` library from the Express server running on `3001` to hit the endpoint in Express server running on `4004` errors out with `Error: connect ECONNREFUSED`. 

The interesting thing is, I have another app running on `4002` using Okteto as well and that endpoint seems to work fine from the server on `3001`.

**To Reproduce**

1. Run an ExpressJs server on `3001` using Okteto
2. Run another ExpressJs server on `4004` using Okteto
3. Inside the server on `3001`, call an endpoint in the server on `4004` using Axios
```
await axios({
  method: 'get',
  url: `http://localhost:4004/api/some-endpoint`,
})
```

**Expected behavior**
It should return `200`, but instead it errors out with `Error: connect ECONNREFUSED` error

**Desktop (please complete the following information):**

- OS: macOS Moneterey
- Version 12.2.1

Okteto yaml files:
```
name: app-dev-svc
selector:
  app: app-dev-svc
command: sh
sync:
- .:/app
forward:
- 9231:9231
- 3001:3001
- 4001:4001
```

```
name: devops-server-dev-svc
selector:
  app: devops-server-dev-svc
command: sh
sync:
- .:/app
forward:
- 9234:9234
- 4004:4004
```

**Comment by pchico83** [comment]
@seunggs since code is running inside of the cluster, you need to use the kubernetes network to access your service.
That means you should probably use:
```
await axios({
  method: 'get',
  url: `http://devops-server-dev-svc:4004/api/some-endpoint`,
})
```
nad make sure `devops-server-dev-svc` is listening on 0.0.0.0:4004 instead of localhost:4004
