### ISSUE TITLE
Updating lib in `node_modules` not reflected in `okteto up`

### ISSUE THREAD

**Issue by seunggs** [okteto/okteto#2318]
**Describe the bug**
Updating lib in `node_modules` not reflected in `okteto up`

**To Reproduce**

1. Svc running in Kubernetes
2. Update a lib using `npm i` -> rebuild the image and redeploy the service to Kubernetes cluster
3. Run `okteto up` again
4. The code is not updated inside the okteto environment

I've checked to make sure during `okteto up`, it's using the latest image. I've also checked to make sure both locally and inside the Kubernetes svc, `node_modules` code is updated. But the `node_modules` is not updated inside okteto environment. The only way to get it to work is to run `npm i` inside okteto environment again.

**Expected behavior**
Updating the svc in Kubernetes after updating lib should have the changes reflected in `okteto up`

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Version 12.2.1

**Comment by pchico83** [comment]
@seunggs do you have `node_modules` in your `.stignore` file?
We recommend it to add it. It's usually faster to run `okteto exec -- npm i` when needed than synchronizing the full `node_modules` folder.

**Comment by seunggs** [comment]
Yes I do - I was able to resolve this by running `okteto down -v`

**Comment by pchico83** [comment]
@seunggs thanks for the update! I will close the issue then
