### ISSUE TITLE
`okteto deploy` should deploy `dependencies` before building the images

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2344]
**Describe the bug**
`okteto deploy` is building the images defined in the `build` section before deploying the `dependencies` in the okteto manifest.
This is un optimal because dependencies can be deployed in parallel while images are built.

**Comment by AdrianPedriza** [comment]
@pchico83 from what I understood, when user exec `okteto deploy` we should have two parallel processes: one for deploy dependencies and the other will build needed images. So my question is: what is the expected behavior related to the output in this parallel processes?
