### ISSUE TITLE
e2e test to validate `okteto up` reconnects to an existing dev container

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2356]
**Is your feature request related to a problem? Please describe.**
`okteto up` takes some time to create a dev container. The old container needs to be terminated, the new one created, volume is attached, ... If I disconnect from my dev container and I run `okteto up` again, `okteto up` should always reconnect to the existing dev container instead of redeploying it.

**Describe the solution you'd like**
We have had regressions here before. We should have an e2e test to validate that two consecutive `okteto up`s don't redeploy the dev container

**Comment by jLopezbarb** [comment]
> can we also do a unit test to detect that the manifest we are updating doesn't change or something likethat? that way we don't depend only on the integration tests, which take a long time to run.

Doing that requires a full refactor of `okteto up` command.

We already have an `okteto up` reconnection test to check that the second `okteto up` kills the first one. We could check if the pod name is the same in both cases and we don't have to create another test that increases the time that e2e tests take

**Comment by pchico83** [comment]
Yes, pod recreation can be affected by many factors, an e2e test is the only reliable approach at this moment.
We could do something like this:
- `okteto up`
- get dev pod name
- stop `okteto up`
- check dev pod name didn't change
I would have two different `okteto up` executions, because each one has a different `id`, and this `id` might affect the pod recreation
