### ISSUE TITLE
If `okteto context` is using a token from an environment variable, it would be useful to show that information to the user

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2378]
**Is your feature request related to a problem? Please describe.**
If I set at some point the environment variable `OKTETO_TOKEN` and I execute `okteto context use https://foo`, it will try to login using the `OKTETO_TOKEN` environment variable but I might not realize I have that env set. It would be useful if the CLI displays an info message letting me know that it will use the env var.

It can be confusing if the token set is no longer available as I'm not specifying the token explicitly. 

**Describe the solution you'd like**
If the command will use the value of the environment variable, I would like to see an info message letting me know.

**Describe alternatives you've considered**
Other option could be to execute a normal auth flow if the auth with the token fails

**Additional context**
It happened to one of our customers. They have set a personal access token in the environment variable and at some point, that access token was removed, so executing `okteto context use` command was failing all the time.

**Comment by rberrelleza** [comment]
Let's ensure we don't log the actual value of the token, only its presence.
