### ISSUE TITLE
Support for empty env vars when using `env_files`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2381]
**Describe the bug**
I am using an `env_file` in my compose file like this one:
```
AUTH0_SECRET_KEY=
```
but it's not getting the value from my `AUTH0_SECRET_KEY=` env var. I have to change my file to be:
```
AUTH0_SECRET_KEY=${AUTH0_SECRET_KEY}
```
which is quite redundant.

**Comment by teresaromero** [comment]
merge to master, pending test after release

**Comment by teresaromero** [comment]
tested at release 2.2.0-rc-1 - ok
moved to done
