### ISSUE TITLE
Show url on "okteto context" when default browser not found

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2386]
**Is your feature request related to a problem? Please describe.**
I use WSL, which doesn't have a default browser configured to open on my windows machine. In this case, okteto thinks that I'm in server mode. 
I think that if the url to authenticate is printed by de cli, I could click it and use it in my normal browser.

**Describe the solution you'd like**
- Print the url for authentication when running `okteto context` if it does not find a default browser.
- Also log the "more information" phrase to help users that actually want the server mode

**Describe alternatives you've considered**
Maybe there is another way to scrape the browsers, but I think its complicated in this scenario where WSL actually uses linux through container

**Additional context**
The feature could be implemented [here](https://github.com/okteto/okteto/blob/7a927165d8f0864cb91433a463683eb5f421acc2/pkg/cmd/login/login.go#L71)

**Comment by miniscruff** [comment]
I was looking at this issue and I am wondering if it is already done with these lines here:
https://github.com/okteto/okteto/blob/6fe4d34b69d2dd73b585c8447d3632b4450c6157/pkg/cmd/login/login.go#L94-L95

**Comment by AgustinRamiroDiaz** [comment]
Hey @miniscruff ! I'm not able to reproduce at the moment since I'm not with WSL at the moment. 

Those lines you are mentioning seem to handle the issue, I'll close this issue until someone is able to reproduce :+1:
