### ISSUE TITLE
Support for "okteto up" to run from a different folder

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#240]
**Is your feature request related to a problem? Please describe.**
I want to be able to run `okteto up` from a different folder than where the source is. This is useful for automation scenarios.

**Describe the solution you'd like**
I'd like to have a key in the okteto.yml manifest to point to a path in my local machine.

**Comment by pchico83** [comment]
Would it work if `okteto` syncs the folder where the `okteto.yml` is located, instead of the current folder where `okteto up` is executed?
