### ISSUE TITLE
`okteto build` and `okteto deploy` pushing different images

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2408]
**Describe the bug**
I am using this repo sample:
https://github.com/okteto/movies-with-compose/

`okteto build` is building the images to:
- okteto.dev/movies-with-compose-init:okteto
- okteto.dev/movies-with-compose-frontend:okteto-with-volume-mounts
- okteto.dev/movies-with-compose-frontend:okteto
- okteto.dev/movies-with-compose-api:okteto-with-volume-mounts
- okteto.dev/movies-with-compose-api:okteto

but `okteto deploy` is looking for different images:

- okteto.dev/movies-init:okteto
- okteto.dev/movies-frontend:okteto-with-volume-mounts
- okteto.dev/movies-frontend:okteto
- okteto.dev/movies-api:okteto-with-volume-mounts
- okteto.dev/movies-api:okteto

**Comment by jLopezbarb** [comment]
Which CLI version where you using? Does it continue happening? I can't reproduce it on master build

**Comment by pchico83** [comment]
@jLopezbarb right, this is now fixed
