### ISSUE TITLE
up is not starting if sync folder are on the stignore file

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2435]
**Describe the bug**
If the `up` command only has one sync folder and that folder is on the `.stignore` file the command will get stuck at the step of synchronizing files.

**To Reproduce**
Create an `okteto.yaml` like:
```
name: cli-bug
image: okteto/golang:1
autocreate: true
command: bash
workdir: /usr/src/app
sync:
  - bin:/usr/src/app
```
And you should have a .stignore file like:
```
/.git
/bin
```
**Expected behavior**
I think that we can detect if the folder we are trying to sync is on the stignore file and return a friendly error

**Comment by pchico83** [comment]
Closing since it's a very corner case
