### ISSUE TITLE
okteto init shouldn't prompt to deploy an environment

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2451]
**Is your feature request related to a problem? Please describe.**
When I run `okteto init`, the CLI gives me the option to deploy my dev environment, and it defaults to Y. I find this a) very confusing, since I'm running a command to initialize files, and b) very easy to click Y by mistake since it's the default.

**Describe the solution you'd like**
I'd like okteto init to just initialize the manifests. I find it confusing in general when a CLI command tries to do more than what it advertises. It also breaks the principle of "simple things that work together", which is pretty standard for UNIX-style CLIs (https://clig.dev/#simple-parts-that-work-together has more info on this)

**Comment by pchico83** [comment]
I am closing all issues related to `okteto init`. I will work on a new spec for `okteto init` to be implemented in q4
