### ISSUE TITLE
Support for `okteto preview sleep|wake`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2463]
**Is your feature request related to a problem? Please describe.**
I want to sleep a preview environment from the Okteto CLI. For example, I want to create a preview environment, run some tests, and sleep it to save resources in the cluster.

**Describe the solution you'd like**
`okteto preview sleep` to mimic the function of the Okteto UI  **sleep** button.
`okteto preview wake` to mimic the function of the Okteto UI  **wake** button.

**Comment by ifbyol** [comment]
The example you posted brings me a question, do users connect the concept of preview environments with namespaces? Do they know/understand that a preview env can be seen as a namespace (for context and this operation you are proposing)?

**Comment by pchico83** [comment]
> The example you posted brings me a question, do users connect the concept of preview environments with namespaces? Do they know/understand that a preview env can be seen as a namespace (for context and this operation you are proposing)?

Great point! I think we should have `okteto preview sleep` and `okteto namespace sleep`. The current use cases I have been requested for are for previews, I will update the issue accordingly because we don't need `okteto namespace sleep` for now

**Comment by jLopezbarb** [comment]
Reopen. Not completed yet

**Comment by pchico83** [comment]
@jLopezbarb Let's close it. We can create the issue again if it becomes a pririty

**Comment by rakshitgondwal** [comment]
Hey, @pchico83! I'd like to work on this!

**Comment by pchico83** [comment]
Awesome, I assigned the issue to you @rakshitgondwal !
We already have commands for sleep/wake a namespace, the logic should be similar.
Do you have access to cloud.okteto.com?

**Comment by rakshitgondwal** [comment]
> Awesome, I assigned the issue to you @rakshitgondwal ! We already have commands for sleep/wake a namespace, the logic should be similar. Do you have access to cloud.okteto.com?

Thank you for assigning me this issue. I am new to this project so I'm just a little bit confused about what kind of access are you mentioning here? I have made an account on okteto already + I have a namespace to my name in the cloud.

**Comment by pchico83** [comment]
> > Awesome, I assigned the issue to you @rakshitgondwal ! We already have commands for sleep/wake a namespace, the logic should be similar. Do you have access to cloud.okteto.com?
> 
> Thank you for assigning me this issue. I am new to this project so I'm just a little bit confused about what kind of access are you mentioning here? I have made an account on okteto already + I have a namespace to my name in the cloud.

Great, that is what I meant. We blocked some accounts based on user profiles, and I wanted to make sure it wasn't your case

**Comment by rakshitgondwal** [comment]
Hey @pchico83 When do we plan to merge the PR?

**Comment by andreafalzetti** [comment]
Re-opening as there is a PR open for this issue.
