### ISSUE TITLE
A Github action for okteto preview sleep

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2464]
Depends on https://github.com/okteto/okteto/issues/2463

Add a `sleep` option (defaults to `false`) in our [Deploy Preview](https://github.com/okteto/deploy-preview#inputs) GitHub Action.

**Comment by jmacelroy** [comment]
@pchico83 how important is this one? If it needs to be worked on we need to either prioritize it for 2.2 and unassign it so it can be picked up.
