### ISSUE TITLE
`okteto up` detached mode support

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2482]
**Is your feature request related to a problem? Please describe.**
I have a few services in my docker-compose file (or okteto manifest) that I usually develop on. Usually I open 3 or 4 terminal to develop. I would like an option to put all of them on dev mode at the same time.

Additionally, this is very useful in non-interactive sessions, like IDE or Docker Desktop extensions.

**Describe the solution you'd like**
`okteto up -d` starts dev mode in all my containers in detached mode. It should stream the output of the containers under development too. By default, all dev containers in my docker-compose file (or okteto manifest) would be dev mode activated. But we should support `okteto up -d serviceA serviceB ...` for activating only a subset of them.

**Additional context**
The implementation could create a "fake" dev container with `autocreate`, and the rest of dev containers would be `services` of this main dev container. The output can be streamline with something similar to https://github.com/okteto/okteto/pull/2120

**Comment by jLopezbarb** [comment]
We already have `-d` flag for `--deploy`. Should we consider using `-d` for `detach` flag instead?

**Comment by pchico83** [comment]
@jLopezbarb let's just support `--detach` for now to avoid breaking changes
