### ISSUE TITLE
`OKTETO_NAMESPACE` is not resolving on okteto manifest v1

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2494]
**Describe the bug**
I have the following okteto manifest:

```
name: api
image: okteto.dev/api:${OKTETO_NAMESPACE}
...
```

In CLI >= 2.0.0, `OKTETO_NAMESPACE` is resolving to an empty string.

**Comment by pchico83** [comment]
@jLopezbarb was this fixed already?

**Comment by jLopezbarb** [comment]
retested again with `2.1.0` and the issue is gone
