### ISSUE TITLE
Review self-signed certificates expiration

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2507]
In a couple of places, we have self-signed certificates in the code (at least for syncthing and the proxy we use in the deploy command). 

We should review the expiration of those certificates and define the best way to renew them with enough time for users using an old version of the CLI to update.

Also, `okteto up` doesn't work properly in some networks and maybe it's because these certificates are self-signed. We may try to verify this and explore different options for those cases. Maybe this could be another separate issue, but as depending on how we tackle any of these could affect to the other, I will leave it here and we can see how to do it when we tackle this ticket.

**Comment by jmacelroy** [comment]
@ifbyol What brought this to your attention? Is it a bug reported by a customer or that we found?

**Comment by jLopezbarb** [comment]
Certificates expire on `31 Dec 2049`. Could we create them programmatically instead of having to check the expiration date every now and then?
