### ISSUE TITLE
Can't run 'okteto deploy' on a minikube context due to certificate issues

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2514]
**Describe the bug**
Running  `okteto up`  when pointing to minikube fails with an error:

![image](https://user-images.githubusercontent.com/475313/162285725-1539f412-c3cd-4e14-8986-b2cdd21570b5.png)

Running `kubectl apply -f k8s.yml` directly works fine.

**To Reproduce**

1. Start minikube
2. Create a kubernetes context for minikube
3. Run 'okteto context' and pick the minikube context
4. `okteto up`

**Desktop (please complete the following information):**

- OS: MacOS
- Version 2.0.3

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by rberrelleza** [comment]
@jLopezbarb the user is reporting that the issue still reproduces on 2.0.3

**Comment by ifbyol** [comment]
@rberrelleza afaik the fix was included in `2.1.0`

**Comment by jLopezbarb** [comment]
yes, the fix was introduced on `2.1.0`. I tested it again with Minikube and it's working fine

**Comment by rberrelleza** [comment]
@Orostome we released 2.1.0 earlier this week. Could you update your CLI and try again?

**Comment by rberrelleza** [comment]
Issue is fixed on 2.1.0
