### ISSUE TITLE
Ignore compose warning if resource has the annotation "dev.okteto.com/auto-create"

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2524]
**Describe the bug**
When I am using divert, ingresses and services could be created by diverted another namespace.
For these resources, okteto adds the annotation `"dev.okteto.com/auto-create"`.
When deploying a compose file,  we should skip those warning in this annotation is present, and update the resource instead:
```
 !  skipping creation of endpoint 'xxx' due to name collision with endpoint in stack 'yyy'
```

**Comment by jmacelroy** [comment]
@pchico83 divert is a newer experimental feature and the release is a bit crowded with bugs and improvements that are less experimental. I'm going to remove this from milestone 2.3. Let's discuss how and when we can focus on this.
