### ISSUE TITLE
Users report `okteto up` failing if there is not kubeconfig locally

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2525]
**Describe the bug**
Users from an online course reported `okteto up` was failing in Cloud if they didn't have a local kubeconfig file.
They run `okteto kubeconfig`(which creates a local kubeconfig and things started to work.

**To Reproduce**

1. A machine without `~/.kube` directory.
2. `okteto context use https://cloud.okteto.com`
3. `okteto up` on any sample

**Additional context**
This is specially relevant for the Docker Desktop extension

**Comment by AgustinRamiroDiaz** [comment]
Do we have the exact errors and steps? I have tried:
- Deleting `~/.kube`
- Deleting `~/.okteto`
with the samples:
- movies-with-compose
- python-fastapi-celery

and could not reproduce

**Comment by pchico83** [comment]
@AgustinRamiroDiaz Let's close it then. I will reopen if I can get repro steps
