### ISSUE TITLE
The Global Registry optimization should be always active unless `--no-cache` is set

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2529]
**Describe the bug**
The Global Registry optimization isn't working on pipelines.
Pipelines execute `okteto deploy --build`. This should use the Global Registry optimization.

The only way to disable the Global Registry optimization is `okteto build --no-cache`.

**Additional context**
This [repo](https://github.com/okteto/movies-with-compose/blob/main/.github/workflows/build-global.yaml) build global images on each merge to `main`, but if you deploy the repo, the Global Registry optimization isn't used.

**Comment by jmacelroy** [comment]
@pchico83 is this needed for the 2.2 release and/or the docker extension?

**Comment by pchico83** [comment]
@jmacelroy no. if possible, it would be nice to have it for the next chart release, so people can use the Global Registry on their pipelines. But not mandatory either
