### ISSUE TITLE
Don't modify deploy commands output with warning icons

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2533]
**Describe the bug**
When I run `okteto deploy`, seems like we are adding our warning icon to the deploy commands output, helm in this case.
We shouldn't modify the original output of the command, it's very confusing:

<img width="581" alt="Screenshot 2022-04-13 at 07 23 40" src="https://user-images.githubusercontent.com/7474696/163106184-14675988-6e94-4678-941b-f061810ded8b.png">

**Comment by jLopezbarb** [comment]
This warnings are only added if the message comes from the stderr output. Some tools use stderr as a log console for the users. An option could be to add a `STDERR:` prefix to all those lines instead of adding the warning symbol. WDYT?

**Comment by pchico83** [comment]
@jLopezbarb I would show the output as it's shown by the original command, otherwise, I have a different output when running the command, and when running `okteto deploy`. @rlamana WDYT?

**Comment by rlamana** [comment]
I also noticed this and I was really confused. We should use those resources (info, warning, etc) for our own output but leave other commands output the way their creators intended.

**Comment by jLopezbarb** [comment]
The problem is that `stderr` is not displayed to the user by default.  A terminal only shows stderr to the user if the command has ended with a status code different to 0, but there are sometimes that you want to get the messages from stderr because it's usually used as the logger.
We want to show `stdout` and `stderr` to the user, but we need a way to show the user that those messages have come from one or another file descriptor.

**Comment by pchico83** [comment]
> The problem is that `stderr` is not displayed to the user by default. A terminal only shows stderr to the user if the command has ended with a status code different to 0, but there are sometimes that you want to get the messages from stderr because it's usually used as the logger. We want to show `stdout` and `stderr` to the user, but we need a way to show the user that those messages have come from one or another file descriptor.

I would show all `stderr` output but without custom formatting. it's what you get when running `helm upgrade`, right? and then we can show the final error at the end with a custom format
