### ISSUE TITLE
update fig integration so that `okteto up` gets autocompletion when there's more than one service defined in okteto.yml

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2536]
**Is your feature request related to a problem? Please describe.**
I'd like to have autocompletion available via fig for the okteto up command, for the case when I have more than one dev service defined on my okteto.yml

**Describe the solution you'd like**
When I type 'okteto up', fig should give me a list of services

**Describe alternatives you've considered**
I can type okteto up and then let okteto list the options, but this is slower.

@RinkiyaKeDad you have experience with this, so feel free to add your thoughts?

**Comment by RinkiyaKeDad** [comment]
For this, we would first need a command like: `okteto ls` or `okteto up --list`, which lists all the running dev services. This is because fig needs a command to run in the background to generate the autocompletion list.

cc @pchico83

**Comment by pchico83** [comment]
@rlamana how should the command look like? `okteto dev ls`?

**Comment by rberrelleza** [comment]
if https://github.com/okteto/okteto/discussions/2537 happens,   `okteto dev ls` should be reserved for listing your live dev environments.

**Comment by rberrelleza** [comment]
maybe you can use `explain` like `kubectl` ?

**Comment by rberrelleza** [comment]
Another option is to make a command that is not part of the public list for this, since it's only meant for automation.

**Comment by pchico83** [comment]
> listing your live dev environments

@rberrelleza what do you mean by ` listing your live dev environments`?

**Comment by rlamana** [comment]
As I understand it, we now see everything around the concept of a "dev environment", that's what we are using in our landing, our docs and also in the UI. What I think @rberrelleza is suggesting here is that the CLI should be aligned with that and in that context `okteto dev ls` should list the dev environments for the current context, just what you would also see if you go to the UI. Am I correct @rberrelleza? I actually like to see it that way too.

**Comment by rberrelleza** [comment]
Yes @rlamana . I think that If "okteto dev up" launches a development environment in context X, "okteto dev ls" (if it exists) should show me the development environments that are running on context X.

**Comment by pchico83** [comment]
This should go through the product backlog
