### ISSUE TITLE
Support for `okteto volume clone` command

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2543]
**Is your feature request related to a problem? Please describe.**
Okteto supports cloning PVCs between namespaces. More and more people are using this feature, but the UX is based on kubernetes manifests, and many users just have compose files.

**Describe the solution you'd like**

`okteto volume clone --from-volume --from-namespace pvc-name`. We should also support `--from-snapshot` and `--from-snapshot-id`. 

We should also have CRUD operations: `okteto volume list`, `okteto volume get -ojson` and `okteto volume delete`

**Comment by rberrelleza** [comment]
What is the difference between this and #2544 ?

**Comment by pchico83** [comment]
@rberrelleza volumes and snapshots are different objects. you can clone from a volume in another namespace. this is slower than creating an snapshot and clone from it. cloning from a volume is not replicable either. but it's usually easier to maintain

**Comment by rberrelleza** [comment]
volumes and snapshots are low level objects. I don't think we should be replicating those things at the command level. The user of a dev environment cares about data.

**Comment by pchico83** [comment]
Closing this until we have a clearer spec for it
