### ISSUE TITLE
`okteto down` not taking account of devs created by `okteto up --detach`

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2552]
**Is your feature request related to a problem? Please describe.**
Right now there is no way of running okteto down on dev env created from okteto up --detach

**Describe the solution you'd like**
Detect if there is a detached env from the manifest and run okteto down of it

**Comment by pchico83** [comment]
@rlamana what should be the command to do this? `okteto down --detach`?

**Comment by rlamana** [comment]
@pchico83 @jLopezbarb can't that be inferred and take into account that the last UP was done with the --detach option? If we see it as the docker-compose equivalent, there is no `--detach` option with `down`

**Comment by pchico83** [comment]
@rlamana what would be the experience if I try to run `okteto down frontend` after `okteto up --detach`? or if I run `okteto up --detach` and then `okteto up frontend`? One option is to fail with a clear message.

**Comment by pchico83** [comment]
@rlamana another option is to have this as a field in the okteto manifest. For compose files, we will default to `true`. 
For okteto manifests, it's optional and it defaults to the current behavior

**Comment by rlamana** [comment]
@pchico83 Maybe we should use both: 
- For users with interactive CLI:
  - `okteto down` -> Currently, this shows a list of the services to do down to. If detach mode was enabled when doing UP, we should show an extra option "All services", or something similar.
  - `okteto down service` -> Would do a normal down to that service
  
 - For non-interactive calls (ci, docker-extension, etc...):
   - `okteto down --detach` is needed with a parameter in this case to do down on all services.

**Comment by jLopezbarb** [comment]
I was thinking about this issue and maybe `okteto down -all` is the solution we want. There is an [ongoing PR](https://github.com/okteto/okteto/pull/2515) to achieve this

**Comment by rberrelleza** [comment]
I don't think that `--detach` makes sense for a  `down` command. `detach` has a meaning in the world of terminals: to start a process detached from the main session. It's not used when killing processes as far as I know.  

What's preventing `okteto down` from working independently of the mode?

**Comment by pchico83** [comment]
Let's keep `--detach` just for the Docker Desktop extension for now, and de-prioritize this issue for now because the extension doesn't support down yet.
I will create a github discussion to define the `detach` experience end to end.

**Comment by pchico83** [comment]
Let's close this, we move `--detach` to the docker desktop extension branch
