### ISSUE TITLE
`okteto deploy` isn't storing my manifest in the configmap is `okteto deploy` fails

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2555]
**Describe the bug**
I run `okteto deploy` and it fails. The Okteto UI isn't showing the manifest.
This makes it harder to debug issues, especially when sharing my namespace with a teammate.

**Comment by jLopezbarb** [comment]
It happens when a build fails or if a dependency deployment fails, after that it will create the correct configmap

**Comment by mnevadom** [comment]
At what point do we want that the config map is created even if we fail to do the deployment?

I mean, do we have to create it at the very beginning of the execution? Or do we have to wait until something is done for sure before?

**Comment by jLopezbarb** [comment]
I would wait until the manifest is read. We need the icon (if it has) and setting the manifest on the yaml part
