### ISSUE TITLE
Okteto doesn't play well with deployments with Horizontal Pod Schedulers

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#256]
**Describe the bug**
In the case when a deployment is associated with a horizontal pod scheduler, the pods launched after the deployment has been turned to development mode will be stuck on `init`, due to the lack of available persistent volume claims for the new replicas

$ kubectl get pods -l dev.okteto.com
NAME                                    READY   STATUS     RESTARTS   AGE
leadgenie-django-www-5ffcfc47d7-2z8hz   0/3     Init:0/1   0          4m53s
leadgenie-django-www-5ffcfc47d7-cw4xg   0/3     Init:0/1   0          4m53s
leadgenie-django-www-5ffcfc47d7-hwlcg   3/3     Running    0          10m
leadgenie-django-www-5ffcfc47d7-xzmb6   0/3     Init:0/1   0          4m53s

**To Reproduce**
1. Create a deployment
2. Associate with a horizontal pod scaler policy
3. Enable dev mode on the deployment
4. Cause the deployment to spin up new pods

**Expected behavior**
Options I can think of:
- New pods are launched with  their own volume claim
- The HPA policy is disabled
- The different pods somehow share the same volume

**Additional context**
This sounds similar to the use case we've discussed before for multiple services sharing the same codebase, or for dynamic containers

**Comment by rberrelleza** [comment]
This was reported by Basilica. I told them to disable the HPA manually for now, but it would be cool to somehow fix it.

**Comment by pchico83** [comment]
For this scenarios, the `services` field should be used instead of an interactive container
