### ISSUE TITLE
okteto up fails to run when using a kubernetes cluster as the context

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2580]
**Describe the bug**
okteto up fails to run when using a kubernetes cluster as the context. It fails with this error:
```
[okteto-dev|okteto] (okteto-dev:okteto)➜  compose-getting-started git:(master) ✗ okteto up -l=debug
INFO[0000] started okteto up -l=debug
INFO[0000] Found okteto file
INFO[0000] Using okteto @ okteto-dev as context
 i  Using okteto @ okteto-dev as context
INFO[0000] Found okteto file
INFO[0000] okteto manifest has no 'dev' section.
 !  okteto manifest has no 'dev' section.
INFO[0000] Do you want to configure okteto manifest now? [y/n]
 ?  Do you want to configure okteto manifest now? [y/n]y
INFO[0002] inferring name from git repository URL
INFO[0002] Okteto manifest (okteto.yml) deploy and build configured successfully
 ✓  Okteto manifest (okteto.yml) deploy and build configured successfully
DEBU[0003] found available port 57020
DEBU[0003] forwarding host: https://34.102.51.102
DEBU[0003] creating temporal kubeconfig file '/Users/ramiro/.okteto/kubeconfig-compose-getting-started'
DEBU[0003] found okteto manifest
DEBU[0003] error: could not parse reference:
INFO[0003] Error checking image at registry : error getting image tag digest: could not parse reference:
 x  Error checking image at registry : error getting image tag digest: could not parse reference:
```

**To Reproduce**

1. Set the okteto context to a kubernetes cluster
2. Clone https://github.com/okteto/movies-with-compose
3. Run 'okteto up api'

**Expected behavior**
App should be build and deployed

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.1.0

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by AdrianPedriza** [comment]
@rberrelleza It seems that the error is due to the fact that the docker-compose file is not specifying the target name of the image so we can't infer one if the user is using a non-okteto cluster. On the other hand, using okteto cloud we can infer the image name if it is not given. I think a solution could be to offer clearer logs to the user in this kind of situation. WDYT?

**Comment by rberrelleza** [comment]
Yes, I think logs on this, and ideally a work around would be great.

**Comment by jmacelroy** [comment]
I'm not sure that offering clearer logs is enough in this case. I think those logs should also point to a solution that makes sense to the user.

It may be that this is a similar case, https://community.okteto.com/t/how-can-i-set-the-registry-of-a-context/54

So, does it make sense to detect that it is a non-okteto kube cluster and either

1. allow them to set a "registry context" for build
2. tell the user to define the image location in the compose?

I'm not sure how this worked before on vanilla clusters but it would be nice to imitate what we used to do if possible?

**Comment by pchico83** [comment]
> I'm not sure that offering clearer logs is enough in this case. I think those logs should also point to a solution that makes sense to the user.
> 
> It may be that this is a similar case, https://community.okteto.com/t/how-can-i-set-the-registry-of-a-context/54
> 
> So, does it make sense to detect that it is a non-okteto kube cluster and either
> 
> 1. allow them to set a "registry context" for build
> 2. tell the user to define the image location in the compose?
> 
> I'm not sure how this worked before on vanilla clusters but it would be nice to imitate what we used to do if possible?

This wasn't supported before, because the CLI didn't have a `deploy` command on vanilla clusters.
I would go this way:
- Add a clear message as a P0
- Integrate with custom registries once we solve the current cli stability issues. The CLI 2.0 experience is kind of incomplete for vanilla clusters until we do integrate with custom registries

**Comment by AdrianPedriza** [comment]
For the time being, more concise logs have been added (see associated PR). On the other hand, an issue has been opened to deal with custom registries. #2637
