### ISSUE TITLE
add --wait to okteto destroy

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2586]
**Is your feature request related to a problem? Please describe.**
It's confusing that `okteto deploy` accepts a `--wait` command but okteto destroy doesn't.  Does this mean that `okteto deploy` can be run async, while `destroy` is always sync?

**Comment by pchico83** [comment]
@jLopezbarb what does `--wait` mean in `okteto deploy`?

**Comment by jLopezbarb** [comment]
Once the commands has been executed if `--wait` is passed, it list all the deployments and statefulsets that has the deployed by label and wait until all of them has the `running` status.

For the destroy command we should wait until no deployments/statefulsets with the label `deployed-by` exists.
