### ISSUE TITLE
Okteto for hashicorp nomad

### ISSUE THREAD

**Issue by thatsk** [okteto/okteto#2587]
We would like to see if we can integrate with hashicorp nomad for inner loop development.
https://nomadproject.io/

**Comment by pchico83** [comment]
Hi @thatsk. How are you using nomad today? are you running it locally for development?

**Comment by thatsk** [comment]
We are deploying our springboot container to nomad cluster. Nomad has master. And client architecture. So if we can use oketo for inner dev loop without using this bulky k8s cluster that would be awesome.

**Comment by jmacelroy** [comment]
Thanks for your submission @thatsk. Currently there are no plans for nomad support. If you think there should be more discussion on this please add a feature request at https://community.okteto.com/
