### ISSUE TITLE
"okteto logs" to show the aggregated logs of a deployment

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#260]
**Is your feature request related to a problem? Please describe.**
I want to show the logs of a deployment, but `kubectl` has a horrible experience since logs are per pod, and the pod name is dynamic.

**Describe the solution you'd like**
"okteto logs" knows the deployment name, queries the associated pods, and show the logs of these pods.
It could also show other interesting information like healthcheck status, events...

**Comment by pchico83** [comment]
workaround is to use `kubectl logs  deployment.apps/vote` for now

**Comment by rberrelleza** [comment]
There are several kubernetes tools that do this already. We'll reevaluate if there's a strong user ask.

**Comment by pchico83** [comment]
@fishera123 would it work, as a first solution, to pipe with `grep` to filter logs? we would add a prefix to every log line with the pod name
