### ISSUE TITLE
error message is missing file name

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2627]
**Describe the bug**
The error message is missing the file name is looking for
![image](https://user-images.githubusercontent.com/475313/166345571-eca473e7-7b6c-4f0d-a20a-3ee2f930dc51.png)

**To Reproduce**

1. Create a repo with only a Dockerfile
2. Run okteto up

**Expected behavior**
I was expecting the error message to include a file name

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.2.1

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by jmacelroy** [comment]
@rberrelleza what would the filename be? It strikes me that it should be `okteto manifest doesn't exist, would you like to create one? [y/n]`
