### ISSUE TITLE
Unable to forward the window resize message to remote

### ISSUE THREAD

**Issue by xis19** [okteto/okteto#2630]
When I use iterm2, and let `okteto` to connect to remote development container, I noticed that if I resize the iterm2 window, the remote is not receiving the resize message. The evidence is that the vim window is not rendering properly when I resize.

**To Reproduce**

1. Open iTerm2
2. `okteto up -f okteto.yml`
3. `vim` or any other full screen program
4. Resize iTerm2 and the `vim` output is messed up

**Expected behavior**
`vim` should re-render with proper output.

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.3.1
- CLI 2.2.1

**Additional context**
I have messaged people in Kubernetes Slack, okteto channel, with a screen snapshot.

**Comment by rberrelleza** [comment]
For context -> https://kubernetes.slack.com/archives/CM1QMQGS0/p1651537768138059
