### ISSUE TITLE
integrate a custom registry to build app images if the user is working on a cluster not managed by okteto

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#2637]
**Describe the bug**
Currently, if the user is using a cluster that does not have okteto installed and does not specify the name of the images of his application, the `docker.io` registry is inferred to build the images which causes in most occasions an error when not knowing the reference or the record of the image.

**To Reproduce**

1. Set the okteto context to a kubernetes cluster not managed by Okteto
2. Clone https://github.com/okteto/movies-with-compose
3. Run 'okteto up api'
4. See error:
![Captura de pantalla 2022-05-04 a las 10 04 17](https://user-images.githubusercontent.com/22500940/166647041-fc97bbe3-66f2-4983-94a7-7223124051c5.png)

**Expected behavior**
Allowing the user to build images using a custom registry would avoid this situation.

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.2.0

**Comment by rberrelleza** [comment]
my personal experience with this is that most people that run into this do it because they are running one our samples, and they don't have an image specified.   My hunch is that a clear error message might be enough here.

Do we know if we have users that need a "custom registry" for this? Do we consider dockerhub a custom registry? How would this work for minikube?

**Comment by pchico83** [comment]
> my personal experience with this is that most people that run into this do it because they are running one our samples, and they don't have an image specified. My hunch is that a clear error message might be enough here.
> 
> Do we know if we have users that need a "custom registry" for this? Do we consider dockerhub a custom registry? How would this work for minikube?

Yes, I would start with a clearer error message and also, making the `image` field more prominent by modifying our samples. If we find that that experience isn't satisfactory, we could think about a better integration for third party registries

**Comment by pchico83** [comment]
This is now partly fixed with a clear error message
