### ISSUE TITLE
"okteto up" never finishes if the manifest filename changes

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#264]
**Describe the bug**
okteto up gets stuck synchronizing files if the manifest filename changes between `okteto up` commands

**To Reproduce**
1. `okteto up`
2.  `exit` or `ctrl + c`
3. `mv okteto.yml app.yml`
4. `okteto up -f app.yml`

**Expected behavior**
`okteto up` should complete the initial sequence

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.0.11

**Comment by pchico83** [comment]
This is due to the okteto init container logic, I will assign it to myself.

**Comment by pchico83** [comment]
Closed by #251
