### ISSUE TITLE
Guidance on debugging with full Visual Studio

### ISSUE THREAD

**Issue by mladedav** [okteto/okteto#2645]
**Is your feature request related to a problem? Please describe.**
I would like our team to start using okteto for cloud development. We use mix of OSs and IDEs so support for Visual Studio (not just Code) is needed for it to work out.

**Describe the solution you'd like**
I would like to see a blog post (or maybe just pointers) on how to make this work. There are several posts about VS Code, but none about Visual Studio. Possibly also JetBrains IDEs (I have seen there is a post about PyCharm, but we use mainly .NET so we would need Rider. I have not checked if there would be any issues there).

**Describe alternatives you've considered**
I have tried to make it work myself with https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-dotnet-core-linux-with-ssh?view=vs-2019
This ends with `Unable to connect to 'root@localhost:59720'. Operation not supported. Unknown error: 0x80004005.` I have used the port from `~/.ssh/config` for the given container.

I have checked that I can ssh into the container with `ssh root@localhost -p 59720 -i ~\.okteto\id_rsa_okteto -o StrictHostKeyChecking=no`. After the first time I can also ssh without that option. Yet Visual Studio gives the same error with the same configuration for ssh.

**Comment by jmacelroy** [comment]
Hello and thanks for opening an issue and describing your situation. Our new community forum seems like a good place to ask so that we can preserve any answers or discussion in share updates more easily. Would you mind asking about this on https://community.okteto.com/ ?
