### ISSUE TITLE
`okteto restart` is not working

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2647]
**Describe the bug**
`okteto restart` is not working

![image](https://user-images.githubusercontent.com/49416765/166915478-1e20ba8b-ea7b-4f82-8fe9-aec793fa241d.png)

**To Reproduce**

1. Deploy a repo
2. Run `okteto up`
3. Get out of the dev pod
4. Run `okteto restart`

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Ubuntu

**Comment by pchico83** [comment]
@AgustinRamiroDiaz which behavior do you expect in this case? `okteto restart` only works for [services](https://www.okteto.com/docs/reference/manifest/#services-object-optional)

**Comment by AgustinRamiroDiaz** [comment]
I don't remember actually, but I've tried it now and it seems to work as expected
