### ISSUE TITLE
`okteto up` panics with nil pointer dereference when there's no backend api working

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2670]
**Describe the bug**
If the okteto api is down, `okteto up` panics. It could arise also when the context is not initialized, or with a vanilla cluster (but I haven't tried it out)

![image](https://user-images.githubusercontent.com/49416765/167699555-4fdcff81-4e4b-466e-aa88-d478b171889a.png)

**To Reproduce**

1. Point your context to an okteto cluster
2. Shut down the api
3. Run `okteto up`

**Expected behavior**
The cli should never panic. It should show an error message to guide the user

**Comment by jmacelroy** [comment]
I changed to high as a stack trace is never nice, especially when it seems preventable through an improvement in handling api usage/calls.

**Comment by AdrianPedriza** [comment]
couldn't reproduce the issue.

![Captura de pantalla 2022-06-29 a las 17 26 47](https://user-images.githubusercontent.com/22500940/176475534-7696625c-cf48-4095-b65c-ff6ea35cae01.png)

@AgustinRamiroDiaz Can you still reproduce it?

**Comment by AdrianPedriza** [comment]
@okteto/cli  WDYT about a new message in these cases?

**Comment by jLopezbarb** [comment]
@AdrianPedriza can you try running again the same command, adding the flag `--log-level=debug`? 
If there is no log or the log is not clear enough, we should write a better message for debugging

**Comment by AgustinRamiroDiaz** [comment]
> @AdrianPedriza can you try running again the same command, adding the flag `--log-level=debug`? If there is no log or the log is not clear enough, we should write a better message for debugging

Agree. A log at the debug level sounds great!

**Comment by AdrianPedriza** [comment]
@AgustinRamiroDiaz we have logs that can give more information about the reason. (502 status code). It is OK for you?

![Captura de pantalla 2022-07-14 a las 14 40 28](https://user-images.githubusercontent.com/22500940/178994507-4e00e529-2262-4eea-933b-74b87ae2958e.png)

**Comment by AgustinRamiroDiaz** [comment]
> @AgustinRamiroDiaz we have logs that can give more information about the reason. (502 status code). It is OK for you?
> 
> ![Captura de pantalla 2022-07-14 a las 14 40 28](https://user-images.githubusercontent.com/22500940/178994507-4e00e529-2262-4eea-933b-74b87ae2958e.png)

Great! That's enough to debug the issue 👍
