### ISSUE TITLE
"okteto context use" doesn't refresh a token

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2673]
**Describe the bug**
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/475313/167795353-85e57f52-6941-4411-821a-731d1d8d4548.png">

**Expected behavior**
I was expecting okteto to re-auth instead of asking me to run a second command with the same data I already provided.

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.2.2

**Comment by ifbyol** [comment]
@rberrelleza I think this is already solved in master or the RC: https://github.com/okteto/okteto/issues/2326. Didi you use one of those versions or another one?

**Comment by ifbyol** [comment]
oh, I didn't see the version in the issue description 🤦 

It is already fixed on master. This is what happened to me with `2.2.1`

<img width="911" alt="Captura de Pantalla 2022-05-12 a las 9 16 11" src="https://user-images.githubusercontent.com/3510171/168014654-6eec04c2-80d2-4c8f-a3e3-95a8db10a23e.png">

And this happened to me with master version

<img width="2302" alt="Captura de Pantalla 2022-05-12 a las 9 21 56" src="https://user-images.githubusercontent.com/3510171/168014723-dfc5995a-de38-4f1e-b99b-fdb21af594ca.png">
