### ISSUE TITLE
error in FinishPipeline: label name "name" missing in label map

### ISSUE THREAD

**Issue by f0ntana** [okteto/okteto#2676]
**Describe the bug**
i'm receiving this error on try to upload my preview app:
error in FinishPipeline: label name "name" missing in label map

**To Reproduce**
<img width="964" alt="Screen Shot 2022-05-11 at 10 22 52" src="https://user-images.githubusercontent.com/6570783/167872899-02fe22d5-1fee-433b-84f1-c7c3129921aa.png">

**Comment by pchico83** [comment]
@f0ntana thanks for reporting this! Would you mind creating the issue in our [community forum](https://community.okteto.com/)? This error seems related to Okteto Cloud, not to the Okteto CLI

**Comment by ifbyol** [comment]
Hi @f0ntana , we have identified the problem and we have applied a fix today in Cloud. You shouldn't face it anymore. The issue shouldn't affect your deployment as it was failing in the last step of a preview environment deployment.
