### ISSUE TITLE
Simplify tests by using t.TempDir

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2677]
Currently we are using os.MkdirTemp and os.RemoveAll to create and cleanup temporary directory in tests. We can use the T.TempDir function from the testing package to create temporary directory. The directory created by T.TempDir is automatically removed when the test and all its subtests complete.

This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.

Reference: https://pkg.go.dev/testing#T.TempDir

**Comment by jLopezbarb** [comment]
We should also start using `t.Setenv()` to cleanup the env vars after the test

**Comment by jmacelroy** [comment]
@jLopezbarb would you like me to schedule this in as part of a release cycle or would you like to manage who does it and when it gets done?

**Comment by jLopezbarb** [comment]
I'll send a PR later today. I think using the `t.Setenv` function makes it easier to parallelise unit tests

**Comment by jmacelroy** [comment]
> I'll send a PR later today. I think using the `t.Setenv` function makes it easier to parallelise unit tests because it detects when a test is conflicting with other because of a race condition with the env vars

Possibly but using t.Setenv and t.Parallel() will cause a panic I think. It's not allowed.

**Comment by jLopezbarb** [comment]
Reopened: We need to wait until windows support this behaviour.
- Need to upgrade to Go 1.18
- Need to have this back port merge: https://github.com/golang/go/issues/52986

**Comment by pchico83** [comment]
@jLopezbarb should we close this issue now?

**Comment by jLopezbarb** [comment]
Yes, we can close it for now
