### ISSUE TITLE
Weird behavior with .stignore patterns

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2679]
**Describe the bug**
A user stated that they get `(?d)` as a prefix in every line in their `.stignore`, even in lines starting with `#` or `!`
[context here](https://community.okteto.com/t/stignore-prefixed-d-for-all-patterns-even-if-include-file-or-exclude-patterns/78) 

**To Reproduce**

1. Create an `.stignore` with some patterns
2. Run `okteto up`
3. Run `cat .stignore`

OS: Windows10

**Comment by pchico83** [comment]
@AgustinRamiroDiaz this is expected:
```
A pattern beginning with a (?d) prefix enables removal of these files if they are preventing directory deletion. This prefix should be used by any OS generated files which you are happy to be removed.
```
Otherwise, a folder deletion could be incomplete, and keep the synchronization in a loop forever.
Is it creating a weird behavior? or is just that users didn't expect to find it there?

**Comment by AgustinRamiroDiaz** [comment]
@pchico83 the user was experiencing this change:

- local .stignore: `#include something`
- remote .stignore: `(?d)#include something`

I tried to recreate and I couldn't repoduce exactly (will try with windows later), but I also got a weird behavior:
- local .stignore: `#include something`
- remote .stignore: nothing, and the `something` file had lines in it

Is this expected?

**Comment by pchico83** [comment]
@AgustinRamiroDiaz the `stignore` is only pushed to the remote at the beginning of `okteto up`, does this explain what you are seeing?

**Comment by AgustinRamiroDiaz** [comment]
@pchico83 still no, I deleted the `.stignore` file and ran `okteto down` on each iteration to make sure the file was cleaned

**Comment by pchico83** [comment]
@AgustinRamiroDiaz I cannot repro it. Could you list the repro steps with an sample git repo?

**Comment by AgustinRamiroDiaz** [comment]
@pchico83 here is an example repo https://github.com/AgustinRamiroDiaz/okteto-stignore

**Comment by pchico83** [comment]
Oh, I see, we shouldn't pre-pend `(?d)` in lines starting with `#` or `!`
