### ISSUE TITLE
when okteto up finishes because my environment was destroyed, I'd like to get a clear error message

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2686]
**Is your feature request related to a problem? Please describe.**
Today, if my dev env is destroyed from a different machine (or via the UI) while okteto up is active, it fails with an error like this:

![image](https://user-images.githubusercontent.com/475313/168221611-f55d24a3-80e5-418c-9000-b4cccbd8ca64.png)

**Describe the solution you'd like**
A clear and concise error that tells me that my dev environment is not running because it was destroyed

**Comment by rberrelleza** [comment]
I haven't seen it in a while @jLopezbarb. Feel free to close if there's no repro.

**Comment by jLopezbarb** [comment]
Closing because we have no clear repro steps. Feel free to reopen if the error appears again
