### ISSUE TITLE
Remove Global registry optimization

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2712]
**Describe the bug**
There is an undocumented feature to skip the build of the image if the image sha256 is already present in the `okteto.global` registry. This feature diverges the behavior of the okteto cli when running locally, or running inside of the pipeline installer job, which makes things harder to test and it's a source of regressions.

Also, the current feature, as it's designed, it's too magic and hard to understand by our users. 

Let's remove the feature to simplify our codebase and testing, and work on a new spec to have similar functionality, but with a design easier to understand, and easier to test.

**Comment by teresaromero** [comment]
@pchico83 do we want to keep the check to the dev registry and skip or this shall also be removed?

**Comment by pchico83** [comment]
> @pchico83 do we want to keep the check to the dev registry and skip or this shall also be removed?

@teresaromero let's remove everything for now. I will create a github discussion with a new approach for this
