### ISSUE TITLE
`okteto deploy` should support several files with the `-f` flag

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2720]
**Describe the bug**
`okteto deploy` is deprecating `okteto stack deploy`, but it's missing the functionality to merge several compose files in a single one. Same for `okteto destroy` and `okteto stack destroy`.

Without this, we cannot deprecate `okteto stack`.

**Comment by jLopezbarb** [comment]
Should this feat work only for compose files? Or should we also merge okteto manifests?

**Comment by pchico83** [comment]
@jLopezbarb We already support merging compose files with this notation:
```
deploy:
    compose:
       - file1
       - file2
       ...
 ``` 
 this issue should be to support merging okteto manifests (or compose files). We can reuse the logic to implement local dependencies https://github.com/okteto/okteto/issues/2254

**Comment by jLopezbarb** [comment]
I think this will require some backend changes to redeploy from the UI when using multiple files, or should we remove the possibility to redeploy from the UI

Another thing is how to display all the manifests in the UI... I thought we could do something like this:
```yaml
deploy:
  - kubectl apply -f k8s.yml
----
services:
  app:
     image: alpine
```
But with that we are losing the name of the manifest and can be confusing

**Comment by pchico83** [comment]
> I think this will require some backend changes to redeploy from the UI when using multiple files, or should we remove the possibility to redeploy from the UI
> 
> Another thing is how to display all the manifests in the UI... I thought we could do something like this:
> 
> ```yaml
> deploy:
>   - kubectl apply -f k8s.yml
> ----
> services:
>   app:
>      image: alpine
> ```
> 
> But with that we are losing the name of the manifest and can be confusing

@jLopezbarb good point. For simplification, we could store the result of merging the okteto manifest for the UI. Another option is to don't implement this feature, and go with local `dependencies`, which covers basically the same use cases, but it's more declarative

**Comment by jLopezbarb** [comment]
I'll implement [local dependencies](https://github.com/okteto/okteto/issues/2254) first until we have a clearer view on how to implement this. 

I think that we still need this issue to be done to be able to deprecate completely `okteto stack deploy`. We already have a way of getting the same behavior using the manifest V2 but we should be able to have the same behavior

**Comment by pchico83** [comment]
> I'll implement [local dependencies](https://github.com/okteto/okteto/issues/2254) first until we have a clearer view on how to implement this.
> 
> I think that we still need this issue to be done to be able to deprecate completely `okteto stack deploy`. We already have a way of getting the same behavior using the manifest V2 but we should be able to have the same behavior

@jLopezbarb yes, let's go with local dependencies. I am going to close this issue. We can create it again when needed.
It's fine to deprecate `okteto stack` and just give support via the v2 compose notation
