### ISSUE TITLE
okteto destroy doesn't destroy dependencies

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2722]
**Describe the bug**
When I have a manifest that includes dependencies, running "okteto deploy" deploys the resources described in the manifest + the dependencies. 

When I then run "okteto destroy", the dependencies are not destroyed. 

Given that 'destroy' is the opposite command of 'deploy', I'd expect the default use of the command to destroy everything that the deploy command created.

- OS: macos
- Version 2.3

**Comment by pchico83** [comment]
You have `okteto destroy --dependencies` for this

**Comment by rberrelleza** [comment]
I think the default should be the opposite, to be consistent with the default behavior of "okteto deploy".

**Comment by pchico83** [comment]
@rberrelleza this would be a new feature, use the product backlog if you want to discuss a new behavior
