### ISSUE TITLE
Warning unmarshall messages are shown two times

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2728]
**Describe the bug**
If a okteto yaml/compose file/pipeline manifest has a warning while unmarshalling the message will appear two times (one before the context initialisation and another one after it). It's weird to see the same warning several times
<img width="686" alt="Captura de pantalla 2022-05-30 a las 12 35 53" src="https://user-images.githubusercontent.com/25170843/170974831-ed71741e-5b8c-4a74-89bf-53544c568f83.png">

**To Reproduce**

1. Create this manifest:
```
name: test
image: okteto/golang:1
command: bash
labels:
  - as:as
sync:
- .:/usr/src/app
forward:
- 2345:2345
- 8080:8080
autocreate: true
```
2. Run okteto up 

**Expected behavior**
I wanted to see only one warning message

**Desktop (please complete the following information):**

- OS: macOs
- Version 2.3.0

**Additional context**
This is due to how we read context. We need to load the same file two times, one to extract the namespace and context (contextresource) and another one to get the manifest struct.  We should be loading only the contextresource instead of reading the whole file and extracting the context resource from the struct.

**Comment by ifbyol** [comment]
@mnevadom was facing a similar issue also when doing a refactor for the build to print a warning when `context` and `Dockerfile` are not properly set.

When executing a `deploy` we are displaying even 3 times the same warning
