### ISSUE TITLE
Add a quiet flag to namespace list

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2729]
**Is your feature request related to a problem? Please describe.**
When you have lots of namespaces and you want to remove all the namespace, right now we have to delete them one by one. It would be useful to run `okteto namespace delete ($okteto namespace list -q)` to remove all namespaces that you have. 

**Describe the solution you'd like**
Add a quiet flag (`-q`) to `okteto namespace list` to list only the namespace ids.

**Comment by jmacelroy** [comment]
I think we have too many options and they aren't always cohesive. I see the use case but I'm not sure it's compelling enough of a reason to warrant adding an option. I think the barrier to entry for updating a command or option should be high. This use case is possible to cover through scripting in the odd case that it's required.

Are there more reasons for a `-q`? Do you see any other value it would add for the users?
