### ISSUE TITLE
Okteto doesn't read .dockerignore when building images

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2744]
**Describe the bug**
When building images with `okteto deploy --build` or `okteto build .`, the `.dockerignore` file is beign ignored

![image](https://user-images.githubusercontent.com/49416765/171440154-233f4fb7-c17f-4c74-ab91-b6a5aa44c2c8.png)

I tested it running okteto with a `docker-compose.yml`

**To Reproduce**

1. Clone https://github.com/AgustinRamiroDiaz/microblogging-app
2. `cd react-frontend` and `npm i`
2. Run `okteto deploy --build`
3. When the frontend image is getting build, you'll see a huge context being transferred, which is the `node_modules` folder

**Expected behavior**
Okteto should build taking into account the `.dockerignore` file

**Additional context**
Another (lighter) way to reproduce could be to create a `.dockerignore` that ignores a file "test.txt" and create a Dockerfile that tries to copy "test.txt". With the current behavior, okteto should build the image, when instead it should fail due to the file being ignored

**Comment by AdrianPedriza** [comment]
@AgustinRamiroDiaz I have not been able to reproduce any of the scenarios, I have the expected behavior. If you still have the problem ping me, maybe I'm not playing it correctly.

**Comment by AgustinRamiroDiaz** [comment]
I cannot reproduce anymore. Thanks for trying! I wonder what change fixed this 🤔
