### ISSUE TITLE
Fallback to "token" when the CLI can't complete the log in sequence due to an error with localhost resolution or with the browser.

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2752]
**Describe the bug**

```
okteto -l debug context use https://cloud.okteto.com/
INFO[0000] started okteto -l debug context use https://cloud.okteto.com/
INFO[0000] authenticating with browser code             
INFO[0000] couldn't access the network: lookup localhost on 192.168.1.1:53: no such host
INFO[0000] couldn't start the login process: couldn't access the network
INFO[0000] Couldn't start the login process, please try again
 x  Couldn't start the login process, please try again
```

**Desktop (please complete the following information):**

- OS: archlinux

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by alexissellier** [comment]
Ola, I am the who rose this ticket, after investigating it appears that in my /etc/hosts file I had not any entries for localhost thus the cli try to lookup using the DNS provided by my operator and fail.

**Comment by rberrelleza** [comment]
@alexissellier ah that's great, thanks for finding the root cause! 

I still want to keep this ticket open because I think the CLI can do a better job on falling back to the "ask for an API key"  flow when we can't start the webserver (we have a similar use case when you're using the CLI on a machine without a browser installed)
