### ISSUE TITLE
okteto deploy doesn't compute well volumes with the `../..` pattern

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2758]
Trying to deploy [this compose file](https://opendev.org/zuul/zuul/src/branch/master/doc/source/examples/docker-compose.yaml) fails with :

```
 => ERROR [3/3] COPY ../../../tools/ /var/zuul-tools/:z                                                                                                 0.0s
------
 > [3/3] COPY ../../../tools/ /var/zuul-tools/:z:
------
 x  Error deploying compose: error building image 'registry.demo.okteto.dev/rberrelleza/examples-gerritconfig:okteto-with-volume-mounts': build failed: failed to solve: failed to compute cache key: "/tools": not found
```

Repro:
1. git clone https://opendev.org/zuul/zuul
2. cd zuul/doc/source/examples
3. okteto deploy

On version 2.2.1 I get the error above. On 2.3.3 I just get ` x  Syntax error volumes should be 'local_path:remote_path' or 'remote_path'`

**Comment by pchico83** [comment]
This is now fixed
