### ISSUE TITLE
Add versions selection to get.okteto.com

### ISSUE THREAD

**Issue by maroshii** [okteto/okteto#2765]
Right now https://get.okteto.com selects the latest binary from a channel and there's no way to select a specific version.

~~Possible DX:~~

1. ~~Have `https://get.okteto.com/{version}` for every versions released. Probably unmaintainable if we want to  keep doing it statically. It would require to upload a copy of the installation script along side the binaries into for eg `https://get.okteto.com/2.2.2`. This script will have the version hardcoded~~
2. ~~Have a server (nginx or the like) that we can use dynamically return the script. This can enable us to have metrics around downloads, etc but it needs to be maintained.~~

~~Other ideas?~~

 cc @pchico83

**Comment by pchico83** [comment]
I would go with simplicity while we implement something better. Documenting (and implementing) somethings like this should work:
```
OKTETO_VERSION=2.2.2 curl https://get.okteto.com/ -sSfL | sh
```

**Comment by pchico83** [comment]
> I tried that exact command and it doesn't work. Playing a little more with it it looks like this should do it:
> 
> ```
> curl https://get.okteto.com/test.sh -sSfL | OKTETO_VERSION=2.2.2 sh
> ```

oh, right! I would go with that approach, seems a reasonable DX and simple to implement
