### ISSUE TITLE
Pull latest available versions from downloads.okteto.com

### ISSUE THREAD

**Issue by maroshii** [okteto/okteto#2775]
We are still using github releases to decide whether there's a new release available and we should use https://downloads.okteto.com/cli/{channel}/versions. This is a follow up of https://github.com/okteto/okteto/pull/2727

**Comment by jLopezbarb** [comment]
@maroshii Isn't this already released?

**Comment by maroshii** [comment]
No, the PR was split into two and the second part was never released because it involved adding the `okteto channel` command but we still need to get the versions from downloads.okteto.com instead of github. This is the reference commit that didn't make it: https://github.com/okteto/okteto/commit/dcb8123ec6320388b4b3f0c470d5ffc1b2951d2e
