### ISSUE TITLE
typo in prompt when running okteto down

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/okteto#2778]
**Describe the bug**
If you run `okteto down` the prompt lists all dev containers but it says to select the container you want to "activate".

**To Reproduce**

1. Start a container
2. Run `okteto down`

**Expected behavior**
The prompt should say select the dev container you want to "deactivate". Another UX improvement could be if it lists down **only** the active containers instead of listing all containers.

**Desktop (please complete the following information):**

- OS: macOS
- Version: Okteto CLI 2.3.3

**Additional context**
![Screenshot 2022-06-10 at 12 17 49 PM](https://user-images.githubusercontent.com/56963264/173007770-cce7fc8f-dbcf-4901-83fa-ffb53408cfd7.png)

**Comment by jLopezbarb** [comment]
It's also affecting all other commands that use this selector (down/doctor/exec/initv1/push/restart/status)
