### ISSUE TITLE
okteto questions should default to yes

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2793]
**Describe the bug**
When I install any package and I get asked to accept. I usually just press enter and it works. It seems that okteto you always need to type `y + Enter`

**To Reproduce**

1. Run okteto up on an empty dir
2. When you get ` ?  okteto manifest (okteto.yml) doesn't exist, do you want to create it? [y/n]` press enter
3. See error

**Expected behavior**
I would like that empty line should default to yes

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.4.beta-1

**Comment by jLopezbarb** [comment]
Reopen since its not fixed

**Comment by volmedo** [comment]
This one should also be easy to fix. Since my other task is mostly done, should I take this one too?

**Comment by pchico83** [comment]
@volmedo awesome, thanks! I assigned the issue to you :-)
