### ISSUE TITLE
`okteto pipeline deploy` and `okteto preview deploy` should stream the pipeline logs

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2794]
**Is your feature request related to a problem? Please describe.**
Similar to `okteto deploy`, `okteto pipeline deploy` and `okteto preview deploy` should stream the logs of the deploy commands execution. This is specially frustrating when debugging GitHub preview actions, because the pipeline logs are lost on each deploy, and from an old GH action is impossible to troubleshoot why a github action failed.

**Comment by jLopezbarb** [comment]
How should be the output? We can't restore colors from the configmap. We only have the stages and the messages

**Comment by pchico83** [comment]
@jLopezbarb we should get the output from the Okteto streaming API, to have it on real time

**Comment by teresaromero** [comment]
@pchico83 @jLopezbarb this means to output the logs at the cli while the pipeline is being deployed? what happens when the --wait flag? if logs are streming how is that compatible with the wait flag?

**Comment by jLopezbarb** [comment]
This feature is only added when the user adds the `--wait` flag. 
I think that the approach should be that the logs stop and restart the spinner `"Waiting for repository '{NAME}' to be deployed..."` so we have the logs and the spinner at the bottom until the command finishes

**Comment by pchico83** [comment]
@jLopezbarb @teresaromero let's show the spinner just after the first line, similar to what we do in the Okteto UI

**Comment by maroshii** [comment]
@teresaromero I mentioned in the daily today that #2120 could help, but it's a completely different thing. My bad. This is to use the `/sse/logs/:spaceId/gitdeploy/:name` endpoint to stream the logs.
