### ISSUE TITLE
Consistency for filename, file and manifest parameters

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2824]
**Describe the bug**
There are several commands or manifest sections that require the path of an okteto manifest. For example, we are using `file` as a flag in Okteto CLI commands, but we are using `manifest` when defining [dependencies](https://www.okteto.com/docs/reference/manifest/#dependencies-string-optional).

We should unify on `file` everywhere to have a consistent notation.

At the `configmap` level, we are using `filename`. Same for the [Develop on Okteto](https://www.okteto.com/docs/cloud/deploy-from-git/#parameters) button

**Comment by jLopezbarb** [comment]
@pchico83 Changing it in the configmap requires changes on the backend and will create incompatibilities with previous okteto versions. Should we create it as part of `3.0` release

**Comment by pchico83** [comment]
@jLopezbarb I would focus on user-facing fields first. We can also make these changes without breaking changes, accepting the old and the new field names

**Comment by abs007** [comment]
I'd like to have a go at this. Could I be pointed to files having the user-facing fields?

**Comment by pchico83** [comment]
@abs007 this one requires a little of internal design, and we also need a few changes in our app to support this.
What do you think about implementing this feature? It's very powerful to customize your dev container:
https://github.com/okteto/okteto/issues/2300
