### ISSUE TITLE
Shell alias handling: /bin/sh: 1: kubectl: not found

### ISSUE THREAD

**Issue by zar3bski** [okteto/okteto#2827]
**Describe the bug**
Okteto does not seem to load aliases from `~/.profile` nor to inherit from system-wide aliases defined in `/etc/profile.d`. This is problematic for developers using distribution such as [microk8s](https://microk8s.io/) that wraps `kubectl`

**~/.profile**
```
alias kubectl='microk8s kubectl'
export kubectl
```

**/etc/profile.d/kubectl_alias.sh**
```
alias kubectl='microk8s kubectl'
export kubectl
```

```
 yarn okteto:up 
yarn run v1.22.11
$ okteto up
/bin/sh: 1: kubectl: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- OS: Ubuntu
- Version 21.10
- yarn v 1.22.11

How can I set Okteto so it understands that `kubectl` means `microk8s kubectl`

**Comment by pchico83** [comment]
@zar3bski one option is to sync your `~/.profile` file using secrets, would that work?
https://www.okteto.com/docs/reference/manifest/#secrets-string-optional

**Comment by zar3bski** [comment]
Thanks for your answer @pchico83  turned out: It's a Yarn limitation. I close the issue
