### ISSUE TITLE
Realtime env synchronization

### ISSUE THREAD

**Issue by ujwaldhakal** [okteto/okteto#2829]
**Is your feature request related to a problem? Please describe.**
I am using okteto to synchronize the pods running on remote server. I have env  file that I wanted to sync but inorder to update sync I need to boot `okteto up` command. Okteto up might take a long time in our case as it takes time to sync files.

**Describe the solution you'd like**
So is it possible to sync env file whenever file is synced or hook any events when the sync is happend to we can write code to update env manually ?

**Describe alternatives you've considered**
Hooking to the events from okteto when sync is happened so we can write code manually to set env vars from file to remote server

**Additional context**

**Comment by jLopezbarb** [comment]
This issue covers another important scenario:
- Let's say the user is developing a Python application and needs to update his `requirements.txt` to add a new dependency. We need to run pip install after updating the file.

We need to define how this should be shown to the user so he knows that we are running the hook and its output to know when it's finished

**Comment by ujwaldhakal** [comment]
> We need to define how this should be shown to the user so he knows that we are running the hook and its output to know when it's finished

I am quite confused here, are you looking for some way to run any commands inside okteto & let the user know the output when it's finished?

**Comment by jLopezbarb** [comment]
> > We need to define how this should be shown to the user so he knows that we are running the hook and its output to know when it's finished
> 
> I am quite confused here, are you looking for some way to run any commands inside okteto & let the user know the output when it's finished?

What I mean is that we need to notify the user when a synchronization event has been triggered and when it is finished. Exporting environment variables is fast enough, however, if someone launches a heavier command such as updating dependencies, we need to notify them when they are done so they can test their application again.

**Comment by pchico83** [comment]
@ujwaldhakal I am closing this issue in favor of https://github.com/okteto/okteto/issues/2025 which explains the propose solution based on sync hooks
