### ISSUE TITLE
Support `#inlcude <file> `at remote .stignore

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2832]
**Describe the bug**
When using the notation `#include <file>` to add more patterns to the .stignore file (for example, ignore all patterns that are covered by an existing .gitignore) we are not adding this line to the remote .stignore. 

When adding this, the file itself is not present yet at the remote folder, so we get an error for sync.

**To Reproduce**

1. Open a repo
2. Add #include .gitignore to the .stignore file
3. Run okteto up
4. You will be sycronizing fileswithout success, as the file .gitignore is not present when inizializing

**Expected behavior**
okteto up runs and the patterns of the .gitignore file are not syncronized

**Desktop (please complete the following information):**

- OS: macOS

**Additional context**
Proposed change is to run over the files listed as `#include <file> ` and add this patterns to the remote `.stignore`

**Comment by pchico83** [comment]
This is a new feature that should go through the product backlog if needed
