### ISSUE TITLE
Deploying an stack with same service modifies the existing one

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2843]
**Describe the bug**
Deploying the same compose with different name skips the creation of endpoints and deployments/sfs/jobs but modifies the current k8s service

**To Reproduce**

1. Copy the following docker-compose:
``` yaml
services:
  test:
    image: alpine
    ports:
      - 8080:8080
```
2. Run `okteto deploy --name test` on the compose folder 
3. Run `okteto deploy --name test-modify` on the compose folder 
4. Check that there are warnings skipping the creation of deployment and endpoint
5. Run `kubectl describe services test` and check that the label `stack.okteto.com/name` has the value of the second deploy (` test-modify`)

**Expected behavior**
It should skip the creation of the k8s service

**Desktop (please complete the following information):**
- Version 2.4.0

**Comment by jmacelroy** [comment]
@jLopezbarb I don't follow. I would expect it to redeploy everything with a new name.

**Comment by jLopezbarb** [comment]
we treat each deploy as if they were different because they have different names. On the other hand, if there is a collision in the deployment/statefulset/jobs we return an error to let the user know that there is already another compose deployed.
