### ISSUE TITLE
Stop updating github actions for deprecated commands

### ISSUE THREAD

**Issue by maroshii** [okteto/okteto#2847]
This applies to:

- Okteto Push
- Okteto Stack Deploy
- Okteto Stack Destroy
- Okteto Login
- Okteto Apply

We should:
- [ ] Remove `v2` branch
- [ ] Remove these repos from CI
- [ ] Add a deprecation notice in the repo README

**Comment by pchico83** [comment]
This will be part of the cli 3.0 release plan
