### ISSUE TITLE
We are not calculating properly the git repo and branch when the manifest specified is not in the root of the repo

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2849]
**Describe the bug**
When I execute `okteto deploy -f <whatever>` with a manifest in a different folder than the repo root, the CLI is not able to calculate properly the git repo and branch when the command is executed from the repo root.

I think it has something to do with the change we did to execute the commands of the manifest from the folder where the manifest is located instead of where the `deploy` command is being executed.

**To Reproduce**

If you go to the UI and redeploy the dev env, you would see that it is using the okteto.ymlfrom the root instead of the one used before because the info in the config map is not the right now

1. Clone the repo https://github.com/jmacelroy/go-getting-started and checkout `target-example` branch
2. From the root of the repo execute `okteto deploy -f functional_tests/okteto.yml`
3. When it finishes, if you check the Okteto UI, you can see that the git URL and branch are not available
4. But, if you copy the folder `.git` within `functional_tests` folder and execute the same command from the repo root, you would see that the git repo and branch are now available in the UI

**Expected behavior**
I would expect that the git url and branch are properly calculated as they are in the same folder where the `okteto deploy` is being executed

**Desktop (please complete the following information):**
- Version [e.g. 22]: 3.4.0

**Additional context**
I think it has something to do with the change we did to execute the commands of the manifest from the folder where the manifest is located instead of where the `deploy` command is being executed.

**Comment by pchico83** [comment]
We should check if the folder is a subfolder of a git repo. For example, running `okteto deploy` from a subfolder should also compute the git URL and branch properly

**Comment by jLopezbarb** [comment]
Blocked until #2855 is released
