### ISSUE TITLE
Retry server errors on pipeline deploy

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2853]
**Describe the bug**
We should retry server errors (5xx) on pipeline command because they can be transient. 

**Expected behavior**
It should retry the error at least one time 

**Desktop (please complete the following information):**

- Version 2.4.0

**Comment by ifbyol** [comment]
Just a note. The issue that originated this ticket was for HTTP status code 5xx. (different of HTTP 200 in the graphql API with some error messages)
