### ISSUE TITLE
Dev Environment name uses manifest path directory instead of repository name when inferred

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2854]
**Describe the bug**
When the cwd is change to execute the deploy command at the directory where the manifest is and the manifest does not contain a name parameter, the inferred name for the development environment is the directory where the manifest is. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Clone the repo https://github.com/jmacelroy/go-getting-started and checkout target-example branch
2. Remove name param from the okteto manifest
3. From the root of the repo execute okteto deploy -f functional_tests/okteto.yml
4. check dev environment 

**Expected behaviour**
Not sure this is a bug or expected behaviour. 

The okteto manifest could be at a sub-repo inside a monorepo-> so in this case makes sense de dev environment is called like the folder that contains the manifest

**Desktop (please complete the following information):**

- OS: macOS

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by pchico83** [comment]
@teresaromero Let's keep the folder name for now, the user can always use the `name` property to control this.
I think what's wrong in this case is:
- the value of `filename`, it should be the path respect the git root folder
- the git repo and branch is not properly computed

**Comment by ifbyol** [comment]
Can we close it then? We can reopen it if needed after some discussion/thinking coming from this ticket: https://github.com/okteto/okteto/issues/2855

**Comment by pchico83** [comment]
> Can we close it then? We can reopen it if needed after some discussion/thinking coming from this ticket: #2855

yes, let's close this one
