### ISSUE TITLE
update possible names a k8s manifest can have

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#2857]
we should add **manifest, manifest.yml, manifest.yaml** as possible names of a k8s manifest.

**Comment by jeremyphua** [comment]
Hello! Is it alright if i take a look at this issue?

To update the possible names, the change would be to add **manifest, manifest.yml, manifest.yaml** to the **manifestSubPath** slice in `pkg/model/manifest.go`.

**Comment by jLopezbarb** [comment]
Yes @jeremyphua, feel free to work on this feature.

> To update the possible names, the change would be to add **manifest, manifest.yml, manifest.yaml** to the **manifestSubPath** slice in `pkg/model/manifest.go`.
Yes, that should fix the issue

**Comment by jmacelroy** [comment]
I've assigned this issue to you. @jeremyphua to indicate you've got a fix in PR and that you requested to work on the issue. @jLopezbarb will help with getting it merged and in a release. @jLopezbarb I went ahead and put it as a candidate for 2.5, let me know if we need to change that.
