### ISSUE TITLE
I would like to have the information message with the context being used on every command executed

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2861]
**Is your feature request related to a problem? Please describe.**
Some commands like `okteto deploy` are printing an information message indicating the Okteto context that is being used. I find it very useful but I realize that other commands like `okteto pipeline deploy` aren't printing that message. I would like that all commands print the context being used.

<img width="529" alt="Captura de Pantalla 2022-06-30 a las 13 23 12" src="https://user-images.githubusercontent.com/3510171/176673816-27aaa579-93e1-47de-905d-396176deb551.png">

**Describe the solution you'd like**
Every Okteto command prints an information message with the context being used

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pchico83** [comment]
Fixed here https://github.com/okteto/okteto/pull/3133
