### ISSUE TITLE
okteto deploy inside container ask you to add `--token` flag but it can't be added

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2868]
**Describe the bug**
If you run okteto up and inside the container you run an okteto deploy command. The command will fail with the following error:
<img width="893" alt="Captura de pantalla 2022-06-30 a las 21 45 30" src="https://user-images.githubusercontent.com/25170843/176764361-4888803f-23a0-4481-846a-071ecb5eeb35.png">

But when adding the flag to the command it will fail with  `x  Unknown flag: --token`

**To Reproduce**

1. Copy the following okteto manifest:
```yaml
name: aaaa
image: okteto/golang-ci:1.17.10
command: bash
sync:
- .:/usr/src/app
autocreate: true
```
2. Run `okteto up` 
3. Run `curl https://get.okteto.com -sSfL | sh` inside the container
4. Create the following okteto manifest inside the container:
```yaml
deploy:
  ls
```
5. Run `okteto deploy` from the path of the new okteto manifest
6. See the image error
7.  Run `okteto deploy --token YOUR_TOKEN` and check that it returns `x  Unknown flag: --token`

**Expected behavior**
Be able to run the command or return a proper error without mentioning `--token` flag

**Desktop (please complete the following information):**

- Version 2.4.1

**Comment by jmacelroy** [comment]
What's the common use case for doing this?

**Comment by pchico83** [comment]
> What's the common use case for doing this?

I guess running inside an online IDE, like GitHub Codespaces or Gitpod

**Comment by teresaromero** [comment]
@jLopezbarb i've been able to reproduce this. I see the error is coming from the context run that is done at the deploy. token is not a flag from deploy, but from the conext command we run prior to the deploy command. Should we intercept this `ErrTokenFlagNeeded` at the commands that use `contextCMD.NewContextCommand().Run` and invite the user to run okteto context before running any command inside a container? or some how pass the OKTETO_TOKEN envvar to the dev container?

**Comment by jLopezbarb** [comment]
I've found that you are able to deploy it if you add the token environment variable. I think we should keep the current behavior but returning a proper error mentioning that you need to specify `OKTETO_TOKEN` as environment variable. WDYT? @pchico83 @jmacelroy
