### ISSUE TITLE
Spec and Validation of Manifest Parsing

### ISSUE THREAD

**Issue by jmacelroy** [okteto/okteto#2870]
The manifest parsing process has become more complicated with multiple manifest types and versions. We should take account and specify what the desired user experience is, follow up with a test plan, and implement the spec and test plan if there's any key differences in implementation.

- [x] Specification
    - [x] User Experience
    - [ ] Technical
- [ ] Test Plan
- [ ] Validation and Implementation

**Comment by pchico83** [comment]
@jmacelroy what's the current state of this one? Should we close it and consider it on planning when needed?
