### ISSUE TITLE
Contributor Docs and Tooling Improvements

### ISSUE THREAD

**Issue by jmacelroy** [okteto/okteto#2871]
- [x] #2985
- [ ] Audit testing tools and make them as easy to run as reasonably possible for all contributors
- [x] Highlight the proper use of PR labels.

The idea is to make it as easy as possible to test your changes and label their impact. The PR labels will need to be reviewed as part of the PR.

**Comment by jLopezbarb** [comment]
Highlighting the proper use of PR labels was already done by @maroshii. 
You can check out the section [pull request labels](https://github.com/okteto/okteto/blob/master/docs/RELEASE.md#pull-request-labels) on the [RELEASE document](https://github.com/okteto/okteto/blob/master/docs/RELEASE.md).

I created #2985 to update the contribution guidelines to link the how-to test document.

Regarding `Audit testing tools and make them as easy to run as reasonably possible for all contributors`, what do you mean, we already encourage our users to use [testify](https://github.com/stretchr/testify) to have descriptive failures.

**Comment by jmacelroy** [comment]
> Highlighting the proper use of PR labels was already done by @maroshii. You can check out the section [pull request labels](https://github.com/okteto/okteto/blob/master/docs/RELEASE.md#pull-request-labels) on the [RELEASE document](https://github.com/okteto/okteto/blob/master/docs/RELEASE.md).
> 
> I created #2985 to update the contribution guidelines to link the how-to test document.
> 
> Regarding `Audit testing tools and make them as easy to run as reasonably possible for all contributors`, what do you mean, we already encourage our users to use [testify](https://github.com/stretchr/testify) to have descriptive failures.

When you submit a PR there are a lot of things that get ran. What is getting run and why? If something fails can I run it all locally and if so, how? Ideally a contributor would be able to run everything that gets run by GH actions and circle ci easily and consistently on their dev setup. Also, are there any tools that run on PRs or commits that we don't actually need and aren't helping us?

**Comment by teresaromero** [comment]
Related to https://github.com/okteto/okteto/issues/2872

**Comment by teresaromero** [comment]
@jmacelroy @jLopezbarb should this issue be done once #2872 has been merged?

**Comment by jLopezbarb** [comment]
yes, I think we can close it for now
