### ISSUE TITLE
Audit Circle CI and Github Actions for the Project

### ISSUE THREAD

**Issue by jmacelroy** [okteto/okteto#2872]
We are using a lot of linters, test runners and bots that may or may not be providing value. We need to audit and decide what we want to keep, what should be reconfigured and what should be removed.

**Comment by Diazbesjorge** [comment]
I was discussing precisely this same topic with @ifbyol a couple of days ago. Our opinion is that we should keep what we are going to proactively use and clean up the rest in order to reduce the noise ratio.

**Comment by teresaromero** [comment]
I've added a document at notion to discuss each workflow and app we have that take part into the dev flow and comment there https://www.notion.so/okteto/Audit-Circle-CI-and-Github-Actions-for-the-Project-aeb00aaee9e543d98bbbd354d157c7da
