### ISSUE TITLE
I can't cancel `okteto destroy`

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2873]
**Describe the bug**
`okteto destroy` won't stop if I press CTRL+C 

**To Reproduce**

1. Deploy a docker-compose
2. run `okteto destroy`
3. press `ctrl+c`

**Expected behavior**
I expect the command to stop. Instead, it continues until it's finalized.

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.4.1

**Comment by pchico83** [comment]
@jLopezbarb is this one already fixed?
