### ISSUE TITLE
Fail with a clearer error when docker compose doesn't have dev section

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2876]
**Describe the bug**
If I run okteto up on a repo with a docker compose and the inferred okteto manifest (docker-compose is transformed into a okteto manifest) doesn't have any dev section (only services with local volumes are transformed into devs) we fail with an unclear error

**To Reproduce**

1. Copy the following docker-compose
```yaml
services:
  web:
    image: alpine
    ports:
    - 8080

```
2. Run `okteto deploy` 
3. Run `okteto up web`
4. See warning indicating that there isn't any dev configured
5. Type `n` when asked if you want to configure
6. See error indicating that no manifest has no dev section

**Expected behavior**
A clear and concise error on why I can't run `okteto up` from my docker-compose file

**Desktop (please complete the following information):**

- Version 2.4.1

**Additional context**
<img width="537" alt="Captura de pantalla 2022-07-01 a las 9 50 57" src="https://user-images.githubusercontent.com/25170843/176850314-f9feae29-495d-4078-99b2-dbb0949b448d.png">

**Comment by odedlaz** [comment]
@jmacelroy put it on me please.

**Comment by jLopezbarb** [comment]
Hi @odedlaz, I assigned you to work on this PR 😉

**Comment by jLopezbarb** [comment]
Hi @odedlaz, Could you post what's the current status of this issue? We would like to have it for the next release. If you don't have time to work on it ping us and will assign any other member to work on it

**Comment by odedlaz** [comment]
@jLopezbarb Ill try to push a fix in the next couple of days. If I don't, reassign. sounds good?
