### ISSUE TITLE
Application endpoints are not displayed anymore when `okteto deploy` is executed

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2885]
**Describe the bug**
When `okteto deploy` was being executed locally (not within a pipeline), we were displaying the endpoints of the applications at the end of the operation.

At some point, this stopped working and checking the output when executing the command with `-l=debug`, you can see 
```
INFO[0004] could not retrieve endpoints: [ingresses.networking.k8s.io](http://ingresses.networking.k8s.io/) is forbidden: User "system:serviceaccount:okteto:xxxx" cannot list resource "ingresses" in API group "[networking.k8s.io](http://networking.k8s.io/)" at the cluster scope
```

The issue is that we are not specifying the right namespace [when creating the options to show the endpoints](https://github.com/okteto/okteto/blob/master/cmd/deploy/deploy.go#L423). This is provoking that the search of ingresses is done with the namespace `""`, and users don't have permissions to do that.

We should initialize properly the namespace when checking the endpoints

**To Reproduce**

1. Clone some repo which should generate an endpoint
2. Execute `okteto deploy` from the root
3. Output doesn't contains the  generated endpoint(s)

**Expected behavior**
The generated endpoint(s ) should be listed as we had before

<img width="436" alt="Captura de Pantalla 2022-07-04 a las 11 33 29" src="https://user-images.githubusercontent.com/3510171/177127260-1321757b-0a64-4851-9604-9e2f9322f487.png">

**Desktop (please complete the following information):**

- Version: `2.4.1`

**Additional context**

We need to do something similar to this

```
diff --git a/cmd/deploy/deploy.go b/cmd/deploy/deploy.go
index 4b8d34c2..3d15692f 100644
--- a/cmd/deploy/deploy.go
+++ b/cmd/deploy/deploy.go
@@ -420,7 +420,7 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
                                }
                        }
                        if !utils.LoadBoolean(model.OktetoWithinDeployCommandContextEnvVar) {
-                               if err := dc.showEndpoints(ctx, &EndpointsOptions{Name: deployOptions.Name}); err != nil {
+                               if err := dc.showEndpoints(ctx, &EndpointsOptions{Name: deployOptions.Name, Namespace: deployOptions.Manifest.Namespace}); err != nil {
                                        oktetoLog.Infof("could not retrieve endpoints: %s", err)
                                }
                        }
```

We should verify this is enough and adding some test

**Comment by ifbyol** [comment]
@jmacelroy This one should be easy and we might want to include it in `2.5`. Our getting started guides mention that output

**Comment by jLopezbarb** [comment]
+1 to include them on `2.5`

**Comment by jmacelroy** [comment]
I added it to 2.5 as a low priority. It would be higher in priority if the endpoints weren't available in the UI. @ifbyol are the endpoints still available in the UI?

**Comment by ifbyol** [comment]
@jmacelroy yes, endpoints are still available in the UI, but only if you deploy the services in an Okteto cluster. For vanilla clusters, which was one of the motivations of implementing `okteto deploy` command, users don't have information about the generated endpoints
