### ISSUE TITLE
`okteto up` doesn't work properly when the service name contains `_` and the deploy replaced that char by `-`

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2888]
**Describe the bug**
If I have a service in a docker compose which contains a `_` and I deploy it, I get a warning saying that is being sanitized:

```
 !  Service 'functional_test' has been sanitized into 'functional-test'. This may affect discovery service.
```

But then, if my okteto manifest references that service using `_` too, when I execute `okteto up <service_name>` it fails with:

```
 x  Application 'functional_test' not found in namespace 'nacho'
```

The deployment it tries to set as dev is called `functional-test`.

If Okteto automatically translate the service name when deploying the service, it should do the same when setting the dev mode for one service

**To Reproduce**

1. Clone https://github.com/jmacelroy/go-getting-started/ repository and checkout branch `target-example`
2. From the root, execute `okteto deploy -f functional_tests/okteto.yml`
3. You will see a warning like the one exposed above
4. If you execute `okteto up -f functional_tests/okteto.yml`, you will get the error I pasted above

**Expected behavior**
If the service name specified in the manifest for dev envs is not a valid one, we should apply the same sanitization we do when deploying a service

**Desktop (please complete the following information):**

- Version: `2.4.1`

**Additional context**
N/A

**Comment by AdrianPedriza** [comment]
I guess that if we sanitize the service name when `okteto up` then a warning message should be displayed like when we execute `okteto deploy..`, right? @ifbyol

**Comment by ifbyol** [comment]
yeah, maybe we can keep the consistency showing the warning message to let the user know that `_` is not allowed. @rlamana what do you think?

**Comment by rlamana** [comment]
@ifbyol @AdrianPedriza I agree, applying the magic without informing the user isn't a good idea, and we cannot miss the opportunity to educate them on how it should be and how Okteto works.
