### ISSUE TITLE
Can't connect to dev environment if image doesn't have `sh`

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2889]
**Describe the bug**
If I try to connect to a dev environment where my image doesn't have `sh`, Okteto will fail with an OCI runtime error saying that sh is not found even if I don't specify to run that command

**To Reproduce**

1. Copy the following `Dockerfile`:
``` Dockerfile
FROM scratch
```
2. Run `okteto build -f Dockerfile -t okteto.dev/scratch:latest`
3. Create the following `okteto.yml`:
``` yaml
name: sh-error
image: okteto.dev/scratch:latest
sync:
- .:/usr/src/app
autocreate: true
```
4. Run `okteto up`
5. See error:
<img width="881" alt="Captura de pantalla 2022-07-04 a las 14 17 17" src="https://user-images.githubusercontent.com/25170843/177153093-0013798e-bff8-4b81-9794-63acbbe7517e.png">

**Expected behavior**
All the init containers should finish without problem and start the main container

**Desktop (please complete the following information):**

- OS: macOS
- Version `2.4.1`

**Additional context**
This is due to how we initialise the dev environment: https://github.com/okteto/okteto/blob/master/pkg/k8s/apps/translate.go#L501. If the image doesn't have a sh terminal it will fail with that error, but we could create an image from that image to inject the sh terminal

**Comment by pchico83** [comment]
@jLopezbarb we can capture the error and show something more human-friendly, but our default command is `sh`. If you want to use an image without `sh`, you should configure your own `command` in the okteto manifest

**Comment by jLopezbarb** [comment]
> @jLopezbarb we can capture the error and show something more human-friendly, but our default command is `sh`. If you want to use an image without `sh`, you should configure your own `command` in the okteto manifest

The container that fails is the init-container named `okteto-init-volume`. 
[Here we add the sh to the command that makes it fail](https://github.com/okteto/okteto/blob/master/pkg/k8s/apps/translate.go#L540). So even if he changes the command on the `okteto.yml` it'll result in a failure

**Comment by pchico83** [comment]
@jLopezbarb oh right. we can inject a portable binary there, although I don't think this is a priority at the moment

**Comment by krzwiatrzyk** [comment]
Up. This is an issue. I can't use the same image for dev and production as for dev I must have `sh` available in container.

**Comment by pchico83** [comment]
@krzwiatrzyk which programming languages are you using? having different images for dev and prod is fine, you usually need a debugger, a hot-reloader, a test framework in your dev image, but not in your prod image

**Comment by krzwiatrzyk** [comment]
@pchico83 I use Go to develop my app. I found other solution, I use multi-stage build and my base image called builder is based on golang:1.18 image, which has sh built in. I use target keyword in okteto.yaml to specify which image should bebuild and uploaded.

It works fine:)
