### ISSUE TITLE
Underscore not sanitized when okteto up with -f and autocreate

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2903]
**Describe the bug**
When having a service and folder with underscore, these underscores are sanitized but when running okteto up is failing

````
❯ okbeta up -f functional_tests/okteto.yml
 i  Using teresa @ okteto.teresa.dev.okteto.net as context
 i  Development environment 'go-getting-started' already deployed.
 i  To redeploy your development environment run 'okteto deploy' or 'okteto up [devName] --deploy'
 x  Couldn't activate your development container
    error creating kubernetes volume claim: PersistentVolumeClaim "functional_test-okteto" is invalid: metadata.name: Invalid value: "functional_test-okteto": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    Find additional logs at: /Users/teresaromero/.okteto/teresa/functional_test/okteto.log
````

**To Reproduce**

1. Clone https://github.com/jmacelroy/go-getting-started/tree/target-example
2. add autocreate property true to the okteto manifest at functional_test
3. run okteto up -f functional_test/okteto.yaml

**Expected behavior**
app should be sanitized to `functional-test` everywhere 

**Desktop (please complete the following information):**

- OS: . macOS]
- Version 2.4.1

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by ifbyol** [comment]
Duplicated of https://github.com/okteto/okteto/issues/2888
