### ISSUE TITLE
Support string syntax for `cache_from`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2908]
**Is your feature request related to a problem? Please describe.**
We do support this syntax for the `build` section:

```
cache_from:
   - okteto.global/gonfalon:okteto
```

but should also support a single string syntax like this:
``` 
cache_from: okteto.global/gonfalon:okteto
```

which is more user friendly and covers 95% of the use cases

**Comment by volmedo** [comment]
hi Okteto CLI maintainers! I'm contributing to open source projects in the context of Hacktoberfest 2022. I would like to give this one a try, if that's ok.

**Comment by pchico83** [comment]
@volmedo I assigned the issue to you, thanks for contributing to our hacktoberfest issues!
