### ISSUE TITLE
failed to solve: content digest... Error

### ISSUE THREAD

**Issue by Diamantino-Op** [okteto/okteto#2914]
I get this error when trying to build my image: https://github.com/Diamantino-Op/OWS
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/59661806/178112988-57de2283-e4dc-45dc-8869-3ab10e15467d.png">
but i don't get it if i build this in Docker Desktop.
This error happens only in these 4 steps: setup, elasticsearch, logstash and kibana, and all of them have the same file not found.

**Comment by jmacelroy** [comment]
@Diamantino-Op What command are you running? Either you've fixed the issue or I'm having a different experience. I ran `okteto build` and all images were built correctly.

When trying to deploy I did hit another issue around what I think is around two services mounting the same volume. We can work on deploy though after we get past the build.

**Comment by Diamantino-Op** [comment]
I did okteto up

**Comment by Diamantino-Op** [comment]
i just tried okteto build, and it fails for me

**Comment by Diamantino-Op** [comment]
The build worked now, and i didn't change anything...

**Comment by jmacelroy** [comment]
> The build worked now, and i didn't change anything...
> 
> But now i get an error and a warning: <img alt="image" width="811" src="https://user-images.githubusercontent.com/59661806/178541658-5a6467d0-f200-44eb-b269-7e7fddeb9dd1.png"> <img alt="image" width="727" src="https://user-images.githubusercontent.com/59661806/178541703-3cbbccce-4886-4137-bf84-942bafdbd661.png">

It looks like you ave exceeded the number of allow ingress for your account. Please reach out to support@okteto.com or ask your question on community.okteto.com for product support.
