### ISSUE TITLE
Validate if build section has image on vanilla clusters

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2920]
**Describe the bug**
On vanilla clusters we can't infer the name of the images built. If the manifest validation detects that the user is running an okteto command inside a vanilla cluster with a build without image name we should guide the user to update their manifest. 

**To Reproduce**

1. Copy the following `okteto manifest`
```yaml
build:
  autocreate:
    context: .
dev:
  autocreate:
    sync:
      - .:/src
    autocreate: true
```
2. Run okteto up on a vanilla cluster
3. See that the error is not descriptive

**Expected behavior**
I want a message guiding the users to update their manifest to include a image field on the build section
 
**Desktop (please complete the following information):**

- Version 2.4.2

**Comment by aniruddha2000** [comment]
I would like to work on this

**Comment by aniruddha2000** [comment]
The vanilla cluster can be a minikube cluster? @jLopezbarb

**Comment by jLopezbarb** [comment]
Hi @aniruddha2000, thank you for taking interest in this issue.

> The vanilla cluster can be a minikube cluster? @jLopezbarb

Answering your question, yes as long as the cluster does not have the okteto chart installed, it is a vanilla cluster.

I have assigned you the issue. If you have any questions during the implementation, do not hesitate to contact us and we will guide you.

**Comment by aniruddha2000** [comment]
I am getting an error of something like -
```
Error getting the image name for the service 'autocreate'. Please specify the full name of the image when using a cluster that doesn't have Okteto installed
```
Am I going in the right direction?

**Comment by abs007** [comment]
@jLopezbarb  From what I can understand, you'd like to have a message guiding the users to have an extra `image` field like in:
```yml
build:
  autocreate:
    context: .
    image: 
```

Also, in the docs [here](https://www.okteto.com/docs/reference/manifest/#build-object-optional), it states that it's optional to mention it in case okteto is installed. Does it mean when the okteto cli is installed? And, in this case, is the Okteto registry used to then get the image instead?

**Comment by jLopezbarb** [comment]
Yes, that is checked in the building step. We want to move that error to the [manifest validation](https://github.com/okteto/okteto/blob/ab51df5924159bb7ab4fa70b815ba0815cefae23/pkg/model/manifest.go#L665) instead of the building validation to have all the validations in one
