### ISSUE TITLE
check if okteto manifest works with multi-line ENV vars when expanding

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#2925]
**Describe the bug**
This issue is to check and fix if the okteto manifest does parse correctly the ENVs that are multine. We had to implement special parser for the stack. As this goes in different flows, we need to check

**To Reproduce**

1. Declare multi-line ENV at your environment
2. add this reference into the okteto manifest as part of args or environment keys.

**Expected behavior**
the variables are parsed correctly

**Comment by AdrianPedriza** [comment]
making use in the okteto manifest of a previously declared multiline variable seems to be resolved as expected but in the commands executed in the `deploy` section, `\n` are ignored. This behavior is the responsibility of bash. Is this expected?

![Captura de pantalla 2022-08-02 a las 11 43 37](https://user-images.githubusercontent.com/22500940/182344856-516b088a-996e-4d43-a599-a60865950156.png)

**Comment by teresaromero** [comment]
When multiline issue, the yml was broken when we where expanding the envs in the stack manifest. This issue is to check the envs are expanded and the yaml of the okteto manifest is not broken after it, so you have to add some ENVS at the build section under ARGS and check if this args are being parsed correctly

**Comment by AdrianPedriza** [comment]
@teresaromero seems that works as expected. I will close the issue
