### ISSUE TITLE
Running context git action WITH token inside a container shows error asking for --token flag

### ISSUE THREAD

**Issue by mnevadom** [okteto/okteto#2932]
Im running a context git action inside a container. 

With --token and use URL. 
Which is giving me this error:
 x  This command is not supported without the ‘--token’ flag from inside a container

When running this:
running: okteto context use --token=token https://okteto.t28feb1.dev.okteto.net/

It seems like is forcing me to export the OKTETO_TOKEN env. When I do that, it works perfectly.

When I run the same in my local I dont get the error.

**Comment by jLopezbarb** [comment]
@mnevadom Could you check if https://github.com/okteto/okteto/pull/3071 fixed this issue? Both issues were pretty similar and I think we can close this one as part of the PR

**Comment by jLopezbarb** [comment]
Closing this issue since #3071 is fixing the issue. @mnevadom feel free to reopen the issue again if the new behavior is not the one you expected
