### ISSUE TITLE
Destroy all resources on namespace

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#2933]
**Is your feature request related to a problem? Please describe.**
You can destroy all resources from the UI but there is no way of doing it through the CLI.

**Describe the solution you'd like**
I'd like to be able to execute `okteto destroy --all` to destroy all the resources on my namespace without having to change my kubeconfig context and then running `kubectl delete all --all`. `okteto destroy --all` should call `okteto destroy [-v]` for each git repo with a `destroy` section.

**Additional context**
We should use `okteto destroy --all [-v]` when calling "Destroy all" from the Okteto UI

**Comment by pchico83** [comment]
@rlamana how would you call it to this command? it's the equivalent to "Destroy all" in the Okteto UI. Should it `okteto namespace destro-all`?

**Comment by rlamana** [comment]
> @rlamana how would you call it to this command? it's the equivalent to "Destroy all" in the Okteto UI. Should it `okteto namespace destro-all`?

Given our `noun + verb` approach, that make sense, unless you have a better naming for `destroy-all`, I'm not a fun of subcommands with `-`, but sometimes you cannot avoid them...

`okteto namespace destroy-all` works fine.

**Comment by pchico83** [comment]
> > @rlamana how would you call it to this command? it's the equivalent to "Destroy all" in the Okteto UI. Should it `okteto namespace destro-all`?
> 
> Given our `noun + verb` approach, that make sense, unless you have a better naming for `destroy-all`, I'm not a fan of subcommands with `-`, but sometimes you cannot avoid them... And it is consistent with the UI naming.
> 
> `okteto namespace destroy-all` works fine.

@rlamana another option is `okteto destroy --all [-v]`. I would go with this one. And that command would be also used when running `Destroy All` from the Okteto UI

**Comment by rlamana** [comment]
@pchico83 🤔 I like this one even better, that way we just have a single `destroy` subcommand 🚀 🚀 🚀

**Comment by pchico83** [comment]
This is now supported
