### ISSUE TITLE
No output for `okteto build XXX` if `XXX` doesn't exist in the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2934]
**Describe the bug**
When building something not defined in the okteto manifest, `okteto build` doesn't return an error.

**To Reproduce**

1. Clone https://github.com/okteto/microservices-demo
2. Run `okteto build bad-image`
3. Nothing happens

**Expected behavior**
A clear error is shown `'bad-image isn't defined in the build section of your okteto manifest

**Comment by jLopezbarb** [comment]
Fixed in 2.7 release
<img width="502" alt="Captura de Pantalla 2022-09-16 a las 15 20 07" src="https://user-images.githubusercontent.com/25170843/190648380-52c8f659-ab71-485e-8725-0776efbe61cc.png">
