### ISSUE TITLE
wrong message when dev environment is deployed

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#2945]
**Describe the bug**
When I run  okteto up frontend using microservices-demo-compose, a message is displayed saying 'Development environment 'movies-with-compose' already deployed.' Instead of referring development environment to frontend or "app 'movies-with-compose' already deployed."
**To Reproduce**

1. Clone https://github.com/okteto/movies-with-compose
2. `okteto deploy`
3. `okteto up frontend`

**Expected behavior**
perhaps we could talk about development environment at component level ("Development environment 'frontend' already deployed." ) or change the reference from dev environment to app ("App 'movies-with-compose' already deployed." )

- OS: macOS
- Version 2.4.2

**Additional context**
<img width="719" alt="Captura de pantalla 2022-07-20 a las 11 32 25" src="https://user-images.githubusercontent.com/22500940/179952705-ad67837d-efd3-43b6-8bed-2f5904037d0a.png">

**Comment by pchico83** [comment]
@AdrianPedriza this is expected. the development environment matches the repo, the development container would be `frontend`
