### ISSUE TITLE
ability to add or delete contexts for vanilla kubernetes clusters using `okteto ctx` subcommands

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/okteto#2957]
**Is your feature request related to a problem? Please describe.**
Currently `okteto ctx use` and `okteto ctx delete` don't work for vanilla k8s clusters.

**Describe the solution you'd like**
To be able to add or delete vanilla clusters using the same `okteto ctx` commands which work for clusters with Okteto installed. Or at least we should have the CLI tell us that vanilla contexts are managed through the `kubeconfig`.

**Describe alternatives you've considered**

**Additional context**

**Comment by vimalpatel19** [comment]
Hello Okteto maintainers! I'm contributing to open source projects for Hacktoberfest and would like to give this a try.

**Comment by pchico83** [comment]
@vimalpatel19 welcome to the okteto community!
That would be awesome. Do you need more context to work on this issue?

**Comment by vimalpatel19** [comment]
@pchico83 yes, any relevant context that you can provide would be great! Additionally, I had the following questions:

- What is considered a vanilla cluster vs. a non-vanilla cluster?
- What would you suggest as the preferred route/solution for this: simply display output to the user that a vanilla context should be managed via `kubeconfig` or allow the `okteto ctx` commands to work for a vanilla cluster?

**Comment by pchico83** [comment]
@vimalpatel19 Okteto has a CLI component (this repo) and a cluster-side component (the whole okteto platform). We usually refer to vanilla clusters as clusters without the okteto cluster component. For example, minikube.
Since removing a kubernetes context is a quite intrusive operation, I would just show a message saying that the context is not managed by okteto and a hint to run `kubectl config delete-context xxx`

**Comment by vimalpatel19** [comment]
@pchico83 I made minor changes to begin with by making the current error messaging to be more descriptive (see the open pull request). Please let me know if that is not sufficient.
