### ISSUE TITLE
Show a warning if a okteto secret is ignored because it's already defined in the local environment

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2963]
**Is your feature request related to a problem? Please describe.**
I am debugging my app and the problem was that I have an okteto secret redefined in local environment.
It was very hard to understand what was going on.

**Describe the solution you'd like**
Prioritizing local env versus okteto secrets is very convenient in many cases, but we should show a clear warning if an okteto secret is ignored because of this.

**Comment by odedlaz** [comment]
@pchico83 can you elaborate? I’d like to fix this issue.

**Comment by jLopezbarb** [comment]
Hi again @odedlaz 😉,
What he means is that we should show a warning when introducing the okteto secrets as environment variables. That is done on: https://github.com/okteto/okteto/blob/master/cmd/context/use.go#L146

I think the easiest way to test is by following these steps:
1. Go to your Okteto cluster and set a new secret, for example: `KEY=remote` ([Secrets documentation](https://www.okteto.com/docs/cloud/secrets))
2. Open a new terminal and export an env var with the same key: `export KEY=local`
3. Copy the following okteto manifest
```yaml
deploy:
  - echo $KEY
```
4. See that the output is the one from local
<img width="543" alt="Captura de pantalla 2022-08-19 a las 16 59 48" src="https://user-images.githubusercontent.com/25170843/185652780-7073f287-1409-4d35-b896-b5c3b1c3923e.png">

**Comment by odedlaz** [comment]
@jmacelroy , great! I'll make time this week to address this.

**Comment by odedlaz** [comment]
@jmacelroy , done.

**Comment by jLopezbarb** [comment]
Closing because it's already merged. Thanks for contributing @odedlaz
