### ISSUE TITLE
Possible bug caught by golangci-lint

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#2967]
In the file [pkg/model/volumes.go](https://github.com/okteto/okteto/pull/2952/files#diff-f07c4ae0ba01563473de575ae41c2a4bd47b09d98b129f456cd0a2d870cdd167), in the funciton `getSourceSubPath` there's a branch that asigns the `path` variable and that's not used. 

The function has unit tests, which could be 2 things:
- tests are ok and test the desired behavior => branch should be removed
- tests miss the behavior => branch should return the path 

Additional context: https://github.com/okteto/okteto/pull/2952/files#r930695403

**Comment by abs007** [comment]
I'd like this issue to be assigned to me, thanks.

**Comment by pchico83** [comment]
@abs007 there we go!

**Comment by abs007** [comment]
Can I get an example of what a basepath and targetpath might be?

**Comment by abs007** [comment]
I feel like we can go ahead and remove the additional `path` variable since everything works without it being used? It'd be great to get some additional feedback too.

**Comment by AgustinRamiroDiaz** [comment]
@abs007 I agree. I'm in favor of deleting it. Here are other things you could do:

Context:
- We found the dead code with golangci-lint. That gave us the impression that maybe a bug was hidden there.

Some things that could help us to gain more trust in that code:
- add more unit tests
- simplify it's logic
- check in which pr that line was added. Maybe there we find more context.

**Comment by abs007** [comment]
Wrt simplifying logic, can we change the code from line [141](https://github.com/okteto/okteto/blob/master/pkg/model/volumes.go#L141) to: 

```go
	rel, err := filepath.Rel(dev.parentSyncFolder, filepath.ToSlash(sourceSubPath))
	if err != nil {
		oktetoLog.Debugf("error on getSourceSubPath of '%s': %s", path, err.Error())
	}
	if filepath.IsAbs(sourceSubPath) {
		if strings.HasPrefix(rel, "..") {
			if filepath.IsAbs(path) {
				oktetoLog.Info("could not retrieve subpath")
				//path = filepath.Base(path)
			} else {
				p, err := filepath.Abs(path)
				if err != nil {
					oktetoLog.Debugf("error on getSourceSubPath of '%s': %s", path, err.Error())
				}
				return filepath.ToSlash(p)
			}
		}
	}
```
tests seem to be working fine

**Comment by abs007** [comment]
@AgustinRamiroDiaz  I'm a bit confused with this test case
https://github.com/okteto/okteto/blob/master/pkg/model/volumes_test.go#L568

Aren't we supposed to be having `src/../test/func` as result for this?

**Comment by AgustinRamiroDiaz** [comment]
@abs007 That seems to be the way that `filepath.Join` works
```go
filepath.Join("src", "../test/func") // "../test/func"
filepath.Join("src", "func") // "src/func"
```
