### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2973]
**Describe the bug**
Currently, integration tests are flaky and they fail from time to time. Usually, retrying them once make them pass. This is frustrating because when you merge something and see the result you don't know if it was due to your changes or temporal issue.

The last failed executions, failure happened in different tests. Last 3 were:

`TestUpGlobalForwarding`
`TestUpDeploymentV1`
`TestUpStatefulsetV1`

All of them failed with a message similar to this one (just change the port number): `Couldn't connect to your development container: local port 44491 is already in-use in your local machine: port is already allocated`

**To Reproduce**
N/A

**Expected behavior**
N/A

**Comment by jLopezbarb** [comment]
This error happens when two or more tests try to allocate the same syncthing port (a race condition). Both tests have the same random seed and try to assign the same port and since the port is not in use by another program at that time it fails later when the CLI tries to allocate them
