### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#2975]
in order to upgrade dependencies, we need to upgrade Golang version

**Comment by ifbyol** [comment]
@AdrianPedriza  Can you be more specific? Does this apply to all the dependencies or a specific one? If we try to upgrade the dependencies without changing go version, what errors are we getting?

**Comment by AdrianPedriza** [comment]
> @AdrianPedriza Can you be more specific? Does this apply to all the dependencies or a specific one? If we try to upgrade the dependencies without changing go version, what errors are we getting?

@ifbyol I am reviewing the open issues and I see that Agustin has already taken care of it, so I am deleting the current issue.
