### ISSUE TITLE
readOnlyRootFilesystem policy not disabled without defined capabilities.

### ISSUE THREAD

**Issue by timsun4** [okteto/okteto#2999]
**Describe the bug**
The ReadOnlyRootFilesystem policy is not disabled on the Okteto container if no `securityContext.capabilities` are defined within the Okteto manifest. 

**To Reproduce**

1. Deploy an application to Kubernetes with `securityContext.readOnlyRootFilesystem: true`
2. Define an Okteto manifest without `securityContext.capabilities`
3. Attempt to `okteto up` on the application and receive a message `Failed to connect to your development container`

**Expected behavior**
I should be able to `okteto up` on my application with ReadOnlyRootFilesystem enabled without needing to modify capabilities on my Okteto container. 

**Desktop (please complete the following information):**

- OS: Ubuntu

**Additional context**
Function appears to terminate before setting `readOnlyRootFilesystem = nil` if no capabilities are defined.
https://github.com/okteto/okteto/blob/master/pkg/k8s/apps/translate.go#L463

The policy setter was originally added as part of https://github.com/okteto/okteto/issues/565

**Comment by pchico83** [comment]
Hi @timsun4 , thanks for opening this issue. Would yo be open to working on a PR? Yoo seem familiar with the involved code

**Comment by timsun4** [comment]
Hey @pchico83 , I would say I only familiarized myself with the code enough to find out where I thought the issue was coming from. I am looking at making a PR but do not have a timeline at the moment. Anyone else is welcome to step in if they would like.
