### ISSUE TITLE
Return a clearer error when  the dev container runs out of space 

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3000]
**Describe the bug**
![image](https://user-images.githubusercontent.com/475313/184248477-d4c9a5b0-53ce-4cc5-8d97-e535d824b850.png)

instead of "no space left on device", I think we should return a user-friendly error, with instructions on how to solve this problem. 

Also, it might be useful to show a warning when the dev container is at 80% of total capacity.

**Comment by alicenstar** [comment]
Thank you for opening this issue, I think it'd be helpful to be more specific as to where we are running out of space, in the error message, or suggesting to increase `persistentVolume`. A warning when close to capacity sounds very useful as well. Thank you!

**Comment by pchico83** [comment]
@jLopezbarb could you try this:
- Wait for the first sync with available space
- Add more files locally so you get out of space

**Comment by jLopezbarb** [comment]
@pchico83, that's another issue we have identified, [when the volume it's full syncthing stops synchronising files](https://github.com/okteto/okteto/issues/2285). The error reported above seems to be happening in the first synchronisation (notice that we don't get the context/namespace/name information)
