### ISSUE TITLE
Okteto manifest spec for linting in IDE

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3005]
**Is your feature request related to a problem? Please describe.**
When starting with okteto it can be difficult to configure properly the `okteto.yml` manifest. Also, the documentation associated is not a specification, making the process harder since it's a manual crafting between examples and some docs.

**Describe the solution you'd like**
1. Have a spec of the manifest
2. Use that spec to create an extension for VSCode

**Additional context**
This is an example of the help given by the kubernetes extension in vscode
![image](https://user-images.githubusercontent.com/49416765/184868552-3eecfaf8-d70b-41eb-9966-d21a2534975e.png)

**Comment by jmacelroy** [comment]
@AgustinRamiroDiaz the image link is broken. Can you update it?

**Comment by AgustinRamiroDiaz** [comment]
@jmacelroy done!

**Comment by jLopezbarb** [comment]
I think we can do it as part of the vscode extension that we already have

**Comment by AgustinRamiroDiaz** [comment]
@jLopezbarb I agree that the vscode extension is very related to this issue, but I think the biggest work around this is the spec for the manifest. I think that we should have the spec in this repo for now.

We could split it into 2 issues:
- Define manifest spec (okteto repo)
- Add intelisense for the vscode extension (remote-kubernetes extension, depenedant from the above)
