### ISSUE TITLE
Add Secrets to Okteto Using CLI

### ISSUE THREAD

**Issue by jmacelroy** [okteto/okteto#3006]
Would be nice to have the ability to add Secrets via CLI, instead of manually via the UI ([Okteto Secrets | Okteto Documentation](https://www.okteto.com/docs/cloud/secrets/#manage-okteto-secrets-from-the-okteto-cloud-ui)).

My use case is that every developer in my group needs to add it’s own private secrets under the same names, so I would like to create a small script that does it for them using the CLI.

**Comment by jLopezbarb** [comment]
What should the command looks like?
- `okteto secrets create`: Creates the secret, but should we allow more than one secret being set at the same time (I.E:`okteto secrets create key1=value key2=value2`)
- `okteto secrets delete`:  Deletes the secret containing that key. This command should be idempontent.

Should we create a `okteto secrets list` and `okteto secrets show` showing only the last 3 chars?

**Comment by hadaromash** [comment]
A `show` command may be useful, to verify if a key exists before creating it.

**Comment by faliqadlan** [comment]
can i ask, how to access okteto secrets which define in settings ?

**Comment by pchico83** [comment]
Closing since this should go through the product backlog now. Also, adding commands that don't work on clusters without the okteto server side installed is porblematic
