### ISSUE TITLE
connect with custome k8s cluster

### ISSUE THREAD

**Issue by rainbowechoes** [okteto/okteto#3025]
I see okteto cli can connect to okteto cloud to develop.

But if I have a k8s cluster in my own server, how can I connect to it to develop by using okteto? 

Did it support?

**Comment by jLopezbarb** [comment]
Yes @rainbowechoes, you just need to point okteto to your k8s cluster by running `okteto context`. That command will extract the clusters that you have on your kubeconfig path and allows you to select the one you want to operate in.

Happy coding!!

**Comment by rainbowechoes** [comment]
thanks for your answer first!

I know this command, but I'm confuse about the url. I don't know what to put in this url. I've just started working with k8s soon

**Comment by jLopezbarb** [comment]
The URL is needed if you try to connect to an Okteto cluster. If you are trying to connect to a vanilla cluster (a cluster without okteto helm chart installed) you'll need to download your credentials first and store them on your `KUBECONFIG` path. That config is the one you create connections to the cluster and make `kubectl` and `helm` available from your terminal. Once you have your `KUBECONFIG` configured properly okteto context will allow you to select that context

If you have an Okteto cluster, those steps are simplified by following [this tutorial](https://www.okteto.com/docs/cloud/credentials/):

**Comment by rainbowechoes** [comment]
> 

I think I got it, I'll try it tomorrow

**Comment by jLopezbarb** [comment]
Glad to hear that!!
I'll keep this issue open in case you need something else, don't hesitate to ask us again and happy coding!!

**Comment by RinkiyaKeDad** [comment]
@rainbowechoes you can also check out this article to learn how to use Okteto CLI with custom k8s clusters: https://www.okteto.com/blog/developing-microservices-by-hot-reloading-on-kubernetes-clusters/ 😄

**Comment by rainbowechoes** [comment]
> @rainbowechoes you can also check out this article to learn how to use Okteto CLI with custom k8s clusters: https://www.okteto.com/blog/developing-microservices-by-hot-reloading-on-kubernetes-clusters/ 😄

it looks like that's what I want! I try it now!

**Comment by rainbowechoes** [comment]
> added link to blog for using okteto cli with vanilla clusters #3027

Hi, @jLopezbarb, @RinkiyaKeDad  I have get `KUBECONFIG` from master, and I can use this config file to login dashboard.
 
but when I use `okteto context list` command  in my mac, I get this error: `FATA[0000] okteto context store is corrupted. Delete the folder '/Users/ruijie/.okteto/context' and try again`.

And I try it again after delete the folder, still have the error.

Did I do some wrong?

**Comment by jLopezbarb** [comment]
> > added link to blog for using okteto cli with vanilla clusters #3027
> 
> Hi, @jLopezbarb, @RinkiyaKeDad I have get `KUBECONFIG` from master, and I can use this config file to login dashboard.
> 
> but when I use `okteto context list` command in my mac after use `export KUBECONFIG=xxx`, I get this error: `FATA[0000] okteto context store is corrupted. Delete the folder '/Users/ruijie/.okteto/context' and try again`.
> 
> And I try it again after delete the folder, still have the error.
> 
> Did I do some wrong?

Have you configured `okteto context` before running `okteto context list`? 
1. Delete the folder `/Users/ruijie/.okteto/context`
2. Run `okteto context use` and select your new cluster
3. Now you can run `okteto context list` and all other okteto commands as usual

**Comment by rainbowechoes** [comment]
> 

Great! 

I don't use `okteto context use` command after delete the folder.

I do as you said, it worked! 

thanks for your help again! 

@jLopezbarb @RinkiyaKeDad

**Comment by rainbowechoes** [comment]
Hi, @jLopezbarb .

I clone https://github.com/okteto/movies-with-vanilla-k8s.git repository, and plan to deploy to my k8s cluster.

but when I use `okteto up` command to deploy front application, I find there is a pvc (frontend-okteto) which status always pending.

I think it maybe no pv in cluster. But I create a pv manually and do again, the pvs still pending. And I can't edit the pvc config yaml.

how should I do?

**Comment by jLopezbarb** [comment]
You should run `kubectl describe pvc frontend-okteto -n YOUR_NAMESPACE` and check the events of the pvc to get the reason on why it's failing. The pod is pending because the pvc can't be attached to it, so you'll need to fix why you can't deploy any pvc before running okteto up.

**Comment by rainbowechoes** [comment]
> 

like you said, I need to fix the pvc error, so I try to edit it's yaml in dashboard, but k8s tell me I can't change it. and I find configuration about the pvc in git repository, result is nothing. so I don't know how to fix it.

I will try to go to community to find help.

thanks for your answer finally!

**Comment by jLopezbarb** [comment]
@rainbowechoes Can you post on the community forum the output of the command I posted above? I'm closing this issue in favour of the community forum thread.

See you there 😄

**Comment by pchico83** [comment]
@rainbowechoes another option is to disable the persistent volume creation:
https://www.okteto.com/docs/reference/manifest/#persistentvolume-object-optional

**Comment by rainbowechoes** [comment]
> @rainbowechoes Can you post on the community forum the output of the command I posted above? I'm closing this issue in favour of the community forum thread.
> 
> See you there 😄

hi, @jLopezbarb . I have post the info on the community forum. If you have time, I hope to get your help. the post url is: https://community.okteto.com/t/connect-with-custome-k8s-cluster/217/4
