### ISSUE TITLE
Can't start development pod

### ISSUE THREAD

**Issue by shepherd1530** [okteto/okteto#3041]
**Describe the bug**

Okteto up fails to start my pod. The below is the output of okteto.log

```
Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:364: creating new parent process caused: container_linux.go:2005: running lstat on namespace path "/proc/3942194/ns/ipc" caused: lstat /proc/3942194/ns/ipc: no such file or directory: unknown
```

- OS: macOS m1
- Version 2.5.2

**Comment by shepherd1530** [comment]
This fixed itself probably by the Okteto team.

**Comment by ifbyol** [comment]
@shepherd1530 yes, yesterday we detected a malfunctioning node that was provoking those errors and we removed it from the pool. Thanks for reporting it
