### ISSUE TITLE
Increase the default size of the okteto dev volume

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3045]
**Describe the bug**
Motivated by Okteto Cloud quotas, the default size of the okteto volume is 2Gi, which is usually not enough for realistic applications. This is generating many `no space errors` when people are experimenting with Okteto.

**Expected behavior**
Increase the default size to 5Gi. Keep 2Gi if the context is Staging or Okteto Cloud. As part of this work, if `okteto up` fails because the new volume size is larger than the previous one (not all storage classes support size expansion) we shouldn't recreate the volume automatically

**Comment by AgustinRamiroDiaz** [comment]
> if okteto up fails because the new volume size is larger than the previous one (not all storage classes support size expansion) we shouldn't recreate the volume automatically

Should this be the new behavior for all cases? Or just for the migration of 2Gi to 5Gi?

**Comment by pchico83** [comment]
> > if okteto up fails because the new volume size is larger than the previous one (not all storage classes support size expansion) we shouldn't recreate the volume automatically
> 
> Should this be the new behavior for all cases? Or just for the migration of 2Gi to 5Gi?

Let's do it for every case

**Comment by AgustinRamiroDiaz** [comment]
> As part of this work, if okteto up fails because the new volume size is larger than the previous one (not all storage classes support size expansion) we shouldn't recreate the volume automatically

@pchico83 seems like that's the current behavior

```
$ k get sc standard -oyaml
allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-02-14T18:55:54Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: standard
  resourceVersion: "141774574"
  uid: 46f4e7f3-d780-49be-a15e-b9178602b72f
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
$ lokteto up
 i  Using ilnovo @ okteto.agustin.dev.okteto.net as context
 i  Development environment 'test2' already deployed.
 i  To redeploy your development environment run 'okteto deploy' or 'okteto up [devName] --deploy'
 i  Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'
 x  Couldn't activate your development container
    error updating kubernetes volume claim: persistentvolumeclaims "web-okteto" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
    Find additional logs at: /home/az/.okteto/ilnovo/web/okteto.log
```

**Comment by pchico83** [comment]
> > As part of this work, if okteto up fails because the new volume size is larger than the previous one (not all storage classes support size expansion) we shouldn't recreate the volume automatically
> 
> @pchico83 seems like that's the current behavior
> 
> ```
> $ k get sc standard -oyaml
> allowVolumeExpansion: false
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   annotations:
>     storageclass.kubernetes.io/is-default-class: "true"
>   creationTimestamp: "2022-02-14T18:55:54Z"
>   labels:
>     addonmanager.kubernetes.io/mode: EnsureExists
>   name: standard
>   resourceVersion: "141774574"
>   uid: 46f4e7f3-d780-49be-a15e-b9178602b72f
> parameters:
>   type: pd-standard
> provisioner: kubernetes.io/gce-pd
> reclaimPolicy: Delete
> volumeBindingMode: Immediate
> 
> $ lokteto up
>  i  Using ilnovo @ okteto.agustin.dev.okteto.net as context
>  i  Development environment 'test2' already deployed.
>  i  To redeploy your development environment run 'okteto deploy' or 'okteto up [devName] --deploy'
>  i  Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'
>  x  Couldn't activate your development container
>     error updating kubernetes volume claim: persistentvolumeclaims "web-okteto" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
>     Find additional logs at: /home/az/.okteto/ilnovo/web/okteto.log
> ```

yes, let's recreate it automatically in all cases as part of this work

**Comment by AgustinRamiroDiaz** [comment]
I'm sorry @pchico83, I got confussed.

You said:
- "... we shouldn't recreate the volume automatically ..."
- "... let's recreate it automatically ..."

What should we do?

---

For context, the current behavior I found while using okteto is:
scenario a)
- `dev volume` with 2Gi size already created
- `okteto up` with 5Gi default
- `allowVolumeExpansion: true` set in the `standard` storage class
Then it automatically resizes

scenario b)
- `dev volume` with 2Gi size already created
- `okteto up` with 5Gi default
- `allowVolumeExpansion: false` set in the `standard` storage class
Then we get an error

**Comment by pchico83** [comment]
@AgustinRamiroDiaz for volumes created by `okteto up` let's go with recreation in any case if the update fails. Recreation here is fine because the volume is to speed up the first sync.
For volumes created by statefulsets, let's create a different issue. Recreation is not acceptable for statefulsets because they have persistent data like databases
