### ISSUE TITLE
Passing -v or --volume results in a potentially surprising data loss

### ISSUE THREAD

**Issue by bwestover** [okteto/okteto#3052]
**Is your feature request related to a problem? Please describe.**

Passing "-v" to many commands means "verbose". In some cases it might mean "version". It's pretty surprising that passing "-v" to `okteto destroy` destroys the persistent volumes. `--volume` is more clear, but even then its not entirely clear that the option _destroys_ the volume.

**Describe the solution you'd like**

Consider dropping the short flag entirely for destructive options. Perhaps `--include-volumes` (and for symmetry it could be `--include-dependencies`) - Coupled with the `destroy` verb this seems pretty clear (e.g. `okteto destroy --include-volumes`). 

Other names might be even more clear, but perhaps redundant (e.g. `okteto destroy --destroy-volumes`).

**Comment by pchico83** [comment]
@bwestover that's for your feedback! This makes a lot of sense. Also, a confirmation message might help. I willl add the label `3.0` to this issues since it would be a breaking change
