### ISSUE TITLE
Okteto build with wrong arguments doesn't print anything

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3061]
**Describe the bug**
When running `okteto build some-inexistent-service`, the cli just finishes without printing anything

**To Reproduce**
Run `okteto build some-inexistent-service` in a folder with an okteto manifest

**Expected behavior**
The CLI should point out that the service is invalid with an error

**Additional context**
I think [here](https://github.com/okteto/okteto/blob/f7aa77dfc6d878d07ff22decf4f2acea54d504d6/cmd/build/v2/build.go#L267) is where the problem arises

**Comment by jLopezbarb** [comment]
@AgustinRamiroDiaz is this still happening? I think we fixed it on `2.7.0`

**Comment by AgustinRamiroDiaz** [comment]
It's fixed!
