### ISSUE TITLE
remove `github.com/ibuildthecloud/finalizers` as dependency

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3091]
**Describe the bug**
We should remove `github.com/ibuildthecloud/finalizers` as a dependency because:
- Code has not been updated in the last 2 years
- Untestable code. We can't test the code using this dependency because it doesn't allow adding fake k8s clients.
- Only using one function. We are only using one function that could be rewritten on our own since it doesn't add a lot of complexity.

**Expected behavior**
Our code should be testable and we should not inject dependencies for a small function

**Additional context**
Function used on the destroy command: https://github.com/okteto/okteto/blob/master/pkg/k8s/namespaces/namespace.go#L78

**Comment by abs007** [comment]
I'd like to take up this issue. Upon removing the dependency, I'm guessing I'll have to implement the [NewTrip](https://github.com/okteto/okteto/blob/master/pkg/k8s/namespaces/namespace.go#L80) and [TravelerFunc](https://github.com/okteto/okteto/blob/master/pkg/k8s/namespaces/namespace.go#L104) funcs locally

**Comment by jLopezbarb** [comment]
@abs007 I have assigned it to you. 

Yes, we'll need to reimplement [NewTrip](https://github.com/okteto/okteto/blob/master/pkg/k8s/namespaces/namespace.go#L80) and [TravelerFunc](https://github.com/okteto/okteto/blob/master/pkg/k8s/namespaces/namespace.go#L104) locally making them testable by injecting the kubernetes client. That way we can also test https://github.com/okteto/okteto/blob/master/pkg/k8s/namespaces/namespace.go#L78
