### ISSUE TITLE
Support build secrets with docker compose manifest

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3094]
Okteto should support all field from docker composes defined by https://github.com/compose-spec/compose-spec

We should check that we handle [secrets in the build section](https://github.com/compose-spec/compose-spec/pull/238/files)
If not, we should implement the feature

**Comment by teresaromero** [comment]
@AgustinRamiroDiaz this is not defined. My comment was a question to clear the scope of the PR. Not sure if this issue is well described.

**Comment by pchico83** [comment]
@AgustinRamiroDiaz since this is a feature requests, it should be handled via the product backlog now. But I don't think this is a priority at the moment since people can use the build section in the okteto manifest
