### ISSUE TITLE
Pipeline logs not working when context is Okteto Cloud

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#3101]
**Describe the bug**
After implementing the logs display when running `okteto pipeline deploy --wait` the logs are not shown when context is `Okteto Cloud`

**To Reproduce**

- run `okteto pipeline deploy --wait` with staging or dev cluster and see the logs are being display at the cli
- run the same cmd but with the okteto cloud context and no logs are display, although the UI show them

**Expected behavior**
Logs should be display when the context is Okteto

Followup issue after merging #2794 to master

**Additional context**

When debugging the response from okteto cloud sse, we only get ping events, so no log is sent from the backend in this case

**Comment by jLopezbarb** [comment]
Let's keep this open a little bit
