### ISSUE TITLE
Nil dereference in up command

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3102]
I stumbled upon the code and I've seen that we would be dereferencing a nil pointer in the up command if we get an error from `okteto.GetK8sClient()`. The problem comes from `up.Dev` being nil at that point.

https://github.com/okteto/okteto/blob/9b88e269b657d95b04e978d963ae5d22ff4887b8/cmd/up/up.go#L221-L224

**Comment by jLopezbarb** [comment]
Hi @adelsz, I assigned this issue to you since the PR that you opened fixes this issue
