### ISSUE TITLE
Handle upsizing for PVCs attached to statefulsets

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3103]
When developing with statefulsets, there could be the necessity to upscale the size of the PVCs attached.

Expected behavior:
When redeploying a statefulset with more size on their PVC:
- okteto should try upsizing the volume
- if it fails, it should guide the user to recreate the PVC, probably with `okteto destroy -v` + `okteto deploy`

_Originally posted by @pchico83 in https://github.com/okteto/okteto/issues/3045#issuecomment-1245857059_

**Comment by pchico83** [comment]
@AgustinRamiroDiaz since this is a feature requests, it should be handled via the product backlog now
