### ISSUE TITLE
Context store may just be non-existent rather than corrupt

### ISSUE THREAD

**Issue by zaheerm** [okteto/okteto#3107]
**Describe the bug**
When running 'okteto ctx ls' without ever having run 'okteto ctx' (for example when following https://www.okteto.com/blog/developing-microservices-by-hot-reloading-on-kubernetes-clusters/ ), the error message: "FATA[0000] okteto context store is corrupted. Delete the folder ..." appears

**To Reproduce**

1. Install okteto cli
1. Run 'okteto ctx ls'
1. See error

**Expected behavior**
The error should suggest running 'okteto ctx' as an alternate to deleting the context folder.

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.6

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by pchico83** [comment]
@zaheerm thanks for reporting this! We will have a look to your PR tomorrow
