### ISSUE TITLE
Add ability to specify storage class for okteto pvcs

### ISSUE THREAD

**Issue by zaheerm** [okteto/okteto#3131]
**Is your feature request related to a problem? Please describe.**
If the k8s cluster has storage classes but none set as default, the pvcs when you run okteto up fail to get ready.

**Describe the solution you'd like**
A command line argument or environment variable or both to specify the storage class to use for the okteto pvcs.

**Comment by jLopezbarb** [comment]
Hi @zaheerm, You can specify the persistent volume class by setting the `storageClass` field in the `persistentVolume` section. More information can be found here: https://www.okteto.com/docs/reference/manifest/#persistentvolume-object-optional

**Comment by jLopezbarb** [comment]
You can also set the default storage class at the cluster level when installing Okteto platform: https://www.okteto.com/docs/self-hosted/administration/configuration/#devstorageclass
