### ISSUE TITLE
Support the configuration of liveness probes when using compose healthchecks

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3135]
**Is your feature request related to a problem? Please describe.**
Okteto supports Docker Compose [healthchecks](https://www.okteto.com/docs/reference/compose/#healthcheck-object-optional) to be assigned to any service in your Docker Compose file. Healthchecks are translated to Kubernetes Readiness Probes.

In some cases, users would prefer to create Kubernetes Liveness Probes. Or both of them, Readiness and Liveness Probes.

**Describe the solution you'd like**
Make it configurable to create Liveness and/or Readiness Probes when using health checks.

Support the following fields in the `healthchecks` section:

- `x-okteto-readiness`: boolean (default `true`)
- `x-okteto-liveness`: boolean (default `false`)

If both are false, we should fail validation of the Docker Compose file.
Otherwise, create Liveness/Readiness Probes based on the values of these fields.

**Additional context**
Update the docs to document these new fields

**Comment by pchico83** [comment]
@jLopezbarb I updated the description to add `okteto` to the field name. We should do this to every `x-name` field we add to make it clearer that this is okteto specific:
```
- `x-okteto-readiness`: boolean (default `true`)
- `x-okteto-liveness`: boolean (default `false`)
```

**Comment by AgustinRamiroDiaz** [comment]
Do we have an intention to stick to the docker-compose spec?

**Comment by pchico83** [comment]
> Do we have an intention to stick to the docker-compose spec?

@AgustinRamiroDiaz yes, we would like to be compose 100% compatible
