### ISSUE TITLE
[Regression] `okteto context` doesn't let me use my cluster

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3136]
**Describe the bug**
When I run `okteto context` and select a cluster that has okteto self hosted installed, it automatically switches the context to the "okteto" one.

You can see here how the cli prints 2 different contexts when running the command
```
$ okteto ctx 
 ✓  Context '<my_cluster_context>' selected
...
 ✓  Context 'okteto.agustin.dev.okteto.net' created
 ✓  Using context agustin @ okteto.agustin.dev.okteto.net
```

**To Reproduce**

1. Have a cluster with okteto self hosted installed
1. Add the okteto context through the okteto cli
1. Add the cluster context with `kubectl`
1. Run `okteto ctx` and select the cluster one
2. See how you are redirected to the self hosted context

**Expected behavior**
`okteto context` should set the context to the context specified

**Desktop (please complete the following information):**

- OS: Ubuntu
- Okteto Version: `2.7.0` and `dev`

**Additional context**
This also happens if the okteto self hosted context is deleted. It seems that there's some logic searching for the okteto self hosted installation

**Comment by pchico83** [comment]
@AgustinRamiroDiaz why did you mark it as a regression? I think this has been the behavior from day one

**Comment by AgustinRamiroDiaz** [comment]
I used to do this before. I don't remember the exact version but I can search for it if needed

**Comment by pchico83** [comment]
@AgustinRamiroDiaz thanks. right, we should investigate if it's a regression then

**Comment by jmacelroy** [comment]
@pchico83 I thought we made it this way on purpose to prevent accidental use of cloud.okteto.com by users on dedicated clusters?

**Comment by pchico83** [comment]
> @pchico83 I thought we made it this way on purpose to prevent accidental use of cloud.okteto.com by users on dedicated clusters?

@jmacelroy I don't think this is related to that. Asking agustin for more detailed repro steps to understand what's going on

**Comment by AgustinRamiroDiaz** [comment]
> @AgustinRamiroDiaz which command do you run here?
> 
> ```
> 3. Add the cluster context with kubectl
> ```

I don't remember, but the important thing is to have it defined as a kubeconfig in some way. It should be displayed when running `kubectl config get-contexts`

**Comment by pchico83** [comment]
@AgustinRamiroDiaz without repro steps, I will close the issue. Please, reopen it if you have repro steps

**Comment by jLopezbarb** [comment]
Hi @AgustinRamiroDiaz, if your kubeconfig context is pointing to an okteto namespace, whenever we try to use that kubernetes context, the CLI checks if the namespace is managed by Okteto and if so, we use the Okteto context. 

If you want to use it as vanilla cluster, the easiest workaround is to point the `context.namespace` to `default` and after that okteto context will let you use the context as if it was a vanilla cluster.

**Comment by AgustinRamiroDiaz** [comment]
Thanks @jLopezbarb ! Is this documented somewhere?
