### ISSUE TITLE
Support for network and volumes network

### ISSUE THREAD

**Issue by TIWA-HARRIS-DEV** [okteto/okteto#3138]
Hello
Tried to deploy a Laravel 8 app on Okteto with a docker-compose file. But I obtained the following warning in console:
![image](https://user-images.githubusercontent.com/57524148/192899382-c2da948a-901d-4682-ab24-6f30ce79d0c2.png)

Without them, i'm unable to make my Laravel app work properly.

Please add support for the fields. 
Thanks

**Comment by jLopezbarb** [comment]
Hi @TIWA-HARRIS-DEV, Can you provide more information about what do you need from them?

All your services will be in the same network so you will be able to connect from one service to another one by using its name.

Volumes is supported, the only thing that is not supported is the driver field, which driver you need to set for `sail-mysql`. It should also work without specifying it, but if you provide the driver that you need maybe we can provide a workaround for you specific use case
