### ISSUE TITLE
Cannot open terminal when using remote SSH in VS Code

### ISSUE THREAD

**Issue by tdenovan** [okteto/okteto#3141]
**Describe the bug**
When using Remote SSH to contact to an okteto development container (either directly or via the Okteto VS Code extension) it is not possible to open a terminal. The terminal immediately closes upon opening.

**To Reproduce**

1. Run `okteto up`
1. Use Remote SSH: Connect to Host in VS Code to connect to the okteto development container
1. Open a terminal in VS Code
1. Note that the terminal closes almost immediately after opening

**Expected behavior**
The terminal should open in an interactive mode

**Desktop:**

- OS: macOS
- Version: VS Code version: 1.71.2 (Universal)

**Additional context**

The issue appears to be caused by the PROMPT_COMMAND environment variable set by Okteto (which seems designed to preserve bash history). It appears that VS Code cannot parse the PROMPT_COMMAND variable properly and so the terminal shell integration does not get initialised correctly (refer https://code.visualstudio.com/docs/terminal/shell-integration).

If you use a dev docker image that contains a `.bashrc` file that unsets PROMPT_COMMAND or sets it in the format proposed in the VS Code documentation (https://code.visualstudio.com/docs/terminal/shell-integration#_when-does-automatic-injection-not-work) the issue is resolved.

Disabling persistence in the okteto manifest also resolves the issue as it prevents the okteto cli from setting the PROMPT_COMMAND env var.

**Comment by mnevadom** [comment]
Hi @tdenovan !

Thanks!

Can you provide the repo you are using? I'm trying to reproduce it with this one
`https://github.com/okteto/go-getting-started`

And it seems to work. Even when I try to get the previous commands


![image](https://user-images.githubusercontent.com/16018223/197830327-fe83b94f-5b8a-440a-b9f5-1419cf6f2183.png)

**Comment by mnevadom** [comment]
Can you check in the settings if you have this enabled? If so, try to disable it: 

![image](https://user-images.githubusercontent.com/16018223/197973234-e5478e1c-90de-4b78-bcf7-3897d0440153.png)

**Comment by teresaromero** [comment]
@tdenovan did you have the chance to check this? thanks

**Comment by dsyer** [comment]
The default setting in VSCode is "enabled" so why does this not work with Okteto? It seems fine for every other remote terminal. The UX here is kind of unpleasant. (Very nice work on Okteto generally though.)
