### ISSUE TITLE
Stream the out of deploying a dependency when `wait` is enabled

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3147]
**Describe the bug**
When deploying a dependency with `wait`, we should stream the output of the deployment dependency to make it easier to follow what's the state of the deployment. It also helps to troubleshot issues when the deployment fails.

Otherwise, we get just an error like this:
```
Pipeline `my-dependency` failed
```

**To Reproduce**
Create a dependency that fails deployment and run `okteto deploy --dependencies`

**Comment by abs007** [comment]
I'd like to work on this

**Comment by pchico83** [comment]
Awesome @abs007 !
@teresaromero could you point to the code where we stream the output of `okteto pipeline deploy`?

**Comment by teresaromero** [comment]
@abs007 

https://github.com/okteto/okteto/blob/master/cmd/pipeline/deploy.go#L251 

A dependency deployment is triggered by a pipeline deploy, when the wait flag for pipeline deployment is true, we have a function streaming logs of this process to the CLI.

@pchico83 as the stream logs is inside pipeline, when deploying the dependency logs should be already be streaming. What is exactly the bug? Are the logs no streaming when there is an error? There is a know issue with Cloud where the streaming is not reaching the clients, could this be the case?

**Comment by pchico83** [comment]
@teresaromero the logs of the dependency deployment aren't streaming.
We just show `Waiting for dependency xxx to be deployed...`

**Comment by abs007** [comment]
Since I personally don't have access to a cloud provider/ have a personal domain, can I instead make a pr with the changes and then be notified if my changes work on the pr itself?

**Comment by abs007** [comment]
And, if I'm right, I'm supposed to write similar functionality for `okteto deploy` to there is for `okteto pipeline deploy` ?

**Comment by pchico83** [comment]
@abs007 when `okteto deploy` deploys a dependency with `wait`, we should stream the output of the dependency deployment here:
https://github.com/okteto/okteto/blob/cdccc9b6ee8e720d3195820f93122a8cd1f57b6b/cmd/pipeline/deploy.go#L173
Same for `okteto preview deploy` when it deploys a dependency and the dependency has `wait`

**Comment by pchico83** [comment]
@teresaromero you are right, I got confused with Cloud. We should revisit how we expose the logs, it looks quite different than `okteto deploy`
@abs007 I will close this issue, we are already streaming the dependencies output.
