### ISSUE TITLE
Remove "images were already built" message if build are not defined

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3149]
**Describe the bug**
When running 'okteto up' we show this message:

```
 Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'
```

We should not show that message if the build section is not defined in okteto.yaml, since it might confuse the user.

**Comment by abs007** [comment]
I'd like to take this issue up, if possible.

**Comment by jLopezbarb** [comment]
Hi @abs007, I've assigned it to you.

If you need some guidance while coding the fix, feel free to reach us and will provide some context.

Happy coding!!

**Comment by abs007** [comment]
I feel like 
```
No images to build. Check the build field in the Okteto manifest file . To rebuild your images run 'okteto build' or 'okteto deploy --build'` 
```
would be a good replacement. Saying this because afai can see, the string already exists to show if no images are left for building. The string above I believe would be a good general case to cover both cases: 
* no images left for building 
* build section missing

**Comment by jLopezbarb** [comment]
We should only show the message if the images are already built, there is no point on showing that message if there is no build section since we are telling the users that they can rebuild the images, but they can't because there are no images to build
