### ISSUE TITLE
If my repo was cloned using `http` protocol, `okteto deploy` command fails

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3150]
**Describe the bug**
If I clone a repository using `http` protocol, the clone is successfully because during the clone is redirected to `https`, but the `.git` configuration locally it specifies `http`. 

For example, If I clone http://github.com/okteto/movies, it successfully clones and you can see a log saying that it is redirected to https://github.com/okteto/movies. If you check the file `.git/config`, you can see the repo URL as http://github.com/okteto/movies.

If you execute `okteto deploy` from that folder, you get the following output

```
 i  Using nacho @ okteto.nacho.dev.okteto.net as context
 x  Could not detect repo protocol
```

The issues seems in [this function](https://github.com/okteto/okteto/blob/366c67cd31a2e85a0b67ea6f999792a7256e1ff8/cmd/deploy/command_configuration.go#L160), where the `http` is not being handled. 

**To Reproduce**

1. Clone http://github.com/okteto/movies
1. From the base repository folder execute `okteto deploy`
1. You'll see the error `Could not detect repo protocol`

**Expected behavior**
The deploy doesn't fail because the protocol is not valid. It should parse correctly the repo URL and keep progressing with next steps.

If `http` protocol is found, it should be converted to `https` as we do with `ssh`

**Desktop (please complete the following information):**

- Version: `2.7.0`

**Comment by manit-comviva** [comment]
@ifbyol were you able to find any solution, except keep changing the remote host url?

**Comment by ifbyol** [comment]
Hi @manit-comviva , the issue is still in triage and we didn't work on it yet, For now, you would need to clone the repository using `https` or `ssh`
