### ISSUE TITLE
Error: panic when pipeline deploy `--wait`fallback to previews

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3167]
**Describe the bug**
If I run `okteto pipeline --wait --namespace test-{YOUR_USERNAMe}` pointing to an Okteto preview environment. The CLI panics 

**To Reproduce**

1. Run `okteto preview deploy --branch cli-e2e --repository https://github.com/okteto/movies --wait`
1. Get the preview name - it should be something like `distracted-wiles-jlopezbarb`
1. Run `okteto pipeline deploy --branch cli-e2e --repository https://github.com/okteto/movies --wait --namespace distracted-wiles-jlopezbarb `
1. See panic error

**Expected behavior**
CLI should fallback correctly to previews and retrieve the correct information

**Desktop (please complete the following information):**

- Version master

**Additional context**
We should also fix https://github.com/okteto/okteto/blob/master/integration/okteto/preview_test.go#L28 making it fail first [here](https://github.com/okteto/okteto/blob/master/integration/okteto/preview_test.go#L58) and fixing it later.

**Comment by Diazbesjorge** [comment]
This is a regression from 2.7 to 2.8. It was introduced in this [PR](https://github.com/okteto/okteto/pull/3081).
