### ISSUE TITLE
CTRL + C when selecting the service doesn't cancel the "okteto up" sequence 

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3174]
**Describe the bug**
**To Reproduce**

1. `okteto up` on github.com/okteto/movies 
1. Wait for it to be deployed
1. On the service selection, type CTRL + C 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/475313/196591361-6606aa5f-8508-49df-b2c2-420a14f7ecf3.png">

**Expected behavior**
I expect the sequence to exit

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.7.0

**Comment by jLopezbarb** [comment]
Reopened since it's not fixed yet

**Comment by andreafalzetti** [comment]
Issue moved to [JIRA](https://okteto.atlassian.net/browse/LAKE-111)
