### ISSUE TITLE
Running "okteto up" twice without proper termination causes logout in Ubuntu

### ISSUE THREAD

**Issue by viilveer** [okteto/okteto#3177]
**Describe the bug**
Running okteto up twice causes my session to be logged out. I have found a specific scenario to reproduce it but it has happened to me without the given scenario also.

**To Reproduce**

Run "okteto up" in a project
Terminate terminal 
Run "okteto up" in a same project again
When "Activating your development container" is displayed I'm logged out of my session

**Expected behavior**
 Should start project again

**Desktop (please complete the following information):**

- OS: Ubuntu 
- Version: 22.04

**Additional context**
From auth.log I can see:
```
Oct 19 16:29:58 mihkel-ThinkPad-X1-Extreme-Gen-4i polkitd(authority=local): Unregistered Authentication Agent for unix-session:12 (system bus name :1.703, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Oct 19 16:29:59 mihkel-ThinkPad-X1-Extreme-Gen-4i gdm-password]: pam_unix(gdm-password:session): session closed for user mihkel
Oct 19 16:29:59 mihkel-ThinkPad-X1-Extreme-Gen-4i systemd-logind[1130]: Session 12 logged out. Waiting for processes to exit.
Oct 19 16:29:59 mihkel-ThinkPad-X1-Extreme-Gen-4i systemd-logind[1130]: Removed session 12.
```

Running okteto cli 2.8.1

**Comment by viilveer** [comment]
I can confirm that okteto CLI verison 2.10.0 fixes issue. Thank you for the efforts.

**Comment by pchico83** [comment]
Thanks @viilveer for confirming the fix, and for your help to troubleshoot this issue :-)
