### ISSUE TITLE
separate between flags used by the user and options allowed by the command

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3186]
**Is your feature request related to a problem? Please describe.**
We already have some issues related to not differentiating between user flags and the options used by the command later (See #3171, #2846 or #2824). 

This is a problem when we need to differentiate between use cases based on the flags of the user if are specified or not or if they are being used as the default behavior. It also add some friction when we are sending metrics about the flags that the user has set.

**Describe the solution you'd like**
I would like to differentiate with two different structs the user flags from the command options for each of the commands:

Related to `context`:
- [ ] Differentiate them in `context`
- [ ] Differentiate them in `context use`
- [ ] Differentiate them in `context create`
- [ ] Differentiate them in `context delete`
- [ ] Differentiate them in `context list`
- [ ] Differentiate them in `context show`
- [ ] Differentiate them in `context update-kubeconfig`
- [ ] Differentiate them in `context use-namespace`
- [ ] Differentiate them in `context use`

Related to namespace:
- [ ] Differentiate them in `namespace`
- [ ] Differentiate them in `namespace use`
- [ ] Differentiate them in `namespace list`
- [ ] Differentiate them in `namespace create`
- [ ] Differentiate them in `namespace delete`

Related to pipeline:
- [ ] Differentiate them in `pipeline deploy`
- [ ] Differentiate them in `pipeline destroy`

Related to preview:
- [ ] Differentiate them in `preview deploy`
- [ ] Differentiate them in `preview destroy`
- [ ] Differentiate them in `preview endpoints`
- [ ] Differentiate them in `preview list`

Related to stack:
- [ ] Differentiate them in `stack deploy`
- [ ] Differentiate them in `stack destroy`
- [ ] Differentiate them in `stack endpoints`

Related to single cmds:
- [ ] Differentiate them in `deploy`
- [ ] Differentiate them in `destroy`
- [ ] Differentiate them in `endpoints`
- [ ] Differentiate them in `init`
- [ ] Differentiate them in `build`
- [ ] Differentiate them in `up`
- [ ] Differentiate them in `doctor`
- [ ] Differentiate them in `down`
- [ ] Differentiate them in `exec`
- [ ] Differentiate them in `kubeconfig`
- [ ] Differentiate them in `push`
- [ ] Differentiate them in `restart`
- [ ] Differentiate them in `status`
- [ ] Differentiate them in `version`

**Comment by omnomagonz** [comment]
@jmacelroy I opened an internal backlog item [here](https://www.notion.so/okteto/Separate-between-flags-used-by-the-user-and-options-allowed-by-the-command-95d7bdfc4a1444759693540ac91b094f) for tracking and prioritization 👍
