### ISSUE TITLE
Document how to revert GitHub actions

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3188]
**Is your feature request related to a problem? Please describe.**
There are multiple ways of reverting a GitHub action to a previous version. We should have a document explaining what to do in case one of the actions has a bug or what to do if we need to revert all the actions where we can check the actions to follow

**Describe the solution you'd like**
We should have a document explaining how to revert GitHub actions in case there is a problem. This document should cover how can we revert only one of them to a previous version or reverting all the actions to the version specified

**Comment by omnomagonz** [comment]
Created a product backlog item for this [here](https://www.notion.so/okteto/Document-how-to-revert-GitHub-actions-f3b59c755fa74738bc0d108228daaea1).

It's unclear to me if this is internal-facing, customer-facing, or both. I'm also not sure what the relative priority of this may be, so I've added it to our backlog to evaluate 😄 

cc @jmacelroy

**Comment by jLopezbarb** [comment]
Completed
