### ISSUE TITLE
Add --dependencies flag to okteto pipeline deploy

### ISSUE THREAD

**Issue by AlonShirion** [okteto/okteto#3209]
**Is your feature request related to a problem? Please describe.**
Can't run "okteto pipeline deploy" and force all the dependencies to redeploy.

**Describe the solution you'd like**
Similar to "okteto deploy --dependencies" I would like a flag like that for the "okteto pipeline deploy" command, so I would run:
"okteto pipeline deploy --dependencies"

**Describe alternatives you've considered**
For now I'm running "okteto deploy --dependencies" but it use the local files instead of the remote repo, and that is what I want to use for my use case.

**Additional context**

**Comment by jLopezbarb** [comment]
Should we reopen this now that pipeline will get deprecated?
cc: @pchico83
