### ISSUE TITLE
Possible bug in up.go

### ISSUE THREAD

**Issue by abs007** [okteto/okteto#3211]
**Describe the bug**
Should this line in `up.go`:
https://github.com/okteto/okteto/blob/39b5b7757668a2b4bea7b3e0054c3b174f010dd9/cmd/up/up.go#L374
be changed to:
```go
 } else if len(args) == maxV1Args { 
```
**Reason**
What if maxV1Args increases beyond 1? Also, seems like cleaner code to set it this way.

**Comment by jLopezbarb** [comment]
Nice catch @abs007!!

**Comment by abs007** [comment]
Happy to help!

**Comment by jLopezbarb** [comment]
I uploaded a PR but after doing it, I reviewed [the PR that you made](https://github.com/okteto/okteto/pull/3215) and since it will be replaced I think the PR that I made is not needed anymore. I think we can tackle this issue in your PR, WDYT @abs007 ?

**Comment by abs007** [comment]
Seems good. Also, I think that the pr I made would also be taking care of this slack discussion: https://kubernetes.slack.com/archives/CM1QMQGS0/p1668059807909449

**Comment by abs007** [comment]
Closing this issue wrt pr #3215
