### ISSUE TITLE
okteto with local k3d cluster and insecured docker registry

### ISSUE THREAD

**Issue by tangenttechno** [okteto/okteto#3213]
**Describe the bug**
Okteto throws error   Error checking image at registry k3d-registry:5000/XXX : error getting image tag digest: Get "https://k3d-registry:5000/v2/": http: server gave HTTP response to HTTPS client
 
okteto.yaml

build:
  express-ts-starter:
    image: okteto.dev/express-ts-starter
    context: .
deploy:
  - kubectl apply -f kubernetes-manifests
dev:
  express-ts-starter:
    command: bash
    sync:
      - .:src/**/*.ts
    forward:
      - 9229:9229

 The local registry is added to the Docker daemon:
 Insecure Registries:
  k3d-registry:5000
  127.0.0.0/8
 Registry Mirrors:
  https://registry-1.docker.io/
 Live Restore Enabled: false

 Tilt works fine to deploy the same. But doesn't work in okteto.
How to run okteto with a local insecure registry?

**Comment by pchico83** [comment]
@tangenttechno could you format the okteto manifest? I look missaligned. Also, where are you specifying the registry "https://k3d-registry:5000/v2/" in the okteto manifest?
