### ISSUE TITLE
Need better error handling

### ISSUE THREAD

**Issue by abs007** [okteto/okteto#3220]
**Describe the bug**
Need error handling here:
https://github.com/okteto/okteto/blob/39b5b7757668a2b4bea7b3e0054c3b174f010dd9/internal/test/utils.go#L36

**Additional context**
Need to check if `SetEnv()` func returns an error. Possibly correct it through updating linters.
Context: https://kubernetes.slack.com/archives/CM1QMQGS0/p1667276346405729

**Comment by abs007** [comment]
I'd like to take this up and work on this. Would help me learn more about linting .

**Comment by pchico83** [comment]
Awesome @abs007! We are using deepsource [here](https://github.com/okteto/okteto/blob/master/.deepsource.toml) but happy to update its config or even use a different one. Sync with @jLopezbarb for proposals

**Comment by abs007** [comment]
Oh, I was looking under the lint section in the makefile 😅

**Comment by pchico83** [comment]
@abs007 that also works, @jLopezbarb can provide more details on monday

**Comment by abs007** [comment]
Hmm, interesting. Sure 👍

**Comment by jLopezbarb** [comment]
Hi @abs007, I've been checking deep source and I haven't been able to find that rule, so if you have a linter proposal to check those uncatched error, I think we have to add it to make our code better 😄

**Comment by abs007** [comment]
Hi, could you point me to the docs you're referring to? I also think that maybe using a transformer may help?

**Comment by jLopezbarb** [comment]
I was referring the deep source docs, there is no way of getting where the rules comes from, but we also have  [.golangci.yaml](https://github.com/okteto/okteto/blob/master/.golangci.yml) to detect them which have `errcheck` disabled.
To enable it we need to disable first, correct all the errors thrown by the linter and remove it from disable section

**Comment by abs007** [comment]
>To enable it we need to disable first, correct all the errors thrown by the linter and remove it from disable section

Do you mean removing `errcheck` from the disable section? I removed it and ran `golangci-lint run` to see a bunch of new linting errors (I'm guessing I'll have to correct those). 

Also, what is the diff btw mentioning `errcheck` in the `enable` section and not mentioning it all? Both seem to be working the same.

**Comment by jLopezbarb** [comment]
> > To enable it we need to disable first, correct all the errors thrown by the linter and remove it from disable section
> 
> Do you mean removing `errcheck` from the disable section? I removed it and ran `golangci-lint run` to see a bunch of new linting errors (I'm guessing I'll have to correct those).
> 
> Also, what is the diff btw mentioning `errcheck` in the `enable` section and not mentioning it all? Both seem to be working the same.

`errcheck` is enabled by default so it doesn't matter if we set it as enabled or not. The [lines that are commented](https://github.com/okteto/okteto/blob/master/.golangci.yml#L12) are the one that are already enabled by default so there is no need to add them in the enable section but if we want to stop using them we have to add them to the disable section.



> I'm also wondering if me adding error handling to the code blocks would break anything? I'm kind of getting the feeling that the files are supposed to be the way that they are (i.e. without the err checking). Can I get some sort of a go-ahead?

I'd suggest you to just log them. That way we don't break the execution but we can check the logs later to know what has happen:
```go
  err := whateverFunc()
  if err != nil {
    oktetoLog.Infof("could not do whatever because: %v", err)
  }
```

**Comment by abs007** [comment]
>errcheck is enabled by default so it doesn't matter if we set it as enabled or not. The [lines that are commented](https://github.com/okteto/okteto/blob/master/.golangci.yml#L12) are the one that are already enabled by default so there is no need to add them in the enable section but if we want to stop using them we have to add them to the disable section.

What about the 2nd block which mentions [Disabled by your configuration linters](https://github.com/okteto/okteto/blob/master/.golangci.yml#L22). Doesn't this line suggest that all the tools mentioned under it would be disabled by default?

>I'd suggest you to just log them. That way we don't break the execution but we can check the logs later to know what has happen:

Also, there seem to be around 50 such err handling so should I divide it over a few commits?

**Comment by jLopezbarb** [comment]
> What about the 2nd block which mentions [Disabled by your configuration linters](https://github.com/okteto/okteto/blob/master/.golangci.yml#L22). Doesn't this line suggest that all the tools mentioned under it would be disabled by default?

My bad, The section commented is the result of running `golangci-lint linters` which takes in count the linters in the `.golangci.yaml`. But yes all the tools that are mentioned under the section you said and are not in the `enable` section are disabled by default.

> Also, there seem to be around 50 such err handling so should I divide it over a few commits?

It's up to you, I'd split by type, If all of them are the same type of errors I'd just create one commit, but you can do whatever you think is better for helping the reviewers 😜

**Comment by abs007** [comment]
>It's up to you, I'd split by type, If all of them are the same type of errors I'd just create one commit, but you can do whatever you think is better for helping the reviewers 😜

If I can't find any distinction over the types, I'll divide it over 5 commits (10 changes in each)

**Comment by abs007** [comment]
Also, should I go for `oktetoLog.Infof()` or `oktetoLog.Errorf()` ?

**Comment by jLopezbarb** [comment]
I think `oktetoLog.Infof()` or `oktetoLog.Debugf()` are the best functions for it since it's not an error that we should show to the user
