### ISSUE TITLE
Show a log stage for `dependencies`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3226]
**Describe the bug**
As a follow-up of [this comment](https://github.com/okteto/okteto/pull/3219#issuecomment-1313390902) we aren't providing a log stage for deploying dependencies. This is specially tricky when using `wait`, since an error in the deployment of the dependency will be shown as an internal server error.

**Expected behavior**
Let's have a single stage for deploying dependencies, calle "Deploying dependencies".
The output will "Dependency scheduled for deployment..." if `wait` is false. And `Wating for dependency to be deployed...` + `Dependency successfully deployed` if `wait` is true. We don't want to stream the output of the dependency here because it's already available in the gitDeploy object of the dependency.

@rlamana ^^

**Comment by rlamana** [comment]
@pchico83 a couple of comments:
- Can we at least provide information in the ouput about what dependencies are those?
- For the output if `wait` is set to false, I would be more direct if there is no more output to see there, so we should avoid the `...` and maybe say `The dependency 'xxx' has been scheduled for deployment.`
- We should also give a hint on where to find that output

**Comment by pchico83** [comment]
> I think the single stage approach makes sense. Would it be a lot of effort to adjust/change this later if we found it to be not ideal?

@omnomagonz no, we could easily change it based on the feedback we get

**Comment by ifbyol** [comment]
@pchico83 @omnomagonz @rlamana  I just want to warn that maybe this task is much more complex than it seems at first glance. I was dealing with this part of the code recently and it has some things to bear in mind. We can talk internally about it
