### ISSUE TITLE
Support for secrets in okteto.yml

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#323]
**Is your feature request related to a problem? Please describe.**
I want to import my docker credentials

**Describe the solution you'd like**
Import secrets from my okkteto.yml file

**Describe alternatives you've considered**
Modify the original deployment, but it is not a clean approach

**Comment by reshadf** [comment]
Is there any progress on this?

**Comment by rberrelleza** [comment]
@reshadf not yet.  What is your use case? Are you using publicly available images in your deployment, and want to use a private image for your development environment?

**Comment by reshadf** [comment]
Hi thanks for the quick reply @rberrelleza Yes that is the use case for now. Local development. I made it work for now by patching the serviceaccount for default namespace and add the secret there. For now, that works too.

**Comment by rberrelleza** [comment]
Looks like it might be the same as #568 , @pchico83 ?

**Comment by pchico83** [comment]
@rberrelleza right. closing this one as a duplicate
