### ISSUE TITLE
Can not detect compose file named compose.yaml and doest not support some grammer

### ISSUE THREAD

**Issue by Zacama** [okteto/okteto#3237]
Hello, my compose file's name is compose.yaml (referenced from https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file) but it can't be detected. When I change it's name to docker-compose.yaml, it can be detected.
And it reports an error in volumes.
![image](https://user-images.githubusercontent.com/50320281/203213865-90f98ee7-2197-4a25-ac9b-2d02b82a68d7.png)
![image](https://user-images.githubusercontent.com/50320281/203213913-db2a24bf-9cdb-4e33-a108-bf26cf2cf80f.png)
I am sorry for my bad English.

**Comment by jLopezbarb** [comment]
Hi @Zacama, Your issue is related to https://github.com/okteto/okteto/issues/1995. Today we don't support the extended syntax in the volume section but it's something that was previously planned. 


cc: @omnomagonz @jmacelroy to track this issue.

**Comment by Zacama** [comment]
OK, thank you very much.
