### ISSUE TITLE
Add more messages to "synchronizing your files" phase

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#324]
**Is your feature request related to a problem? Please describe.**
This phase can take about a minute to create persistent volumes and the user might think okteto is hanging...

**Describe the solution you'd like**
Add a new spinner telling that persistent volumes are being created and warning that this operatiom might take about a minute for the first okteto up execution. If the volumes were already created, this spinner shouldnt appear

**Describe alternatives you've considered**
Move from persistent volumes to local volumes since onteto doesnt require hard persistency. Local volumes require mayor re-arquitecture and more user feedback

**Comment by rberrelleza** [comment]
fixed by #334
