### ISSUE TITLE
refactor volume content container initialization

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3240]
**Describe the bug**
the command that initializes the volume content is too verbose and difficult to work with. Perhaps the command logic related to the volume initialization can be extracted into a binary file. 

https://github.com/okteto/okteto/blob/8a9ed725f30f11590918e7df69714483a3a7c09a/pkg/cmd/stack/translate.go#L336

On the other hand, the code related to [this issue](https://github.com/okteto/okteto/issues/3060) was reverted so it will need to be addressed again at some point.

**Comment by jLopezbarb** [comment]
Let's reopen this. This is something that is low prio but can let the users what's happening behind all the magic
