### ISSUE TITLE
Move from persistent volumes to local volumes

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#325]
**Is your feature request related to a problem? Please describe.**
I want faster okteto up execution. I want my dev pods to be created in several nodes

**Describe the solution you'd like**
Move from persistent volumes to local volumes. Local paths can be associated to a multi write disk to support dev pods in several nodes.

**Comment by pchico83** [comment]
This will only be interesting if we move to a ManyWrite volume world. Closing for now since that change would be in the very long term

**Comment by jagedn** [comment]
this mean cant we use ManyWrite by the moment ?
I have a deployment with 2 pods and want to share a persistent volume between them

**Comment by pchico83** [comment]
@jagedn you can share PVCs and use `ManyWrite` as you wish. This is only for the okteto internal persistent volume.

**Comment by jagedn** [comment]
thanks @pchico83 
sadly I'm not able to create wih `ReadWriteMany` . I'll open an issue due this is not the right place
