### ISSUE TITLE
Add external resource definition in the CLI

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3266]
As a developer I want to be able to define external resources in my okteto manifest, so I can use that information in the UI to have a full view of my application.

The idea is to have a new key at the root of okteto manifest which defines the external resource that will be shown in the UI.

The definition of this new section is:
```golang
type Manifest struct {
  ... 
  ExternalResources map[string]ExternalResourceInfo
}

type externalResourceInfoUnmarshall struct {
  notes string // path from the root of the project
  endpoints []ExternalEndpoints
}

type externalResourceInfo struct {
  notes ExternalResourceNotes
  endpoints []ExternalEndpoints
}

type ExternalResourceNotes struct {
  path string
  markdown string // base64 encoded content of the path
}

type externalResourceEndpoints struct {
  name string // endpoint name
  url string // URL to display in the UI/endpoints cmd
}
``` 

## Acceptance criteria

- [x] Define the external resource structs
- [x] It should be unmarshalled correctly
  - [x] notes must not be empty
  - [x] there must be at least one endpoint
- [ ] It should show a warning and skip it if the user is not in an okteto cluster. 
  - [ ] The warning must be shown only if the external key is present 
- [x] The environment variable `$OKTETO_EXTERNAL_($NAME)_ENDPOINTS_($NAME)_URL` must be available in the deploy section
- [x] Differentiate between the unmarshall struct and the one being used in the rest of the command
- [x] Store the content of `external.$NAME.notes` in base64

**Comment by AgustinRamiroDiaz** [comment]
@jLopezbarb what will the logic around these resources be? Will we hit some health check endpoint?

**Comment by jLopezbarb** [comment]
Today, developers cannot model their external resources, like a local db or a telemetry dashboard as part of their development environments in Okteto, forcing them to have partial development environments.

With this change the users will be able to deploy externals resources that contains the necessary information about their resources that are not in k8s.

> Will we hit some health check endpoint?
 
I don't know what you are referring to. All these external resources are created as k8s resources under the CRD `externals.dev.okteto.com`
