### ISSUE TITLE
okteto destroy must destroy external resources

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3269]
As a developer I want to be able to destroy the external resources I have defined in my okteto manifest, so I can use that information in the UI to have a full view of my application.

The idea is that `okteto destroy` command destroy all the external resources with the label `deployed-by`

## Acceptance criteria

- [ ] okteto destroy must destroy the external resources defined in the okteto manifest
- [ ] okteto destroy --all must destroy all the external resources in the namespace
- [ ] it should throw a warning if the cluster is not a cluster managed by okteto

**Comment by AdrianPedriza** [comment]
I close this task since command destroy already works for resources with the `deploy-by` label
