### ISSUE TITLE
failed to get credentials on Okteto Self Hosted 

### ISSUE THREAD

**Issue by DavoBR** [okteto/okteto#3277]
**Describe the bug**
when use the commands of okteto context use mydomain or okteto up, i am getting the error "Internal server error, please try again"

**To Reproduce**

1. Open terminal
1. Run command okteto context use https://okteto.mydomain.com
1. See error: Internal server error, please try again

**Expected behavior**
A success message when change to my own okteto server

**Desktop (please complete the following information):**

- OS: macOS Apple Silicon
- Version 13.0

**Additional context**

Error in okteto-api container logs:

```
{"timestamp":"2022-12-04T15:01:37Z","serviceContext":{"service":"okteto-backend"},"message":"failed to get credentials: ServiceAccount 64b894ba-0330-4443-b139-f2f0a700c728 doesn't have any secrets","severity":"ERROR","context":{"data":{"http.request.id":"5c75c240-4053-47bd-850e-4089c0fc02dc","instance.id":"okteto-api-5bd64845f7-99265","user.id":"64b894ba-0330-4443-b139-f2f0a700c728"},"reportLocation":{"filePath":"github.com/okteto/app/backend/pkg/graphql/queries.go","lineNumber":449,"functionName":"createQueryType.func12"}}}
```

User Service Account

<img width="702" alt="image" src="https://user-images.githubusercontent.com/498724/205498572-de2f342e-addb-454e-ac18-326cf906ad48.png">

Helm Values: https://gist.github.com/DavoBR/48809c8eeaa06a4617301d3f7820ba15

Consuming graphql api from insomnia i get the same error

<img width="449" alt="image" src="https://user-images.githubusercontent.com/498724/205498893-bad3e649-b7c8-4fea-97b9-08191ba90374.png">

**Comment by pchico83** [comment]
@DavoBR which kubernetes version are you using? 1.24 isn't supported yet

**Comment by DavoBR** [comment]
> @DavoBR which kubernetes version are you using? 1.24 isn't supported yet

i am using 1.24.6+k3s1

Is there any workaround to make it work?

**Comment by pchico83** [comment]
@DavoBR we are working on 1.24 support. Fir now, you need to use 12.3

**Comment by DavoBR** [comment]
> @DavoBR we are working on 1.24 support. Fir now, you need to use 12.3

i downgrade to 1.23.14 and now its working, thanks @pchico83
