### ISSUE TITLE
Recreate dev pod on `okteto up` if it's in error state

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3282]
**Is your feature request related to a problem? Please describe.**
`okteto up` fail because of an infra problem. If I run `okteto up` and the infra issue is solved, my dev pod continues in error state until k8s retries to schedule the pod.

**Describe the solution you'd like**
`okteto up` should always recreate the pod if it's in error state.

**Describe alternatives you've considered**
Let the user recreate the dev pod manually, but this requires context about kubernetes

**Comment by jLopezbarb** [comment]
Reopening since it was not addressed yet
