### ISSUE TITLE
Recrate pods in error state on `okteto deploy`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3283]
**Is your feature request related to a problem? Please describe.**
`okteto deploy` leave pods on error state because of an infra problem. If I run `okteto deploy` again and the infra issue is solved, my pods continue in error state until k8s retries to schedule them.

**Describe the solution you'd like**
`okteto deploy` should always recreate pods if they are in error state.

**Describe alternatives you've considered**
Let the user recreate the pods manually, but this requires context about kubernetes

**Comment by pchico83** [comment]
@abs007 awesome, I assigned it to you. All pods created by `okteto deploy` have a `deploy-by` label. You can use that to identify the pods and destroy them if they are in a failing state since before the last `okteto deploy` command is executed

**Comment by abs007** [comment]
I couldn't find the `deploy-by` label but instead found a `deployed-by` label. Did you mean that?

**Comment by pchico83** [comment]
> I couldn't find the `deploy-by` label but instead found a `deployed-by` label. Did you mean that?

Right, it's `deployed-by`

**Comment by abs007** [comment]
Hi, I've been going through the code and was wondering if the labels are set through `translateReplicaSetSpec()` or `translateDeploymentSpec`  method in [proxy.go](https://github.com/okteto/okteto/blob/master/cmd/deploy/proxy.go)?

**Comment by pchico83** [comment]
@abs007 yes, for example here https://github.com/okteto/okteto/blob/master/cmd/deploy/proxy.go#L360

**Comment by abs007** [comment]
So, it seems the way the method `translateDeploymentSpec()` works is it receives the spec file through the reverse proxy if its of type `Deployment` and then adds the label & alters the dns search domain and then forwards the spec to the k8s server.

**Comment by abs007** [comment]
Do all the kubernetes resources (including pods) which are made through the `deploy` command have the `deployed-by` label?

**Comment by abs007** [comment]
I'm thinking of using the [List()](https://github.com/kubernetes/client-go/blob/v0.26.1/kubernetes/typed/core/v1/pod.go#L88) method to get the list of pods that have the `deployed-by` label. 
I am thinking of then using the [delete()](https://github.com/kubernetes/client-go/blob/v0.26.1/kubernetes/typed/core/v1/pod.go#L163) method to remove the failing pods so that Kubernetes would restart the pod automatically but I'm not sure if that is what will happen.

**Comment by pchico83** [comment]
@abs007 that makes sense! I would restart every pod that it's not running

**Comment by abs007** [comment]
I thought about data in the pod's ephemeral storage that might be lost if the pod gets restarted but I think that having a failed pod means that the data has been lost already.

**Comment by pchico83** [comment]
That's fine @abs007. A pod can be recreated at any time. It would be an application error to store data in the ephemeral storage that needs to be persisted

**Comment by abs007** [comment]
Yep, that makes sense. I'll make the changes then.

**Comment by abs007** [comment]
What would be the `value` for a pod with the key as `deployed-by`? Is it the name of the pod?

**Comment by pchico83** [comment]
> What would be the `value` for a pod with the key as `deployed-by`? Is it the name of the pod?

@abs007 it's the name of the git repo. Or the `name` property of the okteto manifest if defined

**Comment by abs007** [comment]
I was wondering if it would be beneficial to check for all pods and not just the ones that have the `deployed-by` label. Or is it that restarting pods without the label would cause unknown failures?

**Comment by pchico83** [comment]
> I was wondering if it would be beneficial to check for all pods and not just the ones that have the `deployed-by` label. Or is it that restarting pods without the label would cause unknown failures?

Great feedback, but I think it's safer to only recreate the ones deployed by repo for now. 
We can always modify this if we find use cases for it.

**Comment by abs007** [comment]
Got it

**Comment by jLopezbarb** [comment]
Reopen.
