### ISSUE TITLE
Support Envs for CacheFrom and ExportCache build options

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#3289]
When using the options `cache_from` and `export_cache` support the use of environment variables for the values of these options.

We should expand this value when the manifest is read or the option is used at the command as flag.

**Comment by jLopezbarb** [comment]
Reopening since it's not fixed yet

**Comment by pchico83** [comment]
Closing this one for now as we might deprecate this options in favor of the pull first approach
