### ISSUE TITLE
okteto deploy is not injecting the image name in the 'deploy' section on windows machines

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3296]
**Describe the bug**

**To Reproduce**

1. Clone github.com/okteto/movies
1. set up your context
1. `okteto deploy`

The deployment fails with an error due to the value of `$OKTETO_BUILD_FRONTEND_IMAGE` not being available

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 2.10.1
-  Terminal: Powershell

The same issue happened on the regular command prompt

**Comment by rberrelleza** [comment]
we 'echoed' the command, notice how the value passed to image on the `deploy frontend` space is empty.
![image](https://user-images.githubusercontent.com/475313/207423215-d3d58574-c79a-40d3-946c-05ff726e7953.png)

**Comment by pchico83** [comment]
@jLopezbarb we have e2e tests on windows testing this, right?

**Comment by jmacelroy** [comment]
I did a fresh install of cli 2.10.1 using scoop on my windows 11 box and was able to deploy to a 1.2 cluster as well as to our internal staging cluster and did not reproduce the issue. Is there another config or component at play here?

**Comment by jLopezbarb** [comment]
> @jLopezbarb we have e2e tests on windows testing this, right?

Yes, we have several tests that check that the build env vars are populated into the commands.

I couldn't reproduce the issue with 2.10.1 neither.

From the log file I can see that the env vars are set but somehow the commands are either not receiving them or can't expand them correctly

**Comment by jmacelroy** [comment]
Any updates or extra info on this @rberrelleza @jLopezbarb and have both made attempts and are unable to reproduce. I'm in favor of closing until we have more info that may help find the issue.
