### ISSUE TITLE
Pass space param in Credentials query

### ISSUE THREAD

**Issue by maroshii** [okteto/okteto#3336]
It look like we are not passing the current namespace in the `space` param for the credentials query. Here: ~~https://github.com/okteto/okteto/blob/master/pkg/okteto/credential.go#L36~~

https://github.com/okteto/okteto/blob/master/pkg/okteto/secrets.go#L59

This is creating an issue in multicluster where we are recreating the default namespace in the workers some time since it may not exist.

**Comment by jLopezbarb** [comment]
Reopening the issue
