### ISSUE TITLE
Error building image - `docker-credential-desktop resolves to executable in current directory`

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3353]
**Describe the bug**
Whenever I try to build an image, okteto throws the following error
```
 x  Error building service 'frontend': error building image 'xxxxx/xxxxx:xxxx': build failed: failed to solve: error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``
```

**To Reproduce**

1. Change your $PATH to `/usr/bin/:/bin/bash:/bin`
1. Check that your `~/.docker/config.json` has the field `credsStore`
1. Try to build an image
1. See error

**Expected behavior**
It shouldn't fail. If we detect `credsStore` we should be renaming it to `credStore` since it's the correct way of naming it.

Loaded here: https://github.com/okteto/okteto/blob/master/pkg/cmd/build/authprovider.go#L35

**Desktop (please complete the following information):**
- Version 2.11.1

**Comment by jLopezbarb** [comment]
After researching more about this issue, this is what I found:

Buildkit looks for `~/docker/config.json` to check what is the `credStore` that may be used.  If it doesn't exists, it checks the default `credStore` which for macOs is `osxkeychain`. This `credStore` is a binary (`docker-credential-osxkeychain`) that must be in `$PATH`. If the credStore binary is not in `$PATH` we get the error posted above

- We could either log the error in the log file. The user won't be authenticated on external registries but will be able to use okteto registry and public repos on external registries
- We could fail with a clearer error. Mentioning to make sure that the `~/docker/config.json` is pointing to the right `credStore` and to make sure that the binary `docker-credential-$CREDSTORE_NAME` is in the path.

@pchico83 which option seems more reasonable?

**Comment by pchico83** [comment]
@jpf-okteto option is the right one. I wouldn't show a warning. If you don't have a local credential store, you don't have local registry credentials, so we can safely ignore the error
