### ISSUE TITLE
Remote deployment - deploy and destroy should work the same way

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3357]
Okteto deploy and okteto destroy commands should both be executed on remote when the `deploy.image` field is set or if the `--remote` flag is set. 

## Acceptance criteria

- [x] okteto deploy is only executed on remote if `deploy.image` is set
- [x] okteto destroy is only executed on remote if `deploy.image` is set
- [x] Support `--remote` flag on deploy/destroy command that sets `deploy.image` if not set already.

**Comment by pchico83** [comment]
@jLopezbarb let's have a dedicated image for destroy, which will be `destroy.image`. If it's set, or you are running `okteto destroy --remote`, the destroy command is run on remote
