### ISSUE TITLE
Changing syncthing scan interval via config file

### ISSUE THREAD

**Issue by binoychitale** [okteto/okteto#3382]
**Is your feature request related to a problem? Please describe.**
I'm currently using Okteto for Development, and noticed that changes to source files take a while to sync to the dev container running in the cluster. 
I'm able to manually increase the frequency of scans by reducing the scan interval from the syncthing UI, after running `okteto status --info`

**Describe the solution you'd like**
A way to set this config in the okteto config file and have it checked into code so that it does not need to be done manually on each development session?

**Describe alternatives you've considered**
Manually change it on each session via UI, but that is tedious

**Comment by pchico83** [comment]
Hi @binoychitale.
There is an extended notation in the `sync` field to specify the rescan interval:
https://www.okteto.com/docs/reference/manifest/#sync-string-required

But we also configure watchers. If watchers are properly configured, you shouldn't face this problem
