### ISSUE TITLE
K8S resources.requests.memory from docker-compose is not being set

### ISSUE THREAD

**Issue by mnevadom** [okteto/okteto#3383]
**Describe the bug**
If you set in docker-compose the `resources.requests.cpu` value it will never map the `resources.requests.memory` value to the k8s resource.

We have detected this because a Community question: https://community.okteto.com/t/how-to-configure-k8s-resources-limits-requests-from-docker-compose-yml/604

**To Reproduce**

1. Use movies-with-docker-compose repo
2. Add to one of the services the resources requests (cpu and memory)
3. Check that the pod created resource has the memory set with the default value

**Expected behavior**
The result pod should have the memory value you are setting

**Comment by mnevadom** [comment]
The problem is in this line and the `if` after it

https://github.com/okteto/okteto/blob/ee65cf263db00e84bc347f8095742b614641577a/pkg/cmd/stack/translate.go#L664

It will never get into the `if statement` of memory if we create the object before with CPU filled

**Comment by mnevadom** [comment]
Docker-compose doc: https://docs.docker.com/compose/compose-file/compose-file-v3/#resources

@Diazbesjorge

**Comment by Diazbesjorge** [comment]
I would indeed update our docs to reflect those options.

**Comment by mnevadom** [comment]
https://github.com/okteto/docs/pull/326
