### ISSUE TITLE
endpoint does not work! but it was in the past!

### ISSUE THREAD

**Issue by mellahysf** [okteto/okteto#3398]
Hi,

I have a Dev environment in octets, with 2 servers running successfully. 
In the past (1 year ago), there was a response using the endpoint (all work fine), but now it does not!! no response from the endpoint!!
what can be the problem please?

Note: I see just one endpoint, but I think I should have 2 since I have 2 running servers ?
I'm using Github.

thanks!

**Comment by jLopezbarb** [comment]
Closing it since we can't reproduce it. @mellahysf let us know if you are still facing this error
