### ISSUE TITLE
Envvar expansion in `build` section

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3416]
**Describe the bug**
I'm not sure if it's a regression or a feature request

`build.<devenv>.image` section is not getting expanded with envvars

**To Reproduce**

1. `git clone https://github.com/okteto/movies`
1. `cd movies`
1. modify the `okteto.yml` to set `build.api.image=${my_env_var}`
1. `export my_env_var=imagetag`
2. `okteto build api`
3. See error ` x  Error building service 'api': error building image '${my_env_var}': build failed: failed to solve: invalid reference format`

**Expected behavior**
The image should get tagged with `imagetag`

**Additional context**
We now have some envvar handling but it's in other particular places of the manifest like the destroy commands

**Comment by pchico83** [comment]
Closing this one as we will work on a general solution instead
