### ISSUE TITLE
Handle envvar substitution in the entire manifest

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3417]
**Is your feature request related to a problem? Please describe.**
I want to customize my okteto manifests to be able to use envvars so that I can use them in different environments and get the different results

**Describe the solution you'd like**
I don't have the details, but most importantly all the values from the manifest should get envvar expanded. Expanding the keys would not be a common use case

**Describe alternatives you've considered**

**Additional context**
Some things to bear in mind:
- how we are handling the image build envvars that get injected into the deploy and dev section
- at which point we are doing the envvar substitution

**Comment by pchico83** [comment]
Duplicated of https://github.com/okteto/okteto/issues/3483
