### ISSUE TITLE
[Okteto Cloud] Failed to create pod sandbox... errno 524 unknown

### ISSUE THREAD

**Issue by bangbaew** [okteto/okteto#3422]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29559559/222663926-59d53108-6578-41f1-aaae-62bf2a9bff25.png)

4/5 of my deployments in my namespace has been frequently going down, which weren't consuming resource at all, one of them is Next.js app, one of them is golang binary run on scratch image, two of them are rust binary run on alpine,
every deployment has the same error:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown
```
**To Reproduce**
It happens unexpectedly, this first time this error happened showed that the deployments were last updated 19-22 hours ago.

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Windows 10 / Microsoft Edge
- Version 110.0.1587.57

**Additional context**
It's been up for around 22 hours and then down and they're not restarting, tried restarting manually doesn't help, the last time they were down takes only a few minutes to restart.

**Comment by ifbyol** [comment]
Hi @bangbaew ! There was an issue with a node and it was already replaced, it should be working now.

If you have further questions you can also reach out at https://community.okteto.com/
