### ISSUE TITLE
Ignore OKTETO_TOKEN warning if OKTETO_TOKEN is the one in the current context

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3434]
**Describe the bug**
I am running the Okteto CLI in my CI pipeline. The pipeline gets `OKTETO_TOKEN` as an envvar. As part of the pipeline I execute `okteto ctx use`. After that, every Okteto CLI command shows this warning:
```
Initializing context with the value of OKTETO_TOKEN environment variable
```

**To Reproduce**

1. Get the token of your crrent context with `okteto ctx show`
1. `export OKTETO_TOKEN=xxx` with the above value
1. Run `okteto kubeconfig`

**Expected behavior**
If the value of `OKTETO_TOKEN` is the same as the token in the okteto context, we shouldn't show the warning

**Comment by dhanusaputra** [comment]
hi, can I try help with this issue? thanks

**Comment by pchico83** [comment]
Yes, I assigned the issue to you @dhanusaputra!
Let us know if you need more context to solve the issue.

In general, we show a warning when a variable is redefined on your laptop.
We can ignore the warning for all values if the new value is the same, but especially the case of `OKTETO_TOKEN` is quite common
