### ISSUE TITLE
Return and error if using `services` and disabling the okteto persistent volume

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3437]
**Describe the bug**
[services](https://www.okteto.com/docs/reference/manifest/#services-object-optional) requires the persistent volume to be enabled. We should return a clear error if using `services` and `persistentVolume.enabled: false`.

**To Reproduce**

1. Modify https://github.com/okteto/math to disable the persistent volume in the dev container
1. Run `okteto up`

**Expected behavior**
A clear error is returned stating that `persistentVolume.enabled` must be true to use `services`

**Comment by IshaSri-17Speed** [comment]
I would like to work on this issue/

**Comment by pchico83** [comment]
Awesome @IshaSri-17Speed! I assign the issue to you, let us know if we can help

**Comment by IshaSri-17Speed** [comment]
Thank you  for assigning me!!

**Comment by rakshitgondwal** [comment]
Hey! Is this open for grabs?

**Comment by IshaSri-17Speed** [comment]
Heya @rakshitgondwal 

I'm working on this issue already.

**Comment by rakshitgondwal** [comment]
Cool @IshaSri-17Speed

**Comment by nitishfy** [comment]
Do you happen to have any updates on this issue? 
cc @IshaSri-17Speed

**Comment by nitishfy** [comment]
**Update:** A [valid PR](https://github.com/okteto/okteto/pull/3706) has been raised for this issue with some minor additional things that are yet to be done. 

@IshaSri-17Speed You can take a look at the PR and do the additional things that are required.

**Comment by IshaSri-17Speed** [comment]
Surely!!! @nitishfy 
I'll take a look shortly on  futher things that needs to be done.
