### ISSUE TITLE
init command must always create a manifest v2

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3445]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-7fbd3a6a566145d3a4930d3c15fc642d?pvs=4)

## Description

Right now running `okteto init --v1` creates a manifest v1, which is deprecated and will be fully removed on `okteto CLI 3.0`. We need that every `okteto init` command create an okteto manifest v2.

okteto init `--v1` flag is removed since it's generating an okteto manifest v1.

The new behavior is the following one:
- If the cluster that the user is connecting to is a vanilla cluster. We only generate the `dev` section
- If teh cluster is an okteto cluster we generate all the sections (as it is right now)

## Acceptance Criteria

- [ ] `okteto init --v1` is fully removed
- [ ] `okteto init` using a vanilla cluster creates an okteto manifest with just the dev section
- [ ] `okteto init` must use our implementation of [selector](https://github.com/okteto/okteto/blob/master/cmd/utils/selector.go#L80). The one used right now is very frustating because everytime the user moves between selections it rings macOS bell.
- [ ] `okteto init` must continue creating `okteto manifest v2` with all the fields

### Scenario 1
1. Create an empty folder and enter in it.
2. Run `okteto init`
3. Follow the steps to create the manifest
4. Check that the manifest created is a manifest v2

### Scenario 2
1. Deploy any application
2. Create an empty folder and enter in it.
3. Run `okteto init`
4. Move between the different values
5. Check that the macOS bell is no longer ringing for every movement

### Scenario 3
1. Deploy any application
2. Create an empty folder and enter in it.
3. Run `okteto init` using a vanilla cluster as context
4. Choose one of the selections
5. Check that the manifest created is a manifest v2 (with `dev` section)

**Comment by jLopezbarb** [comment]
It's a simple change but we need to schedule it to do it

**Comment by rlamana** [comment]
@jLopezbarb do we have an update on this one?

**Comment by jLopezbarb** [comment]
> @jLopezbarb do we have an update on this one?

We didn't have time to plan this change. It should be ready before launching CLI 3.0 but we didn't have time to work actively on this one. I'll increase the priority in order to work on this when we have enough time
