### ISSUE TITLE
Automatically create a namespace if needed

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3452]
**Describe the bug**
When I have `namespace` in my okteto manifest and the namespace doesn't exist, we are automcatically creating the namespace in Okteto clusters when running an Okteto CLI command. But this is not the case if using the `-n namespace` flag. We should be consistent and create the namespace when using the `-n` flag too.

**To Reproduce**

1. Clone https://github.com/okteto/go-getting-started
1. Run `okteto up -n my-new-namespace`
1. It fails with a low level error because the namespace doesn't exist

**Expected behavior**
The namespace is create and the command works

**Comment by AnshulAngaria** [comment]
@pchico83 I am trying to solve this issue. While reproducing, I observed that even if I specify namespace in manifest file, 
`Okteto up` command does not create the namespace. But some other commands like `okteto deploy` does.
Am I missing something?

**Comment by pchico83** [comment]
> @pchico83 I am trying to solve this issue. While reproducing, I observed that even if I specify namespace in manifest file, `Okteto up` command does not create the namespace. But some other commands like `okteto deploy` does. Am I missing something?

@AnshulAngaria right, `okteto up` should implement the auto create namespace logic implemented by other commands like `okteto deploy`

**Comment by AnshulAngaria** [comment]
@pchico83 I have submitted a PR for this please review.
