### ISSUE TITLE
Support for `okteto namespace sleep|wake`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3470]
**Is your feature request related to a problem? Please describe.**
I want to automate the sleep operation of my namespace. For example, I want to sleep my namespace at a given time.

**Describe the solution you'd like**
`okteto namespace sleep` to mimic the function of the Okteto UI  **sleep** button.
`okteto namespace wake` to mimic the function of the Okteto UI  **wake** button.

**Comment by jLopezbarb** [comment]
Hi @NitishKumar06. I assigned the issue to you. Here is more context about the issue:
This issue consists in creating two new commands under the `cmd/namespace` (see [namespace/delete](https://github.com/okteto/okteto/blob/master/cmd/namespace/delete.go) command implementation).

The logic for `sleeping`/`waking` up a namespace is [here](https://github.com/okteto/okteto/blob/master/pkg/okteto/namespace.go#L135)

**Comment by pchico83** [comment]
@NitishKumar06 do you have access to https://cloud.okteto.com?

**Comment by NitishKumar06** [comment]
Yes, @pchico83.

**Comment by pchico83** [comment]
> Yes, @pchico83.

Awesome, thanks for the update @NitishKumar06 !

**Comment by NitishKumar06** [comment]
> The logic for `sleeping`/`waking` up a namespace is [here](https://github.com/okteto/okteto/blob/master/pkg/okteto/namespace.go#L135)

_namespace/delete_ is helping me more to understand the code. However, it's becoming quite overwhelming understanding the test cases even after debugging. Any suggestions?
