### ISSUE TITLE
when asking about the stignore, okteto doesn't accept `Y` 

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3476]
**Describe the bug**
when asking about the stignore, okteto doesn't accept `Y` , even when that's the option displayed in the console. 

![image](https://user-images.githubusercontent.com/475313/227393395-2d6ce7ce-b33a-47cc-8a06-d518d055db7c.png)

**To Reproduce**

1. do `okteto up` on a repo without .stignore file

**Expected behavior**
The CLI should accept both `Y` and `y`

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.13

**Comment by AnshulAngaria** [comment]
Hi @rberrelleza , I would like to take up this issue.

**Comment by jLopezbarb** [comment]
Hi @AnshulAngaria. I've assigned the issue to you. If you need help identifying where the code is that needs to be updated, don't hesitate to ask. We are eager to help you with whatever you need.
