### ISSUE TITLE
Okteto destroy not reporting dev environment name for local connection

### ISSUE THREAD

**Issue by etrombly** [okteto/okteto#3486]
The output of `okteto destroy` looks like this with okteto 2.13.0 when using a local k8s cluster:

```
 i  Using eric-trombly @ dev/eric.trombly@XXXX as context
 ✓  Development environment '' successfully destroyed
```

it should be:
```
 i  Using eric-trombly @ dev/eric.trombly@XXXX as context
 ✓  Development environment 'login_page' successfully destroyed
```

The message is emitted here:
```
cmd/destroy/local.go
52:             oktetoLog.Success("Development environment '%s' successfully destroyed", opts.Name)
```

Since the message is using options.Name, if the name isn't set specifically it's not reported in the destroy output.

- OS: Ubuntu
- Version 20.04

**Comment by teresaromero** [comment]
I think this is related https://github.com/okteto/okteto/issues/3487

**Comment by etrombly** [comment]
I'll close in favor of #3487
