### ISSUE TITLE
Destroy message has an empty quote if the environment doesn't have a name

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3487]
**Describe the bug**
When destroying an environment, we print out a success log. If the env has a name, it looks like this:

```
✓  Development environment 'my environment' successfully destroyed
```

However, if there's no name, it looks like this:

```
✓  Development environment '' successfully destroyed
```

If the environment doesn't have a name, we should remove the quotes since it looks odd:

```
✓  Development environment successfully destroyed
```

**Comment by NitishKumar06** [comment]
I'd like to work on this.

**Comment by etrombly** [comment]
@NitishKumar06 you can see this PR https://github.com/okteto/okteto/pull/3475 for some previous discussion of the issue.

**Comment by AgustinRamiroDiaz** [comment]
@NitishKumar06 seems like my last PR is the issue, I'll revert it https://github.com/okteto/okteto/pull/3490

Try using one commit earlier from master (3b63511a1e45c6a3953690e0e72369526bead414) or wait for my PR to get merged

**Comment by AgustinRamiroDiaz** [comment]
@NitishKumar06 it was merged. You should be able to use master now

**Comment by NitishKumar06** [comment]
Thanks, @AgustinRamiroDiaz! The PR has been raised.
