### ISSUE TITLE
Provide an easy way to access the original container command

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#351]
**Is your feature request related to a problem? Please describe.**
if i’m developing on an application i don’t know for instance — and i’m dropped into a shell, which is all wired up — i’d likely need to dig around in a few places to figure out “what does this container do by _default_” … either there’s a command (with possible args), defined in the kubernetes manifest — _or_ there’s a default command defined in the image manifest somewhere, which can be difficult to dig out

**Describe the solution you'd like**
Print the original command as part of the `okteto up` command.

**Comment by pchico83** [comment]
`oc` prints the original command
https://bierkowski.com/openshift-troubleshooting-oc-debug/

**Comment by davidreuss** [comment]
Does `okteto` show the original command now? I originally requested this feature, and was notified of it being closed, but i don't see any commits/prs mentioned here.

**Comment by pchico83** [comment]
@davidreuss Sorry for not explaining the reason to close the issue. We opted for postponing it until there are more user requests to support this scenario.
Implementing this feature requires access to the dev image from the local machine, which is not necessarily the case (credentials might be defined on the cluster side).
There are different workarounds to support this scenario, like defining an alias in your dev machine or having a `Makefile` in your repo.
