### ISSUE TITLE
Show a permanent progress bar of sync process

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#352]
**Is your feature request related to a problem? Please describe.**
I don´t know the state of the sync process when synching a big file, like syncthing `node_modules`.

**Describe the solution you'd like**
The top line id the terminal shows the percentage of the sync process.

**Describe alternatives you've considered**
Show the progress bar as part of the `okteto up` command, but it does not cover all the scenarios.

**Comment by rberrelleza** [comment]
fixed by #424
