### ISSUE TITLE
`okteto up` silently dies when disconnected form the network without any kind of feedback or explanation

### ISSUE THREAD

**Issue by rlamana** [okteto/okteto#353]
**Describe the bug**
Lately, when my laptop goes to sleep, my `okteto up` sessions silently die without a message or feedback of any kind:

CLI output:
```
...
    Entrypoint undefined = index.html
       21 modules
ℹ ｢wdm｣: Compiled successfully.

[rlamana:~/Repositories/okteto-app/frontend]
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version okteto 1.2.2

**Comment by rberrelleza** [comment]
@rlamana can you include your okteto logs?

**Comment by rlamana** [comment]
Here you have it: [okteto.log](https://github.com/okteto/okteto/files/3493474/okteto.log)

**Comment by pchico83** [comment]
@rlamana is this still an issue?

**Comment by rlamana** [comment]
This has not happened to me in a while. Closing it....
