### ISSUE TITLE
Okteto CLI removes .env file

### ISSUE THREAD

**Issue by jrx-sjg** [okteto/okteto#3532]
I have an .env file with many environment variables for our project. When I use okteto CLI to deploy, build or destroy environments using a custom docker-file, okteto cli randomly deletes that file (which is very annoying). It's started happening after upgrading to 2.14.1 version.

**To Reproduce**

1. Upgrade to 2.14.1
2. okteto deploy -f docker-kompose.yaml
3. The .env file on the project root is ramdonly deleted.

After downgrading to 2.12.0 the problem has disappeared.

**Comment by jrx-sjg** [comment]
Confirming it's also happening in 2.13.0

**Comment by jrx-sjg** [comment]
This is amazing 😲

**Comment by jLopezbarb** [comment]
Hi @jrx-sjg, we are very sorry for all the inconveniences that this bug may have caused you. We released a new patch to fix the issue! Thanks for spotting it

**Comment by jrx-sjg** [comment]
Brutal support. Okteto project management is awesome.
