### ISSUE TITLE
Unable to set securityContext for a given "service" using cli for dev

### ISSUE THREAD

**Issue by will-beep-lamm** [okteto/okteto#3542]
When running multiple container pods with reasonable pod security contexts, such as running as non-root users or flagging runAsNonRoot, I am unable to set those other containers (running as services) security contexts independently.  Thus while I can allow my interactive container to run as non-root and as a specific user, the other containers will be forced to run as root user 0 and fsGroup 0.

**Describe the solution you'd like**
I would love to just allow the securityContext from the interactive container be replicated in the services array.

**Describe alternatives you've considered**
I have considered allowing deployments to run allowing non-root, but there would be significant security implications to opening that can of worms.

 x  Couldn't activate your development container
     Error: container's runAsUser breaks non-root policy (pod: "xxx", container: web)

Example is a pod with separate "web" and "app" containers with static assets in the "web" container and backend code running in the "app" container.

**Comment by will-beep-lamm** [comment]
Bump

**Comment by jLopezbarb** [comment]
@will-beep-lamm If we allow `securityContext` field  on the dev.services. Will that work for you?

**Comment by will-beep-lamm** [comment]
Yes, that is exactly what I would suggest. It would work to have security
context per dev.service.
