### ISSUE TITLE
`okteto up` command shows duplicate log

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3569]
**Describe the bug**
when I run `okteto up` in an empty namespace, `Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'`  message is shown duplicated.

**To Reproduce**

in an empty namespace:
1. clone https://github.com/okteto/go-getting-started
2. execute `okteto up`
3. see duplicate logs
<img width="890" alt="Captura de Pantalla 2023-04-20 a las 11 58 39" src="https://user-images.githubusercontent.com/22500940/233332069-e4588719-c960-4dc7-b315-d0d7e258092d.png">

**Expected behavior**
`Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'` should be displayed only once.

**Desktop (please complete the following information):**

- Version CLI `2.14.2`

**Comment by NitishKumar06** [comment]
Are there any possibilities that this issue somehow relates to https://github.com/okteto/okteto/issues/3501?

In https://github.com/okteto/okteto/issues/3501, the text replicates at certain width of the terminal. Can you confirm whether this happens for `okteto up`?

**Comment by jLopezbarb** [comment]
> Are there any possibilities that this issue somehow relates to #3501?
> 
> In #3501, the text replicates at certain width of the terminal. Can you confirm whether this happens for `okteto up`?

No, the selector is a unique way of displaying logs and doesn't affect this issue. This issue is because we are calling two times the `GetServicesToBuild` function from the `okteto up` command
