### ISSUE TITLE
fix `okteto version update` logic to not rely on the order of the github releases

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3576]
**Describe the bug**
When I execute `okteto version update` and the latest CLI release has a commit older than the latest patch in the previous release, the command displays `The latest okteto version is already installed` but I keep working with the older version. This is because GH releases take into account commit date to order releases. We need to modify our `okteto version update` command [to not rely on the order returned by github](https://github.com/okteto/okteto/blob/master/cmd/utils/upgrade.go#L59) to check if there is a new available release.

**Comment by jLopezbarb** [comment]
Not implemented. We could work on this since the CLI version no longer uses GH as the source of truth
