### ISSUE TITLE
Option to create namespace without setting it as current

### ISSUE THREAD

**Issue by Mark90** [okteto/okteto#3579]
The description of `okteto namespace create` (version 2.14.0) is currently:

```
Usage:
  okteto namespace create <name> [flags]

Flags:
  -h, --help                  help for create
  -m, --members stringArray   members of the namespace, it can the username or email
```

When you use this to create a new namespace, it automatically sets this as the current namespace (same as applying `okteto namespace use <namespace>`).

We want to script things on top of `okteto namespace create` to automate create a namespace (or sometimes multiple) without having to remember to switch back to the previous namespace.

# Proposed solution

To have an option `--keep-current` or `--no-change-current` or something, to disable automatically changing the current namespace

**Comment by pchico83** [comment]
@Mark90 I think we can use the flag `--use` and `--use=false` since the command to switch contexts is `okteto ctx use`.
Do you think you could work on a PR? Otherwise, I can mark it as "good-first-issue" an any of our contributors might work on it

**Comment by Mark90** [comment]
Haven't done much with Go lately, marking it a good-first-issue has my preference. If after some time nobody else has shown interest I could give it a shot.

**Comment by NitishKumar06** [comment]
I'd like to take this up. Please assign this to me!

**Comment by pchico83** [comment]
> I'd like to take this up. Please assign this to me!

@NitishKumar06 assigned, thanks! Let's follow the syntax explained in [this comment](Pablo Chico de Guzman Huerta
)

**Comment by NitishKumar06** [comment]
> @NitishKumar06 assigned, thanks! Let's follow the syntax explained in [this comment](https://github.com/okteto/okteto/issues/3579#issuecomment-1524709937)
yes, I'll be raising a PR as soon as I implement the changes. Thanks!
