### ISSUE TITLE
CLI should not fail on `okteto destroy` if the metrics server is not available

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3582]
**Describe the bug**
When the metrics server is not available in the cluster for whatever reason, `okteto destroy` fails when try to delete all resources by label. As the logic checks all the available APIs to delete resources, if the metrics server is not available, we should not fail. We should keep deleting other resources.

Similar logic was already implemented in the backend to prevent it when deleting all resources within a namespace. A similar approach would be needed here

![Screenshot 2023-04-28 at 09 58 25](https://user-images.githubusercontent.com/3510171/235186158-df9db321-8f8f-4451-87be-b5f491c90873.png)

**To Reproduce**

1. Have a cluster with metrics-service deployed but not available
2. Deploy an application with `okteto deploy`
3. Execute `okteto destroy` and you should get the error

**Expected behavior**
Even if the metrics service is not available, rest of resource should be deleted and it should succeeds.

**Desktop (please complete the following information):**

- Version: At least in `2.15.1`

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by pchico83** [comment]
@ifbyol is this already fixed?

**Comment by ifbyol** [comment]
> @ifbyol is this already fixed?

No, it isn't fixed yet

**Comment by maroshii** [comment]
moved to: https://okteto.atlassian.net/browse/RAIN-45
