### ISSUE TITLE
Support `variables` in the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3583]
**Is your feature request related to a problem? Please describe.**
I want to configure my `deploy` comands with environment variables, but I need to define default values for those variables.

**Describe the solution you'd like**
Support a `variables` section to define variables to my environment:

```
variables:
  var1: value1
  var2: value2
```

This values can be overwtiten with the okteto deploy `--var` flag and will be stored in the deploy configmap

[ ] Document this feature in https://github.com/okteto/docs

**Comment by PriyanshuAhlawat** [comment]
Hi @pchico83 can I work on this?

**Comment by pchico83** [comment]
@PriyanshuAhlawat awesome, go for it! Let us know if need more context to implement the feature

**Comment by PriyanshuAhlawat** [comment]
@pchico83 I have got the basic idea of the project, now I will be coding so firstly acc. to my understanding-

- we need to introduce a new section of variables 

- read the declared variables from this section and validate their types

-  then application code can utilize the validated environment variables as required

will like to have your input and also can you help me with the file where I have to declare this new section, having a bit trouble in finding where to start😓

**Comment by PriyanshuAhlawat** [comment]
@pchico83 please look into this so I can move forward with this issue

**Comment by jLopezbarb** [comment]
Hi @PriyanshuAhlawat , You're correct. Here is a little explanation about the bullet points you wrote: 

> we need to introduce a new section of variables

We need to add a new varibles section [here](https://github.com/okteto/okteto/blob/master/pkg/model/manifest.go#L181)

> read the declared variables from this section and validate their types

Yes, we need to support reading the variables in a list syntax or a map syntax (read the declared variables from this section and validate their types).

> then application code can utilize the validated environment variables as required

Yes, we should always check that the variables in the section replaces local environment variables but they don't override variables that comes from the `--var` flag.

Here is an snippet on how you could test almost all the scenarions:

### Test the new behavior

1. Create the following okteto.yml
```yaml
deploy:
  commands:
  - echo $MYVAR
  variables:
  - MYVAR=test
```
2. Run `okteto deploy`
3. Check that the output of the command is `test`

### Test the old behavior is still working

1. Create the following okteto.yml
```yaml
deploy:
  commands:
  - echo $MYVAR
  variables:
  - MYVAR=test
```
2. Run `okteto deploy --var=MYVAR=foo`
3. Check that the output of the command is `foo`

### Test that it overrides local env var

1. Create the following okteto.yml
```yaml
deploy:
  commands:
  - echo $MYVAR
  variables:
  - MYVAR=test
```
2. Run `export MYVAR=foo`
3. Run `okteto deploy`
4. Check that the output of the command is `test`

### Test that local env are propagated if there is no variables section

1. Create the following okteto.yml
```yaml
deploy:
  commands:
  - echo $MYVAR
```
2. Run `export MYVAR=foo`
2. Run `okteto deploy`
3. Check that the output of the command is `foo`

**Comment by PriyanshuAhlawat** [comment]
Thanks @jLopezbarb for explaining👍, working on it

**Comment by jLopezbarb** [comment]
> Thanks @jLopezbarb for explaining👍, working on it

Hi @PriyanshuAhlawat, how is it going? Do you need anything?

**Comment by PriyanshuAhlawat** [comment]
@jLopezbarb sorry have been busy with university exams since mid june, I am on it now

**Comment by jLopezbarb** [comment]
> @jLopezbarb sorry have been busy with university exams since mid june, I am on it now

First things first. I hope the exams went well. If you have any problems or need more information do not hesitate to ask us.
