### ISSUE TITLE
Exporting cache results in error 

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3588]
**Describe the bug**
From time to time an `okteto deploy --build` fails because the cache that okteto is trying to export fails. The error message is different but it's always while exporting the cache. The most common one is:
```
#9 ERROR: error writing config blob: failed to open writer: failed to do request: Post "https://registry.staging.okteto.net/v2/testbuildwithsecrets-linux-1682432799-cindylopez/001-test/blobs/uploads/": EOF
```

**To Reproduce**

1. Run e2e tests several times
1. When one of them has failed is probably because of this

**Expected behavior**
If the build completes successfully and there is an error while exporting the cache (the image that is going to be used is already built) we should warn the user that there was an error exporting the cache but don't fail the deploy

**Desktop (please complete the following information):**

- Version 2.15.2

**Additional context**
It happens from time to time but most of the times it makes e2e tests very annoying because of this failure

**Comment by pchico83** [comment]
@jLopezbarb could we also use this issue to only show one line in the logs exposed to the user for pushing the cache iamge?

**Comment by jLopezbarb** [comment]
@pchico83 That would require more research since this is just checking if the image has been built and don't fail if the error comes from the export cache step. It doesn't involve checking the logs. We could open another issue to track that

**Comment by pchico83** [comment]
> @pchico83 That would require more research since this is just checking if the image has been built and don't fail if the error comes from the export cache step. It doesn't involve checking the logs. We could open another issue to track that

@jLopezbarb makes sense
