### ISSUE TITLE
Pipeline streaming logs are hidden almost instantly

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3590]
**Describe the bug**
Whenever I run an `okteto pipeline --wait`, the logs that the pipeline shows are hidden almost instantly and the only thing I can see is the `waiting for pipeline to finish` spinner. It doesn't happen if my terminal is width enough to display the full line.

**To Reproduce**

1. Run `okteto pipeline --wait` on a repo
1. Make your terminal narrower
1. See that the logs dissapears

**Expected behavior**
I want them to be there so I can check what's actually happening on real time without having to resize my terminal

**Desktop (please complete the following information):**

- Version 2.15.2

**Comment by pchico83** [comment]
@jLopezbarb on which cluster was this happening?

**Comment by jLopezbarb** [comment]
This happens in all the clusters. It's because the spinner length is longer that my terminal width and the experience is very weird...
