### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gtaranas** [okteto/okteto#360]
**Describe the bug**
 okteto up
  Provisioning your persistent volume...
 +  Persistent volume provisioned
  Starting the file synchronization service...
  Synchronizing your files...
  Overriding existing files in your Okteto environment...
 +  Files synchronized
  Activating your Okteto Environment...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x18 pc=0x12c66f2]

goroutine 21 [running]:
github.com/okteto/okteto/pkg/k8s/deployments.TranslateDevContainer(0x0, 0xc000c59450)
        /home/circleci/project/pkg/k8s/deployments/translate.go:125 +0x62
github.com/okteto/okteto/pkg/k8s/deployments.translate(0xc000069b00, 0xc0004203f0, 0xc001269d08)
        /home/circleci/project/pkg/k8s/deployments/translate.go:92 +0x6ae
github.com/okteto/okteto/pkg/k8s/deployments.TraslateDevMode(0xc0004203f0, 0xc000307680, 0xc001204f90)
        /home/circleci/project/pkg/k8s/deployments/crud.go:105 +0x9a
github.com/okteto/okteto/cmd.(*UpContext).devMode(0xc000d22280, 0xc000307600, 0xc000307680, 0x0, 0x0, 0x0)
        /home/circleci/project/cmd/up.go:377 +0x18c
github.com/okteto/okteto/cmd.(*UpContext).Activate(0xc000d22280)
        /home/circleci/project/cmd/up.go:209 +0x3ac
created by github.com/okteto/okteto/cmd.RunUp
        /home/circleci/project/cmd/up.go:119 +0x170

**To Reproduce**
run okteto up

**Desktop (please complete the following information):**
 - OS: win 10
 - Version 1.3.0

**Comment by rberrelleza** [comment]
Thanks for the information @gtaranas , looking into it.  Would it be possible for you to share the `okteto.yml` and the deployment you're targeting? (do remove anything proprietary or private)

**Comment by gtaranas** [comment]
The yml file is from vscode folder on the samples repo

**Comment by pchico83** [comment]
@gtaranas does the error happen consistently? 
does it happen if you do:
```
okteto down -v
okteto up
```
I am not able to repro the issue, I am wondering if it is a race condition.

**Comment by gtaranas** [comment]
thanks @pchico83 it is working now 
`okteto  down -v`
`okteto up`

**Comment by pchico83** [comment]
@gtaranas cool!
I am closing the issue then, thanks!
