### ISSUE TITLE
`--log-level` and `--log-output` doesn't work with `okteto context [*]`

### ISSUE THREAD

**Issue by jpf-okteto** [okteto/okteto#3617]
**Describe the bug**
The following command flags don't work with `okteto context` and children commands:
- `--log-level`
- `--log-output`

**To Reproduce**

1. `okteto context list -l debug --log-output json`
2. Notice that neither the debug logs are shown nor the output is json.

**Expected behavior**

Command flags work as defined.

**Desktop (please complete the following information):**

- OS: any
- Version: https://github.com/okteto/okteto/commit/b2c03cdced8670e1f181e2d5abe2d651c0388596, master > 2.15.2 

**Additional context**

`okteto context` command defines an spf13/cobra PersistentPreRun, which overrides `okteto` root command PersistentPreRun. 

Regression introduced at:
- https://github.com/okteto/okteto/issues/3075

**Comment by teresaromero** [comment]
@jpf-okteto I do not reproduce this scenario

```
❯ ok context list -l debug --log-output json
{"level":"debug","stage":"","message":"server name override: \"\"","timestamp":1686299249}
{"level":"info","stage":"","message":"started /Users/teresaromero/Github/okteto/bin/okteto context list -l debug --log-output json","timestamp":1686299249}
{"level":"debug","stage":"","message":"insecure mode: false","timestamp":1686299249}
Name                                                            Namespace     Builder                                         Registry
https://cloud.okteto.com                                        teresaromero  tcp://buildkit.cloud.okteto.net:443             
{"level":"info","stage":"","message":"finished /Users/teresaromero/Github/okteto/bin/okteto context list -l debug --log-output json","timestamp":1686299250}
```
