### ISSUE TITLE
Build hash should not check secret content to create it

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3622]
**Describe the feature**
When we are generating the [build hash](https://github.com/okteto/okteto/blob/master/cmd/build/v2/config.go#L96). We should only check the key value and not the content of the secret, since buildkit is just checking the key/value to use the cache.

**Expected behavior**
I want that the build hash is generated only with the key value of secrets, without checking the content of secret file.

**Comment by sankalp-r** [comment]
@jLopezbarb 

I want to work on this.
Please assign it to me and also point me to the right direction.

**Comment by jLopezbarb** [comment]
Hi @sankalp-r, on this issue you should be changing [this line](https://github.com/okteto/okteto/blob/master/cmd/build/v2/config.go#L96) to instead getting the secrets file content generate the hash with the name and value of the secrets. 

We  are already doing it for [buildArgs](https://github.com/okteto/okteto/blob/master/cmd/build/v2/config.go#L92-L95C1).  Note that the type for BuildArgs is a custom type and for secrets is a `map[string]string`

There is [this unit test](https://github.com/okteto/okteto/blob/master/cmd/build/v2/config_test.go#L243-L261) to check that the functionality works as expected.
