### ISSUE TITLE
Track duration of every relevant step of `okteto build`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3642]
**Is your feature request related to a problem? Please describe.**
We want to track the duration of every relevant step of the build command to understand where to invest more time to speed up the execution of the `okteto build` command.

**Describe the solution you'd like**
At least, we should track as part of the build event, time to configure the okteto context, time to chec if the image is already built in the global registry, time to build the image, time to push it, time to push the cache, ... and the total execution time

**Comment by jLopezbarb** [comment]
Already planned for the next release
