### ISSUE TITLE
Track duration of every relevant step of `okteto deploy`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3643]
**Is your feature request related to a problem? Please describe.**
We want to track the duration of every relevant step of the deploy/destroy command to understand where to invest more time to speed up the execution of the `okteto deploy/destroy` commands.

**Describe the solution you'd like**
At least, we should track as part of the deploy/destroy event, time to configure the okteto context, fire another event if there is a `build`, time to synchronize the `--remote` context, time to run all the commands, ... and the total execution time.

**Comment by jLopezbarb** [comment]
Already planned for the next release
