### ISSUE TITLE
Track duration of every relevant step of `okteto up`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3644]
**Is your feature request related to a problem? Please describe.**
We want to track the duration of every relevant step of the up command to understand where to invest more time to speed up the execution of the `okteto up` command.

**Describe the solution you'd like**
We are already tracking the time it takes the initial sync, but we can track more things like time to configure the okteto context, fire another event if there is a `build`, fire another event if there is a `deploy`, time to create the dev container, time to synchronize the the context, time to scan local folders, ... and the total execution time.

**Comment by AnshulAngaria** [comment]
@pchico83 I want to work on this.

**Comment by pchico83** [comment]
> @pchico83 I want to work on this.

@AnshulAngaria this one is a little tricky because it requires mixpannel access
