### ISSUE TITLE
Support a `remote` boolean field in the `deploy` section of the okteto manifest

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3645]
**Is your feature request related to a problem? Please describe.**
I need to configure `--remote` in my pipelines.

**Describe the solution you'd like**
An option equivalent to `--remote` in the `deploy` and `destroy` sections of the okteto manifest.

We should also support the environment variable `OKTETO_FORCE_REMOTE=true` to always force `--remote`

**Comment by Ayush9026** [comment]
can i work on this issue.

**Comment by pchico83** [comment]
Thanks @Ayush9026 , I assigned the issue to you. Let us know if you need more context to implement it. The idea is to support the okteto deploy --remote` flag in your okteto manifest like this:
```
deploy:
   remote: true
   commands:
...
```

**Comment by Ayush9026** [comment]
Thanks @pchico83 sir for assigning issue if i need any information i will tell you .

**Comment by Ayush9026** [comment]
which Tech stack i have to use in it i think yaml. In Circleci folder I
have to solve this  please explain i am new to open source but want to
contribute .

**Comment by jLopezbarb** [comment]
Hi @Ayush9026, 
You'll have to create a new field remote in the data structure [Deploy struct](https://github.com/okteto/okteto/blob/master/pkg/model/manifest.go#L181) with the label for being accepted in the yaml. 
After that you'll need to add the logic for executing the deploy on remote if the field is true. That could be done [here](https://github.com/okteto/okteto/blob/master/cmd/deploy/deploy.go#L520).

You can test all this changes in [okteto cloud](https://cloud.okteto.com/login). Let us know if you have any question or problem

**Comment by jatinagwal** [comment]
@Ayush9026 are you on it? I would like to pick this up.

**Comment by jatinagwal** [comment]
@jLopezbarb I have made the necessary changes. For testing, I am little bit unclear,  I am new to okteto cloud. Can you please refer some doc or high level overview ?? Because I saw in oketeto cloud platform, it is asking for git URL. So, is it that I have to push changes in my fork, then only I can test them?

**Comment by nitishfy** [comment]
> @jLopezbarb I have made the necessary changes. For testing, I am little bit unclear, I am new to okteto cloud. Can you please refer some doc or high level overview ?? Because I saw in oketeto cloud platform, it is asking for git URL. So, is it that I have to push changes in my fork, then only I can test them?

I'm not sure if i understood your question well. If you're mentioning about how to test you changes locally, run the `make` command. This will create an okteto binary which you can use to test your changes. In case, you'd like to provide an alias for it, read [here](https://github.com/okteto/okteto/blob/master/contributing.md#executing).

Let me know if you have any doubts.

**Comment by jLopezbarb** [comment]
> > @jLopezbarb I have made the necessary changes. For testing, I am little bit unclear, I am new to okteto cloud. Can you please refer some doc or high level overview ?? Because I saw in oketeto cloud platform, it is asking for git URL. So, is it that I have to push changes in my fork, then only I can test them?
> 
> I'm not sure if i understood your question well. If you're mentioning about how to test you changes locally, run the `make` command. This will create an okteto binary which you can use to test your changes. In case, you'd like to provide an alias for it, read [here](https://github.com/okteto/okteto/blob/master/contributing.md#executing).
> 
> Let me know if you have any doubts.

@jatinagwal This ^^

If you need to test your unit tests you can also run `make test` from the project root directory. But if you have already done the changes, you can open a PR and we can provide more feedback based on that

**Comment by nitishfy** [comment]
It's been a long time since there was a response from the assignee. I'll solve this issue.

**Comment by nitishfy** [comment]
**Update:** I've started working on this and would like to confirm some  things:
- We would like to have a new section in our `okteto.yml` file called `remote` such that whenever it's value is set to try the deploy/destroy will happen remotely. Correct?
- How can we support the env variable? Which part of the code has information around env variable that is required?
- I tried testing a little bit and got this error, would like to know how can I resolve this error?
 ```
x  Invalid manifest: 
    - line 19: field remote not found in type model.deployInfoRaw
    See https://okteto.com/docs/reference/manifest/ for details
 x  Error building image 'okteto/pipeline-runner:1.0.3': build failed: failed to solve: process "/bin/sh -c mkdir -p $HOME/.ssh && echo \"UserKnownHostsFile=/run/secrets/known_hosts\" >> $HOME/.ssh/config &&   okteto deploy --log-output=json --server-name=\"$INTERNAL_SERVER_NAME\" --name \"go-movies-CRUD\" --timeout 5m0s" did not complete successfully: exit code: 1
```

**Comment by jLopezbarb** [comment]
> **Update:** I've started working on this and would like to confirm some things:
> 
> * We would like to have a new section in our `okteto.yml` file called `remote` such that whenever it's value is set to try the deploy/destroy will happen remotely. Correct?

Yes but under the deploy section. An example of a valid manifest would be:
```yaml
build:
  api:
    context: .
 deploy:
  remote: true
  commands:
  - kubectl apply -f k8s.yml
destroy:
  remote: true
  commands:
  - kubectl delete pod api
```

> * How can we support the env variable? Which part of the code has information around env variable that is required?

I'd just go with the simplest approach and check on the unmarshaller if the env var exists. If exists, show a warning telling the user that we are using that env var and assign the value (if it's a bool) to the `remote` field

> * I tried testing a little bit and got this error, would like to know how can I resolve this error?
> 
> ```
> x  Invalid manifest: 
>    - line 19: field remote not found in type model.deployInfoRaw
>    See https://okteto.com/docs/reference/manifest/ for details
> x  Error building image 'okteto/pipeline-runner:1.0.3': build failed: failed to solve: process "/bin/sh -c mkdir -p $HOME/.ssh && echo \"UserKnownHostsFile=/run/secrets/known_hosts\" >> $HOME/.ssh/config &&   okteto deploy --log-output=json --server-name=\"$INTERNAL_SERVER_NAME\" --name \"go-movies-CRUD\" --timeout 5m0s" did not complete successfully: exit code: 1
> ```

You'll have to build your own CLI (docker build -t ${YOUR_DOCKERHUB_USERNAME}/okteto:remote-deploy -f Dockerfile) image and set it [here](https://github.com/okteto/okteto/blob/0380bd5b1a2ba7ea8928ecfc5a9421c7e3388687/cmd/deploy/remote.go#L261C27-L261C68) in order to test this. This is because we are building remotely with the latest published image which doesn't have the changes you've done locally

**Comment by nitishfy** [comment]
> You'll have to build your own CLI (docker build -t ${YOUR_DOCKERHUB_USERNAME}/okteto:remote-deploy -f Dockerfile) image and set it [here](https://github.com/okteto/okteto/blob/0380bd5b1a2ba7ea8928ecfc5a9421c7e3388687/cmd/deploy/remote.go#L261C27-L261C68) in order to test this. This is because we are building remotely with the latest published image which doesn't have the changes you've done locally

I think i understood most part of it. However, the following questions would help me more to understand about the codebase and okteto in general:

- How's `remote` field option different for `local`?
- Do we need to set the value at [RemoteDeployEnvVar](https://github.com/okteto/okteto/blob/0380bd5b1a2ba7ea8928ecfc5a9421c7e3388687/cmd/deploy/remote.go#L263)? If yes, What value are we targeting to mention?
- In the above example, I modified my existing `okteto.yml` to mention about the remote field and tried running using my latest build, however I'm not sure why do we need to build a new image?

**Comment by nitishfy** [comment]
Ping @jLopezbarb

**Comment by jLopezbarb** [comment]
Sorry for the late answer.

> * How's `remote` field option different for `local`?

If the remote field is set okteto should behave as the  current `okteto deploy --remote` and get the proper deployer [here](https://github.com/okteto/okteto/blob/master/cmd/deploy/deploy.go#L370). The `remote` command  field instead of running all the commands from your computer it will create a deployer in the cluster and run the commands directly in the cluster which can reduce the latency between your computer and the cluster meaning that it can be deployed faster

> * Do we need to set the value at [RemoteDeployEnvVar](https://github.com/okteto/okteto/blob/0380bd5b1a2ba7ea8928ecfc5a9421c7e3388687/cmd/deploy/remote.go#L263)? If yes, What value are we targeting to mention?

No, When we choose the remoteDeployer the correct env var will be set accordingly, so there is no need to work on that

> * In the above example, I modified my existing `okteto.yml` to mention about the remote field and tried running using my latest build, however I'm not sure why do we need to build a new image?

We'll need to build the image because you have your changes in your local okteto binary but the okteto binary running on the remote doesn't have those changes that you have local (that's why it's failing parsing the manifest in the remote but not locally). In order to have the same binary and be able to parse the manifest locally and in the remote we have to build the image and hardcode it (we need to figure out how to do this easier for the all of us that work in the CLI).

I hope everything is clear, if you have further doubts don't hesitate to reach out

**Comment by nitishfy** [comment]
> I hope everything is clear, if you have further doubts don't hesitate to reach out

Got it! One last question is how do you set the environment variable as mentioned in the issue description?

**Comment by jLopezbarb** [comment]
> > I hope everything is clear, if you have further doubts don't hesitate to reach out
> 
> Got it! One last question is how do you set the environment variable as mentioned in the issue description?

The environment variable must be set by the user in his own terminal, for example by running`export OKTETO_FORCE_REMOTE=true`.

**Comment by Ayush9026** [comment]
Hi @pchico83 and @jLopezbarb  sir i am busy so that i will not able to work on this issue for sometime. Anyone who is interested in issue can work.

**Comment by nitishfy** [comment]
> The environment variable must be set by the user in his own terminal, for example by running`export OKTETO_FORCE_REMOTE=true`.

Here's the approach I've followed:
1. I set a new field Remote  for the DeployInfo providing yaml,json keys as well.
2. Once done with this, I added a new line to check if the value is set to true for the field, if yes, run the command in remote. [This is where](https://github.com/okteto/okteto/blob/master/cmd/deploy/command_configuration.go#L48) I have added.
```
if deployOptions.Manifest.Deploy.Remote == true {
    deployOptions.RunInRemote = true
}
```
3. I think this was most part we need to add. I'm still to add the env variable as you mentioned [here](https://github.com/okteto/okteto/issues/3645#issuecomment-1639975477). However, I'm not sure how do I add an env variable and proceed with this: _"I'd just go with the simplest approach and check on the unmarshaller if the env var exists. If exists, show a warning telling the user that we are using that env var and assign the value (if it's a bool) to the remote field"_

I believe, if I get a little help with it, I'd be able to solve this issue very soon.

**Comment by jLopezbarb** [comment]
for the environment variable I'd get it using `utils.LoadBool(OKTETO_FORCE_REMOTE)` and if it's `true` I'll also set `deployOptions.RunInRemote = true`.

In order to test it you can run it by running `OKTETO_FORCE_REMOTE=true; okteto deploy`

**Comment by nitishfy** [comment]
> for the environment variable I'd get it using `utils.LoadBool(OKTETO_FORCE_REMOTE)` and if it's `true` I'll also set `deployOptions.RunInRemote = true`.
> 
> In order to test it you can run it by running `OKTETO_FORCE_REMOTE=true; okteto deploy`

Let's say I set the value of `remote` to true in my manifest. Does this mean `utils.LoadBool(OKTETO_FORCE_REMOTE)` will be automatically set to true?

**Comment by jLopezbarb** [comment]
We don't need to set the environment variable, only check if the value is set and if so, we change `deployOptions.RunInRemote`. If it's not set or set to `false`, we'd go with the value that is in the manifest. 

So the final solution would be something like if any of `--remote`, `OKTETO_FORCE_REMOTE` or `deployOptions.Manifest.Deploy.Remote` is `true` we should set `deployOptions.RunInRemote` to true

**Comment by nitishfy** [comment]
> So the final solution would be something like if any of `--remote`, `OKTETO_FORCE_REMOTE` or `deployOptions.Manifest.Deploy.Remote` is `true` we should set `deployOptions.RunInRemote` to true

Tried building the image, and set the values as well & still getting the same error. I think I'm doing something wrong here.

**Comment by jLopezbarb** [comment]
Did you used the new docker image [here](https://github.com/okteto/okteto/blob/fb80d9c4ebe688444b972a5a9dd9a8a9ea33dcdb/cmd/deploy/remote.go#L261)

It should be something like:
```golang
dockerfileSyntax := dockerfileTemplateProperties{
		OktetoCLIImage:         "nitishkumar06/okteto:remote-deploy"
		UserDeployImage:        opts.Manifest.Deploy.Image,
		RemoteDeployEnvVar:     constants.OktetoDeployRemote,
		ContextArgName:         model.OktetoContextEnvVar,
		NamespaceArgName:       model.OktetoNamespaceEnvVar,
		TlsCertBase64ArgName:   constants.OktetoTlsCertBase64EnvVar,
		InternalServerName:     constants.OktetoInternalServerNameEnvVar,
		TokenArgName:           model.OktetoTokenEnvVar,
		ActionNameArgName:      model.OktetoActionNameEnvVar,
		GitCommitArgName:       constants.OktetoGitCommitEnvVar,
		InvalidateCacheArgName: constants.OktetoInvalidateCacheEnvVar,
		DeployFlags:            strings.Join(getDeployFlags(opts), " "),
	}
```

Let me know if you are still stuck with this change. I'll focus on enabling you as soon as possible
