### ISSUE TITLE
Disable automatic pull & export default cache

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3698]
**Describe the bug**
Since Okteto CLI 2.15.0, there is logic to automatically pull &  export the buildkit cache.
Looking at the metrics, it didn't help to accelerate builds, and it even adding delays on average because of the extra time to import/export the cache.

**Expected behavior**
Remove the feature for automatically export/import the build cache, and let the user specify `export_to/import_from` as desired

**Comment by AnshulAngaria** [comment]
Hey @pchico83 , I can take this up. I was just curious to know why didn't buildkit cache help accelerate builds?

**Comment by pchico83** [comment]
> Hey @pchico83 , I can take this up. I was just curious to know why didn't buildkit cache help accelerate builds?

@AnshulAngaria Buildkit already works with a local cache, which most of the times accelerate the build. Exporting/Importing the cache to a persistent store is not improving cache hits too much, and it introduces a big delay to import/export the cache

**Comment by pchico83** [comment]
@AnshulAngaria I assigned the issue to you. We need to fix this for the next CLI release. If you think you can't make it on time, no worries, one of our engineers can work on this issue

**Comment by AnshulAngaria** [comment]
@pchico83 When is the next CLI release?

**Comment by AnshulAngaria** [comment]
@pchico83 Raised PR.

**Comment by pchico83** [comment]
> @pchico83 Raised PR.

Thanks @AnshulAngaria! The next CLI release is in about 2 weeks

**Comment by andreafalzetti** [comment]
Thanks for raising the PR, @AnshulAngaria - I will have a look at it as soon as I can 🙏
