### ISSUE TITLE
Orphaned .git/index.lock file running `okteto up [svc]`

### ISSUE THREAD

**Issue by mkraft** [okteto/okteto#3699]
**Describe the bug**

I'm using git version 2.41.0 (which was released last week so granted it's possible this is a bug with git itself) and I'm not using an IDE or any other software that is interacting with git other than okteto cli.

**To Reproduce**

1. Go to the root of the project
1. Ensure there is no .git/index.lock file (`rm .git/index.lock` if there is)
1. Run `okteto up [svc]`
1. An orphaned .git/index.lock file appears

**Expected behavior**

No orphaned .git/index.lock file remains.

**Desktop (please complete the following information):**

- OS: macOS
- Version 13.4

**Additional context**

The .git/index.lock file is orphaned by multiple services we run (e.g. web, api).

Here's a screenshot of `okteto up` running in one terminal and `sudo fs_usage | grep .git/index.lock` in another. I confirmed that before running `okteto up` the index.lock did not exist and afterwards the file is orphaned (ie exists).

<img width="1234" alt="Screenshot 2023-06-07 at 11 30 17 AM" src="https://github.com/okteto/okteto/assets/1149597/238807dd-92af-4e01-a858-9c5f5fd504c2">

**Comment by teresaromero** [comment]
@mkraft we are trying to reproduce the scenario but for now we have not been able, with latest okteto cli and git versions.

However, we would like to know more regarding the operation `git status` run at your repository, as okteto has a 1 second timeout for this operation and we might be having something there.

Could you run `time git status --porcelain -z` at your repository and let us know the time the operation spends? This can be useful for investigation.

Thanks!
