### ISSUE TITLE
Dashboard indicator to find deployments in dev mode

### ISSUE THREAD

**Issue by Mark90** [okteto/okteto#3700]
**Is your feature request related to a problem? Please describe.**
We have have around 15 applications in our namespace, and it is a bit tedious to find out if any of them has a deployment running in development mode. I think the only way currently is just to expand all applications in the dashboard and see for which ones it says "In development". I find myself doing this quite often, almost daily.

**Describe the solution you'd like**
A visual indicator to the "ResourceListItem" divs in the dashboard when an application has 1 or more deployments "in development"

Roughly something like this (but then properly aligned of course :) )
![image](https://github.com/okteto/okteto/assets/1482100/fc7e43b0-3bd1-425f-9e99-6ea1415d837f)

This would make it clear from scrolling through the namespace, whether or not there is anything running in development.

**Comment by pchico83** [comment]
@Mark90 what's your use case to know which deployments are in dev mode?

**Comment by Mark90** [comment]
@pchico83 I'm often switching between work on different applications, during which I'll just close the terminal/IDE where `okteto up` was running; I rarely remember to do `okteto down` first. Which I then notice later when another dependend application errors on it. 

I don't know, it could just be a problem that I need to fix in my workflow somehow.

**Comment by pchico83** [comment]
> @pchico83 I'm often switching between work on different applications, during which I'll just close the terminal/IDE where `okteto up` was running; I rarely remember to do `okteto down` first. Which I then notice later when another dependend application errors on it.
> 
> I don't know, it could just be a problem that I need to fix in my workflow somehow.

@Mark90 would `okteto down --all` help? `okteto down --all` disables all dev containers in your current namespace

**Comment by Mark90** [comment]
> `okteto down --all` disables all dev containers in your current namespace

This only seems to stop the dev containers specific to an application
