### ISSUE TITLE
Refactor docker-compose parser with OSS alternative

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3710]
This is an initiative to reduce tech-debt and simplify the codebase by removing the [custom parsing logic](https://github.com/okteto/okteto/blob/master/pkg/model/stack_serializer.go) for the docker compose manifest and instead using the https://github.com/compose-spec/compose-go

**Comment by enraiha0307** [comment]
Hi @andreafalzetti, I would like to work on this.

**Comment by andreafalzetti** [comment]
@enraiha0307 sounds good to me, do you need any additional info? let me know if you need any help.

I think @pchico83 had some additional context or ideas about this, if I am not mistaken.

**Comment by andreafalzetti** [comment]
@enraiha0307 after discussing directly with @pchico83, we agreed not to prioritize this task for now, mainly because it's a large chunk of work and could possibly lead to regressions. I will not close the issue right now, as in the future we might look at this!

**Comment by enraiha0307** [comment]
No worries, Thanks for the update 👍

**Comment by jLopezbarb** [comment]
@andreafalzetti I think the code used by docker is [this repo](https://github.com/compose-spec/compose-go).

**Comment by andreafalzetti** [comment]
Thanks @jLopezbarb, I've updated the description
