### ISSUE TITLE
Remove okteto stack command

### ISSUE THREAD

**Issue by maroshii** [okteto/okteto#3717]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-Epic-2-Default-to-remote-and-remove-deprecated-features-64f818252e6944d88186f7572e4e1294?pvs=4)

## Description

This command is deprecated and will be removed from the okteto backend chart version 1.10. To complete this issue we must:

- Remove root main cmd
- Remove okteto stack dead code references across the code ([utils created for them specifically](https://github.com/okteto/okteto/blob/master/cmd/utils/stack.go))
- Remove e2e tests asociated with the command
- Remove GH actions ([deploy-stack](https://github.com/okteto/deploy-stack) and [destroy-stack](https://github.com/okteto/destroy-stack)) auto-update
- Remove GH actions ([deploy-stack](https://github.com/okteto/deploy-stack) and [destroy-stack](https://github.com/okteto/destroy-stack)) from marketplace (repo must exists)
- Remove documentation referring to this command in favour of `okteto deploy`

## Acceptance Criteria

- [ ] Users can no longer run `okteto stack deploy/destroy/list`
- [ ] Removed` okteto deprecated` tests about `okteto stack`
- [ ] GH actions no longer appears on https://github.com/marketplace?type=actions&query=stack+
- [ ] GH actions are not updated after a release

### Test strategy

- [ ] Test that `okteto deploy` using a compose file still works
- [ ] Test that `okteto deploy` using a stack file still works

**Comment by nitishfy** [comment]
I'd like to take this up.

**Comment by nitishfy** [comment]
> @nitishfy this is a breaking change and requires and CLI 3.0 release. The plan is to work on it on Q3 or maybe Q4

I'd like to get involved with it to learn more about how we're managing the breaking changes internally. Is there a way I can contribute here?

**Comment by pchico83** [comment]
@nitishfy we follow semantic versioning. That means breaking changes must be done in a major release, in this case, Okteto CLI 3.0. We plan to release CLI 3.0 before the end of the year. At that moment we will be able to remove this and other commands
