### ISSUE TITLE
Hint to the "Automatic SSL" docs if no endpoints are available

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3719]
**Is your feature request related to a problem? Please describe.**
One of the main friction points when configuring the `deploy` section of the okteto manifest is how to make your application available using public endpoints. There is no guidance on how to do that.

**Describe the solution you'd like**
While we invest on a better solution at the product level, we can add a link to the docs when no endpoints are available for the application. This is [the link](https://www.okteto.com/docs/cloud/ssl/) to the docs, and we should show the link when [no endpoints are available](https://github.com/okteto/okteto/blob/master/cmd/deploy/endpoints.go#L230).

We could show something like:
```
There are no available endpoints for XXX
Follow this link to know more about how to create public endpoints for your application:
https://www.okteto.com/docs/cloud/ssl/
```

**Additional context**
We should update the docs to explain how to create public endpoints using Docker Compose.

**Comment by nitishfy** [comment]
Here's the [PR](https://github.com/okteto/okteto/pull/3722)
