### ISSUE TITLE
If I run a command with a namespace that doesn't exist, I get an 'internal-server-error'

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3720]
<img width="1268" alt="image" src="https://github.com/okteto/okteto/assets/475313/ed37fa3f-e86d-486f-9b5b-749c2541c8d7">

I think it's better if we return an 'namespace doesn't exist' or 'namespace is not managed by Okteto' as the error.

**Comment by MateSousa** [comment]
@pchico83 can i try?

**Comment by MateSousa** [comment]
@rberrelleza @pchico83 can i try?

**Comment by pchico83** [comment]
@MateSousa great, I assigned the issue to you! Let us know if you need more context to start working on it

**Comment by MateSousa** [comment]
@pchico83 thanks, to handle the error is easy but i'm thinking of something like if the namespace doesn't ask to create one?

**Comment by pchico83** [comment]
> @pchico83 thanks, to handle the error is easy but i'm thinking of something like if the namespace doesn't exist ask to create one?

@MateSousa that's what `okteto up` does here:
https://github.com/okteto/okteto/blob/master/cmd/up/up.go#L163

**Comment by MateSousa** [comment]
@pchico83 it seems that there is already a treatment for this in deploy (https://github.com/okteto/okteto/blob/master/cmd/deploy/deploy.go#L164), but it just creates a new namespace if isOkteto is true, as I don't know much about the ecosystem this is a valid behavior, right? If so, then just handling the error so it doesn't return an internal server error would be enough.

**Comment by pchico83** [comment]
> @pchico83 it seems that there is already a treatment for this in deploy (https://github.com/okteto/okteto/blob/master/cmd/deploy/deploy.go#L164), but it just creates a new namespace if isOkteto is true, as I don't know much about the ecosystem this is a valid behavior, right? If so, then just handling the error so it doesn't return an internal server error would be enough.

If the namespace doesn't exist and we are in a cluster where Okteto isn't install, I would return a clear error telling that the namespace doesn't exist

**Comment by nitishfy** [comment]
Hi @pchico83, I'd like to take this up.

**Comment by andreafalzetti** [comment]
This has been fixed with: https://github.com/okteto/okteto/pull/3798

Thanks @nitishfy 🙇

**Comment by andreafalzetti** [comment]
@nitishfy if you see the PR linked (https://github.com/okteto/okteto/pull/3798) the description will explain it :)
