### ISSUE TITLE
`okteto deploy --remote` doesn't mask variables specified with `--var`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3735]
**Describe the bug**
Run `okteto deploy --remote --var TEST=111` with a deploy command `echo $TEST`.
The variable value isn't masked

**Expected behavior**
The variable is masked as any other variable/secret

**Comment by AnshulAngaria** [comment]
@pchico83 I can work on this.

**Comment by pchico83** [comment]
> @pchico83 I can work on this.

@AnshulAngaria I assigned the issue to you. Let us know if you need help with it :-)

**Comment by pchico83** [comment]
I am going to assign this issue to an okteto engineer. We need a fix in the following days and the team told me this issue requires low-level context about `--remote` which is not well documented yet.
Sorry for any inconvenience.
I would propose the following issue instead:
https://github.com/okteto/okteto/issues/3174

**Comment by AnshulAngaria** [comment]
@pchico83 No problem.
