### ISSUE TITLE
"okteto down" does not handle okteto manifest changes

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#374]
**Describe the bug**
I run okteto up with different services. I remove a few services from the manifest. okteto down does not handle this change properly.

**Propose solution**
okteto down cheks dev deployments by querying the okteto dev label

**Comment by rberrelleza** [comment]
I would postpone this, I don't think is that  common of an scenario

**Comment by rberrelleza** [comment]
By design. A manifest change requires down and up. We'll document this behavior.
