### ISSUE TITLE
Catalog name is not recognized on `okteto up`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3748]
**Describe the bug**
When I deploy a catalog item with a `name`, and then run `okteto up`, `okteto up` doesn't recognize the catalog name and I end up with two dev environments:
<img width="350" alt="Screenshot 2023-06-23 at 08 47 13" src="https://github.com/okteto/okteto/assets/7474696/17631dbe-845a-423c-9d49-2402a9f01d7a">

**To Reproduce**

1. Deploy the Catalog item `Oktaco Shop` in demo.okteto.dev
1. Clone https://github.com/okteto/external-resources-tf-aws locally
1. Run `okteto up`

**Expected behavior**
`okteto up` should reuse the `Oktaco Shop` dev environment instead of creating a new one.
One way to detect this is by checking the repo name and okteto manifest path against existing dev environments.

**Comment by jLopezbarb** [comment]
I was able to run okteto up without any problem. @pchico83 did you run `okteto up` with a flag like `--deploy`:


![Image](https://github.com/okteto/okteto/assets/25170843/fad8c0a7-30c1-454f-98bc-7bcbac35b42a)

**Comment by pchico83** [comment]
@jLopezbarb I changed the catalog definition. To repro it, you need to set the okteto path in the catalog definition

**Comment by jLopezbarb** [comment]
> @jLopezbarb I changed the catalog definition. To repro it, you need to set the okteto path in the catalog definition

I could reproduce it with that. Thanks!!

**Comment by jLopezbarb** [comment]
Hi @pchico83, 
I've created this scenario where it's a monorepo with two okteto manifest. Each one deploys one part of the application:
<img width="396" alt="Captura de Pantalla 2023-07-11 a las 18 39 18" src="https://github.com/okteto/okteto/assets/25170843/1107bffd-b4fe-4ead-9f44-4f653c8e0fa8">

If we don't go with the filename approach we should show a selector each time we have this scenario. I also don't know if we should also check with the user if he is trying to deploy something new or use one of the previous one created.

I started developing the first option so the solution should be: If there is just one configmap with the same repository, use that one, if there is more than one we'll ask the user which one to use. Do you think this is the right choice?

**Comment by pchico83** [comment]
> Hi @pchico83, I've created this scenario where it's a monorepo with two okteto manifest. Each one deploys one part of the application: <img alt="Captura de Pantalla 2023-07-11 a las 18 39 18" width="396" src="https://user-images.githubusercontent.com/25170843/252732415-1107bffd-b4fe-4ead-9f44-4f653c8e0fa8.png">
> 
> If we don't go with the filename approach we should show a selector each time we have this scenario. I also don't know if we should also check with the user if he is trying to deploy something new or use one of the previous one created.
> 
> I started developing the first option so the solution should be: If there is just one configmap with the same repository, use that one, if there is more than one we'll ask the user which one to use. Do you think this is the right choice?

I would go with the filename approach. But it should match if `filename` is the same as the default `filename`MEaning that `okteto up` and `okteto up -f okteto.yml` should match
