### ISSUE TITLE
add `--output` flag to `okteto preview list` command

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3772]
**Describe the bug**
```
ok preview list --log-output json
```

```
Name                                        Scope     Sleeping  Labels
test-quickstart                             personal  true      -
msd-pr-20                                   global    true      -
oktaco-pr-3                                 global    true      -
oktaco-pr-4                                 global    true      -
oktaco-pr-6                                 global    true      -
preview-8-update-voting-app-to-version-2-0  global    true      -
```

**Expected behavior**
The output is formated in json

**Comment by pchico83** [comment]
> @pchico83 we have `--output` on other commands to have that. Should we be consistent with it and keep the same approach?

@jLopezbarb makes sense, but we should be backward compatible to avoid breaking changes

**Comment by nitishfy** [comment]
I'll solve this issue, Please assign this to me!

**Comment by pchico83** [comment]
@nitishfy done! Thanks so much for your contributions!

**Comment by nitishfy** [comment]
@pchico83 Thanks for appreciating!

Regarding this issue, Do you have any idea/context of why is this happening?

**Comment by pchico83** [comment]
> @pchico83 Thanks for appreciating!
> 
> Regarding this issue, Do you have any idea/context of why is this happening?

I think @jLopezbarb or @AdrianPedriza have more context about it

**Comment by nitishfy** [comment]
> I think @jLopezbarb or @AdrianPedriza have more context about it

cc @jLopezbarb @AdrianPedriza

**Comment by AdrianPedriza** [comment]
> > I think @jLopezbarb or @AdrianPedriza have more context about it
> 
> cc @jLopezbarb @AdrianPedriza

seems that we are not using `oktetoLog` abstraction to write the output (it use `--log-output` arg [here](https://github.com/okteto/okteto/blob/master/main.go#L106)). That is the reason why we are not using `--log-output` arg. But this use will need also to take into account that to convert the message into json format we will need to set previously a log stage https://github.com/okteto/okteto/blob/master/pkg/log/json.go#L269, if not we will return an empty message. For `okteto ctx show --log-output json` we are displaying an empty output because an stage is not previously set, maybe a bug?   :confused: @jLopezbarb

**Comment by nitishfy** [comment]
The output format being displayed is shown as `json` while using `--log-output json` for okteto `preview list`. However, setting a stage something like `oktetoLog.SetStage(" ")` is not yielding the desired result again. How do we proceed with this?

**Comment by AdrianPedriza** [comment]
> The output format being displayed is shown as `json` while using `--log-output json` for okteto `preview list`. However, setting a stage something like `oktetoLog.SetStage(" ")` is not yielding the desired result again. How do we proceed with this?

I get the same results reported in the issue. Can you show a screenshot and the version you are using?

**Comment by nitishfy** [comment]
> I get the same results reported in the issue. Can you show a screenshot and the version you are using?

![image](https://github.com/okteto/okteto/assets/86051118/477db9d2-d20c-4a73-adb8-7cb426d22f67)

**Comment by jLopezbarb** [comment]
> @pchico83 Thanks for appreciating!
> 
> Regarding this issue, Do you have any idea/context of why is this happening?

What I would do is to create a new `--output` flag with a shortcut `-o`, just like we have for other commands like `[okteto context list](https://github.com/okteto/okteto/blob/master/cmd/context/list.go#L46)` or `[okteto endpoints](https://github.com/okteto/okteto/blob/master/cmd/deploy/endpoints.go#L155)`.

**Comment by nitishfy** [comment]
> What I would do is to create a new `--output` flag with a shortcut `-o`, just like we have for other commands like [okteto context list](https://github.com/okteto/okteto/blob/master/cmd/context/list.go#L46) or [okteto endpoints](https://github.com/okteto/okteto/blob/master/cmd/deploy/endpoints.go#L155)

The description has been changed. I'll raise a PR for this issue soon.

**Comment by AdrianPedriza** [comment]
> > What I would do is to create a new `--output` flag with a shortcut `-o`, just like we have for other commands like [okteto context list](https://github.com/okteto/okteto/blob/master/cmd/context/list.go#L46) or [okteto endpoints](https://github.com/okteto/okteto/blob/master/cmd/deploy/endpoints.go#L155)
> 
> The description has been changed. I'll raise a PR for this issue soon.

I've revert the change in the description. Sorry for the noise. Let's follow what @jLopezbarb said

**Comment by nitishfy** [comment]
How about this one? @AdrianPedriza 
![image](https://github.com/okteto/okteto/assets/86051118/07359744-978c-404a-b224-c907f0b951ca)

**Comment by AdrianPedriza** [comment]
> How about this one? @AdrianPedriza ![image](https://user-images.githubusercontent.com/86051118/251792243-07359744-978c-404a-b224-c907f0b951ca.png)

I expect a list as the first level because we are querying `preview list`. Something like:
````
{
  "previews": {
     "id": "my-preview-id",
     "sleeping": false,
     ....
   }
}
````

**Comment by AdrianPedriza** [comment]
> > How about this one? @AdrianPedriza ![image](https://user-images.githubusercontent.com/86051118/251792243-07359744-978c-404a-b224-c907f0b951ca.png)
> 
> I expect a list as the first level because we are querying `preview list`. Something like:
> 
> ```
> {
>   "previews": [
>      {
>      "id": "my-preview-id",
>      "sleeping": false,
>      ....
>      }
>    ]
> }
> ```

@jLopezbarb if I exec `okteto ctx list -o json` it return a list of jsons instead a json object. It is correct? should we apply same principle here? IMO we should return a json with a field that contains the list

**Comment by pchico83** [comment]
> > @jLopezbarb if I exec `okteto ctx list -o json` it return a list of jsons instead a json object. It is correct? should we apply same principle here? IMO we should return a json with a field that contains the list
> 
> If we follow by that, here's how it looks like: ![image](https://user-images.githubusercontent.com/86051118/251802471-9d638d27-e052-4d64-a314-183e402e0770.png)

@nitishfy Could we get rid of the `null` values? I would show the same fields we show in `okteto preview list`

**Comment by nitishfy** [comment]
> @nitishfy Could we get rid of the `null` values? I would show the same fields we show in `okteto preview list`

Looks good? (added the output for `yaml` as well)
![image](https://github.com/okteto/okteto/assets/86051118/9bf6f168-7198-470d-9650-bc8125307657)

**Comment by AdrianPedriza** [comment]
> > @nitishfy Could we get rid of the `null` values? I would show the same fields we show in `okteto preview list`
> 
> Looks good? (added the output for `yaml` as well) ![image](https://user-images.githubusercontent.com/86051118/251836007-9bf6f168-7198-470d-9650-bc8125307657.png)

json output looks good comparing with what we have for `okteto ctx list -o json` 👍 . About `yaml` option, I would use same format displayed by `ok ctx list -o yaml` : 
`````yaml

- name: <name-a>
  namespace: <namespace-a>
  builder: <buider-name-a>
  registry: <rgistry-name-a>
  current: true
- name: <name-b>
  namespace: <namespace-b>
  builder: <buider-name-b>
  registry: <rgistry-name-b>
  current: true
`````

**Comment by nitishfy** [comment]
I'll do it as well. Do we need to create a separate PR for `yaml` or can we address it in the same PR?

**Comment by AdrianPedriza** [comment]
> I'll do it as well. Do we need to create a separate PR for `yaml` or can we address it in the same PR?

I think we can address it in the same issue since they are both related to adding the output flag to the command

**Comment by nitishfy** [comment]
**Update:** [PR](https://github.com/okteto/okteto/pull/3804) raised!

**Comment by andreafalzetti** [comment]
> **Update:** [PR](https://github.com/okteto/okteto/pull/3804) raised!

Thanks @nitishfy, I've left you some feedback 🙇
