### ISSUE TITLE
`okteto up` get's stuck in hybrid mode

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#3774]
**Describe the bug**
`okteto up` get's stuck when using hybrid mode

**To Reproduce**

1. Clone https://github.com/okteto/movies-with-helm
1. Switch to the `hybrid` branch
1. Run `okteto up`
1. Execution get's stuck

<img width="1137" alt="Screenshot 2023-07-03 at 14 32 18" src="https://github.com/okteto/okteto/assets/7474696/cbc65223-9a36-4ff4-b116-3468673d5e82">

**Expected behavior**
`okteto up` terminates successfully or a proper error is shown

**Additional context**
It could be related to the fact of using init containers in the `api` deployment

**Comment by teresaromero** [comment]
I haven't reproduced the bug as is in the image, but not sure if you refer to "get stuck" when the remote terminal is activated?

```
❯ ok up api
 i  Using xxxxxx @ xxxxxxxx as context
 i  'movies-with-helm' was already deployed. To redeploy run 'okteto deploy' or 'okteto up --deploy'
 i  Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'
 ✓  Images successfully pulled
 ✓  Files synchronized
    Context:   staging.okteto.dev
    Namespace: teresaromero
    Name:      api
    Reverse:   8080 <- 8080


```

i get here but there is no command run, also if i CTRL+C the timeout is triggered and the process does not exit inmediatly

cc @pchico83

**Comment by pchico83** [comment]
> I haven't reproduced the bug as is in the image, but not sure if you refer to "get stuck" when the remote terminal is activated?
> 
> ```
> ❯ ok up api
>  i  Using xxxxxx @ xxxxxxxx as context
>  i  'movies-with-helm' was already deployed. To redeploy run 'okteto deploy' or 'okteto up --deploy'
>  i  Images were already built. To rebuild your images run 'okteto build' or 'okteto deploy --build'
>  ✓  Images successfully pulled
>  ✓  Files synchronized
>     Context:   staging.okteto.dev
>     Namespace: teresaromero
>     Name:      api
>     Reverse:   8080 <- 8080
> ```
> 
> i get here but there is no command run, also if i CTRL+C the timeout is triggered and the process does not exit inmediatly
> 
> cc @pchico83

In my case it was stuck on "activating development container...", let me try to repro.

But yes, command execution is totally broken. That should be the first issue for it, I created this issue:
https://github.com/okteto/okteto/issues/3775

**Comment by teresaromero** [comment]
Closing this issue as is not reproducible anymore in favor of https://github.com/okteto/okteto/issues/3775 which should solve the problem shown above
