### ISSUE TITLE
Remove deprecated code that relied on the backend

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3781]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-Epic-2-Default-to-remote-and-remove-deprecated-features-64f818252e6944d88186f7572e4e1294?pvs=4)

## Description

There are several graphql calls that have been deprecated more than 1 year. We need to remove these dead code lines to keep with a clean project.

The graphql calls are:
- [deprecatedGetUserContext](https://github.com/okteto/okteto/blob/f403244be0812d54a489e8862d910a9d066ae6dc/pkg/okteto/secrets.go#L190)
- [deprecatedAuthUser](https://github.com/okteto/okteto/blob/f403244be0812d54a489e8862d910a9d066ae6dc/pkg/okteto/auth.go#L163)
- [deprecatedDestroy (pipeline)](https://github.com/okteto/okteto/blob/f403244be0812d54a489e8862d910a9d066ae6dc/pkg/okteto/pipeline.go#L279)
- [deprecated okteto down](https://github.com/okteto/okteto/blob/f403244be0812d54a489e8862d910a9d066ae6dc/pkg/k8s/apps/translate.go#L143)

## Acceptance Criteria

- [ ] Remove the code posted above and all the code that depends on it (types, functions, tests...)
- [ ] Check that the `okteto pipeline destroy` keeps working after removing the code
- [ ] Check that `okteto down` is working correctly after removing the code

**Comment by jLopezbarb** [comment]
Reopenning. Need planning for 3.0

**Comment by andreafalzetti** [comment]
Re-opened for 3.0
