### ISSUE TITLE
Remove commands that has been replaced

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3785]
## Parent epic/feature

* Feature: [Okteto CLI 3.0](https://www.notion.so/okteto/Okteto-CLI-3-0-Epic-2-Default-to-remote-and-remove-deprecated-features-64f818252e6944d88186f7572e4e1294?pvs=4)

## Description

The following commands have been dreprecated for a long period of time and should be removedfrom the code. These 3 commands calls the code used in the replaced commands so we shouldn't have any error while removing them:
- `okteto login` -> Replaced by `okteto ctx`
- Remove GH action ([login](https://github.com/okteto/login)) auto-update
- Remove GH action ([login](https://github.com/okteto/login)) from the marketplace
- `okteto update` -> Replaced by `okteto version update`
- `okteto restart` -> Rerun `okteto up ` 

## Acceptance Criteria

- [ ] The replaced commands are not affected by the removal of the code
- [ ] The user no longer can use use the commands above
- [ ] There is no dead code after removing the code
- [ ] GH actions no longer appears on https://github.com/marketplace?type=actions&query=login+
- [ ] GH actions are not updated after a release

### Test strategy

- [ ] Test that the user can't run `okteto login` 
- [ ] Test that the user can't run `okteto update` 
- [ ] Test that the user can't run `okteto restart` 
- [ ] Test that `okteto ctx use` works correctly
- [ ] Test that `okteto version update` works correctly
- [ ] Test that `okteto up` works correctly when using services in dev section

**Comment by nitishfy** [comment]
Can I work on this?

**Comment by jLopezbarb** [comment]
> Can I work on this?

Hi @nitishfy. We are creating all these issues to track what have to be done in order to release Okteto CLI 3.0. All the breaking breaking changes must be done in a major release. We plan to release CLI 3.0 before the end of the year, but right now we won't be actively working on this until we prepare everything. We'll let you know when that moment comes to help to create the new major version
