### ISSUE TITLE
`okteto init` causes panic when no valid manifest is found

### ISSUE THREAD

**Issue by nitishfy** [okteto/okteto#3791]
**Describe the bug**

`okteto init` causes panic when there's no valid manifest file found. However, the default `okteto.yml` file is automatically created with panic being introduced. 

**To Reproduce**

1. Clone the  [movies-with-helm](https://github.com/okteto/movies-with-helm).
2. Run the `ls` command and you'll notice that `okteto.yml` manifest is present
3. Change the `okteto.yml`name  to `demo.yml`. (You can do this using `mv okteto.yml demo.yml`)
4. Run the `okteto init` command. Panic will occur.
5. Run the `ls` command again and you'll notice that in spite of panic, `okteto.yml` file is still created.

**Note:** The next time you'll try doing the above steps again, panic will not occur (why? Because `okteto.yml` is already there). Destroy it using `okteto destroy` and then repeating steps again, you'll notice the panic again.

**Expected behavior**
The manifest should be created without any panic.

**Additional context**
![Screenshot from 2023-07-04 22-22-39](https://github.com/okteto/okteto/assets/86051118/324602f3-e33d-4fbe-9de2-f1c62bf50e62)

**Comment by nitishfy** [comment]
cc @pchico83

**Comment by pchico83** [comment]
@nitishfy do you have an idea of where the issue is? this looks like a very bad bug
