### ISSUE TITLE
okteto down (and up) should automatically select the service when there is only one

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/okteto#3801]
When there is only one service present, I don't think there is any value in asking the user to select it. We should automatically select it for them and run the command they requested. 

![image](https://github.com/okteto/okteto/assets/56963264/b4f70d68-6009-4819-ac11-78ac3042d4f7)

**Comment by SD-13** [comment]
@RinkiyaKeDad Can I work on this?

**Comment by jLopezbarb** [comment]
> @RinkiyaKeDad I want to work on this, please assign it to me. Thanks,

@SD-13 Sure. I've assigned it to you. Let us know if you need more context or help and we'll be glad to help you resolving the issue 😃

**Comment by RinkiyaKeDad** [comment]
Hey @SD-13! Are you still working on this?

**Comment by SD-13** [comment]
@RinkiyaKeDad Sorry for the delay. I just started working on it
