### ISSUE TITLE
Refactor Hybrid executor to avoid enforcing a shell

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3816]
## Description

Similarly to the deploy executor, the hybrid one should not enforce a shell but we detect the user shell and use that one (eg. Powershell, Bash, etc)

## Context

Currently we enforce `bash`

**Comment by rlamana** [comment]
@andreafalzetti was this a blocker for hybrid?

**Comment by rlamana** [comment]
Perfect, I'll link to the card here for context: https://www.notion.so/okteto/Remove-BASH-as-a-Dependency-b7eee2537d8a4cd4b85f4db6dba124b0

**Comment by andreafalzetti** [comment]
Issue migrated to [JIRA](https://okteto.atlassian.net/browse/LAKE-112)
