### ISSUE TITLE
`okteto deploy` panics on Windows powershell

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3820]
**Describe the bug**
When running `okteto deploy` agianst the [movies](https://github.com/okteto/movies) example, in native Windows 10 powershell, it doesn't work and it panics. It doens't happen if you run it from `Git Bash` or wSL

**To Reproduce**

1. Using Windows 10 and powershell
1. Run `okteto deploy` in [movies](https://github.com/okteto/movies)

**Expected behavior**
The command should work successfully

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10
<img width="1023" alt="Screenshot 2023-07-13 at 15 16 23" src="https://github.com/okteto/okteto/assets/2318450/259d689f-5d6f-4893-af2b-a37bf2ce72dd">

**Comment by AdrianPedriza** [comment]
I cannot repro it with the current master version. Can you?

**Comment by andreafalzetti** [comment]
We discussed that it depends if the user has `bash` so we'll move it back to To Do until we decide further, @teresaromero has a fix that can be added in the meantime in the comments

**Comment by teresaromero** [comment]
This is the fix i've done on my local no bash environment to make it work 

https://github.com/okteto/okteto/commit/6dcb4a336846735fdcd292bd7183c5f303be9154

always running `okteto deploy --no-bash`

**Comment by teresaromero** [comment]
closing in favor of #3854
