### ISSUE TITLE
Using context message is not shown on okteto build

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3823]
**Describe the bug**
When I run `okteto build` I don't get the message `Using namespace @ cluster as context`. This makes me check which context I was pointing to know where I've built the images

**To Reproduce**

1. Copy the following `Dockerfile`:
```Dockerfile
FROM alpine

RUN echo hello world
```
2. Run `okteto build`
3. See that the message is missing

**Expected behavior**
I want to have the using context message at the beggning

**Comment by nitishfy** [comment]
when we're loading the context, we can set the value of _show_ to True. WDYT?
