### ISSUE TITLE
[CLI Quality][CI] Trigger e2e test from a PR

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#3826]
This is part of the CLI Quality initiative.

Currently the workflow to trigger e2e test is triggered when a PR is merged to master. In order to trigger this kind of test on a single PR prior to merge, the branch should be rename to end in e2e or win, depending the platform we want to use for this test.

In order to avoid the creation of branches and be able to develop and trigger the workflow for e2e tests, we want to implement a trigger from the PR that on every change of that branch will trigger the e2e for the platform selected.

Examples of implementation:
- label at the PR
- checkbox active at the PR description
- comment at the PR enabling integration

**Comment by AdrianPedriza** [comment]
following the description it is not clear to me what should be the definitive method for triggering the e2e tests. Using labels? What format should these labels have? As for `checkbox active at the PR description` and `comment at the PR enabling integration` I am not clear what they mean. Can you define it in the issue description? 🙏
