### ISSUE TITLE
I got '%!s(MISSING)' in a warning while deploying a compose in vanilla cluster

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3827]
**Describe the bug**
I was redeploying a docker compose on a vanilla cluster and got the following `WARNING`:
`skipping deploy of movies due to name collision: the ingress '%!s(MISSING)' was running before deploying your compose`

It sbuold show the name of the ingress instead of `%!s(MISSING)`

**To Reproduce**

1. Deploy https://github.com/okteto/movies-with-compose on a vanilla cluster
1. Redeploy the repository
1. See error

**Expected behavior**
It should show the name of the ingress

**Comment by AnshulAngaria** [comment]
@jLopezbarb I can take this up.

**Comment by jLopezbarb** [comment]
@AnshulAngaria  Sure,  let me know if you have any doubt and we'll provide you some tips
