### ISSUE TITLE
[CLI Quality][CI] Implement basic `golang-ci` linters

### ISSUE THREAD

**Issue by teresaromero** [okteto/okteto#3828]
As part of the CLI Quality initiative, `golang-ci` is being implemented as a local and remote workflow.

This first issue will implement the basics for the lint tool and as part of it a refinement has to be made in order to fix the possible ignored rules that appear from this implementation.

## Acceptance criteria

- [x] `golang-ci` is run locally, the same config is run for every PR and when integration on master
- [ ] `golang-ci` config rules are the default ones
  - [x] errcheck
  - [x] gosimple
  - [ ] govet
  - [ ] ineffassign
  - [ ] staticcheck
  - [ ] typecheck
  - [ ] unused
- [ ] update the linters research to decide which rules are we applying
- [ ] code failures because of this rules have to be ignored, and an issue has to be created and described its priority to be solved in next sprint

**Comment by jLopezbarb** [comment]
Expanding  `golang-ci config rules are the default ones` because I'll create a PR for each of the default rules:

- [ ] errcheck
- [ ] gosimple
- [ ] govet
- [ ] ineffassign
- [ ] staticcheck
- [ ] typecheck
- [ ] unused
