### ISSUE TITLE
okteto cli logs are not properly displayed in windows powershell

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/okteto#3842]
**Describe the bug**
executing an okteto command in windows powershell doesn't display the output color properly. Instead, it prints some kind of format code related to the log displayed.

**To Reproduce**

1. Exec `okteto deploy` on windows powershell
2. Check the output:

![Captura de Pantalla 2023-07-20 a las 19 34 51](https://github.com/okteto/okteto/assets/22500940/a4acca9a-b9c7-4b28-a342-a81a4a61a810)
**Expected behavior**
Color should be displayed when exec every command

**Desktop (please complete the following information):**

- OS: windows
- Version Okteto CLI master version

**Comment by jLopezbarb** [comment]
Closing since it's duplicated of https://github.com/okteto/okteto/issues/3821
