### ISSUE TITLE
Dependency update request: `mixpanel/mixpanel-go`

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3847]
# Dependency Update Request

We should update from https://github.com/dukex/mixpanel to the [official mixpanel library](https://github.com/mixpanel/mixpanel-go). The current dependency that we are using has not been updated for a year.

**Current Dependency: https://github.com/dukex/mixpanel**

**Official Library: https://github.com/mixpanel/mixpanel-go**

## Reason for Update:

- Ability to add a context with timeout to the request. We shouldn't be stuck on sending metrics for too long since it's a bad experience
- The dependency used doesn't have the latest updates 
- It's more secure to depend on the official library
- We'll be getting the latest updates
- The official release code has unit test which makes it more stable

## Steps to Update:

1. Remove [github.com/dukex/mixpanel](https://github.com/dukex/mixpanel) from `go.mod` and replace it with [github.com/mixpanel/mixpanel-go](https://github.com/mixpanel/mixpanel-go).
2. Update the `analytics` package to use the new module

## Testing Plan:

- Create unit test for each of the events we send 
- Check that the events are being sent after the upgrade

## Potential Risks:

- Affects all the commands tracking system

**Comment by andreafalzetti** [comment]
I think it would be helpful to introduce an interface to track events and the library is one implementation. This will allow moving to a different analytics tool or library very easily in the future. @jLopezbarb wdyt?
