### ISSUE TITLE
Panic when `bash` is not installed

### ISSUE THREAD

**Issue by rlamana** [okteto/okteto#3854]
**Describe the bug**
Right now `bash` is a hard dependency in the CLI and if it is not install it results in a **panic**. This happen in any platform, Windows, Linux and Mac.

**Expected behavior**
Until we decouple `bash`, the CLI should gracefully exit and inform users that `bash` is a dependency and should be installed.

**Comment by teresaromero** [comment]
Linking this comment for context https://github.com/okteto/okteto/issues/3820#issuecomment-1647870016
