### ISSUE TITLE
support deleteing multiple contexts at once

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/okteto#3857]
**Is your feature request related to a problem? Please describe.**
Right now you can't delete multiple contexts at once when running `okteto ctx delete`

**Describe the solution you'd like**
Being able to delete multiple contexts using `okteto ctx delete ctx1 ctx2 ctx3`

**Additional context**
![Screenshot 2023-07-28 at 1 35 46 PM](https://github.com/okteto/okteto/assets/56963264/ee4bf5a7-cc2e-4c45-b251-53c4e596f6b3)

**Comment by RinkiyaKeDad** [comment]
Could be a good first issue for new contributors

**Comment by jLopezbarb** [comment]
> Could be a good first issue for new contributors

Sure, let's add the labels `help-wanted` and `good-first-issue`

It'll also be good to track if more than one context is deleted using the command, that way we know how people are using the CLI

**Comment by jLopezbarb** [comment]
Hi @jeremyphua. I've assigned the issue to you. Let us know if you face any issue or need any help to close the issue

**Comment by RinkiyaKeDad** [comment]
Hey @jeremyphua! 👋 Are you still working on this?

**Comment by jeremyphua** [comment]
Hi @RinkiyaKeDad! I think the PR is done and is pending to be merged.
