### ISSUE TITLE
"okteto deploy -f non-existing.yaml" doesnt fail instead it searches for okteto.yaml

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3869]
**Describe the bug**
When running "okteto deploy -f non-existing.yaml" the command doesn't fail. Instead, of `non-existing.yaml` doesn't exist, it runs `okteto deploy` with `okteto.yaml`.

**To Reproduce**

1. On a repo with an `okteto.yaml` run `okteto deploy -f foo.yaml`

**Expected behavior**
Command should wail with `non-existing.yaml file doesn't exist`

**Desktop (please complete the following information):**

- Version 2.18.0

**Comment by nitishfy** [comment]
I'd like to take this up

**Comment by jLopezbarb** [comment]
Hi @nitishfy, I've assigned the issue to you. Let us know if you have any doubt while implementing this one

**Comment by nitishfy** [comment]
hey @jLopezbarb , the issue has not been assigned yet. I've started working on this and maybe a little late to raise the PR because of preparation for LFX period.

**Comment by jLopezbarb** [comment]
Nice catch, I though I assigned it to you but it seems I didn't. Now it's fixed!! Sorry

**Comment by nitishfy** [comment]
Hi @jLopezbarb, could you provide some context on this issue on what might be the possible cause for this error? I'll figure the rest of the stuff once I get some more context over the code.

**Comment by nitishfy** [comment]
**Update:** PR raised!

**Comment by andreafalzetti** [comment]
If we change `deploy` we should do the same for `destroy` and `endpoints` because they have the same logic, and it would be inconsistent. 

When this PR is merged let's raise the other two issues.
