### ISSUE TITLE
okteto destroy gets an error if namespace is already deleted

### ISSUE THREAD

**Issue by phoenix-bjoern** [okteto/okteto#3881]
In the Okteto manifest we've configured a command to remove the entire namespace on destroy:

```
destroy:
  - name: Delete namespace
    command: kubectl delete namespace ${NAMESPACE}
```

Okteto then tries to remove its resources but could run into permission issues:

```
Configmaps "okteto-git-app" is forbidden: User "u-xyz" cannot get resource "configmaps" in API group "" in the namespace "okteto-test-app"
```

What is interesting is that this error only occurs for users with restricted access. Admins usually don't see this error.

Either those errors should be handled in a more relaxed way (= simple ignore errors if the resource is already gone) or the destroy method has to check more carefully whether the resources still exist.

**Comment by jLopezbarb** [comment]
Hi @phoenix-bjoern, Have you tried using `okteto namespace delete`? 

[okteto namespace delete](https://www.okteto.com/docs/reference/cli/#delete-1) provides a safe way for a user to remove completely a namespace he is owner of without having access to another cluster member namespace.

**Comment by phoenix-bjoern** [comment]
@jLopezbarb Sure: "This command is only available in clusters where Okteto is installed."
But maybe it a good enhancement to make it configurable in the destroy section to also remove the entire namespace. That way it is not necessary to have a separate command and delete the namespace either via Okteto (server) or "kubectl delete ns" like we do.

**Comment by phoenix-bjoern** [comment]
Issue is still there.

**Comment by jLopezbarb** [comment]
Hi @phoenix-bjoern, We didn't have enough capacity to tackle this, but we'll try to address it during the following weeks

**Comment by phoenix-bjoern** [comment]
@jLopezbarb can you add a flag to this issue to prevent automatic closing?
