### ISSUE TITLE
okteto displays the  "insecure mode" message twice

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#3894]
**Describe the bug**
```
 okteto context use https://okteto.131-153-227-138.nip.io --token ac90c872 --insecure-skip-tls-verify
 !  Insecure mode enabled
 !  Insecure mode enabled
 ✓  Context 'okteto.131-153-227-138.nip.io' created
 ✓  Using okteto-admin @ okteto.131-153-227-138.nip.io
```

**To Reproduce**

1. Run ` okteto context use https://DOMAIN  --insecure-skip-tls-verify` on a okteto cluster with a self-signed certificate

**Expected behavior**
We should only display ` !  Insecure mode enabled` once. 

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.18.2

**Comment by ifbyol** [comment]
I will close it as we already have a ticket for it: https://github.com/okteto/okteto/issues/3885. I'll close it as duplicated
