### ISSUE TITLE
Display a friendly error when the local proxy cannot start 

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3916]
**Describe the bug**
When I execute `okteto deploy` or `okteto destroy` and the local proxy cannot start because there is no available port or because `localhost` cannot be resolved I would like to have a friendly error and possible actions. For example, review `/etc/hosts` to verify there is an entry for `localhost`

**To Reproduce**

1. Modify your `/etc/hosts` file and comment any rule referring to `localhost`
2. Deploy a manifest that talks to Kubernetes, for example, in the deploy section add a command to list pods `kubectl get pods`
3. You will get a `no such host` error

**Expected behavior**
I should get a message in the CLI with some hint about it. Review you /etc/hosts configuration to make sure that there is an entry for `localhost`

**Desktop (please complete the following information):**

- Version: 2.19

**Additional context**
It is really hard for the user to troubleshoot the problem without a hint. The proxy we use should be transparent for them.

**Comment by rlamana** [comment]
Migrated to JIRA: https://okteto.atlassian.net/browse/LAKE-16
