### ISSUE TITLE
[Pull First Approach] Build always to global and `okteto.dev`

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3922]
**Is your feature request related to a problem? Please describe.**
When I run `okteto deploy --build` + `okteto up` I might have different images.

1. Clone [movies with helm](https://github.com/okteto/movies-with-helm)
2. Modify `frontend/src/index.html`:
```diff
diff --git a/frontend/src/index.html b/frontend/src/index.html
index 91d047a..366c9f3 100644
--- a/frontend/src/index.html
+++ b/frontend/src/index.html
@@ -1,7 +1,7 @@
 <!DOCTYPE html>
 <html>
   <head>
-    <title>Movies</title>
+    <title>Movies test</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
   </head>
```
3. Run `okteto deploy --build`
4. Check that we have the latest changes:
<img width="133" alt="Captura de pantalla 2023-08-18 a las 14 11 50" src="https://github.com/okteto/okteto/assets/25170843/e7ae22c8-cfa2-4415-ae91-c0fb5c912328">

5.  Modify `frontend/src/index.html`:
```diff
diff --git a/frontend/src/index.html b/frontend/src/index.html
index 91d047a..5369868 100644
--- a/frontend/src/index.html
+++ b/frontend/src/index.html
@@ -1,7 +1,7 @@
 <!DOCTYPE html>
 <html>
   <head>
-    <title>Movies</title>
+    <title>Movies with okteto</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
   </head>
```
6. Run `git add . && git commit -m "test"`
7. Run `okteto deploy --build`
8. Modify `frontend/src/index.html`:
```diff
diff --git a/frontend/src/index.html b/frontend/src/index.html
index 91d047a..5369868 100644
--- a/frontend/src/index.html
+++ b/frontend/src/index.html
@@ -1,7 +1,7 @@
 <!DOCTYPE html>
 <html>
   <head>
-    <title>Movies with okteto</title>
+    <title>Movies with okteto global</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
   </head>
```
9. Run `okteto deploy`
10. Check that the changes that we have is the one generated in `step 3`

**Describe the solution you'd like**
It should point to the latest image built. In this case the one in `step 7`. We should be pushing both tags when building with buildkit, to `okteto.global/image:hash` and `okteto.dev/image:okteto`. This will ensure that everyone uses the latest images

**Additional context**
We'll need to change our Build command to support a list of tags instead of a single tag.

**Comment by teresaromero** [comment]
Regarding the acceptance criteria of this issue i have couple of questions:

> Describe the solution you'd like
> It should point to the latest image built. In this case the one in step 7. We should be pushing both tags when building with buildkit, to okteto.global/image:hash and okteto.dev/image:okteto. This will ensure that everyone uses the latest images

+ When builder is Buildkit 
+ When image tag is okteto.dev/image:okteto (tagged by user via -t flag, or using the build.image field at the manifest, or leaving this empty so we infer it)
= We should push both okteto.dev/image:okteto and okteto.global/image:hash to both registries


? the hash is the SHA of the image? or is the hash of aguments?

> Additional context
> We'll need to change our Build command to support a list of tags instead of a single tag.
- 

I think this should be a separate PR enabling the build option `Tag` to be `[]string` instead of `string`

**Comment by teresaromero** [comment]
> ~When image tag is okteto.dev/image:okteto (tagged by user via -t flag, or using the build.image field at the manifest, or leaving this empty so we infer it)~~

Talked offline:
When we are pushing to global, we should push to dev also
