### ISSUE TITLE
Add an indicator on `okteto up` to show which services are already running on dev mode

### ISSUE THREAD

**Issue by omnomagonz** [okteto/okteto#3934]
**Is your feature request related to a problem? Please describe.**
When running `okteto up` and being presented with the list of services to run, there's currently no indicator which service(s) are already running in dev mode. This creates situations where someone could attempt to launch the same service that's already running resulting in errors and a degraded UX on the CLI.

**Describe the solution you'd like**
Add a simple indicator (e.g. an arrow `>`) to the service selection options in CLI after running `okteto up`

**Describe alternatives you've considered**
We could also consider highlighting services that are already running in a different color but this feels less intuitive.

We could also consider adding `(running)` to services that are already running, which could be more explicit and clear.

**Additional context**

**Comment by andreafalzetti** [comment]
@omnomagonz this issue is gone stale, if you want to push forward this proposal, please create a ticket in JIRA
