### ISSUE TITLE
Remove `token` from `okteto context show` by default

### ISSUE THREAD

**Issue by omnomagonz** [okteto/okteto#3935]
**Is your feature request related to a problem? Please describe.**
When executing the `okteto context show` command the object returns the `token` value, which is not best practice for security.

**Describe the solution you'd like**
We should remove the `token` value by default from this object.

We should also consider adding an option `--include-token` to the `okteto context show` command to optionally include that token in scenarios where it's useful. This way the disclosure of the `token` value can be better controlled/managed.

**Describe alternatives you've considered**

**Additional context**

**Comment by nitishfy** [comment]
I'd like to take this up!

**Comment by omnomagonz** [comment]
@nitishfy Feel free to pick this up if you'd like 🙂

**Comment by nitishfy** [comment]
Should we try adding a new env using `os.Getenv`?

**Comment by omnomagonz** [comment]
@pchico83 WDYT?

**Comment by pchico83** [comment]
> Should we try adding a new env using `os.Getenv`?

@nitishfy what do you mean?

**Comment by nitishfy** [comment]
> @nitishfy what do you mean?

we need to hide the token information here. I was thinking of creating an environment variable to store the token value. What do you think on how should we solve this issue in other way?

**Comment by pchico83** [comment]
@nitishfy `okteto ctx show` shouldn't show an entry for the `token` field. And maybe a tip about `--include-token` in case the user wants to see the token.

**Comment by nitishfy** [comment]
> @nitishfy okteto ctx show shouldn't show an entry for the token field. And maybe a tip about --include-token in case the user wants to see the token.

Oh, I thought we were supposed to show the Token field in the command `okteto ctx show` but hide the actual value of the token.

**Comment by omnomagonz** [comment]
@nitishfy that's probably my fault in how I wrote the issue. When I say "remove the `token` value" I mean to remove the key:value pair entirely from the object that's returned, not keep the `token` key and obfuscate the actual `token` value 😅 

So today the object looks like this when running `okteto context show`:

```
{
  "name": "https://cloud.okteto.com",
  "id": "abc123-cd12-ef34-abc123",
  "username": "omnomagonz",
  "token": "my_exposed_token_value",
  "namespace": "omnomagonz",
  "builder": "tcp://buildkit.cloud.okteto.net:443",
  "registry": "registry.cloud.okteto.net",
  "personalNamespace": "omnomagonz",
  "isOkteto": true
}
```

We want it to default show like this (`token` key:value removed):

```
{
  "name": "https://cloud.okteto.com",
  "id": "abc123-cd12-ef34-abc123",
  "username": "omnomagonz",
  "namespace": "omnomagonz",
  "builder": "tcp://buildkit.cloud.okteto.net:443",
  "registry": "registry.cloud.okteto.net",
  "personalNamespace": "omnomagonz",
  "isOkteto": true
}
```

And Pablo's suggestion is to also include a tip when running this command akin to:

> You can use `--include-token` in this command to retrieve your token value

Rough copy idea but that's the gist 😄

**Comment by nitishfy** [comment]
> @nitishfy `okteto ctx show` shouldn't show an entry for the `token` field. And maybe a tip about `--include-token` in case the user wants to see the token.

How do we remove some specific values here? 

I thought of creating a map that will contain the new data without any token field. When we use the flag as mentioned, we can explicitly mention the token field there. Curious to know how are we removing some specific values from context store to display it to the user.

cc: @pchico83 @jLopezbarb
