### ISSUE TITLE
Enable alternative OKTETO_INSTALLATION_PATH for install/upgrade script

### ISSUE THREAD

**Issue by viddo** [okteto/okteto#3963]
**Is your feature request related to a problem? Please describe.**
I'd like to install multiple versions of `okteto` and be able to choose _where_ the binary is written.
Primary use-case is for confirming bug before writing up a report, specifically to ease comparing behavior between a _stable_ / _beta_ version.

**Describe the solution you'd like**

Hypothetical, proposed happy-path:

```shell
curl https://get.okteto.com -sSfL | OKTETO_CHANNEL=beta OKTETO_INSTALLATION_PATH=/tmp/okteto-beta sh
> Using Release Channel: beta
> Using Version: 2.20.0-beta.1
> Using custom installation path: /tmp/okteto-beta
> Downloading https://downloads.okteto.com/cli/beta/2.20.0-beta.1/okteto-Darwin-arm64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.2M  100 76.2M    0     0  28.6M      0  0:00:02  0:00:02 --:--:-- 28.7M
> Installing /tmp/okteto-beta
Password:
> Okteto successfully installed!
```

**Describe alternatives you've considered**

I'm aware that I can _manually_ download a release from Github's release page, e.g. https://github.com/okteto/okteto/releases/tag/2.20.0-beta.1 but I find it clunky when there already exist a script

**Additional context**

- I believe it should suffice to modify [scripts/get-okteto.sh](https://github.com/okteto/okteto/blob/8e82c7788afcd5d1a3a758bb47b3ebb822573db4/scripts/get-okteto.sh)?
- Suggested behavior:
  - `OKTETO_INSTALLATION_PATH` is _optional_
  - `OKTETO_INSTALLATION_PATH` requires a _full path_ to binary if it's defined. E.g. `/tmp` would not be accepted and fail early
  - Set path is created if it does not exist, and fail early indicating what is wrong, e.g. lacking permission to create directory, …

**Comment by ifbyol** [comment]
When triaging/working on this, be aware of the implications of this and the dynamic Kubetoken feature. If the CLI is not installed in the PATH, it won't be used for the Kubeconfig generated by Okteto.

**Comment by andreafalzetti** [comment]
Issue moved to JIRA: https://okteto.atlassian.net/browse/LAKE-110

**Comment by viddo** [comment]
FWIW, found workaround in case someone is interested in this for whatever reason, it's enough to make a shell script to get a hold of older versions by steps outlined in release → installation methods https://github.com/okteto/okteto/blob/eab2d4914fc3628455639bed71a0182cc8438477/docs/RELEASE.md?plain=1#L43-L62
