### ISSUE TITLE
Add support for error hints in `okteto build`

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3996]
We can make the DevX better if we include error hints for errors such as `Error building service 'hello-world': secret should have an id`.

The `okteto build` command currently does not output `Hint` from `oktetoErrors.UserError`, as part of this issue we could"

1. add support for `oktetoErrors.UserError` in the [build command](https://github.com/okteto/okteto/blob/master/cmd/build/command.go#L76-L108)
2. add `oktetoErrors.UserError` for the function `parseSecretFromString`

**Comment by rlamana** [comment]
@andreafalzetti do you consider this part of the entire error handling effort (https://www.notion.so/okteto/Error-Handling-and-Guidance-49d665c233334e9bbf2e8610270ead6b)? Should we add it to the list there and prioritize as part of the effort or is there another reason why you included it in the "Priority" column that I should be aware of?
