### ISSUE TITLE
More information on the sync status

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#423]
**Is your feature request related to a problem? Please describe.**
It's hard to tell if a file has been synchronized or not. I end up having to check the timestamp or the file, or just `cat` the content when I'm not sure if a change has been applied or not. It would be useful to see what was synched, when, and if something went wrong without going to the logs.

**Comment by rlamana** [comment]
Maybe we could add some sort of `status` command to output a diff of the local and remote directories and the current synchronization status.

It could be interesting not only for the case you described but also for other software to consume. For example, our VSCode plugin could use this output to visually mark those files still being synched in the file explorer.

**Comment by pchico83** [comment]
@rlamana what about showing something in the okteto terminal?
We could have a bash plugin or something that shows the status all the time

**Comment by pchico83** [comment]
Closed by #713
