### ISSUE TITLE
Linux ARM64 binary

### ISSUE THREAD

**Issue by tonidy** [okteto/okteto#433]
**Is your feature request related to a problem? Please describe.**
I'm using [userland](https://userland.tech/) in my Android phone. The problem is there is no Linux ARM64 binary to download in [Okteto release page](https://github.com/okteto/okteto/releases). I've tried to build the source but the process is take long time and I stop the build process. So, it's better if I could download okteto binary for ARM64.

**Describe the solution you'd like**
Add Linux ARM64 binary

**Comment by rberrelleza** [comment]
@tonidy thanks for filing the issue. Pretty cool use case. Would you mind beta testing https://s3-us-west-2.amazonaws.com/downloads.okteto.com/cli/master/okteto-Linux-arm ? (we'll include it in the next release, but would be great to get your feedback.

**Comment by tonidy** [comment]
@rberrelleza thanks for implementing arm binary. I've tried to play with okteto arm but i got the following error:

![Screenshot_2019-10-01-18-04-18-433_tech ula](https://user-images.githubusercontent.com/823034/65957247-8b8c1c80-e476-11e9-9ec4-baafa1fd1e56.png)

The first command is okteto from your link. And the second command is my okteto build. My build is using arm64. I think i cannot use arm binary here.

**Comment by tonidy** [comment]
I saw you commit only for linux arm. Could you add also for arm64 ? I think syncthing also supports arm64.

Thanks

**Comment by rberrelleza** [comment]
Ah, thanks for checking @tonidy . I was hoping  userland could run `amd` binaries as well as `amd64` (I tested it on one of the AWS ARM VMs and it worked there). Let me publish the amd64 instead and see if that one works. 

https://s3-us-west-2.amazonaws.com/downloads.okteto.com/cli/master/okteto-Linux-arm64 is an `arm64` build and uses the `arm64` binary, could you give it a try? Delete  `~/.okteto/syncthing` before running the new binary so it downloads the correct syncthing binary.

**Comment by tonidy** [comment]
@rberrelleza OK, I'll try it. Will edit this comment after testing

**Comment by rberrelleza** [comment]
> @rberrelleza OK, I'll try it. Awesome, it's working now 🎉 and I can code while I'm outside 😄 . I'll test it with my mobile network, currently I'm using WIFI connection. I think I should buy surface pro 😃

Nice! Thanks for trying it out. Which binary worked then the `arm64` one? Save some for that sweet Surface Neo 🤑

**Comment by tonidy** [comment]
@rberrelleza yes, the `arm64` binary was working when I tested it. Please release it. Nice one for surface neo 😄

**Comment by pchico83** [comment]
Closes by #434

**Comment by rberrelleza** [comment]
@tonidy https://github.com/okteto/okteto/releases/tag/1.4.8 the arm binary is now available ;)

**Comment by tonidy** [comment]
@rberrelleza awesome 🎉 , thanks for building okteto 👍
