### ISSUE TITLE
Add configurable SSH server key type

### ISSUE THREAD

**Issue by logic01** [okteto/okteto#4399]
**Is your feature request related to a problem? Please describe.**

Okteto generates an RSA key when creating the SSH server for `okteto up`.

https://github.com/okteto/okteto/blob/29b67e00c07a33576f845f212012614c067f6332/pkg/ssh/key.go#L87

Visual Studio 2022 V17.10 no longer supports RSA key for remote debugging.

https://learn.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=msvc-170#set-up-the-remote-connection

> Versions of Visual Studio before 17.10 support EC, RSA, and DSA keys for remote connections. Because of security concerns, RSA and DSA keys are no longer supported in VS 17.10 and later. Only EC keys are currently supported. To create a key pair compatible with the connection manager use the command: ssh-keygen -m pem -t ecdsa -f <key-name>

**Describe the solution you'd like**
The ability to configure what type of SSH key is generated to support backward and forward compatibility.

**Describe alternatives you've considered**
The ability to tell Okteto what key file to use for it's ssh server.

**Comment by codyjlandstrom** [comment]
Thanks for flagging this @logic01 
We have a backlog ticket to address this, but currently no ETA on when we can get to it.
Could you share a bit more information about your VS Code configuration? Is this using Windows?

**Comment by logic01** [comment]
The issue is with Visual Studio 2012 v17.10 attaching to an remote process that runs on an Okteto configured container. Okteto creates an SSH key for that container in the RSA format but Visual Studio no longer supports that format. as per the [documentation ](https://learn.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=msvc-170#set-up-the-remote-connection) I provided. 

![image](https://github.com/user-attachments/assets/a0bf58c5-881f-4323-8dc8-45360d49f7d4)

![image](https://github.com/user-attachments/assets/be96dac6-8e9f-49fb-8767-c9efc469f472)
