### ISSUE TITLE
sample project: coder is not sync update for every locally edit.

### ISSUE THREAD

**Issue by xiaods** [okteto/okteto#488]
**Describe the bug**
coder sample project can't working 

**To Reproduce**
1.  git clone https://github.com/okteto/samples && cd samples/coder
2. okteto up
3. See error
```
xiaods at xiaodeshi in ~/Documents/code/okteto-projects/samples/coder on master*
$ okteto up
 ✓  Persistent volume provisioned
 x  The synchronization service hasn't made any progress in the last 30 seconds
    Help us improve okteto by filing an issue in https://github.com/okteto/okteto/issues/new.
    Please include your syncthing log (/Users/xiaods/.okteto/xiaods/vote/syncthing.log
[syncthing.log](https://github.com/okteto/okteto/files/3726934/syncthing.log)
[syncthing.log](https://github.com/okteto/okteto/files/3726935/syncthing.log)

) if possible.
```

**Expected behavior**
coder project can work.

**Desktop (please complete the following information):**
 - OS: macos
 - Version 10.14

$ okteto version
okteto version 1.4.9 

**Additional context**
[syncthing.log](https://github.com/okteto/okteto/files/3726937/syncthing.log)

**Comment by rberrelleza** [comment]
@xiaods thanks for the information, could you also include your `$HOME/okteto.log` file?

**Comment by xiaods** [comment]
@rberrelleza got it. see attach files.
[okteto.log](https://github.com/okteto/okteto/files/3732153/okteto.log)

**Comment by rberrelleza** [comment]
@xiaods did this happen the first time you did `okteto up` on that folder, or was it after the first time?

**Comment by xiaods** [comment]
@rberrelleza i use cloud.okteto.com.
when i enter to sample project golang: 
```
cd okteto-projects/samples/golang.
okteto up
```
it will active the pod environment and sync files all fine.

then i use local editor to update the main.go's string. i wait some minitues, i have not found the local files to sync to remote pod folder.

**Comment by xiaods** [comment]
hi team, now i have test the situation about the syncing tools, i found the new okteto.log will give some insights.

[okteto.log](https://github.com/okteto/okteto/files/3801739/okteto.log)

please give some help to me. thanks a lot.

```
$ okteto version
okteto version 1.5.2 
```

**Comment by pchico83** [comment]
@xiaods it looks like aa timeout issue connecting to the remote syncthing.
I have increased the timeout, let me know if it fixes the issue:
https://github.com/okteto/okteto/pull/529

**Comment by xiaods** [comment]
@pchico83  i patch your fix and reproduce the go-getting-started project. and i found the good issues  and logs. please see this log and get some insight. the log is here:

```
read: connection reset by peer
```
I feel the network is block by chain region's GFW blocking .
[okteto.log](https://github.com/okteto/okteto/files/3803614/okteto.log)

**Comment by xiaods** [comment]
```
$ okteto version
okteto version 6632724 
```
@pchico83  i edit files locally and they  are not synced at all.
i have to cancel the okteto shell and re-run command: okteto up, then the local files sync to remote folder.

see attached syncthing.log.
[xiaods-hello-world-syncthing.log](https://github.com/okteto/okteto/files/3804312/xiaods-hello-world-syncthing.log)

**Comment by xiaods** [comment]
@rberrelleza hi team, do you have some way or script, let me testing on my environments. i don't think this is okteto's bug, it seem like the syncthing's bug.

**Comment by pchico83** [comment]
@xiaods `okteto up` works on any cluster, it reads your local kubeconfig file.
Is that what you mean?

**Comment by xiaods** [comment]
@pchico83 you mean the okteto can work on my local development cluster,such docker-desktop k8s?  i only testing the feature to cloud.okteto.com .  let me investigate this issue.

**Comment by pchico83** [comment]
@xiaods yes, the okteto cli works on any cluster. If you can run `kubectl` commands, you can run 
 `okteto up`

**Comment by xiaods** [comment]
<img width="1001" alt="屏幕快照 2019-11-08 上午8 30 25" src="https://user-images.githubusercontent.com/37678/68439294-0aa50b00-0202-11ea-81a3-bfdc8bbe760d.png">
@pchico83 it confuse me on your site. the okteto cli can working on-premise kubernetes cluster?

**Comment by pchico83** [comment]
@xiaods yes, we have received the same feedback several times, we are working on a new landing version that makes it clearer.
The Okteto CLI uses your local kubeconfig credentials to work, it can be used in any kubernetes cluster as long as your kubeconfig credentials have deploy access to the cluster.

**Comment by xiaods** [comment]
@pchico83 thanks for your cool tools, i will continue  to fix this sync bug. if the sync bug fix, it rocks my development lifecycle. :-)

**Comment by nicotine5051986** [comment]
💯

**Comment by xiaods** [comment]
@pchico83 hi, please let me explain my retry for the local docker-for-desktop environment.
steps:
1. Use docker desktop for mac to provisioning a kubernetes cluster.
2. brew install okteto.  the version is updated:
```
$ okteto version
okteto version 1.5.8 
```
3. git clone sample repo: go-getting-started project. and okteto up
4. follow the README.md from go-getting-started project. Step 3: Develop directly in Kubernetes.
only the first initialized step is ok, the data folder is syncing. 
5. use my sublime editor to change the local folder's main.go file. and save.
6. go to remote shell. and cancel and return run the main.go.
7. the remote folder is not change and only i cancel the okteto remote shell and re-run okteto up, then the folder sync once again.
8. i have retry many more time for the environment. and send more log to the issue. i don't found some values log to debug the situation.
9. ***i suggest give some syncthing's sync process in the remote shell. it will help me to know the syncthing  is working on it.***

**Comment by pchico83** [comment]
Hi @xiaods 
I have tried `okteto up` with Docker for Desktop and the `go-getting-started` repo and it worked fine :-(. I suggest the following steps:
Run `okteto up --loglevel=info` and you will find a logline similar to this one:
```
INFO[0054] syncthing pid-21742 running on http://localhost:54786 and tcp://localhost:54787 with password 'c9bc52ec-7932-495c-9027-f3a51b317b62' 
```
You can then go to the `http` endpoint (something like http://localhost:54786 but you will have a different port), and login with the user `okteto` and the password shown in your logline.
There you can see the state of syncthing, syncthing errors and more. It could help to find the issue.

**Comment by xiaods** [comment]
<img width="1164" alt="屏幕快照 2019-12-05 下午9 15 20" src="https://user-images.githubusercontent.com/37678/70238517-61bbe280-17a4-11ea-9304-11c4cf180581.png">
@pchico83 thanks for your help. i do the step with your information. but i found i curious case:
in local folder, even i add anything to the local folder, the syncthing page show the status always is "up to date".
```
$ okteto up --loglevel=info                                                                                                           [32/1652]
INFO[0001] current: 1.3.0, expected: 1.3.0              
Deployment go-getting-started doesn't exist in namespace default. Do you want to create a new one? [y/n]: y
⠋ Activating your development environment... INFO[0006] create deployment secrets                                                      
⠙ Activating your development environment... INFO[0006] created okteto secret 'okteto-go-getting-started'. 
INFO[0006] creating service 'go-getting-started'...            
⠹ Activating your development environment... INFO[0006] created service 'go-getting-started'.          
INFO[0006] deployment go-getting-started with revision 1 is progressing  
INFO[0006] replicaset go-getting-started-5d9fb44db6 with revison 1 is progressing                
INFO[0006] replicaset go-getting-started-5d9fb44db6 with revison 1 is progressing      
⠸ Activating your development environment... INFO[0006] pod go-getting-started-5d9fb44db6-6bsbx updated 
INFO[0006] pod go-getting-started-5d9fb44db6-6bsbx event: Successfully assigned default/go-getting-started-5d9fb44db6-6bsbx to docker-desktop 
INFO[0006] pod go-getting-started-5d9fb44db6-6bsbx updated 
⠧ Attaching persistent volume... INFO[0008] pod go-getting-started-5d9fb44db6-6bsbx event: Container image "okteto/bin:1.0.6" already present o
n machine                                                              
⠇ Attaching persistent volume... INFO[0008] pod go-getting-started-5d9fb44db6-6bsbx event: Created container okteto-bin 
⠋ Attaching persistent volume... INFO[0008] pod go-getting-started-5d9fb44db6-6bsbx event: Started container okteto-bin 
⠙ Attaching persistent volume... INFO[0009] pod go-getting-started-5d9fb44db6-6bsbx event: Container image "docker.io/istio/proxyv2:1.4.0" alre
ady present on machine                                                 
INFO[0009] pod go-getting-started-5d9fb44db6-6bsbx updated 
INFO[0009] pod go-getting-started-5d9fb44db6-6bsbx event: Created container istio-init 
⠸ Attaching persistent volume... INFO[0009] pod go-getting-started-5d9fb44db6-6bsbx event: Started container istio-init 
⠙ Attaching persistent volume... INFO[0010] pod go-getting-started-5d9fb44db6-6bsbx event: Pulling image "okteto/golang:1" 
INFO[0010] pod go-getting-started-5d9fb44db6-6bsbx updated 
⠙ Pulling image "okteto/golang:1"... INFO[0013] pod go-getting-started-5d9fb44db6-6bsbx event: Successfully pulled image "okteto/golang:1" 
⠹ Pulling image "okteto/golang:1"... INFO[0013] pod go-getting-started-5d9fb44db6-6bsbx event: Created container dev 
⠼ Pulling image "okteto/golang:1"... INFO[0013] pod go-getting-started-5d9fb44db6-6bsbx event: Started container dev 
⠴ Pulling image "okteto/golang:1"... INFO[0013] pod go-getting-started-5d9fb44db6-6bsbx event: Container image "docker.io/istio/proxyv2:1.4.0" 
already present on machine 
INFO[0014] pod go-getting-started-5d9fb44db6-6bsbx event: Created container istio-proxy 
⠇ Pulling image "okteto/golang:1"... INFO[0014] pod go-getting-started-5d9fb44db6-6bsbx event: Started container istio-proxy 
⠦ Pulling image "okteto/golang:1"... INFO[0015] pod go-getting-started-5d9fb44db6-6bsbx updated 
INFO[0015] forwarding: [8080:8080 2345:2345 59855:22000 59856:8384]                                                                            
INFO[0015] Development environment activated            
 ✓  Development environment activated
⠋ Starting the file synchronization service... INFO[0015] syncthing pid-21822 running on http://localhost:59857 and tcp://localhost:59858 with 
password '6642e078-98e0-4f7f-af23-7ba5418e56bc' 
INFO[0015] waiting for syncthing to be ready...         
⠦ Starting the file synchronization service... INFO[0015] first session to the remote container: command terminated with exit code 137 
⠧ Starting the file synchronization service... INFO[0017] waiting for syncthing to be ready...         
INFO[0017] Sending '.stignore' file to the remote container... 
⠇ Starting the file synchronization service... INFO[0017] waiting for initial scan to complete...      
INFO[0017] waiting for synchronization to complete...   
⠼ Synchronizing your files... INFO[0017] syncthing folder is 100.00%, needBytes 0, needDeletes 0 
⠏ Synchronizing your files... INFO[0019] restarting synchting...                       
INFO[0019] Files synchronized                            
 ✓  Files synchronized
INFO[0019]     Namespace: default               
    Namespace: default
INFO[0019]     Name:      go-getting-started   
    Name:      go-getting-started
INFO[0019]     Forward:   8080 -> 8080         
    Forward:   8080 -> 8080
INFO[0019]                2345 -> 2345                  
               2345 -> 2345

INFO[0019] starting remote command                       
Welcome to your development environment. Happy coding!
okteto> ls
Dockerfile  LICENSE  Makefile  README.md  go.mod  k8s.yml  main.go  okteto.yml
okteto> ls
Dockerfile  LICENSE  Makefile  README.md  go.mod  k8s.yml  main.go  okteto.yml
okteto> ll
```

**Comment by xiaods** [comment]
@rberrelleza @pchico83 hi,team
today i use my rest time to deal the bug. i found the sync halting is caused by Syncthing.

when i browser the Syncthing status page, i found the sync working only first time. when i modify the file, the sync not working. if i force click "[Rescan]" button, it will do a sync working and everything will sync done.

**Comment by pchico83** [comment]
@xiaods are you in MacOS? Could you attach the `$HOME/.okteto/*-syncthing.log` file?
Looks like the local file watcher is not detecting your file changes.

**Comment by xiaods** [comment]
<img width="1408" alt="屏幕快照 2020-02-05 下午11 37 06" src="https://user-images.githubusercontent.com/37678/73856703-d4af0b80-4870-11ea-82ca-94111855fa1a.png">
[xiaods-hello-world-syncthing.log](https://github.com/okteto/okteto/files/4160381/xiaods-hello-world-syncthing.log)

**Comment by pchico83** [comment]
@xiaods Looking at the logs, it looks like the change is detected by the local syncthing process and successfully copied to the remote pod:
```
[ABKAV] 23:34:27 VERBOSE: Local change detected in folder "okteto-hello-world": added file new.go
[ABKAV] 23:34:27 VERBOSE: Local change detected in folder "okteto-hello-world": modified file main.go
```
This should happen automatically, but I guess it is not happening until you manually rescan, right?
Could you check on the advances settings on the top right corner of the syncthing UI is this setting is activated? It should shown something like this:

<img width="924" alt="Screenshot 2020-02-05 at 17 03 29" src="https://user-images.githubusercontent.com/7474696/73859127-d90c0200-4839-11ea-9ecc-5e5443723a84.png">

If it is activated, syncthing should automatically pick the local code changes on your laptop. 
Does the folder you are syncthing have any special mounting properties?
Is it the standard MacOS file system?

**Comment by xiaods** [comment]
hi @pchico83 this is my main develop mac pro book. i double check the setting for fs watcher enabled. it have same settings with your screenshot. all everything is default. my system is default macos filesystem, i have not change it anymore.

maybe this is my notebook's FS bug. this is not okteto's bug.

**Comment by pchico83** [comment]
@xiaods we are going to release "okteto rescan" this month. It is meant for troubleshooting, but it might helm in your use case

**Comment by xiaods** [comment]
@pchico83 Thanks in advance.

**Comment by yucongo** [comment]
> Run `okteto up --loglevel=info` and you will find a logline similar to this one:
> 
> ```
> INFO[0054] syncthing pid-21742 running on http://localhost:54786 and tcp://localhost:54787 with password 'c9bc52ec-7932-495c-9027-f3a51b317b62' 
> ```
> 
> You can then go to the `http` endpoint (something like http://localhost:54786 but you will have a different port), and login with the user `okteto` and the password shown in your logline. There you can see the state of syncthing, syncthing errors and more. It could help to find the issue.

This helps me fix my problem, thanks very much. I spent hours trying to figure out why it does not sync when I do `okteto up` while `okteto status -i`  says ` Synchronization status: 100.00%`.

It turns out my disk space is lower than 1% (syncthing hence refuses to sync). I logged in at the endpoint mentioned above  and changed to 10MB and everything works as expected.
