### ISSUE TITLE
`okteto delete namespace` should remove the `Kubeconfig` entry

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#493]
`okteto delete namespace` should remove the `Kubeconfig` entry, since `okteto create namespace` created it.

**Comment by mohammedaktar** [comment]
I #560

**Comment by adhaamehab** [comment]
Does this still active? Can I work on it?

**Comment by rberrelleza** [comment]
Yeah, I don't think @rmitr  had for it. The goal with this is to delete the namespace and remove the context entry from kubeconfig.

**Comment by Dino14882146** [comment]
What is this?

**Comment by Dino14882146** [comment]
Nop wayyy,, u gotta leave the space for the name and add my name to it. Get
it exactly like ur mother did,  u pussy ass bitch's!!  I wish a mfa would,
let me find the fuck out I got all u stinking hoes.
