### ISSUE TITLE
do `okteto restart` on a single service

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#510]
**Is your feature request related to a problem? Please describe.**
Sometimes I'd like to restart a single service, instead of all of them

**Describe the solution you'd like**
`okteto restart api` 

**Describe alternatives you've considered**
Right now I do `okteto restart` but it takes longer because it has to restart multiple services

**Comment by Tozamm** [comment]
#427

**Comment by parschina** [comment]
[واردات از چین](https://parschina.ir/)

گروه تجاری آوا

**Comment by adhaamehab** [comment]
Hi, Can I work on this?

**Comment by pchico83** [comment]
@adhaamehab that would be great!
If you need help or more context, we can talk more on the #okteto channel in the Kubernetes community Slack
