### ISSUE TITLE
Include the state of the file sync in the syncthing healthcheck

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#532]
**Describe the bug**
Okteto monitors synching health pinging the remote syncthing service. Syncthing might stop working for file scan errors but it would still respond to ping requests. We should ping the state of the sync folder (both, local and remote) and report errors to the user if something is not working as expected. Otherwise, everything looks good but changes are not synchronized.

**Comment by xiaods** [comment]
hi @pchico83 the syncthing is core feature for the tools.  it indeed visualize the syncing process.

**Comment by pchico83** [comment]
Closed by #718 
You can also run `okteto status -i --watch` now to visualize the state of the syncthing process.
