### ISSUE TITLE
Allow non-blocking background execution of commands

### ISSUE THREAD

**Issue by kklemon** [okteto/okteto#550]
**Is your feature request related to a problem? Please describe.**
Executing long-running tasks (e.g. training of ml models, running tests, etc.) in a remote environment is difficult with the Oktekto CLI as it only allows to do so in a blocking manner.

**Describe the solution you'd like**
The `okteto exec` command should offer an option to run a command in the background, in a non-blocking mode respectively.

Alternatively a `okteto job` command could be introduced that allows the execution of a single command, similar to `okteto exec` but does so, by spawning a new container.

**Describe alternatives you've considered**
Install tmux or screen in the Oktekto environment to detach safely from a session after execution of a command.

**Comment by pchico83** [comment]
@kklemon thanks for this suggestion, we had an internal proposal to do this but it was never implemented. What are the advantages versus running a background process in your use case?
Our original proposal was something similar to `docker-compose run`.
It would run a new container for a given okteto manifests up to completion and mounting your current folder content.

**Comment by kklemon** [comment]
> What are the advantages versus running a background process in your use case?
Running a background process didn't even work in the end. What I basically tried is to start and detach from a job, e.g. using tmux or nohup but after detaching from the okteto environment, also the corresponding background processes have stopped although the pod was still running. I haven't further investigated the reasons for this but even if it would theoretically work, it would be probably more safe and practical to spawn a new pod/container for each submitted job. The user could then directly profit from jobs being distributed on different pods/nodes.

A use case might be for example, that one wants to run many ML experiments in a short time in a large K8s cluster and hence want to make use of proper resource distribution.

**Comment by pchico83** [comment]
@kklemon We have been thinking about this use case. Would this workflow make sense for your use case? There would be an `okteto job` command that does: 
1 - Build a docker image from your source code
2 - Launch a new container/pod consuming the image built in the previous step.
3a - Wait for the pod to finish and streamline its logs
3b - Launch the pod in detached mode, and support `okteto job ls` and `okteto job logs` commands to check the state of the job.
We feel like using code synchronization does not make sense for async jobs since you don't want to modify the job source code/data while it is being executed.

**Comment by kklemon** [comment]
The workflow sounds very good.

However, with regard to code synchronization it might be useful in the sense, that it could avoid building new images all the time for slight code changes. Of course this does not imply the full synchronization feature but for example, that the working directory is synced with a volume and this volume then simply mounted into the container / pod / job instead of being explicitly copied into the image.

**Comment by pchico83** [comment]
@kklemon right, it is the other approach we are considering. The problem is that mounting the same volume forces both containers to run in the same node.

**Comment by kklemon** [comment]
Ah, I see. But is this also the case for PVs provided by NFS providers?

**Comment by pchico83** [comment]
@kklemon that should work, but we haven't test it yet. Are you using an NFS provider?

**Comment by kklemon** [comment]
Yes, I do.

**Comment by pchico83** [comment]
Thanks. That makes sense. We will make the build image before running the job optional.
This will probably go in the january monthly plan.
