### ISSUE TITLE
CLI argument to define image pull policy override

### ISSUE THREAD

**Issue by telefoontoestel** [okteto/okteto#552]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to define the imagePullPolicy with an attribute in the manifest. Because it is inconvenient to have to manually update the image tag everytime a new deployment is done, the latest tag has been added to each new build. With the pull policy set to always it will indeed always try to update the image, even when it is not always necessary. This causes a lot of unnecessary pulls on the container registry.

**Describe the solution you'd like**
We would like to have a CLI option (e.g. --force-image-pull) available to override the imagePullPolicy attribute in the manifest. With this we can define the value IfNotPresent in the manifest, but force a pull anyway when desired.

**Describe alternatives you've considered**
We had the ImagePullPolicy set with the value Always but, because of the cost of the unnecessary requests, we changed it to IfNotPresent. Due to the use of the latest tag we have to manually change this to Always and change it back and remembering to do so before committing.

**Comment by pchico83** [comment]
@telefoontoestel thanks for this suggestion.
What do you think about using the pull policy in the original deployment manifest by default?
The precedence would be:
1) Use  the okteto cli pull argument if defined
2) Use the okteto yaml pull policy if defined
3) Use the k8s deployment pull policy
We will fix this issue for the next release

**Comment by telefoontoestel** [comment]
If that also gives the possibility to define the suggestes cli argument that would be even better I guess. Any idea when the release can be expected?

**Comment by pchico83** [comment]
We are planning a release for next monday

**Comment by telefoontoestel** [comment]
Excellent. Thanks so much.

**Comment by pchico83** [comment]
@telefoontoestel okteto 1.5.8 is now available and it includes the flag `--pull` to force the pull of images

**Comment by telefoontoestel** [comment]
That was fast! Thanks a lot.
