### ISSUE TITLE
stat /tmp/hostpath_pv/28b5fe30-30af-433e-8dbc-f4881ce57a9e: no such file or directory

### ISSUE THREAD

**Issue by adibrastegarnia** [okteto/okteto#559]
I followed the instructions here:
https://okteto.com/blog/how-to-develop-go-apps-in-kubernetes/

but I ended up with this error:
```
okteto up
 x  Error: stat /tmp/hostpath_pv/28b5fe30-30af-433e-8dbc-f4881ce57a9e: no such file or directory
```

**Comment by pchico83** [comment]
Hi @adibrastegarnia, thanks for reporting this issue.
Which kubernetes distro are you using? Did you retry and get the same error?
Could you share `$HOME/.okteto/okteto.log`?

**Comment by rberrelleza** [comment]
this seems to be the same issue as #517

**Comment by rberrelleza** [comment]
close as dup of #517
