### ISSUE TITLE
enum String cases 

### ISSUE THREAD

**Issue by Anas12-Prog** [okteto/okteto#563]
Hello guys can u help me getting my Syntax Correct , i want to verify a Scientifique number ( exemple : " 12.12e102 " just using cases enum and my String . 
here is my Code help me Please 

#include <iostream>
#include<string>
#include <strstream>
#include<stdlib.h>

#include <iostream>

double zahl1 ,zahl2 ;
using namespace std;

enum zustand { Vorzeichen , Vorkommazahl , Komma , Nachkommazahl , Expo ,  Vorexpozeichen   ,  Nachexpoziffern  , Error  } ;

bool CheckDoubleNumber ( string eingabe ) {

		 zustand next = Vorzeichen;

		 for(int i=0 ; i< eingabe.length() ; i++  ){

			switch(next)

			{
			case Vorzeichen :
				   if (eingabe[i]== '+'|| eingabe[i]== '-')
				{
					   next = Vorzeichen;
				}
					else if(eingabe[i]>= '0' && eingabe[i] <= '9')
                 {
					   next= Vorkommazahl ;
                 }
					else
				{
						next = Error ;
				}

			case Vorkommazahl :
				if (eingabe[i]>= '0' && eingabe[i]<= '9')
					next= Vorkommazahl ;
				else if(eingabe[i]== '.')
				{	next = Komma ; }
				else if ( eingabe[i] == 'e' )
				next = Expo;
				else
				{next = Error ; }

			case Komma :

				if (eingabe[i]>= '0' && eingabe[i]<= '9'   )
						{next= Nachkommazahl ;}
					else
						{next = Error  ;}

			case Nachkommazahl :
              if (eingabe[i]>= '0' && eingabe[i]<= '9'   )
						next=Nachkommazahl;
              else if (eingabe[i]=='e' )
            	        next= Expo ;
              else
              { next = Error ; }

			case Expo :
				  if (eingabe[i]== '+'|| eingabe[i]== '-')
			           next = Vorexpozeichen ;
				  else if (eingabe[i]>= '0' && eingabe[i]<= '9'  )
				       next = Nachexpoziffern ;
				  else
				            { next = Error ;  }

			case  Vorexpozeichen  :

				    if ( eingabe[i]>= '0'&& eingabe[i]<= '9' )
				   { next  = Nachexpoziffern ;}
				   else
					   {
					   next = Error ; }

			case  Nachexpoziffern :
				if (  eingabe[i]>= '0' && eingabe[i]>= '9' )
					next =  Nachexpoziffern ;
				else
				{next = Error ;  }

			case Error :
				return false ; break ;

			}
}
		 if ((next ==Vorkommazahl ) || (next == Nachkommazahl  ) || (next == Nachexpoziffern ))
				 return true ;
		 else
			 return false ;
}

int main(){

	string eingabe ;
	cout<< "Eingabe eingeben : " << endl ;
	getline(cin , eingabe );
	CheckDoubleNumber(eingabe);
	if (CheckDoubleNumber(eingabe) ==false  ){
		cout<< "True "<< endl ;
	}
	else
		cout<< "False !!!! "<<  endl ;

	return 0 ;

}

**Comment by Anas12-Prog** [comment]
it could be just "+12 " , "-12 " "12" or "+ or - 12.12" or "+ or - 12.12e+or - 102 "

**Comment by rberrelleza** [comment]
this is unrelated to Okteto
