### ISSUE TITLE
Can't connect to `okteto --remote` with putty

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#567]
**Describe the bug**
Can't connect to the okteto remote environment with putty. Trying to connect results in Okteto logging `Remote side unexpectedly closed network connection`

**To Reproduce**
1. `okteto up --remote=22000`
2. Connect via putty to `root@localhost -p 22000`

**Expected behavior**
SSH client should be able to connect

- OS: Windows  
- Putty: 
 - Okteto 1.6.0

**Comment by RubenAtPA** [comment]
Some additional information:
`Edition: Windows 10 Pro
Version: 1903
Build of operating system:  18362.476
Putty Release 0.73
Build platform: 64-bit x86 Windows
Compiler: clang 7.0.0 (tags/RELEASE_700/final), emulating Visual Studio 2013 (12.0), _MSC_VER=1800
Source commit: 745ed3ad3beaf52fc623827e770b3a068b238dd5`

**Comment by rberrelleza** [comment]
fixed by #586
