### ISSUE TITLE
Support for developer secrets

### ISSUE THREAD

**Issue by RubenAtPA** [okteto/okteto#568]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to define additional secrets that should only be available when running in development mode.

**Describe the solution you'd like**
It would be helpfull when it's possible to define expandable secrets in the okteto manifest that can be mounted as either a file or as environment variable when running in development mode.

**Describe alternatives you've considered**
This is currently not possible and manual actions are required a.t.m.

**Additional context**
This can be usefull for setting specific information like developer ssh keys, db credentials as environment variables etc.

**Comment by aw185176** [comment]
How does this support imagePullSecrets?  #603 and the documentation are not clear that it actually does.

**Comment by pchico83** [comment]
@aw185176 `imagePullSecrets` are managed independently. You can add `imagePullSecrets` to your deployment manifest, or to your service account:
https://okteto.com/docs/reference/private
