### ISSUE TITLE
Make remote mode compatible with Intellij's SSH plugin

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#574]
**Is your feature request related to a problem? Please describe.**
I want to be able to use `okteto up --remote` with PHPStorm or Pycharm's remote dev features

**Describe the solution you'd like**
I want to run `okteto up --remote` and be able to connect it to pycharm or phpstorm as a remote interpreter. 

**Describe alternatives you've considered**
Creating my own dev image with an SSH server, or manually configuring the whole thing.

**Comment by RubenAtPA** [comment]
Some additional information concerning PHPStorm (and maybe others):

There is a problem with the ssh command `cd` in the okteto ssh-server.
When using the  ssh-server configured directly in the image:
`ssh root@localhost -p 22000 cd /var/www && echo "Hello world"`  => `$ Hello world`
When using the ssh-server configured with okteto remote:
`ssh root@localhost -p 22000 cd /var/www && echo "Hello world"` => `$ internal error`

All other commands seem to work just find, so it looks like it's isolated to the `cd` command which is unfortunately used by default by PHPStorm.

**Comment by rberrelleza** [comment]
@RubenAtPA which dev image are you using for the `--remote` case?

**Comment by rberrelleza** [comment]
fixed by #590
