### ISSUE TITLE
Test our windows support

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#58]
We need to test that cnd works in Windows

**Comment by dadoeyad** [comment]
I'm testing it!

I'm getting an error when okteto tries to execute syncthing

```
okteto up
Installing dependencies...
syncthing.exe 16.56 MiB / 16.56 MiB [======================================================================] 100.00% 7s
                                                           ✕  Exec: "C:\\Users\\dado_/.okteto/syncthing": file does not exist
```

I also tried executing the syncthing bin installed in .okteto and got the same error.

**Comment by dadoeyad** [comment]
I saw that syncthing is available via [chocolatey](https://chocolatey.org/) and I installed it but okteto is installing it's own binary.

May I suggested adding Okteto to be installed by chocolatey? if I have time this weekend I might check how chocolatey packages are created.

**Comment by dadoeyad** [comment]
Wait I just noticed that this is the CND repo and not Okteto. My bad!
Couldn't find the Okteto repo for issues though?

**Comment by rberrelleza** [comment]
You're in the right repo for those issue. CND is the core library of Okteto 👍 .

Thanks for testing it on windows!  The current design is for the binary itself to download the dependency. We did it that way because most of our users where directly downloading the binary, and so that we didn't depend on external package managers (brew for macOS, chocolatey for Windows, etc...). 

As for the issue you ran into, I think there might two issues there:
1. https://github.com/cloudnativedevelopment/cnd/blob/master/pkg/syncthing/syncthing.go#L33 assumes that the name of the binary is "syncthing", but based on the screenshot it looks like for windows is "syncthing.exe". Maybe we need an OS-dependent way of generating that binary name?
1.  Looks like we're using the wrong file separator on Windows( "/" instead of "\"). Based on https://github.com/golang/go/issues/1423, it seems like we need to use filepath.Join instead of path.Join when creating paths.

**Comment by dadoeyad** [comment]
Ok. Before I go any further and to be able to help better. I have to say I'm not very experienced in Windows command line. It just happened that I thought of testing this today.

I was trying to run okteto in bash using [cmder](http://cmder.net/). I couldn't/didn't know how to run it in cmd or PowerShell..

I don't wanna assume that they run the same way. So maybe running from bash caused the path problem? if so, could you please let me know how can I run the binary in cmd or PowerShell so I can test again? :)

**Comment by rberrelleza** [comment]
This is great @dadoeyad . We'll add a guide to our docs on how to run on windows, both on powershell and on the regular cmd line.

I don't think cmder had anything to do with the issue you encountered. I think it's related to how we calculate paths and binary names.

**Comment by dadoeyad** [comment]
I think better docs will help so thanks!!

Let me know when the new okteto binary is released and I'll test again.
