### ISSUE TITLE
`okteto up` doesn't play well with kubernetes manifest changes

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#580]
**Is your feature request related to a problem? Please describe.**
If I apply a change to the deployment once `okteto up` are running, the changes are not properly applied. And when I do `okteto down`, the pod is rolled back to what I had when I ran the `up`, instead of the latest updates.

**Describe the solution you'd like**
`okteto up` should react to changes in the k8s manifestl, without requiring any server side components.

**Comment by pchico83** [comment]
Won't fix it, we will document the limitations #613
