### ISSUE TITLE
Debug mode showing the kubernetes API calls

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#582]
**Is your feature request related to a problem? Please describe.**
I want to check which Kubernetes API calls my `okteto` commands are executing for auditing the Okteto CLI.

**Describe the solution you'd like**
A flag to log every Kubernetes API call. We should also log local commands, like running syncthing.

**Comment by rberrelleza** [comment]
Can we just include them in our existing logs instead? We could add a keyword to make it greppable.

**Comment by rberrelleza** [comment]
Investigate if we can give `client-go` a custom logger so we can send it to the same file as everything else.
