### ISSUE TITLE
Proposed plan for January 2020

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#611]
# Features
Access services in my namespace directly from my local machine #577
Support for okteto PVC size at the okteto manifest level #602
Support for storage class at the okteto manifest level  #508 
Support for build primitives in the okteto manifest #581
Okteto up inside of a cloud environment enters an error loop #287
Show a warning if the watchers are not properly configured in the node #610
Add e2e test for okteto down #400

# Docs
Document how to use private images #612 
Document Okteto CLI limitations on manifest changes #613

# Research
More information on the sync status #423

**Comment by rberrelleza** [comment]
The January milestone tracks this.

**Comment by kandubard** [comment]
I wan't to sée m'y wallet
