### ISSUE TITLE
Document how to use private images

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#612]
Create a document that explains how to use private container images with Okteto. This should be focus on using private images as a dev environment.  For other use cases, we can defer to the kubernetes official documentation.

**Comment by rberrelleza** [comment]
docs available at https://okteto.com/docs/reference/private/index.html

**Comment by kingdonb** [comment]
That is a broken link, it appears... and https://okteto.com/docs/reference/private/index.html still appears in the search index as a result, but it appears to be missing.

**Comment by pchico83** [comment]
@kingdonb thanks for pointing it out. We moved it to the FAQs section:
https://okteto.com/docs/reference/faqs#how-to-use-private-images

**Comment by kingdonb** [comment]
awesome, I have it working now :+1:

With that, I think now, I don't need Okteto to have access to my private git repo either... I can just use "okteto build" or let my existing CI solution build images, and have Flux deploy them.
