### ISSUE TITLE
HostPID is not supported

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#637]
**Describe the bug**
I have a deployment with `HostPID: true`.
`okteto up` does not work.

**Additional context**
```
DEBU[0006] error calling 'rest/system/ping' remote syncthing API: Get http://localhost:52139/rest/system/ping?limit=30: EOF 
⠏ Starting the file synchronization service... DEBU[0006] unhandled error: an error occurred forwarding 52139 -> 8384: error forwarding port 8384 to pod 3476c4d30a73edbbf2035d76b41532a25eda5af653ecd8343547cfcd83b26921, uid : exit status 1: nsenter: cannot open /proc/109418/ns/net: No such file or directory 
DEBU[0006] error calling 'rest/system/ping' remote syncthing API: Get http://localhost:52139/rest/system/ping?limit=30: EOF 
⠏ Starting the file synchronization service... DEBU[0007] unhandled error: an error occurred forwarding 52139 -> 8384: error forwarding port 8384 to pod 3476c4d30a73edbbf2035d76b41532a25eda5af653ecd8343547cfcd83b26921, uid : container not running (3476c4d30a73edbbf2035d76b41532a25eda5af653ecd8343547cfcd83b26921) 
```

**Comment by senser-davidfurman** [comment]
Why is this issue did not get any comments? this feature is a must with my application and i must debug with hotsPID on.
We need to bring this issue to more attention, i dont think its that hard to fix that - i wish i knew how

**Comment by jLopezbarb** [comment]
Hi @senser-davidfurman ,

Thank you for your feedback regarding the `HostPID` feature. We apologize for the lack of comments and attention to this issue previously. To provide some context, we initially didn't have the capacity to address this, and there was limited demand for it. However, your recent interest has highlighted its importance, and we are now reevaluating its priority.

We are now reopenning the issue and will work on it when we have enough capacity
