### ISSUE TITLE
Handle connection failure: retry port forwards

### ISSUE THREAD

**Issue by ankitrgadiya** [okteto/okteto#643]
**Describe the bug**

The connection to Pod breaks after sometime. This might be because the connection times out while forwarding port. This also stops the port forwarding and `okteto` exits.

**To Reproduce**

Happens seemingly randomly after sometime of running `okteto up`.

**Expected behavior**

Possible option can be to gracefully handle connection failure and have retries for port forwarding. Also, have retries for connection drops in `exec`. The environment will be lost but a message to show that retry happened with attempt to `exec` into the pod again will be sufficient in most cases.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: 1.16.4, 1.16.5

**Comment by rberrelleza** [comment]
@ankitrgadiya we are working on a change to use SSH tunnels instead of port-forwards, which gives us more control of the forwards, retries, etc. Would you mind trying it to see if it solves this issue for you?

To use it you need to do build an okteto binary from master, `export OKTETO_EXECUTE_SSH=1`, and then `okteto up` with the new binary.

**Comment by ankitrgadiya** [comment]
@rberrelleza I'll check it in a few days and let you know. Really appreciate the changes, thank you.

**Comment by ankitrgadiya** [comment]
I was not able to replicate the original setup because since then we removed the HTTP Proxy between client and API server. But I tried both v1.8.1 and v1.8.2 and so far it worked flawlessly.

**Comment by rberrelleza** [comment]
Thanks for checking. We are making some changes in the next releases that should  also mitigate that issue.

**Comment by rberrelleza** [comment]
this is now fixed
