### ISSUE TITLE
Activating your development environment

### ISSUE THREAD

**Issue by bigloupe** [okteto/okteto#654]
When I launched the command okteto up, i 've got an issue :
couldn't activate your development environment : stream error: stream ID 19; INTERNAL_ERROR

**Comment by pchico83** [comment]
Hi @bigloupe 
Could you attach the file `$HOME/.okteto/okteto.log`?
Which OS are you on?

**Comment by pchico83** [comment]
@bigloupe were you running in Okteto Cloud? or your own cluster?

**Comment by pchico83** [comment]
@bigloupe closing this one. If you were in Okteto Cloud, this is probably because your node was restarting. The best way to make it work again is to do:
```
okteto down -v
okteto up
```
