### ISSUE TITLE
Warning if there are concurrent manifest changes while "okteto up" is running

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#661]
**Is your feature request related to a problem? Please describe.**
I run `okteto up`, then I run `kubectl apply`. `okteto up` reconnects and it undoes the changes applied by `kubectl apply`.

**Describe the solution you'd like**
This is a known issue that cannot be solved for external clusters (see https://okteto.com/docs/reference/known-issues/index.html#kubectl-apply-changes-are-undone-by-okteto-up for more details).
But a warning or an error should be shown in these cases.

**Additional context**
Check the revision field when running `okteto up`.

**Comment by rberrelleza** [comment]
@pchico83 should be block the up or just tell the user that the changes are being overriden?

**Comment by pchico83** [comment]
I would fail the up. Executing the `up` in this case has wide side effects
