### ISSUE TITLE
Monitor the state of the local syncthing process

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#662]
**Is your feature request related to a problem? Please describe.**
Local syncthing stops working.

**Describe the solution you'd like**
Detect the issue and relaunch syncthing.

**Comment by rberrelleza** [comment]
@pchico83 do we have any information on what causes syncthing to die? The syncthing daemon is supposed to be configured to relaunch it if it fails (that's why there are two syncthing processes)
