### ISSUE TITLE
"okteto down" does not wait for dev pod termination

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#664]
**Describe the bug**
I run `okteto down` + `okteto up` and the dev pod is not recreated

**Expected behavior**
`okteto down` + `okteto up` should always recreate the dev pod

**Additional context**
This happens because if the pod takes a while to be terminated, and you execute `okteto up` again, k8s can reuse the previous pod because it matches the same manifest

**Comment by rberrelleza** [comment]
@pchico83 what's the recommended implementation here? For `down` to wait until the pod is shutdown, or for `up` to be aware of this and ensure the recreation?

**Comment by pchico83** [comment]
It is better to wait on "down" and it is also easier to implement.
It just needs to wait until it is marked for termination
