### ISSUE TITLE
Proposed plan for February

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#666]
# Features
- Support for "okteto build-push-redeploy" #656
- Support for "okteto status" #657
- Support for "okteto rescan" #658
- Support for "okteto doctor" command #663
- Warning if there are concurrent manifest changes while "okteto up" is running #661
- Make the "okteto build" "-t" flag more explicit

# Bug fixes
- Monitor syncthing error events API  #622
- `okteto down` does not wait for dev pod termination #664
- Monitor local syncthing for errors #662
- Fail when a port is not allocatable #630

**Comment by azulaluna** [comment]
#664
