### ISSUE TITLE
Use DockerFile as base image

### ISSUE THREAD

**Issue by janvdpol** [okteto/okteto#672]
**Is your feature request related to a problem? Please describe.**
I gave Okteto a try with the ASPNetCore example. It worked like a charm. Next step was to try it with our own solution. During that attempt I noticed that the OS my microservice was running in, was based upon some Microsoft SDK docker image. We have had issues in the past, where 1 image produced slightly different results than another image.

**Describe the solution you'd like**
We want to be as close as possible to the real production environment. This includes having the same docker base image for working with Okteto as the production environment would be great. So if possible I would prefer a way to enrich the DockerFile belonging to the (ASPNetCore) project in such way that it can work with Okteto.

**Describe alternatives you've considered**
Could not think of an alternative solution to this problem

**Comment by rberrelleza** [comment]
@janvdpol thanks for filing the issue! when you talk about "So if possible I would prefer a way to enrich the Dockerfille belonging to the ASPNetCore", could you give us some examples of what would you like to add?

Today, the way it works is that Okteto is using the official ASPNetCore image, and when you run `okteto up` it only injects a  binary for the file synchronization service. So you are using the image mostly unmodified.

**Comment by janvdpol** [comment]
We had some difficulties in the past with OpenSSL for instance. It worked with the Microsoft provides ASPNetCore image, but not in production where we use an image based on CentOS. We managed to get it working on CentOS at the end. To . Therefore we decided to have our images as close to production as possible. Ideally we would use the same (production like) image as a basis for Okteto.

**Comment by rberrelleza** [comment]
Yeah, with that idea in mind is that we build the sample  [dotnet sample](https://github.com/okteto/aspnetcore-getting-started) to uses mcr.microsoft.com/dotnet/core/aspnet (plus the app's DLL) for production, and mcr.microsoft.com/dotnet/core/sdk [for development](https://github.com/okteto/aspnetcore-getting-started/blob/master/okteto.yml).  What else would like to see there to make it better for your scenario?

**Comment by janvdpol** [comment]
In my testing, I got blocked by this issue and by #668. I have good hopes that it will fit our scenario after these two are addressed.
