### ISSUE TITLE
Okteto up fails when .ssh folder is not present

### ISSUE THREAD

**Issue by shyim** [okteto/okteto#676]
**Describe the bug**
Run okteto up while .ssh folder is not present

**To Reproduce**
1. Remove .ssh
2. Run okteto up

**Expected behavior**
It works

**Desktop (please complete the following information):**
 - OS: Windows
 - Version current

**Additional context**
 x  couldn't activate your development environment: fail to save C:\Users\shyim\.ssh\config: open C:\Users\shyim\.ssh\config.1581527528154798700: The system cannot find the path specified.

**Comment by rberrelleza** [comment]
@shyim I can't reproduce this on my side, it might be a windws-specific issue. Could you share your `okteto.log` ?

**Comment by shyim** [comment]
@rberrelleza Do you need still my okteto.log? I see there is pr attached :)
