### ISSUE TITLE
Okteto init puts the powershell to black and also requires pressing enter to make manifest

### ISSUE THREAD

**Issue by genievot** [okteto/okteto#684]
**Describe the bug**
When I run `okteto init` in the PowerShell window, The windows background turns black and after selecting the appropriate option from the given list, It stops and waits for another confirmation which does not appear to the terminal (Maybe because font color changes too for that but not sure)

**To Reproduce**
1. Go to 'project directory`
2. Open 'PowerShell' in that directory
3. Type `okteto init`

**Expected behavior**
The background color or other settings of PowerShell should not change. If okteto needs one more confirmation before making manifest file, The text should appear with y/n choice.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Okteto Version [okteto version 1.6.5]

**Additional context**
If you are unable to reproduce the issue, I will send you a video of it.

**Comment by kivi** [comment]
Hello @genievot,

I could not reproduce that on PowerShell on Windows 10 with okteto **version 1.8.1**
Could you please retry with an update?

Thanks
Vikas

**Comment by genievot** [comment]
> Hello @genievot,
> 
> I could not reproduce that on PowerShell on Windows 10 with okteto **version 1.8.1**
> Could you please retry with an update?
> 
> Thanks
> Vikas
> 

That is very issue, i will close it

**Comment by genievot** [comment]
Or should be closed
