### ISSUE TITLE
Add capability to set IP for remote binding via CLI

### ISSUE THREAD

**Issue by thatnerdjosh** [okteto/okteto#703]
**Is your feature request related to a problem? Please describe.**

As a user, sometimes would like to work via a port forward on another machine on the LAN.
In order to do this, I could either use IPTables and Masq NAT or similar, or Okteto could support setting the IP address directly.
As such, it would be convenient to do this through the CLI as a flag

**Comment by rberrelleza** [comment]
@NerdsvilleCEO is the requirement to have okteto bind the port forward to a different port than `0.0.0.0`?

**Comment by thatnerdjosh** [comment]
I don't remember exactly... but I think the idea is doing a port forward for localhost:80 for example to 10.0.0.10:80 for example

**Comment by pchico83** [comment]
@thatnerdjosh we have support for the `interface` field:
https://okteto.com/docs/reference/manifest#interface-string-optional
is that what you mean?

**Comment by thatnerdjosh** [comment]
Not certain, but possibly, it's been a while since I used Okteto. I'll take a look :)

**Comment by thatnerdjosh** [comment]
@pchico83 yes, I'll close this issue :) thanks!
