### ISSUE TITLE
Store the okteto token in a local vault if available

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#711]
**Is your feature request related to a problem? Please describe.**
We currently store the okteto token in `$HOME/.okteto/.token.json`. It would be great if we could follow the same pattern that the docker cli does, and we store the API token in the local keychain (or similar). 

Maybe we can use the same libraries that docker uses?

**Comment by adhaamehab** [comment]
I'm not 100 sure but apparently docker cli implements it's own [keychain store](https://github.com/docker/cli/tree/master/cli/config/credentials). I'm more than happy to follow the same pattern here if that's the right call. What do you think?

**Comment by rberrelleza** [comment]
I think that's a good pattern to follow. Looking at their code, it seems like they defer to the native OS stores for the actual storage, which would be useful for us, since we want to support running okteto in macos, windows, linux and linux arm64.

**Comment by pchico83** [comment]
@adhaamehab this would be awesome!
