### ISSUE TITLE
add headless mode to okteto commands

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#727]
**Is your feature request related to a problem? Please describe.**
When running okteto as part of a script (or in the remote-kubernetes plugin) having the ascii animations makes reading the logs harder. 

**Describe the solution you'd like**
I'd like to have a --headless (or similarly named parameter) that disables the animations and just prints text messages.

**Comment by Cirrith** [comment]
What is meant by animation? Like the progress bar in downloading dependencies?

**Comment by rberrelleza** [comment]
Yes, the progress bar on download, and the bar and ascii animations during `okteto up` and `okteto down`

**Comment by rberrelleza** [comment]
Superseded by #1041
