### ISSUE TITLE
`okteto push` doesn't check if namespace exists

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#740]
**Describe the bug**

**To Reproduce**
okteto push -n=missing-namespace

Build fails with an `invalid format error` during the build.

**Expected behavior**
A clear and concise error about the namespace not existing

**Desktop (please complete the following information):**
 - okteto 1.7.5

**Additional context**
Add any other context about the problem here (e.g okteto.yml, k8s manifests, logs)

**Comment by pchico83** [comment]
@rberrelleza cannot repro it.
I get this error:
```
 x  deployments.apps "hello-world" is forbidden: User "system:serviceaccount:okteto:7ef8a375-bd77-43a0-96e5-0dc6f53ac5c9" cannot get resource "deployments" in API group "apps" in the namespace "asda"
```
which I think it  is good enough
