### ISSUE TITLE
Execute commands and port forwards via SSH

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#748]
**Is your feature request related to a problem? Please describe.**
Idle connection can be closed by proxies. `kubectl portforward` and  `kubectl exec` does not support keep-alive connections. 

**Describe the solution you'd like**
Executing port forwards and commands via ssh let us configure keep-alive connections.

**Comment by rberrelleza** [comment]
I've been doing some testing with #755 and it looks promising. I was able to keep an unused dev env on kind for over an hour without disconnection.

**Comment by pchico83** [comment]
Closed by #755
