### ISSUE TITLE
Add support for team namespaces

### ISSUE THREAD

**Issue by fenixsolorzano** [okteto/okteto#792]
As far as I understand okteto is taking the github username to create a namespace, I'd like to setup okteto for my team under our team name as namespace.

**Comment by xiamuguizhi** [comment]
I hope I can customize the second-level domain name

****-xiamuguizhi.cloud.okteto.net   NO!!!

****.cloud.okteto.net     YES!!!  good!

**Comment by pchico83** [comment]
@xiamuguizhi we are working on supporting custom domains:
https://github.com/okteto/cloud-feedback/issues/13

Closing it here since this repo is just about the Okteto CLI.
