### ISSUE TITLE
Does Okteto work with OpenShift?

### ISSUE THREAD

**Issue by tc8** [okteto/okteto#795]
Sorry if this is a dumb question but does this tool work with OpenShift?

AFAIK, OpenShift doesn't use the `Deployment` resource and instead uses the `DeploymentConfig` resource. When I run `oc get deployment`, I get back "No resources found". 

I'm trying to use Okteto to setup a reverse tunnel into my pod so that I can debug my application using PyCharm. Is all help lost?

**Comment by pchico83** [comment]
Which version are you using?
`DeploymentConfig` is not supported, but you can also use `Deployment` in OpenShift and it works with okteto.
Adding support for `DeploymentConfig` is not hard

**Comment by tc8** [comment]
We're using OpenShift 3.11.

It would be great if you could add support for `DeploymentConfig` since `Deployment` appears to be deprecated according to `oc explain deployment`

**Comment by rberrelleza** [comment]
closing this to use #868 to track it.
