### ISSUE TITLE
Feature request - please support mounting arbitrary volumes in manifest

### ISSUE THREAD

**Issue by cameronbraid** [okteto/okteto#811]
An example of when this is useful:

I currently have a development cluster where I already have a PV containing a M2 cache which is used for for tekton build pipelines, I would like to mount this PV into my /root/.m2 path in the deployment when I `okteto up` rather than maintaining a separate duplicate volume

My deployment uses files from PVs and I wish to override them and use a different volume when running `okteto up`

**Comment by pchico83** [comment]
@cameronbraid this is an interesting use case :-)
Would something like this in the okteto manifest work?
```
externalVolumes:
 - pvcName1:/mountPath1
 - pvcName2:/mountPath2
```

**Comment by cameronbraid** [comment]
that would work
