### ISSUE TITLE
Feature request - support more than one replica 

### ISSUE THREAD

**Issue by cameronbraid** [okteto/okteto#812]
I would like to be able to test my app running with multiple replicas in the okteto environment

Curently okteto edits the deployment to inject the okteto configured environment.  Would it make more sense to leave the deployment alone and scale it to 0 and instead create a pod using the deployment as the template, applying the okteto envirnment to the pod.

It would then be possible to run okteto multiple times as a new pod would be created each time.  

Would probably also need to be able to specify a different manifest to use, or one that provides overrides so that different ports can be used among other things.

**Comment by pchico83** [comment]
@cameronbraid which programming language are you using? 
You can use the `services` field, which is less intrusive with your deployment (it just mounts the volume where you decide, but keeps the replicas, the start command if you don't overwrite it).
This example might be a little bit outdated, but it can help as inspiration:
https://github.com/okteto/samples/blob/master/jib/okteto.yml

**Comment by cameronbraid** [comment]
Hi, I don't want to put another container in my deployment in development mode, but rather run as if the deployment was scaled to 2 replicas

In the production environment I run replicas = 3 and I wish to test the clustering operations of my deployment.  I wish to have 2 okteto environments running for the same deployment, with vscode connected via ssh to each of them, launching and debugging each instance in vscode.

**Comment by cameronbraid** [comment]
One workaround is for me to duplicating the deployment, but that means I have to manuall do that for each microservice I wish to test with > 1 replicas

**Comment by pchico83** [comment]
@cameronbraid why don't you want to run another dev container? Would it work if you could edit the files from a single vscode windows, and debug the different replicas from a single vscode window too? That vscode windows would be attached to the extra dev container, and mounting a volume with your deployment replicas

**Comment by cameronbraid** [comment]
A few reasons 

- each pod discovers the other pods via a headless service so they need to run in separate pods
- each pod uses its own istio proxy container to implement mutual tls  inter pod access
- external clients connect via a istio proxy which is also relying on istio virtualservice, destination rule and kube service resource which target by label selectors - once again requiring separate pods
- each pod relies on a unique pod name to uniquely identify itself with the other pods in the replica set

I am sure there are others, these are just off the top of my head
