### ISSUE TITLE
okteto  status --watch fails with error after sync is complete

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#819]
okteto  status --watch fails with error after sync is complete:

![image](https://user-images.githubusercontent.com/475313/79285646-00eb9780-7e73-11ea-98e2-6336093dd4b7.png)

**To Reproduce**
1. Run `okteto up ` in a large repo
2. Run  `okteto status --watch` on a separate window
3. Wait for the file sync to finish

**Desktop (please complete the following information):**
 - OS: macos
 - Version 1.8.3

**Comment by pchico83** [comment]
This is solved in current versions
