### ISSUE TITLE
When creating a stack, the  --namespace parameter is not respected

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#822]
**Describe the bug**
The --namespace parameter in stacks is not respected

**To Reproduce**
1. Setup your context for your personal namespace
1. Create a second namespace (e.g. stack)
1. okteto stack create --namespace=stack

![image](https://user-images.githubusercontent.com/475313/79395586-cf380680-7f2e-11ea-9d82-4f40800bffb5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.8.4

**Comment by pchico83** [comment]
Fixed by https://github.com/okteto/charts/pull/54
