### ISSUE TITLE
Support for "env_file" in okteto stacks

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#826]
**Is your feature request related to a problem? Please describe.**
I want to run `okteto stack deploy` with a bunch of environment variables.

**Describe the solution you'd like**
Support for `env_file`:
https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

**Comment by ZaxR** [comment]
Dupe of #793 ? I would very much like this feature as well

**Comment by pchico83** [comment]
@ZaxR thanks for the interest. This will be implemented very soon :-)
