### ISSUE TITLE
the shell started by `okteto up` doesn't forward the SSH agent

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#845]
**Describe the bug**
The shell started by `okteto up` doesn't forward the SSH agent

**To Reproduce**

1. Ensure you are forwarding keys (run ssh-add -L in macos)
2. Check that your SSH agent is running (printenv SSH_AUTH_SOCK)
3. `export OKTETO_EXECUTE_SSH=1`
4. `okteto up`
5. `okteto>ssh -T git@github.com`

**Expected behavior**
My key should be forwarded in the main session.  

**Desktop (please complete the following information):**
 - OS: macos
 - Version 1.8.4

**Additional context**
Add any other context about the problem here (e.g okteto.yml, k8s manifests, logs)

**Comment by unthought** [comment]
The agent forwarding has to be set up separately. Here's a working example (not by me): https://play.golang.org/p/kMhHvbl4SG
