### ISSUE TITLE
Spinning wheel doesn't appear in powershell

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#846]
**Describe the bug**
The spinning wheel we display for things in progress doesn't show up correctly in powershell. The text appears, but the spinner is not displayed.

**To Reproduce**
1. okteto up

**Desktop (please complete the following information):**
 - OS: windows
 - Version 1.8.5

**Comment by alanmbarr** [comment]
I'm considering taking a crack at this. Would this section of https://github.com/okteto/okteto/blob/b8d3be59e18d56ccfb728a710b090c4398b56201/main.go#L58 main.go be appropriate to put the below code importing the go runtime as osruntime and golang.org/x/sys/windows

```
if osruntime.GOOS == "windows" {

		virtTermEnabledHandle := windows.Handle(os.Stdin.Fd())
		windows.SetConsoleMode(virtTermEnabledHandle, windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING)

	}
```

If I compare this to the [containerd approach](https://github.com/containerd/console/blob/master/console_windows.go#L32) they do a lot more error handling and I'm assuming the okteto command in general is short lived?

![image](https://user-images.githubusercontent.com/760506/99886254-9d8fc800-2c00-11eb-8374-ab14cb002c26.png)

**Comment by rberrelleza** [comment]
Yes, that's a good location for that change @alanmbarr . do you only need to set it once?

> If I compare this to the containerd approach they do a lot more error handling and I'm assuming the okteto command in general is short lived?

The okteto command is meant to be long-running (at least as long as your coding session). We implemented something like that [here](https://github.com/okteto/okteto/blob/fca1affd7e595e1935d72aa447e7947eb395d931/pkg/ssh/exec.go#L76), but didn't realize that we needed to do more windows-specific terminal management. But we can deal with that as a separate issue.
