### ISSUE TITLE
Feature Request: Option to disable file synchronization

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#850]
**Is your feature request related to a problem? Please describe.**
I want to launch a dev env, but I want to keep all the code and binaries in the cloud only.

**Comment by Ursegor890** [comment]
That will be awesome!!

**Comment by xiaods** [comment]
@rberrelleza if this feature is supported, I proposal add a client option to support manually sync action.

**Comment by rberrelleza** [comment]
@xiaods how would you implement it? Would a separate command that forces the current state of the repo into the remote work?  `okteto sync`

**Comment by xiaods** [comment]
I like it way`okteto sync`

**Comment by pchico83** [comment]
This can be accomplished by using a `.stignore` file that ignores everything:

**Comment by pchico83** [comment]
Closing in favor of this workaround:
https://github.com/okteto/okteto/issues/850#issuecomment-703104089
