### ISSUE TITLE
Only okteto Cloud, Deploy openfaas  got failed!

### ISSUE THREAD

**Issue by xiaods** [okteto/okteto#856]
**Describe the bug**
I login okteto cloud,  click Deploy button to create openfaas instance, follow example case: https://github.com/okteto/python-openfaas, the running instance got failed.
<img width="896" alt="截屏2020-05-02 下午3 13 05" src="https://user-images.githubusercontent.com/37678/80857851-e80f1e80-8c87-11ea-99e1-357ffd8ce809.png">

**To Reproduce**
1. Go to okteto cloud default page
2. Click on 'Deploy', and select openfaas helm package.
3. Scroll down to 'openfaas' log tab.

**Expected behavior**
openfaas can be installed successfully.

**Desktop (please complete the following information):**
 - OS: macos
 - Version: latest
**Additional context**
N/A

**Comment by pchico83** [comment]
@xiaods is the issue still happening? We have released a hotfix that might be related to this

**Comment by xiaods** [comment]
@pchico83 I can confirm it happened right now. 
double check it again.
<img width="1328" alt="截屏2020-05-02 下午8 03 33" src="https://user-images.githubusercontent.com/37678/80863600-17d21c80-8cb0-11ea-9ab7-a4ca5eaa152f.png">

**Comment by pchico83** [comment]
@xiaods I think we finally found the issue. Could you try again?

**Comment by xiaods** [comment]
@pchico83 I have been fresh install openfass deploy, it now works like a charms! rocks!
