### ISSUE TITLE
latest okteto  client, local folder can't update to upstream 

### ISSUE THREAD

**Issue by xiaods** [okteto/okteto#857]
**Describe the bug**
I follow documents sample: go-getting-started project to reproduce this bug:
<img width="1432" alt="截屏2020-05-02 下午3 28 31" src="https://user-images.githubusercontent.com/37678/80858174-2a395f80-8c8a-11ea-8de8-7842b5365261.png">

local main.go can't sync to upstream.

**To Reproduce**
1. Go to clone go-getting-started project. and `okteto up` to run this project, it works.
2. Then modified local file main.go's hello message, then waiting some time, the upstream main.go can't update correctly.
3. in a local project, run `okteto status` show sync working.
4. See the screenshot for my steps.  and attach /home/xiaods/.okteto's project synching log.
[syncthing.log](https://github.com/okteto/okteto/files/4567274/syncthing.log)

**Expected behavior**
local and upstream can sync right now.

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Version: okteto version 1.8.4

**Additional context**
in the earlier version, I have to try and came across same issue.  your team gives some more detailed steps to debug. we can confirm this is not okteto client's bug. Just some issue on the specified case:  My location is on China by GFW blocking. please give some help to resolve this annoying issue, let me use these cool tools. thanks.

**Comment by pchico83** [comment]
@xiaods my guess is that file watching is not working. We run a full file sync every 5minutes.
Could you keep the environment running for more than 5min and check if it finally syncs?
Also, could you share the `okteto doctor` file after this experiment?

**Comment by xiaods** [comment]
[okteto-doctor-20200502201821.zip](https://github.com/okteto/okteto/files/4567660/okteto-doctor-20200502201821.zip)

@pchico83 Thanks for your hints, yes, When I wait for 5 mins, it updates it done.

**Comment by xiaods** [comment]
My Macbook is my working notebook, I have not some setting for the harddrive. please double check it logs, let me know which step causes my wrong behavior.

**Comment by pchico83** [comment]
@xiaods syncthing on Mac has some issues with upper letters on the sync path.
Could you try cloning the sample repo on a path that does not contain upper letters?
Other option is the device itself, is there anything remarkable about the device you are using?

**Comment by xiaods** [comment]
@pchico83 thanks for your help, it bingo!
Could you try cloning the sample repo on a path that does not contain upper letters?
my original project path:  /Users/xiaods/Documents/Code
when I move to  /Users/xiaods/,  then it works like a charm.

Other option is the device itself, is there anything remarkable about the device you are using?
no, it's standard Apple macbook device , I buy it from the Apple store.

**Comment by xiaods** [comment]
How about adding a reminder notes on documents?

**Comment by pchico83** [comment]
@xiaods Yes, now we know the issue, we will print a warning when this happens.
Thanks for reporting it!

**Comment by pchico83** [comment]
I created this issue to track the warning:
https://github.com/okteto/okteto/issues/858

**Comment by pchico83** [comment]
@xiaods I was working on the warning message but I cannot repro it on my mac.
Which MacOS version do you have?

**Comment by xiaods** [comment]
@pchico83 reploy on the tracking issue.
