### ISSUE TITLE
Add a warning if on MacOS and sync path has upper letters other than `Users`

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#858]
**Is your feature request related to a problem? Please describe.**
`okteto up` file watching does not work on Mac for sync paths with upper case letters.

**Describe the solution you'd like**
Since we cannot fix at the synching level, `okteto up` should show a warning on this case.

**Describe alternatives you've considered**
The syncthing community already know the issue but the fix is not trivial

**Comment by xiaods** [comment]
here:

<img width="587" alt="截屏2020-05-04 下午10 44 42" src="https://user-images.githubusercontent.com/37678/80978615-e21c6780-8e58-11ea-8cfd-df919067f199.png">

**Comment by pchico83** [comment]
Closing this one. Syncthing is moving to case insensitive paths by default
