### ISSUE TITLE
Feature Request: Allow users to override serviceAccountName on pod spec

### ISSUE THREAD

**Issue by jtcressy** [okteto/okteto#867]
**Is your feature request related to a problem? Please describe.**
I frequently use okteto in an EKS cluster on AWS and would like to make use of IAM Roles for Serivce Accounts on my okteto deployment/pod to authenticate to AWS. Currently, I am unable to change the service account on the pod from the default service account in the namespace okteto is deployed. If I have another service account with the iam role arn annotation, I cannot use it on the okteto deployment.

**Describe the solution you'd like**
Allow the user to specify a serviceAccountName in the manifest file to override the default service account on the pod.

**Describe alternatives you've considered**
One workaround is to manually edit the default service account and add the role arn annotation, however the AWS IAM role has to trust this service account and this means that any pod in my namespace is now able to connect to aws with this role using the default service account. This has been ok for one-off namespaces with no other resources in them but it is still a slight security concern and harder to maintain.

**Additional context**
AWS Doc on this feature of EKS: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

While this feature request appears very EKS-specific, i'm sure there are other use cases for changing the service account name, such as setting up custom kubernetes rbac for your okteto pod and granting permissions via in-cluster authentication. This can be used while developing apps that interact with the kubernetes api in-cluster.

**Comment by rberrelleza** [comment]
@jtcressy thanks for filling the issue! 

When you run `okteto up`, are you letting it create the deployment with your development environment from scratch, or are you replacing an existing deployment?

When you run `okteto up`, the pod that Okteto deploys with your development environment will inherit the configuration of the existing deployment with the same `name` or `labels`, including the service account.  Have you tried this approach?

**Comment by jtcressy** [comment]
I have not tried this, but what if I'm using a statefulset or daemonset? will the labels catch this?

**Comment by rberrelleza** [comment]
At the moment, `okteto up` only works with resources of the type `deployments`. If you are interested in using it with daemonsets or statefulsets, would you mind filing an issue to track that request?

**Comment by jtcressy** [comment]
No problem.

**Comment by rberrelleza** [comment]
That being said, I think there are use cases where overriding the serviceAccount could be useful (like, as you mention, access dev-only resources). Let me think how that could fit in our manifest and we can add it, so let's keep this alive to track that for now.

**Comment by Carlangueitor** [comment]
Hi!
Is this feature planned to be on okteto? If not, can I try to implement it? I would really like to try okteto but I do need to have a service account other than the default (IAM Role annotation plus Vault role binding).

**Comment by Carlangueitor** [comment]
Cool!, Then I'll start to dig into the code :ok_hand:

**Comment by marov** [comment]
@pchico83 I submitted a PR, but `mock-release` fails with
```
ERROR: (gcloud.auth.activate-service-account) Missing required argument [ACCOUNT]: An account is required when using .p12 keys
```
Am I missing some authorization?

**Comment by rberrelleza** [comment]
@marov the issue is on our side, the CI is misconfigured for PRs coming from users not in the `okteto` organization. I'll fix it.
