### ISSUE TITLE
Feature Request: Support Other Controllers in apps/v1 

### ISSUE THREAD

**Issue by jtcressy** [okteto/okteto#868]
**Is your feature request related to a problem? Please describe.**
Attaching and transforming existing deployments into development environments is nice, but if my application is deployed using a StatefulSet or a DaemonSet, okteto currently doesn't attach to these resources and configure my environment. I would like to be able to connect to these resources and debug/develop my app without changing the deployment architecture.

**Describe the solution you'd like**
Setting labels in the okteto yaml identifies statefulsets or daemonsets and configures a dev environment on them.

**Describe alternatives you've considered**
The application would have to get reimplemented with a deployment, which may be ok for some testing circumstances but if I need to interact with a stateful app cluster that has volumes, it's harder to maintain a Deployment manifest with RWO PVC's.

**Additional context**
This would offer an alternative solution to one of the use cases in #867 since you can reuse the serviceAccountName from the existing manifest.

**Comment by rberrelleza** [comment]
How do you think a user should specify the type of resource? add a `type` key to the manifest? (and default to `deployment`)?

**Comment by jtcressy** [comment]
Sounds reasonable, could also match nomenclature and use `kind` with title case (`Deployment`, `StatefulSet`, `DaemonSet`) for consistency with k8s.

**Comment by rberrelleza** [comment]
#795 covers a similar request

**Comment by jtcressy** [comment]
Do you think the apiVersion will conflict? an OpenShift DeploymentConfig is actually under the `v1` api scope, oddly enough.

**Comment by rberrelleza** [comment]
I think that's something we can handle in the code. Maybe have `kind` be a set of [Deployment, StatefulSet, DaemonSet, DeploymentConfig], and based on that we can figure out which API to call?

**Comment by tarrencev** [comment]
Would really like the ability to develop daemonsets and statefulsets too. Is this something that has been prioritized?

**Comment by pchico83** [comment]
We already support statefulsets
