### ISSUE TITLE
error when accessing '/'

### ISSUE THREAD

**Issue by maxandersen** [okteto/okteto#878]
**Describe the bug**
this is a minor thing and just wondering if intended.

When you have a kubernetes client access '/' you get an error like: ```"doesn't have permission. forbidden: User "system:serviceaccount:okteto:cc2c44e2-0a5f-4919-abca-8286994d5f9e" cannot get path "/".```

we used '/' to check if we could connect to the server - works on all other k8s we tried but not on okteto. We've now moved to check `/version` and then it works.

**Expected behavior**
Allow '/' access without permission errors.

**Comment by pchico83** [comment]
Thanks for reporting it @maxandersen. Which command/code do you use to access "/"?
Also, would you mind opening the issue here https://github.com/okteto/cloud-feedback?
This repo is for the open-source CLI project.
