### ISSUE TITLE
Support for generateName

### ISSUE THREAD

**Issue by ZaxR** [okteto/okteto#880]
**Is your feature request related to a problem? Please describe.**
I often have to create multiple development environments at the same time, but have to change the name in the yml to avoid collision

**Describe the solution you'd like**
In k8s I use 
```
metadata:
  generateName: basename-
```

Which adds a uuid to the end of basename to avoid collisions

**Comment by pchico83** [comment]
Hi @ZaxR 
What is your use case? why do you need different dev env for the same app?

**Comment by ZaxR** [comment]
Thanks for the quick response!

I'm a data scientist, and my team uses k8s to run batch processing tasks as opposed to apps. When we don't have enough resources locally, we also spin up interactive development environments on the cloud, which we tear down at the end of the day. In our specific case, the k8s environment will usually have a ton of ram and ipython installed, but is more flexible than using a pre-built cloud service (there are a lot of jupyter notebook based services of this kind, but you can't install much into them). It's not uncommon for sever people on the team to be working on the same project at the same time, so we want to be able to avoid name collision.

**Comment by pchico83** [comment]
@ZaxR Our recommendation is for every developer to work on a different namespace to avoid name collisions. Would that work? Or isn't it possible on your setup?
Also, do you know Okteto Cloud (www.okteto.com)? 
Data science is a use case we want to promote more. If you want, join the #okteto channel in the Kubernetes community Slack (https://slack.k8s.io/) and we can talk more about how to improve your use case.

**Comment by ZaxR** [comment]
We do have control over namespaces, but using them had seemed like overkill for our use case. We also have an auto-scaling cluster set up just for our team, and with just seven people on the team, we don't need to control for separate auth/policies.

Additionally, and unrelated to our potential use of this tool, we may run multiple instances of the same bulk process (usually via airflow and KubernetesPodOperators), so having the name be recognizable, but with an automatic uuid on the end was more convenient than changing names via code or name spaces for runs.

I actually did just join the slack, so will join the channel shortly :)
