### ISSUE TITLE
okteto prompt doesnt get color when in powershell

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#884]
**Describe the bug**
![image](https://user-images.githubusercontent.com/475313/82489501-9b548180-9a96-11ea-8594-77c5718a55c5.png)

**To Reproduce**
1. git clone github.com/okteto/go-getting-started
1. cd go-getting-started
1. okteto.exe login
1. okteto.exe up

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.8

**Comment by rberrelleza** [comment]
setting `Set-ItemProperty HKCU:\Console VirtualTerminalLevel -Type DWORD 1` globally fixes the issue

**Comment by rberrelleza** [comment]
@rlamana where do you think we should document this?

**Comment by rlamana** [comment]
> @rlamana where do you think we should document this?

Probably here:
https://okteto.com/docs/reference/known-issues
