### ISSUE TITLE
Provide a mechanism for running a command after a file synchronization event

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#898]
After a file synchronization, I'd like okteto to automatically stop and restart the command for me. This is useful for scenarios where a hot-reloader is not available, or practical to use (e.g when running a binary as the command)

**Comment by rberrelleza** [comment]
An example that was mentioned was when developing openfaas functions, and you want fwatchdog to restart automatically.

**Comment by austinrivas** [comment]
another use case would be building / testing in the container on change.

I tend to put my entire dev environment in the container whenever possible to avoid local dependency mismatches.

**Comment by pchico83** [comment]
Duplicated of https://github.com/okteto/okteto/issues/1263
