### ISSUE TITLE
Next "okteto init" iteration

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#907]
**Is your feature request related to a problem? Please describe.**
I want to clone a git repo, run `okteto init` and have my okteto manifests auto-generated.

**Describe the solution you'd like**
- `okteto init` receives an optional parameter with the deployment to put on dev mode. If not specified, the current list of deployments is shown. The user picks one, she can also pick an isolated dev environment.
- If it is a new isolated dev environment, the behavior is the same as for today.
- For existing deployments, if it has labels, select it in the okteto manifests based on labels. If not, select it by name.
- Check if there is only one container in the target deployment.
- Infer the language. For python, node, ruby and PHP, use the deployment image. Try to inspect the deployment image to get the start command and workdir.
- For Go and Java, use the okteto dev image. We could ask for the `Dockerfile` and add the `build` field to use `okteto up --build`.
- Infer port forwards from associated service.
- If deployed by Flux, add flux ignore annotation.
Infer `.stignore` from `.dockerignore` or `.gitignore`. If none is present, use the current defaults.

**Comment by rberrelleza** [comment]
We could so something similar for openfaas functions

**Comment by pchico83** [comment]
@rberrelleza I thought about it, but it is a more complex case, I am going to skip it from this iteration

**Comment by rberrelleza** [comment]
It would be useful if okteto init also detected the current requests/limits, and set an override on okteto.yml for something more dev-friendly.
