### ISSUE TITLE
"okteto init" checking default storage class

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#947]
**Is your feature request related to a problem? Please describe.**
I run `okteto init` for a Go a Java app and the generated okteto manifest does not work on my cluster because my cluster does not have persistent volume support.

**Describe the solution you'd like**
Check if the cluster has persistent volume support and adapt the okteto manifest based on it.

**Comment by trevormerritt** [comment]
I added a default storage class and was then able to bring the system up.  A check for a default storage class might be enough to point novice users, like myself, to the right answer.  :)

https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/
