### ISSUE TITLE
UP reconnection renders shell's standard input unusable

### ISSUE THREAD

**Issue by rlamana** [okteto/okteto#948]
**Describe the bug**
When connectivity fails in `okteto up` the connection is automatically re-establish, but the shell becomes unusable. Any command you write is not properly interpreted. See screenshot:

<img width="591" alt="Screenshot 2020-06-23 at 10 24 43" src="https://user-images.githubusercontent.com/237819/85379651-4c3db880-b53c-11ea-81fa-38fb0ce35bef.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Okteto Version: 1.8.9

**Comment by rberrelleza** [comment]
@rlamana what caused the `killed` message? Do you have a repro to trigger that? Also, does it reproduce in 1.8.12?

Could you include okteto and syncthing logs?
