### ISSUE TITLE
okteto up routinely deletes every file in the current directory

### ISSUE THREAD

**Issue by jsnouffer** [okteto/okteto#949]
**Describe the bug**

`okteto up` routinely deletes every file in the current directory. I'm using Okteto version 1.8.12.
Similar to #522 

**To Reproduce**
1. `okteto up -n <namepsace> -d`
2. Occasionally the Syncthing process hangs, and I need to Ctrl+C to terminate
3. Files are deleted

**Expected behavior**
The files should not be deleted.

**Desktop (please complete the following information):**
 - OS: Centos
 - Version: 7.8.2003 (Core)

**Additional context**
[cli.txt](https://github.com/okteto/okteto/files/4826281/cli.txt)
[syncthing.log](https://github.com/okteto/okteto/files/4826282/syncthing.log)
[okteto.yaml.txt](https://github.com/okteto/okteto/files/4826294/okteto.yaml.txt)

**Comment by pchico83** [comment]
@jsnouffer could you attach the file generated by `okteto doctor` after the issue happens?
It also contains the remote synching logs

**Comment by jsnouffer** [comment]
@pchico83: Here you go:

[okteto-doctor-20200624131733.zip](https://github.com/okteto/okteto/files/4826985/okteto-doctor-20200624131733.zip)

I had to run okteto-up/okteto-down several times before I was able to re-create the issue, and I see a pattern, so here are my revised steps to reproduce.

1. Run `okteto up -n <namepsace> -d`
2. Occasionally the CLI hangs after printing "Files Synchronized"

Screenshot:
![Capture](https://user-images.githubusercontent.com/20827051/85603144-107b1f80-b61e-11ea-88df-5000ffca4f9f.PNG)

I cannot verify whether the intermittent hanging issue is on my end or not. Even when the CLI hangs, a pod is successfully started for the target deployment and my container is running and the okteto/bin init container has completed. I can shell into my container using kubectl.

3. When the CLI hangs, I kill it with Ctrl+C after about 5 minutes. 
4. Run `okteto up -n <namepsace> -d` again.
5. The files are deleted.
6. Once again, the CLI hangs after printing "Files Synchronized"

**Comment by pchico83** [comment]
@jsnouffer what is the content of `docker-entrypoint.bash`?
Looking at the logs seems like something in the remote container is removing the files, and the local synching applyes these changes to the local filesystem, removing everything:
```
2020-06-24T17:13:16.64708266Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 INFO: Ready to synchronize \"lmacs-driver\" (okteto-lmacs-driver) (sendreceive)" process=syncthing
2020-06-24T17:13:16.649844523Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 VERBOSE: Folder \"okteto-lmacs-driver\" is now scan-waiting" process=syncthing
2020-06-24T17:13:16.649869301Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 VERBOSE: Folder \"okteto-lmacs-driver\" is now scanning" process=syncthing
2020-06-24T17:13:16.649881345Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 VERBOSE: Local change detected in folder \"okteto-lmacs-driver\": modified file okteto.yml" process=syncthing
2020-06-24T17:13:16.64988597Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 INFO: Completed initial scan of sendreceive folder \"lmacs-driver\" (okteto-lmacs-driver)" process=syncthing
2020-06-24T17:13:16.649890425Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 VERBOSE: Local change detected in folder \"okteto-lmacs-driver\": deleted file Dockerfile" process=syncthing
2020-06-24T17:13:16.649894722Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 VERBOSE: Local change detected in folder \"okteto-lmacs-driver\": deleted file Makefile" process=syncthing
2020-06-24T17:13:16.649899415Z time="2020-06-24T17:13:16Z" level=info msg="[ATOPH] 17:13:16 VERBOSE: Local change detected in folder \"okteto-lmacs-driver\": deleted file docker-entrypoint.bash" process=syncthing
```
Or maybe the `/okteto` folder is remounted in the remote container and its content is lost?

**Comment by jsnouffer** [comment]
@pchico83 
So to rule out the `docker-entrypoint.bash` file, I recreated the issue with command set to /bin/bash. It only occurs after I previously kill the client because it was hanging, so I think it might be related to running `okteto up` on a previously created development container. Maybe I should be doing `okteto exec /bin/bash` instead?

Here is an updated `okteto.yaml` and a new zip file from `okteto doctor`:

[okteto.yaml.txt](https://github.com/okteto/okteto/files/4831507/okteto.yaml.txt)
[okteto-doctor-20200625091703.zip](https://github.com/okteto/okteto/files/4831508/okteto-doctor-20200625091703.zip)

**Comment by pchico83** [comment]
@jsnouffer I haven't been able to repro it or to find some light in the logs :-(
Which kubernetes distribution are you using? a local cluster like minikube? or a managed cloud provider cluster?
We are packaging the 1.8.13 release for tomorrow. I am adding more debug logs around to see if we find the source of the issue.

**Comment by jsnouffer** [comment]
@pchico83 I am deploying to a 3-node cluster deployed on our own VMs. The host I'm running on and the cluster are on the same subnet.

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by pchico83** [comment]
@jsnouffer I have a theory that might explain the issue. Would you mind attaching the yaml manifest of your pod after running `okteto up`? I am particularly interested in resource memory limits.
Also, could you add:
```
persistentVolume:
   enabled: true
```
to your okteto manifest and check if it fixes the issue?
Btw, thanks for helping to troubleshoot this issue. It is a very important one for us.

**Comment by pchico83** [comment]
@jsnouffer I created a PR that I think it is going to fix the issue:
https://github.com/okteto/okteto/pull/961
Could you give it a try with your current okteto manifest?
Respect to the memory constraints, if the pod is being killed because of it, you can set new limits for your dev container in the okteto manifest:
https://okteto.com/docs/reference/manifest#resources-object-optional

**Comment by jsnouffer** [comment]
@pchico83 Here is the pod yaml after running `okteto up` :

[okteto_pod.yaml.txt](https://github.com/okteto/okteto/files/4837496/okteto_pod.yaml.txt)

**Enabling the persistent volume prevents the file deletion issue.** I have not been able to reproduce with it enabled, but can readily reproduce without the volume.

I tried out #961, but the pod keeps crashing with the following error in the pod log:
`Invalid option: -c`

Here is the output from `okteto doctor` : 
[okteto-doctor-20200626102408.zip](https://github.com/okteto/okteto/files/4837527/okteto-doctor-20200626102408.zip)

**Comment by pchico83** [comment]
@jsnouffer sorry, I was doing some tests on the branch and it was broken.
But I am now able to repro the issue, fix will be ready soon. In the meantime, enabling persistent volumes fixes the issue

**Comment by pchico83** [comment]
@jsnouffer I updated the branch in case you want to give it a try.

**Comment by jsnouffer** [comment]
@pchico83 The fix works great! Thank you so much for helping me out.

**Comment by pchico83** [comment]
@jsnouffer cool, thanks to you!
you have been really helpful to solve the issue :-) this was an important one!
