### ISSUE TITLE
okteto init doesn't overwrite the specified file

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#951]
**Describe the bug**
I ran `okteto init -o new.yml`, and the command overwrote my existing `okteto.yml` instead of the specified parameter.

**Desktop (please complete the following information):**
 - OS: macOS
 - 1.8.12

**Comment by pchico83** [comment]
The syntax would be `okteto init -o -f new.ml`. Should show an error is ìnit` receives cli arguments?
We should do it for all the cli commands

**Comment by rberrelleza** [comment]
Ah right, 100% user error then.
