### ISSUE TITLE
Log output with JSON formatter for JSON based log viewers

### ISSUE THREAD

**Issue by kivi** [okteto/okteto#957]
**Is your feature request related to a problem? Please describe.**

I am getting in Stackdriver 2 to 3 log entries of the following in Stackdriver every five minutes.

```
severity:  "ERROR"   
textPayload:  "time="2020-06-25T09:00:44Z" level=info msg="[ATOPH] 09:00:44 VERBOSE: Folder \"okteto-myapp\" is now idle" process=syncthing

```

**The possible solution you'd like**
As discussed in slack channel, switching to a json formatter could be an approach.

**Alternative**
A Okteto pod is has `dev.okteto.com: "true"` set. That could be filtered in log viewer

**Comment by pchico83** [comment]
@kivi I think we have found a relatively simple way to fix it (syncthing does not support json format logs).
I will work on the PR because it requires changes in other repos too.
