### ISSUE TITLE
`okteto init` doesn't include helm-related labels

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#962]
**Describe the bug**
When generating an okteto manifest from a helm-managed deployment, my `okteto.yml` doesn't include the labels.

**To Reproduce**
1. `cd /tmp`
1. `helm create repro`
1. `cd repro`
1.  `helm install repro .`
1. `okteto init` 

**Expected behavior**
I was expecting `okteto.yml` to include labels to identify my deployment, since in helm the resource names are dynamic.

**Desktop (please complete the following information):**
 - OS: macos
 - Version 1.8.12

**Comment by pchico83** [comment]
@rberrelleza `helm create` does not create "component" labels.
All the labels generated by this sample depend on the helm release name and cannot be used in the okteto manifest.

**Comment by rberrelleza** [comment]
Ah ok. We should document the criteria then.
