### ISSUE TITLE
Feature Request: Okteto Build should support creation of multiple tags

### ISSUE THREAD

**Issue by kingdonb** [okteto/okteto#969]
The Docker cli supports the creation of multiple tags on `docker build` by passing `-t <tagname>` more than once. Most of the features of Docker CLI (such as `--build-arg`) appear to be supported natively on `okteto build`, but this one is not.

When passing `-t <tagname>` to `okteto build` more than once, the build should pass all `-t` flags along to Docker CLI so it can generate multiple tags from the build. Then `okteto build` should push all tagged images at once to the registry remote. It would be good if okteto.yml also could accommodate `build` tagging multiple images, and multiple targets.

My use case is a Makefile which calls `okteto build` a few times in succession, once to build a `dev` image and again to build the production tag, I have a script `image-tag` that generates a tag like `branch-name-1234abcd` with a git hash, or with the git tag if the current commit is tagged. This is one of the reasons for using a Makefile, so I can run this script. I would like to push this semantic tag alongside of a `latest` or `dev` tag for each target.

So in my Makefile, I run `make okteto-build`, which calls `okteto build` for the first time as `okteto build --target dev`, I generate an image and wish for it to be tagged several times, `dev`, `dev-20200707`, etc. so my registry can keep the old revisions around as historic artifacts. Assuming that build succeeds, `make okteto-build` moves on to call `okteto build` a second time, this time building the production target, which I'd like to tag as `branch-name-1234abcd`, `latest`, `branch-name`, etc. so there can be multiple production tags again with the idea of keeping older tags for historical purposes.

A unique tag is usually best practice but does not jibe well with `okteto.yml` which needs to carry a stable tag reference like `registry/kingdonb/app:dev` so that it can easily provide a context for the dev environment, without additional inputs.

I have considered pulling the image down to my local machine once it is built and then re-tagging it, to push the other tags back into the registry, which of course does work but also has obvious disadvantages, I'd like to avoid doing it that way.

I brought this up in slack, and @rberrelleza suggested submitting it as a feature request. Thanks!

**Comment by kingdonb** [comment]
At the same time, it may be important (and desirable to be able to reliably configure) which tag is mentioned first:

```
 => ERROR importing cache manifest from registry.empfin.kingdonb.dev/kingdonb/pzaexcp-frontend:frontend-rails-6-dev-e490cfa1
```

My production build uses a unique tag, which means each build will hit this error. I'm not sure what side effect this failure might have (docker build image caching seems to work regardless of the error, perhaps this is the file containing any time stamps to help inform the build about which files might have changed since last build). It would seem to make sense to use the branch name in the "primary" tag so that importing a cache manifest would not fail, and add the unique tag later, as well as `latest`, so multiple branches can still coexist and progress at once, and they would import their own cache manifests.

Thanks for adding `okteto build` to the enterprise chart! This feature seems really useful, I am still shaking out how exactly I can incorporate it in my own workflow optimally. It looks like it has the potential to save a lot of data transfer and make it go faster generally every day in really powerful ways. I look forward to what features you will add to Okteto next!

**Comment by proof-nicholas** [comment]
Hi, what is the status of this, it is closed but there is no indication of its resolution?

**Comment by jLopezbarb** [comment]
Hi @proof-nicholas. This is something that we have been discussing lately, It was closed because of inactivity but it's something we have under the radar
