### ISSUE TITLE
option for okteto push to wait until the new deployment is ready

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#970]
**Is your feature request related to a problem? Please describe.**
Currently, `okteto push` finishes the execution when the deployment is launched. 

**Describe the solution you'd like**
A `--wait` command that waits until the deployment is up and running. 

**Describe alternatives you've considered**
I have to check the status of the deployment, or call the URL multiple times until it's done

**Additional context**
This would be useful for automation and github actions as well

**Comment by hzliangbin** [comment]
May I take it?

**Comment by pchico83** [comment]
@hzliangbin sounds good!
If it helps, we are already listing endpoints for preview environments:
https://github.com/okteto/okteto/blob/master/cmd/preview/endpoints.go
