### ISSUE TITLE
okteto fails to write to the log if more than one `okteto up` is active at the same time

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#977]
**Describe the bug**
okteto fails to write to the log if more than one `okteto up` is active at the same time

**Error**
`Failed to write to log, can't rename log file: rename W:\.okteto\okteto.log W:\.okteto\okteto-2020-07-20T12-15-47.445.log: The process cannot access the file because it is being used by another process.`

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by avishaiNB** [comment]
Hi @rberrelleza,
Completing bug details as you asked:

I'm running okteto on windows 10 Pro.
Trying to run two okteto pods in the same k8s cluster.
I ran the following command in each okteto console:

- Oktoto up
- node server.js

i used this okteto manifest file on both pods:
```
name: <pod-name>
image: okteto/node:12
command:
- bash
workdir: /usr/src/app
forward:
  - 9229:9229
reverse:
  - 3000:3000
```
I get the error printed only in the first okteto console after i started the second okteto console.
**FYI:** This only throws a warning but allows me to work with both console running (i didn't try to debug yet)

Hope it helps! :)

> **Describe the bug**
> okteto fails to write to the log if more than one `okteto up` is active at the same time
> 
> **Error**
> `Failed to write to log, can't rename log file: rename W:\.okteto\okteto.log W:\.okteto\okteto-2020-07-20T12-15-47.445.log: The process cannot access the file because it is being used by another process.`
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows

**Comment by tf0054** [comment]
I am having the same msgs while using okteto version 1.10.3 on win10 pro.
Additionally for my case the msgs will start to be printed after few mins? from starting two pods.
