### ISSUE TITLE
set upgrade policy to 'Recreate' for dev environments

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#989]
**Is your feature request related to a problem? Please describe.**
I think we should set the upgrade policy to Recreate, so it's faster to relaunch a dev env, and so that it doesn't require twice the resources available.

**Describe alternatives you've considered**
We can run okteto down and then up again, but it'd be easier if I don't have to do that.

**Comment by pchico83** [comment]
This is the current behavior
